= Verifique se a instrumentação está funcionando
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Se o coletor e a configuração da instrumentação foram bem-sucedidos, os dados devem estar disponíveis no SUSE Observability em cerca de um ou dois minutos.

Você pode verificar se o SUSE Observability está recebendo rastros:

. Abra o SUSE Observability em um navegador
. Encontre (um dos) pods que está instrumentado
. Selecione o pod para abrir a página de Destaques
. Abra a perspectiva de rastros. Se o pod estiver atendendo tráfego, agora deve mostrar rastros.

Para verificar se o SUSE Observability está recebendo métricas:

. Abra o SUSE Observability em um navegador
. Abra o explorador de métricas no menu
. Pesquise as métricas expostas pelo seu aplicativo

Se ainda não houver métricas após 5 minutos, algo provavelmente está mal configurado. Veja xref:/setup/otel/troubleshooting.adoc[solução de problemas] para obter ajuda.
