ifdef::ss-ff-stackpacks2_enabled[]
= Presentation Highlight Metrics
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-11
:page-revdate: {revdate}
:description: SUSE Observability

== Overview

The highlight metrics show up on the xref:/use/views/k8s-highlights-perspective.adoc[Highlights perspective].  It contains an (ordered) list of sections, each of which has an (ordered) list of metric charts.

[,yaml]
----
presentation:
  highlight:
    metrics:
      - sectionId: string
        title: string
        order: double
        metrics:
          - metricId: string
            order: double
            ...
----

=== Merging

For each section (identified by the `sectionId`), more specific presentations can override fields from more generic presentations.  For each metric in a section (identified by the `metricId`), more specific presentations can override fields from more generic presentations.  If a metric is defined in a section of a generic presentation, its fields will be used unless a specific presentation overrides them.  The ordering is

* Most Specific Section Metric
* Most Specific Generic Metric
* Less Specific Section Metric
* Less Specific Generic Metric
* etcetera

[NOTE] 
====
Only overrides from the same section are taken into account.  If a different section reuses the same metric, overriding some fields, those are merged separately.
====

endif::ss-ff-stackpacks2_enabled[]
