ifdef::ss-ff-stackpacks2_enabled[]
= Metrics Schema
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-11
:page-revdate: {revdate}
:description: SUSE Observability

== Schema

[,yaml]
----
metricId: string
name: string
chartType: "line"                     # "line" is the only type for now
unit?: string
description?: string
queries:
  - expression: string                # promql query
    alias: string                     # name in legend
    componentIdentifierTemplate?: string    # URN template for linking
    primary?: boolean                 # is this query the primary one
tags:
  <key>: <value>
----

* `metricId` The id of the metric, used for overriding/referencing when used in any of the charts
* `name`: The name for the metric binding
* `chartType`: {stackstate-product-name} will support different chart types (`line`, `bar`, etc.), currently only `line` is supported
* `unit`: The unit of the values in the time series returned by the query or queries, used to render the Y-axis of the chart. See the xref:/develop/reference/k8sTs-chart-units.adoc[supported units] reference for all units
* `description`: Optional description, displayed on-hover of the name
* `queries`: A list of queries to show in the chart for the metric (see xref:/develop/reference/writing-promql.adoc[Writing PromQL queries])
** `expression`: The (templated) promql query
** `alias`: Name for the query in the legend
** `componentIdentifierTemplate`: Template for identifier of related component, populated with labels of timeseries resulting from the query
** `primary`: Is this query the primary one
* `tags`: Will be used to organize metrics in the user interface, can be left empty using `{}`

endif::ss-ff-stackpacks2_enabled[]
