ifdef::ss-ff-stackpacks2_enabled[]
= Presentation Summary Metrics
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-11
:page-revdate: {revdate}
:description: SUSE Observability

Summary metrics concisely show the most important metrics of a component.  They are shown in the right-hand-side panel and when hovering a component in the xref:/use/views/k8s-topology-perspective.adoc[Topology Perspective].

[,yaml]
----
presentation:
  summary:
    metrics:
      - metricId: string
        order: double
        ... metric overrides ...
----

== Merging

For each metric (identified by the `metricId`), more specific presentations can override fields from more generic presentations.  If a metric is defined in the summary of a generic presentation, its fields will be used unless a specific presentation overrides them.  The ordering is

* Most Specific Summary Metric
* Most Specific Generic Metric
* Less Specific Summary Metric
* Less Specific Generic Metric
* etcetera

endif::ss-ff-stackpacks2_enabled[]
