= À propos des StackPacks
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé v5.1.x

== Présentation

Les StackPacks étendent les fonctionnalités de SUSE Observability et offrent une intégration automatisée avec des systèmes externes. Ils peuvent être facilement installés et désinstallés depuis la page des StackPacks dans SUSE Observability.

Il existe deux types de StackPack : les modules complémentaires et les intégrations. Les modules complémentaires et intégrations de StackPack disponibles peuvent être trouvés sur la page *StackPacks* dans l'interface utilisateur de SUSE Observability.

== Installer ou désinstaller un StackPack

Les StackPacks peuvent être installés et désinstallés depuis la page *StackPacks* dans SUSE Observability. Des instructions complètes pour installer et désinstaller le StackPack sont fournies.

[NOTE]
====
*Veuillez tenir compte de ce qui suit :*

* Un StackPack peut nécessiter des étapes d'installation *manual* ou la configuration du système externe. Veuillez lire attentivement les instructions fournies.
* Lorsqu'un StackPack ou une instance de StackPack est désinstallé, *toutes les données reçues via le StackPack (instance) seront supprimées de SUSE Observability.*
* Toute configuration ou installation (manuelle) des composants de StackPack dans un système externe peut devoir être désinstallée séparément.

====


=== Instances de StackPack

Certains StackPacks vous permettent de vous connecter à plusieurs comptes sur un système externe. Chaque compte est configuré dans une instance séparée du StackPack.

Par exemple, le StackPack AWS peut se connecter à plusieurs comptes AWS et combiner les informations de tous les comptes dans SUSE Observability. Pour chaque compte, une instance séparée de SUSE Observability est configurée avec les informations nécessaires pour recevoir des données de ce compte AWS.

== Mettre à niveau un StackPack

[CAUTION]
====
Lorsqu'un StackPack est mis à niveau, *toutes les modifications apportées aux éléments de configuration de ce StackPack seront écrasées*. Pour plus de détails, voir xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[éléments de configuration verrouillés].
====


Si une nouvelle version de StackPack est disponible, une alerte sera affichée sur la page StackPack de l'interface utilisateur SUSE Observability et vous aurez la possibilité de consulter les détails de la mise à niveau et de lire les notes de version. Si la nouvelle version est une mise à niveau mineure par rapport à la version actuellement installée, vous pouvez également mettre à niveau le StackPack depuis ici.

=== Nouvelle version mineure de StackPack

Pour mettre à niveau vers une nouvelle version mineure d'un StackPack, cliquez sur *MISE À NIVEAU MAINTENANT* sur la page StackPack de l'interface utilisateur SUSE Observability.

Notez que tous les éléments de configuration du StackPack seront écrasés lors de la mise à niveau. Pour continuer à utiliser les modifications apportées à ceux-ci, choisissez de *GARDER* la configuration existante lorsque vous mettez à niveau le StackPack. Pour plus de détails, voir xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[éléments de configuration verrouillés].

=== Nouvelle version majeure de StackPack

[CAUTION]
====
Lorsqu'un StackPack est mis à niveau, *toutes les modifications apportées aux éléments de configuration de ce StackPack seront écrasées*. Pour plus de détails, voir xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[éléments de configuration verrouillés].
====


Pour mettre à niveau vers une nouvelle version majeure d'un StackPack, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[désinstallez et réinstallez] le StackPack.

[TIP]
====

Continuez à utiliser les modifications apportées aux éléments de configuration personnalisés du StackPack après la mise à niveau :

. Avant de mettre à niveau, exportez chaque élément personnalisé :
 ** Allez à la page *Paramètres* dans l'interface utilisateur SUSE Observability.
 ** Cliquez sur *Exporter* dans le menu *...* pour chaque élément personnalisé.
. Mettez à niveau le StackPack (désinstaller et réinstaller).
. Changez le `name` et le `identifier` pour chaque élément exporté :
 ** Ouvrez le fichier d'exportation dans un éditeur de texte.
 ** Modifiez les champs `name` et `identifier` de niveau supérieur.
 ** Enregistrez l'exportation.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Importez] le(s) fichier(s) d'exportation mis à jour.
. Les éléments de configuration personnalisés seront désormais disponibles dans SUSE Observability et pourront être copiés dans les nouveaux éléments de configuration du StackPack installé.

====


== Éléments de configuration verrouillés

Les StackPacks contiennent des informations de configuration pour SUSE Observability qui sont installées lorsque le StackPack (instance) est installé. Parmi d'autres choses, cela pourrait être des modèles de composants, des fonctions, des actions de composants et des vues. Lorsqu'un StackPack est mis à niveau, *les éléments de configuration installés par la version précédente du StackPack seront remplacés par ceux du StackPack plus récent.* Cela signifie que tout changement manuel apporté à ces éléments de configuration sera remplacé lorsque le StackPack sera mis à niveau.

Pour empêcher un utilisateur d'apporter des modifications aux éléments de configuration installés par un StackPack qui seront remplacés lors de la mise à niveau, ces éléments de configuration sont *verrouillés* par défaut. Cela signifie qu'ils sont protégés contre les modifications par l'utilisateur et doivent être explicitement *déverrouillés* avant de pouvoir être modifiés.

[TIP]
====

Vous pouvez xref:/setup/data-management/backup_restore/configuration_backup.adoc[faire une sauvegarde des éléments de configuration]. Notez que l'état de verrouillage des éléments de configuration ne sera pas exporté dans le cadre d'une sauvegarde de configuration.
====

