ifdef::ss-ff-stackpacks2_enabled[]
= UI Presentation Concepts
:revdate: 2026-01-08
:page-revdate: {revdate}
:description: UI Presentation Concepts

This is a summary of the most important concepts in Open Telemetry and should be sufficient to get started. For a more detailed introduction use the https://opentelemetry.io/docs/concepts/[Open Telemetry documentation]

== ComponentPresentation

The central concept of the UI Presentation model is the *ComponentPresentation*.

A `ComponentPresentation` defines how one or more matching components are presented in the UI, depending on the active context.

At a high level, a ComponentPresentation:

* Selects components using a binding (a simple STQL query).
* Applies within a specific mode (for example, observability).
* Defines one or more presentation aspects (such as overview tables or highlights).
* Can partially define presentation properties and compose with other matching definitions.

Multiple ComponentPresentations may apply to the same component. In such cases, their definitions are combined to determine the final presentation.

endif::ss-ff-stackpacks2_enabled[]
