= 認証オプション
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自己ホスト型

初期設定では、SUSE Observabilityは管理者と、xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[インストール中に設定されたランダムなパスワード]を使用したxref:/setup/security/authentication/file.adoc[シングルパスワード認証]で構成されています。これにより、サーバー上のシンプルな秘密でユーザーが認証されます。しかし、これは運用準備完了のセットアップではありません。

より良いセキュリティのために、SUSE Observabilityは次の認証メカニズムのいずれかを使用するように構成できます（標準の管理者を置き換えます）：

* xref:/setup/security/authentication/single_password.adoc[単一のパスワード]
* xref:/setup/security/authentication/file.adoc[ファイルベース]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak（OIDCの特化版）]

[NOTE]
====
認証設定はHelmチャートの一部であり、変更があると自動的にポッドの再起動がトリガーされます。
====


== ユーザの役割

ユーザーが認証されると、そのユーザーの権限は通常、ユーザーが持つ役割に基づいて割り当てられます。特定の認証メカニズムに関するドキュメントには、外部システムからSUSE Observabilityの4つの標準役割に役割やグループをマッピングする方法の例も含まれています：

* *ゲスト* - 情報を表示できますが、変更はできません。
* *Kubernetesトラブルシューティング担当者* - すべての情報を表示し、モニターやメトリックの設定を表示および変更できます。
* *パワーユーザー* - すべての設定を表示および変更でき、StackPacksをインストールできます。
* *管理者* - SUSE Observabilityの内容を表示および変更できます。たとえば、すべての設定を表示し、StackPacksをインストールし、ユーザーの権限を付与および取り消し、（新しいバージョンの）StackPacksをアップロードできます。

ユーザーに割り当てる役割を決める際は、プラットフォーム管理者と管理者という少数のグループに限定することを強くお勧めします。たとえば、SUSE Observabilityのインストールと初期設定を担当するエンジニアのみです。管理者はSUSE Observabilityへのアクセスを管理し、どのStackPacksを使用できるかを決定できます。StackPacksのインストールや設定の微調整を、パワーユーザー役割を持つより多くのユーザーに委任できます。プラットフォーム管理者はデータベースをクリアし、データ保持設定を変更し、ログを表示し、その他のプラットフォーム管理タスクを実行できます。

さらに、役割を追加することも可能です。ページxref:/setup/security/rbac/rbac_roles.adoc[役割（RBAC）]および他のxref:/setup/security/rbac/README.adoc[RBACドキュメントページ]を参照してください。
