= 単一のパスワード
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} 自己ホスト型

初期設定では、{stackstate-product-name} は単一パスワードの設定になっており、xref:/k8s-suse-rancher-prime.adoc#_installation[インストール中に設定されます]。これにより、インストール中に提供されなければならない単一のパスワードでユーザーが認証されます。

これは {stackstate-product-name} を始める最も簡単な方法ですが、運用環境では他の xref:/setup/security/authentication/authentication_options.adoc[認証オプション] のいずれかを推奨します。

== 外部シークレットからパスワードを取得する

デフォルトのパスワードが外部シークレットから取得されるべき場合は、xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[これらの手順] に従って、次のデータを入力してください：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

パスワードのエンコーディングは次のいずれかです： +
* プレーンテキストパスワードの場合は、`$plain$your-password` を提供してください（`$plain$` はプレーンテキストを示す接頭辞です） +
* bcrypt パスワードの場合は、`bcrypt-hashed-password` を提供してください。パスワードの bcrypt ハッシュを作成するには、`htpasswd -bnBC 10 "" <password> | tr -d ':\n'` を使用できます。

== 関連項目

* xref:/setup/security/authentication/authentication_options.adoc[認証オプション]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[定義済みの {stackstate-product-name} ロールの権限]
* xref:/setup/security/rbac/rbac_roles.adoc[RBAC ロールを作成する]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[外部シークレット]
