= Requirements
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

Requirements for <<_client_browser,SUSE Observability client (browser)>> can be found at the bottom of the page.

=== Compatibility with Rancher and Kubernetes
Check out the compatibility page here xref:setup/install-stackstate/Compatibility Self Hosted.adoc[Rancher/Kubernetes compatibility]

=== Resource requirements

There are different installation options available for SUSE Observability. It is possible to install SUSE Observability either in a High-Availability (HA) or single instance (non-HA) setup. The non-HA setup is recommended for testing purposes only. For production environments, it is recommended to install SUSE Observability in a HA setup. For a standard, production, deployment, the SUSE Observability Helm chart will deploy many services in a redundant setup with 3 instances of each service.

In the table below you can find the resource requirements for the different installation options. For the HA setup you can find different installation profiles depending on the size of the environment being observed.
An observed node in this sizing table is taken to be 4 vCPUs and 16GB of memory, our `default node size`.
If nodes in your observed cluster are bigger, they can count for multiple `default nodes`, so a node of 12vCPU and 48GB counts as 3 `default nodes` under observation when picking
a profile.

|===
|  | trial | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *CPU Requests*
| 7.5
| 7.5
| 10.5
| 15
| 25
| 49
| 62
| 86.5
| 210

| *CPU Limits*
| 16
| 16
| 21.5
| 30.5
| 50
| 103
| 128
| 176
| 278

| *Memory Requests*
| 25.5Gi
| 25.5Gi
| 31Gi
| 35Gi
| 54Gi
| 129Gi
| 146Gi
| 164.5Gi
| 259Gi

| *Memory Limits*
| 26Gi
| 26Gi
| 31.5Gi
| 36Gi
| 54Gi
| 133.5Gi
| 150Gi
| 168.5Gi
| 320Gi
|===

[NOTE]
====
The requirement shown for profile represent the total amount of resources needed to run the Suse Observability server.
To ensure that all different services of Suse Observability server can be allocated:

* For non-HA installations the recommended node size is 4VCPU, 8GB
* For HA installations up to 500 nodes the min recommended node size is 8VCPU, 16GB
* For 4000 nodes HA installations the min recommended node size is 16VCPU, 32GB
====


These are just the upper and lower bounds of the resources that can be consumed by SUSE Observability in the different installation options. The actual resource usage will depend on the features used, configured resource limits and dynamic usage patterns, such as Deployment or DaemonSet scaling. For our Self-hosted customers, we recommend to start with the default requirements and monitor the resource usage of the SUSE Observability components.

[NOTE]
====
The minimum requirements do not include spare CPU/Memory capacity to ensure smooth application rolling updates.
====


For installation of SUSE Observability please follow the installation instructions provided below:

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== Storage

SUSE Observability uses persistent volume claims for the services that need to store data. The default storage class for the cluster will be used for all services unless this is overridden by values specified on the command line or in a `values.yaml` file. All services come with a pre-configured volume size that should be good to get you started, but can be customized later using variables as required.

[NOTE]
====
For production environments, NFS is not recommended and supported for storage provisioning in SUSE Observability due to the potential risk of data corruption.
====


For our different installation profiles, the following are the defaulted storage requirements:

|===
|  | trial | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *Retention (days)*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *Storage requirement*
| 125GB
| 280GB
| 420GB
| 420GB
| 600GB
| 2TB
| 2TB
| 2.5TB
| 5.5TB
|===

[NOTE]
====
The storage estimates presented take into account a default of 14 days of retention for NONHA and 1 month for HA installations. For short lived test instances the storage sizes can be further reduced.
====


For more details on the defaults used, see the page xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[Configure storage].

=== Namespace resource limits

It isn't recommended to set a ResourceQuota as this can interfere with resource requests. The resources required by SUSE Observability will vary according to the features used, configured resource limits and dynamic usage patterns, such as Deployment or DaemonSet scaling.

If it's necessary to set a ResourceQuota for your implementation, the namespace resource limit should be set to match the node xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[sizing requirements].

== Client (browser)

To use the SUSE Observability GUI, you must use one of the following web browsers:

* Chrome
* Firefox
