= Requirements
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

Requirements for <<client-browser,SUSE Observability client (browser)>> can be found at the bottom of the page.

=== Compatibility with Rancher and Kubernetes
Check out the compatibility page here xref:setup/install-stackstate/Compatibility Self Hosted.adoc[Rancher/Kubernetes compatibility]

=== Resource requirements

There are various installation and sizing options available for the SUSE Observability platform, these options are captured in a 'sizing profile'. It is possible to install SUSE Observability either in a High-Availability (HA) or single instance (non-HA) setup. The non-HA setup is recommended for testing purposes only. For production environments, it is recommended to install SUSE Observability in a HA setup. The HA setup will deploy the core services in a redundant setup.

Every sizing profile has a maximum size of the observed environment it can process. The size of the environment is expressed in `Default Nodes`, representing the amount of kubernetes nodes that are being observed. Because kubernetes nodes can vary in size, a `Default Node` represents 4 vCPUs and 16GB of memory: the `Default Node Size`. If nodes in your observed cluster are bigger than the `Default Node`, they can count for multiple `Default Nodes`. For example, a kubernetes node of 12vCPU and 48GB counts as 3 `Default Nodes` under observation when picking a profile.

[IMPORTANT]
====
The numbers in the profile names (for example, the "150" in 150 HA) refer to the number of `Default Nodes`, not the literal number of physical or virtual machines in your cluster.
====

An example profile would be `100 non-HA`.  This is a profile which supports 100 `default nodes` and is not highly available. In the table below you can find the various sizing profiles and resource requirements for them:

|===
|  | trial | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *CPU Requests*
| 7.2
| 7.2
| 9.5
| 14.2
| 24.1
| 49.8
| 61.8
| 85.3
| 212.3

| *CPU Limits*
| 16.2
| 16.2
| 20.5
| 29.9
| 49.5
| 106.3
| 129.4
| 177.3
| 282.1

| *Memory Requests*
| 23.4Gi
| 23.4Gi
| 27.2Gi
| 32.6Gi
| 45.7Gi
| 130.6Gi
| 145.8Gi
| 176.1Gi
| 267.6Gi

| *Memory Limits*
| 24.0Gi
| 24.0Gi
| 27.9Gi
| 32.7Gi
| 45.8Gi
| 135.5Gi
| 150.4Gi
| 180.9Gi
| 325.4Gi

| *Minimum Node Size*
| 4vCPU, 8GB
| 4vCPU, 8GB
| 4vCPU, 8GB
| 4vCPU, 8GB
| 4vCPU, 8GB
| 8vCPU, 16GB
| 8vCPU, 16GB
| 8vCPU, 16GB
| 16vCPU, 32GB

| *Minimum Node Count*
| 1
| 1
| 1
| 1
| 1
| 3
| 3
| 3
| 5

|===

[NOTE]
====
The requirements shown for the profiles represent the total amount of resources needed to run the Suse Observability server.

The `Minimum Node Size` and `Minimum Node Count` refer to the minimum size and amount of nodes required in the cluster into which the SUSE Observability platform is installed. It is unrelated to the `Default Node Size` used to measure the size of the environment under observation.
====


These are just the upper and lower bounds of the resources that can be consumed by SUSE Observability in the different installation options. The actual resource usage will depend on the features used, configured resource limits and dynamic usage patterns, such as Deployment or DaemonSet scaling. For our Self-hosted customers, we recommend to start with the default requirements and monitor the resource usage of the SUSE Observability components.

[NOTE]
====
The minimum requirements do not include spare CPU/Memory capacity to ensure smooth application rolling updates.
====


For installation of SUSE Observability please follow the installation instructions provided below:

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== Storage

SUSE Observability uses persistent volume claims for the services that need to store data. The default storage class for the cluster is used for all services unless this is overridden by values specified on the command line or in a `values.yaml` file. All services come with a pre-configured volume size that should be good to get you started, but can be customized later using variables as required.

[NOTE]
====
For production environments, NFS is not recommended and supported for storage provisioning in SUSE Observability due to the potential risk of data corruption.
====


For our different installation profiles, the following are the defaulted storage requirements:

|===
|  | trial | 10 non-HA | 20 non-HA | 50 non-HA | 100 non-HA | 150 HA | 250 HA | 500 HA | 4000 HA

| *Retention (days)*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *Storage requirement*
| 154Gi
| 335Gi
| 375Gi
| 475Gi
| 525Gi
| 2595Gi
| 2695Gi
| 3595Gi
| 6995Gi
|===

[NOTE]
====
The storage estimates presented take into account a default of 14 days of retention for NONHA and 1 month for HA installations. For short lived test instances the storage sizes can be further reduced.
====


For more details on the defaults used, see the page xref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[Configure storage].

=== Namespace resource limits

It isn't recommended to set a ResourceQuota as this can interfere with resource requests. The resources required by SUSE Observability will vary according to the features used, configured resource limits and dynamic usage patterns, such as Deployment or DaemonSet scaling.

If it's necessary to set a ResourceQuota for your implementation, the namespace resource limit should be set to match the node xref:/setup/install-stackstate/requirements.adoc#_resource_requirements[sizing requirements].

[#client-browser]
== Client (browser)

To use the SUSE Observability GUI, you must use one of the following web browsers:

* Chrome
* Firefox
