= SUSE Observability Cluster performance test
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

This page provides a method to profile a running cluster to verify it is performing according to expectation. This can be used when experiencing degraded performance to actively investigate how several parts are performing. This
is an addition to the xref:/setup/install-stackstate/support-package-logs.adoc[Support Package (Logs)] collector for collecting logs in general

== Notes

The script should be executed from a host that has kubectl configured with access to the SUSE Observability cluster or from any other host with the necessary permissions and connectivity to the cluster.
This can be done directly on the host using the root user or via sudo.  If kubeconfig is not set, use the command `export KUBECONFIG=$PATH-TO-YOUR/kubeconfig`.

== Usage

The script needs to be downloaded and run directly on the host, using the `root` user or `sudo`.

=== Download and run the script

Download the xref::attachment$suse-observability_performance_collector.sh[suse-observability_performance_collector.sh] script.

* Save the script as: `suse-observability_performance_collector.sh`
* Run the script using the following commands:
+
[,bash]
----
bash suse-observability_performance_collector.sh
----
+
This will generate a file in the current directory named `suse-observability_performance_<date>.tar.gz`. Please upload this file to the case.

Additional arguments can be specified, for now just to choose a different namespace:
[,bash]
----
> bash suse-observability_performance_collector.sh -h
SUSE Observability performance measurement tool.
Runs some rudimentary performance tests on a deployed instance to validate performance.

Usage: $0 [options] [<namespace>]

options:
  -h  Print this help

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----
