= SUSE Observability Cluster performance test
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

This page provides a method to profile a running cluster to verify it is performing according to expectation. This can be used when experiencing degraded performance to actively investigate how several parts are performing. This is an addition to the xref:/setup/install-stackstate/support-package-logs.adoc[Support Package (Logs)] collector for collecting logs in general.

== Notes

The script should be executed from a host that has kubectl configured with access to the {stackstate-product-name} cluster or from any other host with the necessary permissions and connectivity to the cluster.
This can be done directly on the host using the root user or via sudo. If kubeconfig is not set, use the command `export KUBECONFIG=$PATH-TO-YOUR/kubeconfig`.

== Usage

The script needs to be downloaded and run directly on the host, using the `root` user or `sudo`.

=== Download and run the script

Download the xref::attachment$suse-observability_performance_collector.sh[suse-observability_performance_collector.sh] script.

* Save the script as: `suse-observability_performance_collector.sh`
* Run the script using the following commands:
+
[,bash]
----
bash suse-observability_performance_collector.sh
----
+
This will generate a file in the current directory named `suse-observability_performance_<date>.tar.gz`. Upload this file to the case.

Additional arguments can be specified. For example, to choose a different namespace:
[,bash]
----
> bash suse-observability_performance_collector.sh -h
SUSE Observability performance measurement tool.
Runs some rudimentary performance tests on a deployed instance to validate performance.

Usage: $0 [options] [<namespace>]

options:
  -h  Print this help

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----

== Reference performance

Below is an output we use as reference for the performance of a system, which we also use to tweak our own profiles. Customer disk and
speeds should approach these numbers.

----
=== SUSE Observability Performance Summary ===
Date: 2026-03-06T07:59:22Z

--- Hdfs Disk Buffered ---
  suse-observability-hbase-hdfs-dn-0                           154 MB/s
  suse-observability-hbase-hdfs-dn-1                           135 MB/s
  suse-observability-hbase-hdfs-dn-2                           154 MB/s

--- Hdfs Disk Direct ---
  suse-observability-hbase-hdfs-dn-0                           59.8 MB/s
  suse-observability-hbase-hdfs-dn-1                           58.8 MB/s
  suse-observability-hbase-hdfs-dn-2                           59.2 MB/s

--- Kafka Disk Buffered ---
  suse-observability-kafka-0                                   158 MB/s
  suse-observability-kafka-1                                   146 MB/s
  suse-observability-kafka-2                                   156 MB/s

--- Kafka Disk Direct ---
  suse-observability-kafka-0                                   59.5 MB/s
  suse-observability-kafka-1                                   59.5 MB/s
  suse-observability-kafka-2                                   59.4 MB/s

--- Kafka Producer Local ---
  suse-observability-kafka-0                                   55285.272004 records/sec (53.99 MB/sec), 507.46 ms avg latency
  suse-observability-kafka-1                                   56060.096423 records/sec (54.75 MB/sec), 489.71 ms avg latency
  suse-observability-kafka-2                                   56306.306306 records/sec (54.99 MB/sec), 492.49 ms avg latency

--- Kafka Producer Remote ---
  suse-observability-kafka-0                                   71797.817346 records/sec (70.12 MB/sec), 378.06 ms avg latency
  suse-observability-kafka-1                                   75357.950264 records/sec (73.59 MB/sec), 361.79 ms avg latency
  suse-observability-kafka-2                                   71530.758226 records/sec (69.85 MB/sec), 372.92 ms avg latency
----

Clarifications:

- Buffered IO relates to raw disk throughput, allowing data to buffer in the kernel
- Direct disk measures disk throughput using O_DIRECT, disallowing buffering, which more closely approximates our databases using fsync() and gives insight in the latency of the underlying storage
- Kafka Producer local puts data into kafka over localhost, remote over the network. Remote can be faster than local when CPU is the bottleneck rather than network (which was the case here, causing remote to be more efficient).