= SUSE Observability Support Package (logs)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

This page provides tools and guidance for collecting logs from a SUSE Observability cluster. These logs are essential for diagnosing issues, identifying root causes, and troubleshooting problems in clusters that may not be functioning as expected.
If you're experiencing unexpected behavior, degraded performance, or a failure in your SUSE Observability cluster, this page will help you gather the necessary data to understand what went wrong and take corrective action.

== Notes

The script should be executed from a host that has kubectl configured with access to the SUSE Observability cluster or from any other host with the necessary permissions and connectivity to the cluster.
This can be done directly on the host using the root user or via sudo.  If kubeconfig is not set, use the command `export KUBECONFIG=$PATH-TO-YOUR/kubeconfig`.

== Usage

The script needs to be downloaded and run directly on the host, using the `root` user or `sudo`.

=== Download and run the script

Download the xref::attachment$suse-observability_logs_collector.sh[suse-observability_logs_collector.sh] script.

* Save the script as: `suse-observability_logs_collector.sh`
* Run the script using the following commands:
+
[,bash]
----
bash suse-observability_logs_collector.sh
----
+
This will generate a file in the current directory named `suse-observability_logs_<date>.tar.gz`. Please upload this file to the case.

Additional arguments can be specified:
[,bash]
----
> bash suse-observability_logs_collector.sh -h
SUSE Observability support package collector.
Fetches details of a SUSE Observability instance for troubleshooting.

Usage: ./suse-observability_logs_collector.sh [options] [<namespace>]

options:
  -h  Print this help
  -e  Fetch logs for suse-observability pods from Elasticsearch
  -r  Time range for logs to fetch from Elasticsearch,
      when not specified "7d" is used

<namespace>:
  The namespace that is running SUSE Observability, or
  "suse-observability" when not specified
----

E.g. to collect 3 days of logs from the embedded elasticsearch when {stackstate-product-name} is deployed in namespace `my-observability`:
[,bash]
----
bash suse-observability_logs_collector.sh -e -r 3d my-observability
----
