= Monitores
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Descripción general

SUSE Observability tiene las mejores prácticas codificadas a través de monitores. Los monitores de SUSE Observability no solo supervisan métricas, eventos o registros, sino que también pueden monitorizar la topología y los metadatos para detectar problemas comunes, asegurando el cumplimiento y la adherencia a los estándares de la industria.
Combinando monitores con nuestra inteligencia única de resolución de problemas, SUSE Observability detecta rápidamente problemas relacionados y aconseja sobre cómo remediarlos. Este enfoque proactivo reduce el riesgo de problemas no detectados y ayuda a mantener un entorno de Kubernetes saludable y robusto.
Los monitores están acompañados de guías de remediación específicas para el recurso que ha generado la alerta y la condición monitorizada para guiar a nuestros usuarios en su resolución de problemas.

== Supervisión de resultados

Los resultados de los monitores se muestran en dos lugares:

. En las páginas de resaltado de todos los recursos para ver inmediatamente qué está sucediendo y cómo remediarlo.
. En el panel lateral si seleccionas un elemento en la topología para darte una indicación rápida de los problemas de ese componente.

== Guías de remediación

Las guías de remediación se muestran en el panel de estado del monitor que aparece si abres un monitor haciendo clic en el mensaje en la perspectiva de resaltado de un recurso.

== Consulte también

* xref:/use/alerting/kubernetes-monitors.adoc[Monitores listos para usar para Kubernetes]
