ifdef::ss-ff-stackpacks2_enabled[]
= Getting Started with Open Telemetry Mappings
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Overview of Open Telemetry Mappings

{stackstate-product-name} can automatically derive application and infrastructure topology from OpenTelemetry (OTel) telemetry data.
This is achieved through OpenTelemetry topology mappings which declaratively transform trace and metric signals into topology components (vertices) and relations (edges).

== Overview

At a high-level, topology generation from OpenTelemetry works as follows:

* OpenTelemetry telemetry (metrics and/or traces) is received by the Collector.
* The OTel collector uses a topology connector that evaluates configured mappings against the telemetry.
* When mapping conditions match telemetry, components and/or relations are produced.
* These topology objects are consumed by the `sync` service and merged into the topology graph.
* Mappings are declarative, YAML-based, and evaluated continuously as telemetry flows through the system.

Currently supported signals:

* Metrics
* Traces

[NOTE]
====
Log-based topology generation is not yet supported.
====

For more information on component and relation mappings, see xref:/setup/otel/otelmappings/concepts.adoc[concepts] page.

endif::ss-ff-stackpacks2_enabled[]