= Effacer les données stockées
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

Les données dans SUSE Observability sont divisées en quatre ensembles différents :

* Données Elasticsearch
* Données du topic Kafka
* Données StackGraph
* Données de métriques

Avec autant de données à stocker, il est important d'avoir les moyens de les gérer. Il y a une période de conservation des données standard de 30 jours définie dans SUSE Observability. Ceci peut être configuré selon vos besoins en utilisant le CLI SUSE Observability. En savoir plus sur xref:/setup/data-management/data_retention.adoc[la conservation des données SUSE Observability].

== Effacer les données manuellement

Pour effacer les données stockées dans SUSE Observability fonctionnant sur Kubernetes, il est recommandé d'effectuer une installation propre :

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Désinstaller SUSE Observability]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Supprimer tous les PVC]
. Installer à nouveau SUSE Observability en utilisant la même configuration qu'auparavant, sur xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] ou xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
