ifdef::ss-ff-stackpacks2_enabled[]
= Visión general de integraciones personalizadas
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-01-06
:page-revdate: {revdate}
:description:  Visión general de integraciones personalizadas

[IMPORTANT]
====
Las Integraciones Personalizadas son características en pre-producción, no lanzadas y, por lo tanto, podrían experimentar cambios drásticos a medida que evolucionan. No está destinada a uso en producción. Pero se puede probar en entornos no de producción.
====

== Descripción general

Las integraciones personalizadas aprovechan Open Telemetry para recopilar y enviar datos de telemetría (métricas, trazas, registros) desde diversas fuentes a {stackstate-product-name}. Al utilizar Open Telemetry, los usuarios pueden instrumentar sus aplicaciones y servicios para obtener información sobre el rendimiento, la fiabilidad y la salud operativa.
En el lado de {stackstate-product-name}, el xref:setup/custom-integrations/otelmappings/README.adoc[Mapeos de Open Telemetry] procesa los datos de telemetría entrantes, aplica las transformaciones necesarias y los mapea a las entidades apropiadas dentro de {stackstate-product-name}. xref:use/alerting/k8s-add-monitors-cli.adoc[Añadiendo monitores usando la CLI], xref:setup/custom-integrations/metric-bindings/index.adoc[asignaciones de métricas] y xref:setup/custom-integrations/ui-presentation/README.adoc[presentación en la UI] se pueden definir para presentar la telemetría ingerida en la UI, añadir alertas y observabilidad. Todo se envuelve en un xref:setup/custom-integrations/develop.adoc[stackpack] para su distribución.

== Configuración de desarrollo

Las Integraciones Personalizadas deben desarrollarse contra una ampliación en pre-producción de la {stackstate-product-name} plataforma. Para obtener una configuración en pre-producción para comenzar a desarrollar tu integración personalizada, hay dos opciones:

=== Instancia SaaS (Recomendada):
Para los equipos internos de SUSE, recomendamos solicitar una instancia SaaS al equipo de {stackstate-product-name}. Estas instancias tienen Integraciones Personalizadas habilitadas y se actualizan automáticamente al menos con cada nueva versión; en algunos casos, recibirían versiones preliminares que contienen corrección de fallos importantes o mejoras en características experimentales.
Contáctanos a través del canal dedicado (próximamente se anunciará).

=== Autoalojado:
Puedes habilitar Integraciones Personalizadas en tu propia instalación autoalojada de {stackstate-product-name} configurando algunas banderas de características al instalar a través de helm:

    . Genera el `custom_integrations_values.yaml`. Esta guía asume que lo guardas en el `$VALUES_DIR`.

+
.$VALUES_DIR/custom_integrations_values.yaml
[,yaml]
----
global:
  features:
    experimentalStackpacks: true
----
+

    . Despliega el chart Helm de {stackstate-product-name} con los valores generados junto con el `.$VALUES_DIR/custom_integrations_values.yaml`.

+
.helm_deploy.sh
[,text]
----
helm upgrade --install \
    --namespace suse-observability \
    --create-namespace \
    --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
    --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
    --values $VALUES_DIR/custom_integrations_values.yaml \
    suse-observability \
    suse-observability/suse-observability
----
+

endif::ss-ff-stackpacks2_enabled[]
