= Solución de problemas de notificaciones
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Cuando un canal de notificación no logra enviar notificaciones, la vista general de notificaciones mostrará un estado de error. Para inspeccionar los errores:

. Haz clic en la notificación
. La parte superior de la página muestra un banner con un resumen de los errores
. Desplázate hacia abajo hasta los canales, haz clic en el enlace "error" para el canal o canales afectados para abrir los detalles del error.

== Errores habituales

=== Slack

Los errores de Slack suelen contener un código de error:

* `token_revoked`, `token_expired` o `missing_scope`: Estos códigos de error indican un problema con la autorización de SUSE Observability para publicar mensajes en Slack. Para resolver estos, recrea el canal para reautorizar a SUSE Observability con Slack de manera que se concedan todos los permisos requeridos.
* Para otros códigos de error, consulta https://api.slack.com/automation/cli/errors[códigos de error de la API de Slack].

=== HTTP

La mayoría de los canales, específicamente el webhook, esperan una respuesta HTTP con estado 200 OK. Otras respuestas se consideran un error. Los errores HTTP contienen un mensaje, generalmente corto, y el código de estado que se recibió en lugar de 200 OK.

Verifica que cualquier URL y token configurados sean correctos y, en el caso del webhook, que las solicitudes POST se manejen correctamente y devuelvan una respuesta 200 OK.

=== Otros

En caso de que el error sea del tipo "Otro", es muy probable que SUSE Observability no pueda ni siquiera conectarse al servicio externo o webhook. Verifica que la URL sea correcta, se pueda resolver y pueda ser accedida por SUSE Observability.
