= Schritte zum Upgrade
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

[CAUTION]
====
Um von StackState 6.0 auf SUSE Observability zu upgraden, folgen Sie dem xref:/setup/upgrade-stackstate/migrate-from-6.adoc[Migrationshandbuch].
====


== Übersicht

Dieses Dokument beschreibt das Upgrade-Verfahren für SUSE Observability.

== Vor dem Upgrade

Seien Sie sich beim Ausführen eines SUSE Observability Upgrades der folgenden Punkte bewusst:

[CAUTION]
====
*Lesen Sie immer die* xref:/setup/upgrade-stackstate/version-specific-upgrade-instructions.adoc[*versionsspezifischen Upgrade-Hinweise*] *vor dem Upgrade von SUSE Observability.*
====


[CAUTION]
====
Beim Upgrade eines StackPacks *werden alle Änderungen, die Sie an den Konfigurationselementen dieses StackPacks vorgenommen haben, überschrieben*. Siehe xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[Konfigurationssperre] für weitere Informationen.
====


[WARNING]
====
Wenn in Ihrer SUSE Observability-Installation *Hotfixes* installiert sind, kontaktieren Sie vor dem Upgrade den technischen Support von SUSE Observability.
====


== Schritte zum Upgrade

=== Kleinere oder Wartungsversion von SUSE Observability

Eine kleinere Version von SUSE Observability wird durch eine Änderung der zweiten Ziffer der Versionsnummer angezeigt, zum Beispiel 4.1.0. Wartungsversionen werden durch eine Änderung der dritten Ziffer der Versionsnummer identifiziert, zum Beispiel 4.1.1.

Wenn Sie auf eine neue *kleinere* Version von SUSE Observability oder eine *Wartungsversion* Version upgraden, sind SUSE Observability selbst und die StackPacks mit der aktuellen Installation kompatibel.

Ein kleineres Upgrade besteht aus den folgenden Schritten:

. <<_create_a_backup,Erstellen Sie eine Sicherung>>
. <<_upgrade_suse_observability,Upgrade SUSE Observability>>
. <<_verify_the_new_installation,Überprüfen Sie die neue Installation>>
. Überprüfen Sie, ob installierte StackPacks ein Upgrade benötigen

=== Große Version von SUSE Observability

Eine große Version von SUSE Observability wird durch eine Änderung der ersten Ziffer der Versionsnummer angezeigt, zum Beispiel 4.0.0.

Wenn Sie auf eine neue *große* Version von SUSE Observability upgraden, können SUSE Observability und die installierten StackPacks mit der aktuellen Installation inkompatibel sein. Für Details, überprüfen Sie die xref:/setup/upgrade-stackstate/version-specific-upgrade-instructions.adoc[versionsspezifischen Upgrade-Hinweise].

Ein großes Upgrade besteht aus den folgenden Schritten:

. xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc#_create_a_backup[Erstellen Sie eine Sicherung]
. Optional: xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc#_uninstall_stackpacks_optional[Deinstallieren Sie die StackPacks]
. xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc#_upgrade_stackstate[Upgrade SUSE Observability]
. Optional: xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc#_install_stackpacks_optional[Installieren Sie die StackPacks]
. xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc#_verify_the_new_installation[Überprüfen Sie die neue Installation]

== Anleitung für ein Upgrade

=== Erstellen Sie eine Sicherung

Vor dem Upgrade von SUSE Observability wird empfohlen, Ihre Konfigurations- und Topologiedaten zu sichern:

* xref:/setup/data-management/backup_restore/kubernetes_backup.adoc[Kubernetes-Sicherung]
* xref:/setup/data-management/backup_restore/configuration_backup.adoc[Konfigurationssicherung]

[NOTE]
====
Bitte beachten Sie, dass es nicht möglich sein wird, die Sicherung in der geupgradeten Version von SUSE Observability wiederherzustellen. Die SUSE Observability-Sicherung kann nur in der SUSE Observability-Version vor dem Upgrade wiederhergestellt werden.
====


=== Upgrade SUSE Observability

Stellen Sie sicher, dass Sie die Versionshinweise und alle optionalen Upgrade-Hinweise überprüfen, bevor Sie das Upgrade durchführen.

[tabs]
====

Kubernetes::
+
--

. Holen Sie sich das neueste Helm-Chart, indem Sie `helm repo update` ausführen.
. Überprüfen Sie die xref:/setup/upgrade-stackstate/version-specific-upgrade-instructions.adoc[versionsspezifischen Upgrade-Hinweise] auf alle Änderungen zwischen Ihrer aktuellen Version und der Version, auf die Sie upgraden werden. Wenn Änderungen an den in Ihrer `values.yaml` Datei angegebenen Konfigurationselementen vorgenommen wurden, sollte die Datei aktualisiert werden.
. Um ein Upgrade durchzuführen, verwenden Sie denselben Helm-Befehl wie für die xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[erste Kubernetes-Installation]. Das neue Helm-Chart wird neuere Versionen von Docker-Images abrufen und das Upgrade durchführen.
--

OpenShift::
+
--

. Holen Sie sich das neueste Helm-Chart, indem Sie `helm repo update` ausführen.
. Überprüfen Sie die xref:/setup/upgrade-stackstate/version-specific-upgrade-instructions.adoc[versionsspezifischen Upgrade-Hinweise] auf alle Änderungen zwischen Ihrer aktuellen Version und der Version, auf die Sie upgraden werden. Wenn Änderungen an den in Ihrer `values.yaml` Datei angegebenen Konfigurationselementen vorgenommen wurden, sollte die Datei aktualisiert werden.
. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_additional_openshift_values_file[Aktualisieren Sie die `openshift-values.yaml`] Datei.
. Um ein Upgrade durchzuführen, verwenden Sie denselben Helm-Befehl wie für die xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[erste OpenShift-Installation]. Das neue Helm-Chart wird neuere Versionen von Docker-Images abrufen und das Upgrade durchführen.
--

====

=== Überprüfen Sie die neue Installation

Sobald SUSE Observability geupgradet und gestartet wurde, überprüfen Sie, ob die neue Installation von SUSE Observability erreichbar ist und die Anwendung läuft.

== Siehe auch

* xref:/stackpacks/about-stackpacks.adoc#_upgrade_a_stackpack[Ein StackPack manuell upgraden]
* xref:/setup/upgrade-stackstate/version-specific-upgrade-instructions.adoc[Versionsspezifische Upgrade-Hinweise]
