= Monitors
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Overview

SUSE Observability has the best practices encoded via monitors. SUSE Observability monitors not only monitor metrics, events or logs but can also monitor the topology and meta-data to detect common issues, ensuring compliance and adherence to industry standards.
Combining monitors with our unique troubleshooting intelligence, SUSE Observability quickly detects issues that are related and advises on how to remediate them. This proactive approach reduces the risk of undetected problems and helps maintain a healthy and robust Kubernetes environment.
Monitors are accompanied by remediation guides specific to the resource on which is alerted and the monitored condition to guide our users in their troubleshooting.

== Monitor results

Monitor results are shown in two places:

. On highlight pages of all resources to immediately see what is going on and how to remediate it.
. On the right-hand side panel if you select an element in the topology to give you a quick indication of issues for that component.

== Remediation guides

Remediation guides are shown on the Monitor Status drawer which is shown if you open a monitor by clicking on the message on the Highlight perspective of a resource.

== See also

* xref:/use/alerting/kubernetes-monitors.adoc[Out-of-the-box monitors for Kubernetes]
