= Role based access control (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Access Management helps you manage who has access to the specific topology elements, metric data, traces, UI elements, and which APIs they can call.

RBAC is an authorization system that provides fine-grained access management of SUSE Observability resources, a clean and easy way to audit user privileges and to fix identified issues with access rights.

== What can you do with RBAC?

Here are examples of what you can do with RBAC:

* Allow one user to have access to the development cluster only, another one to both the production and development cluster and a third can access the development cluster and only 1 namespace in the production cluster.
* Give a small group of users an administrator role to setup and configure SUSE Observability. While giving all developers a troubleshooter role to view all topology, metrics, traces, logs and events, but with limited configuration capability.

== What's a role in SUSE Observability?

A role in SUSE Observability is a combination of a configured subject and a set of xref:/setup/security/rbac/rbac_permissions.adoc[permissions]. Process of setting up a role in SUSE Observability is described in xref:/setup/security/rbac/rbac_roles.adoc[How to set up roles].

== Sources of RBAC roles

You can define roles in several ways.  All use the same xref:/setup/security/rbac/rbac_permissions.adoc[Permissions].

* **Configuration** - in the xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[helm values] for SUSE Observability
* **Dynamic** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[use the `sts` CLI]
* **Mapped from Kubernetes** - xref:/setup/security/rbac/rbac_rancher.adoc[map Kubernetes `Roles` and `RoleBindings`]

== More on RBAC configuration

* xref:/setup/security/rbac/rbac_permissions.adoc[Permissions]
* xref:/setup/security/rbac/rbac_roles.adoc[How to set up roles]
* xref:/setup/security/rbac/rbac_rancher.adoc[Use with Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Scopes]
* xref:/setup/security/authentication/README.adoc[How to configure authentication]
