= Acerca de StackPacks
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojado v5.1.x

== Descripción general

Los StackPacks amplían la funcionalidad de SUSE Observability y ofrecen integración automatizada con sistemas externos. Se pueden instalar y desinstalar fácilmente desde la página de StackPacks en SUSE Observability.

Existen dos tipos de StackPack: complementos e integraciones. Los complementos e integraciones de StackPack disponibles se pueden encontrar en la página de *StackPacks* en la interfaz de usuario de SUSE Observability.

== Instalar o desinstalar un StackPack

Los StackPacks se pueden instalar y desinstalar desde la página de *StackPacks* en SUSE Observability. Se proporcionan instrucciones completas para instalar y desinstalar el StackPack.

[NOTE]
====
*Tenga en cuenta que:*

* Un StackPack puede requerir pasos de instalación *manual* o configuración del sistema externo. Por favor, lea las instrucciones proporcionadas con atención.
* Cuando se desinstala un StackPack o una instancia de StackPack, *todos los datos recibidos a través del StackPack (instancia) serán eliminados de SUSE Observability.*
* Cualquier configuración o instalación (manual) de componentes de StackPack en un sistema externo puede necesitar ser desinstalada por separado.

====


=== Instancias de StackPack

Algunos StackPacks permiten conectarse a múltiples cuentas en un sistema externo. Cada cuenta se configura en una instancia separada del StackPack.

Por ejemplo, el StackPack de AWS puede conectarse a múltiples cuentas de AWS y combinar información de todas las cuentas en SUSE Observability. Para cada cuenta, se configura una instancia separada de SUSE Observability con la información necesaria para recibir datos de esa cuenta de AWS.

== Actualizar la versión de un StackPack

[CAUTION]
====
Cuando se actualiza un StackPack, *cualquier cambio realizado en los elementos de configuración de ese StackPack será sobrescrito*. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[elementos de configuración bloqueados].
====


Si hay una nueva versión de StackPack disponible, se mostrará una alerta en la página de StackPack de la interfaz de usuario de SUSE Observability y tendrás la opción de ver los detalles de la actualización y leer las notas de la versión. Si la nueva versión es una actualización menor de la versión actualmente instalada, también puedes actualizar la versión del StackPack desde aquí.

=== Nueva versión menor de StackPack

Para actualizar a una nueva versión menor de un StackPack, haz clic en *ACTUALIZAR AHORA* en la página de StackPack en la interfaz de usuario de SUSE Observability.

Ten en cuenta que todos los elementos de configuración del StackPack se sobrescribirán cuando actualices la versión. Para continuar utilizando cualquier cambio realizado en estos, elige *MANTENER* la configuración existente cuando actualices la versión del StackPack. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[elementos de configuración bloqueados].

=== Nueva versión mayor de StackPack

[CAUTION]
====
Cuando se actualiza un StackPack, *cualquier cambio realizado en los elementos de configuración de ese StackPack será sobrescrito*. Para más detalles, consulte xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[elementos de configuración bloqueados].
====


Para actualizar a una nueva versión mayor de un StackPack, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[desinstala y reinstala] el StackPack.

[TIP]
====

Continúa utilizando los cambios realizados en los elementos de configuración personalizados del StackPack después de la actualización:

. Antes de actualizar, exporta cada elemento personalizado:
 ** Ve a la página de *Configuración* en la interfaz de usuario de SUSE Observability.
 ** Haz clic en *Exportar* en el menú *...* para cada elemento personalizado.
. Actualiza la versión del StackPack (desinstala y reinstala).
. Cambia el `name` y el `identifier` para cada elemento exportado:
 ** Abre el archivo de exportación en un editor de texto.
 ** Edita los campos de nivel superior `name` y `identifier`.
 ** Guarda la exportación.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Importa] el(los) archivo(s) de exportación actualizado(s).
. Los elementos de configuración personalizados estarán ahora disponibles en SUSE Observability y se pueden copiar a los elementos de configuración del StackPack recién instalado.

====


== Elementos de configuración bloqueados

Los StackPacks contienen información de configuración para SUSE Observability que se instala cuando se instala el StackPack (instancia). Entre otras cosas, esto podría incluir plantillas de componentes, funciones, acciones de componentes y vistas. Cuando se actualiza un StackPack, *los elementos de configuración instalados por la versión anterior del StackPack serán sobrescritos por los de la nueva versión del StackPack.* Esto significa que cualquier cambio manual realizado en estos elementos de configuración será sobrescrito cuando se actualice el StackPack.

Para evitar que un usuario realice cambios en los elementos de configuración instalados por un StackPack que serán sobrescritos en la actualización, estos elementos de configuración están *bloqueados* por defecto. Esto significa que están protegidos de ser modificados por el usuario y deben ser *desbloqueados* explícitamente antes de que puedan ser cambiados.

[TIP]
====

Puedes xref:/setup/data-management/backup_restore/configuration_backup.adoc[hacer una copia de seguridad de los elementos de configuración]. Ten en cuenta que el estado de bloqueo de los elementos de configuración no se exportará como parte de una copia de seguridad de configuración.
====

