= Página de análisis
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojada

La página de análisis proporciona una interfaz potente y flexible para consultar y analizar tus datos de observabilidad utilizando xref:/develop/reference/k8sTs-stql_reference.adoc[consultas STQL].
Este entorno interactivo te permite ir más allá de los paneles predefinidos y obtener una comprensión más profunda de la salud, el rendimiento y las dependencias de tu entorno dinámico.

[CAUTION]
====
*La página de análisis queda obsoleta, pero aún puedes habilitarla configurando permisos específicos. Sin embargo, recomendamos encarecidamente aprovechar los StackPacks para una observabilidad y análisis mejorados, ya que proporcionan una alternativa más robusta y activamente soportada.*

Se requieren dos permisos para habilitar la página de análisis:

* `access-analytics`
* `execute-scripts`

Más detalles: xref:/setup/security/rbac/rbac_permissions.adoc[Gestión de permisos]

====

