= Version specific upgrade instructions
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Overview

[CAUTION]
====
*Review the instructions provided on this page before you upgrade!*

This page provides specific instructions and details of any required manual steps to upgrade to each supported version of SUSE Observability. Any significant change that may impact how SUSE Observability runs after upgrade will be described here, such as a change in memory requirements or configuration.

*Read and apply all instructions from the version that you are currently running up to the version that you will upgrade to.*
====

== Upgrade instructions

=== Next version

Minio was replaced with S3Proxy, this affects the backup and restore process. If you are using the backup and restore feature (i.e. `global.backup.enabled=true`), please follow the instructions in the xref:setup/data-management/backup_restore/migration_to_s3proxy.adoc[migration guide] to migrate your backup and restore configuration to S3Proxy.

== 2.7.0

The `backup.enabled` Helm value has been replaced by `global.backup.enabled`. Using the old `backup.enabled=true` value will now cause the deployment to **fail**.

== See also

* xref:/setup/release-notes/README.adoc[Release Notes]
* xref:/setup/upgrade-stackstate/steps-to-upgrade.adoc[Steps to upgrade SUSE Observability]
