= Single password
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Out of the box, SUSE Observability is configured with a single password configuration, xref:/k8s-suse-rancher-prime.adoc#_installation[configured during installation]. This authenticates users with a single, password that must be provided during installation. 

This is the simplest way to get started with SUSE Observability, but for production one of the other xref:/setup/security/authentication/authentication_options.adoc[authentication options] is recommended.

== Get the password from an external secret

When the default password should come from an external secret, follow xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[these steps] but fill in the following data:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

The password encoding can be one of these:
* For a plain text password provide: `$plain$your-password` (`$plain$` is a prefix indicating plain text)
* For a bcrypted password provide: `bcrypt-hashed-password`. Creating a bcrypted hash of the password can be done using `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== See also

* xref:/setup/security/authentication/authentication_options.adoc[Authentication options]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissions for predefined SUSE Observability roles]
* xref:/setup/security/rbac/rbac_roles.adoc[Create RBAC roles]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[External Secrets]
