= Rédigez un guide de remédiation pour aider les utilisateurs à résoudre des problèmes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

{stackstate-product-name} fournit xref:/use/alerting/k8s-monitors.adoc[des moniteurs prêts à l'emploi], qui offrent une surveillance des problèmes courants pouvant survenir dans un cluster Kubernetes. Ces moniteurs contiennent également des guides de remédiation prêts à l'emploi qui sont destinés à aider les utilisateurs à résoudre avec précision les problèmes. Ils sont créés en utilisant les meilleures pratiques et les connaissances de la communauté. Suivez les indications sur cette page pour apprendre à rédiger vous-même un guide de remédiation efficace.

== Autres indications

* Fournissez des instructions étape par étape pour guider un utilisateur dans la résolution du problème détecté par le moniteur ;
* Assurez-vous que les instructions sont ordonnées par les causes les plus probables.
* Si possible, incluez des liens vers des données et/ou des ressources pertinentes pour accélérer l'enquête.
* Soyez concis et allez droit au but :
 ** Évitez de trop expliquer - ajoutez des liens vers la documentation de soutien si nécessaire ;
 ** Évitez d'utiliser une table des matières et des blocs de contenu similaires ;
 ** Évitez d'avoir un résumé du même contenu ;
* Essayez de structurer le guide de manière organisée. Utilisez :
 ** des puces
 ** de la numérotation
 ** des phrases courtes
 ** des paragraphes
 ** exemples formatés en ligne
* S'il y a des points ouverts (il peut y avoir différentes causes qui sont encore inconnues), fournissez des conseils pour escalader le problème. Par exemple, fournissez à l'utilisateur un lien/numéro de support, etc.

== Exemple de guide de remédiation

----
When a Kubernetes container has errors, it can enter into a state called CrashLoopBackOff, where Kubernetes attempts to restart the container to resolve the issue. The container will continue to restart until the problem is resolved.Take the following steps to diagnose the problem:

### Pod Events

Check the pod events to identify any explicit errors or warnings.
1. Go to the "Events" section in the middle of the [Pod highlight page](/#/components/\{{ componentUrnForUrl \}})
2. Check if there is are events like "BackOff", "FailedScheduling", "FailedAttachVolume" or "OOMKilled" in the Alert Category by clicking on 'Alerts'.
3. You can see the details of the event (click on the event) to give more information about the issue.
4. If the 'Show related event' option is enabled all events of resources related to this resource like a deployment will also show up and can give you a clue if any change on them is causing this issue. You can see this by checking if there is a correlation between the time of a deployment and a change of behaviour seen by the metrics and events of this pod.
For easy correlation you can use 'shift'-'click' to add markers to the different graph, log and event widgets.

### Container Logs
Check the container logs for any explicit errors or warnings
Inspect the [Logs](/#/components/\{{ componentUrnForUrl \}}#logs) of all the containers in this pod.
Search for hints in the logs by:
1.  Looking for changes in logging pattern, by looking at the number of logs per time unit (The histogram bars).
    In many cases the change in pattern will indicate what is going on.
    You can click-drag on the histogram bars to narrow the logs displayed to that time-frame.
2.  Searching for "Error" or "Fatal" in the search bar.
3.  Looking at the logs around the time that the monitor triggered

### Recent Changes
Look at the pod age in the "About" section on the [Pod highlight page](/#/components/\{{ componentUrnForUrl \}}) to identify any recent deployments that might have caused the issue
1. The "Age" is shown in the "About" section on the left side of the screen
2. If the "Age" and the time that the monitor was triggered are in close proximity then take a look at the most recent deployment by clicking on [Show last change](/#/components/\{{ componentUrnForUrl \}}#lastChange).
----

== Insertion de liens

La syntaxe que nous utilisons est différente pour les "liens profonds" et les "liens dans la page". Les "liens profonds" redirigeront l'utilisateur depuis la page actuelle, tandis que les "liens dans la page" garderont l'utilisateur sur la même page.

=== Liens profonds

Pour lier à n'importe quelle perspective (par exemple, "points saillants", "topologie", "événements", "métriques") de la ressource actuelle, utilisez la syntaxe suivante :

----
[highlight page](/#/components/\{{ componentUrnForUrl \}})
----

----
[topology](/#/components/{{ componentUrnForUrl }}/topology)
----

----
[events](/#/components/{{ componentUrnForUrl }}/events)
----

----
[metrics](/#/components/{{ componentUrnForUrl }}/metrics)
----

=== Liens dans la page

Pour lier à des données supplémentaires (par exemple, "afficher les journaux", "afficher le dernier changement", "afficher l'état", "afficher la configuration") sur la ressource actuelle, utilisez la syntaxe suivante :

----
[logs](/#/components/\{{ componentUrnForUrl \}}#logs)
----

----
[last change](/#/components/\{{ componentUrnForUrl \}}#lastChange)
----

----
[status](/#/components/\{{ componentUrnForUrl \}}#status)
----

----
[configuration](/#/components/\{{ componentUrnForUrl \}}#configuration)
----
