= Dépannage des moniteurs
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,Le résultat du moniteur ne s'affiche pas sur un composant>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,Le moniteur affiche une erreur dans l'aperçu de l'état du moniteur>>

=== Le résultat du moniteur ne s'affiche pas sur un composant

Vérifiez d'abord si le moniteur xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[produit des résultats]. Si c'est le cas mais que les résultats du moniteur ne s'affichent pas sur les composants, il pourrait y avoir un problème avec la liaison. Utilisez d'abord la commande suivante pour vérifier :

[,bash]
----
sts monitor status --id <id>
----

Si la sortie contient `Monitor health states with identifier which has no matching topology element (<nr>): ....`, cela montre que le `urnTemplate` peut ne pas générer un identifiant correspondant à la topologie. Pour remédier à cela, xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[revoyez votre urnTemplate].

=== Le moniteur affiche une erreur dans l'aperçu de l'état du moniteur

Obtenez l'état du moniteur via la CLI

[,bash]
----
sts monitor status --id <id>
----

La section `Monitor Stream errors:` affichera les erreurs survenant sur le moniteur et offrira une aide supplémentaire.

