= SUSE Observability documentation

SUSE Rancher product documentation for SUSE Observability.

To work locally:

* Fork this repo.
* `git clone --recursive <your_fork>`
* `cd stackstate-product-docs`
* `make environment`
* `make local`
* `make preview # Start a local http server. Or skip and just load build/site/index.html into a browser.`

== Feature flag toggle for content visibility in production documentation

*Attribute location*: `ss-local-playbook.yml`
*Attribute defined*: `ss-ff: true`

Introduced in the `ss-local-playbook.yml` file, `ss-ff: true` ('ss' is stackstate & 'ff' is feature flag) hides the content encased in the condition in production docs but always displays the content in the netlify preview for review purposes.

For example, to hide a doc section titled 'User management' in production, set the attribute as `ss-ff-user-manage-url: true` in the ss-local-playbook.yml file.

The content to be hidden is encased within the `ifdef` function as follows:

ifdef::ss-ff[]

[content block]

endif::ss-ff[]

