= SUSE Observability documentation

SUSE Rancher product documentation for SUSE Observability.

To work locally:

* Fork this repo.
* `git clone --recursive <your_fork>`
* `cd stackstate-product-docs`
* `make environment`
* `make local`
* `make preview # Start a local http server. Or skip and just load build/site/index.html into a browser.`

== Feature flag toggle for content visibility in production documentation

An attribute is introduced in the `antora.yml` file - `hide: true/false`. "hide" is user-defined. This attribute hides/unhides the desired content in production docs as per the boolean value - "true"/"false" respectively. 

You can set the attribute as per requirement. For example, to hide a doc section titled "User management URL", you can set the attribute as "user-manage-url: false".

FYI, leaving the attribute value empty in the `antora.yml` file equates to 'false'.

The content to be hidden is encased within the `ifdef` function as follows:

----
ifdef::hide[]

[content block]

endif::hide[]
----
