= 要件
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自己ホスト型

== 概要

<<_client_browser,SUSE Observability クライアント (ブラウザ)>> の要件はページの下部にあります。

=== RancherとKubernetesの互換性
こちらの互換性ページをご覧ください xref:setup/install-stackstate/Compatibility Self Hosted.adoc[Rancher/Kubernetes 互換性]

=== リソースの要件

SUSE Observability には異なるインストールオプションがあります。SUSE Observability は、高可用性 (HA) または単一インスタンス (非高可用性) のセットアップでインストールすることが可能です。非 HA セットアップは、テスト目的のみに推奨されます。本番環境では、SUSE Observability を高可用性セットアップでインストールすることを推奨します。標準の本番デプロイメントでは、SUSE Observability Helm チャートが各サービスの 3 インスタンスを持つ冗長セットアップで多くのサービスをデプロイします。

以下の表には、異なるインストールオプションのリソース要件が記載されています。高可用性セットアップでは、監視対象環境の規模に応じて異なるインストールプロファイルを確認できます。
このサイズ表における観測ノードは、4 vCPU と 16GB のメモリを備えたものとみなされます。当社の `default node size`
観測クラスター内のノードが大きい場合、それは複数の `default nodes` としてカウントされることがありますので、12vCPU と 48GB のノードは、プロファイルを選択する際に観測下で 3 `default nodes` としてカウントされます。

|===
|  | トライアル | 10 非高可用性 | 20 非高可用性 | 50 非高可用性 | 100 非高可用性 | 150 HA | 250 HA | 500 HA | 4000 HA

| *CPU リクエスト*
| 7.0
| 7.0
| 9.3
| 14.0
| 23.6
| 49.6
| 61.6
| 85.1
| 212.1

| *CPU 制限*
| 15.1
| 15.1
| 19.4
| 28.8
| 47.9
| 105.2
| 128.3
| 176.2
| 281

| *メモリ リクエスト*
| 22.7Gi
| 22.7Gi
| 26.5Gi
| 30.9Gi
| 47.0Gi
| 127.0Gi
| 142.1Gi
| 166.4Gi
| 263.9Gi

| *メモリ 制限*
| 23.3Gi
| 23.3Gi
| 27.2Gi
| 31.0Gi
| 47.2Gi
| 131.8Gi
| 146.7Gi
| 171.2Gi
| 321.7Gi
|===

[NOTE]
====
プロファイルに示されている要件は、SUSE Observability サーバーを運用するために必要なリソースの総量を表しています。
SUSE Observability サーバーの異なるサービスが割り当てられることを確実にするために：

* 非高可用性インストールの場合、推奨ノードサイズは 4 vCPU、8GB です。
* 高可用性インストールの場合、500ノードまでの最小推奨ノードサイズは 8 vCPU、16GB です。
* 4000ノードの高可用性インストールの場合、最小推奨ノードサイズは 16 vCPU、32GB です。
====


これらは、異なるインストールオプションでSUSE Observabilityが消費できるリソースの上限と下限に過ぎません。実際のリソース使用量は、使用される機能、設定されたリソース制限、およびデプロイメントやデーモンセットのスケーリングなどの動的使用パターンに依存します。自己ホスト型のお客様には、デフォルトの要件から始めて、SUSE Observabilityコンポーネントのリソース使用量を監視することをお勧めします。

[NOTE]
====
最小要件には、アプリケーションのローリングアップデートをスムーズに行うための余分なCPU/メモリ容量は含まれていません。
====


SUSE Observabilityのインストールについては、以下のインストール手順に従ってください：

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[Kubernetes]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift]

=== ストレージ

SUSE Observabilityは、データを保存する必要があるサービスのために永続ボリュームクレームを使用します。クラスターのデフォルトストレージクラスは、コマンドラインまたは`values.yaml`ファイルで指定された値によって上書きされない限り、すべてのサービスに使用されます。すべてのサービスには、開始するのに適した事前設定されたボリュームサイズが付属していますが、必要に応じて後で変数を使用してカスタマイズできます。

[NOTE]
====
本番環境では、データ破損のリスクがあるため、SUSE ObservabilityのストレージプロビジョニングにNFSは推奨されず、サポートされていません。
====


異なるインストールプロファイルに対して、以下がデフォルトのストレージ要件です：

|===
|  | トライアル | 10 非高可用性 | 20 非高可用性 | 50 非高可用性 | 100 非高可用性 | 150 HA | 250 HA | 500 HA | 4000 HA

| *保持期間（日）*
| 3
| 30
| 30
| 30
| 30
| 30
| 30
| 30
| 30

| *ストレージ要件*
| 163GB
| 358GB
| 401GB
| 508GB
| 562GB
| 2.8TB
| 2.9TB
| 3.9TB
| 7.5TB
|===

[NOTE]
====
提示されたストレージの推定値は、非高可用性インストールのデフォルト保持期間14日および高可用性インストールの1か月を考慮しています。短命のテストインスタンスの場合、ストレージサイズはさらに削減できます。
====


使用されるデフォルトの詳細については、ページxref:/setup/install-stackstate/kubernetes_openshift/storage.adoc[ストレージの構成]を参照してください。

=== ネームスペースリソース制限

リソースリクエストに干渉する可能性があるため、ResourceQuotaを設定することは推奨されません。SUSE Observabilityが必要とするリソースは、使用される機能、設定されたリソース制限、およびデプロイメントやDaemonSetのスケーリングなどの動的使用パターンに応じて異なります。

実装のためにResourceQuotaを設定する必要がある場合、ネームスペースリソース制限はノードのxref:/setup/install-stackstate/requirements.adoc#_resource_requirements[リソース要件]に合わせて設定する必要があります。

== クライアント（ブラウザ）

SUSE Observability GUIを使用するには、次のいずれかのウェブブラウザを使用する必要があります。

* Chrome
* Firefox
