ifdef::ss-ff-stackpacks2_enabled[]
= UIプレゼンテーションの概念
:revdate: 2026-01-08
:page-revdate: {revdate}
:description: UIプレゼンテーションの概念

[IMPORTANT]
====
*ステータス:*現在、積極的に開発中です。

*Availability:*StackPacks 2.0の機能フラグの背後にあります。機能を有効にする方法については、xref:/setup/custom-integrations/overview.adoc[カスタム統合の概要]を参照してください。

このドキュメントは、現在の設計意図と高レベルな設定内容を説明しています。

注意：動作や機能はまだ実装されていません。

この機能は現在積極的に開発中であるため、動作、スキーマ、および機能はモデルの進化に伴い変更される可能性があります。
====

これはUIプレゼンテーションに関連する最も重要な概念の概要であり、始めるのに十分です。

== ComponentPresentation

UIプレゼンテーションモデルの中心的な概念は*コンポーネントプレゼンテーション*です。

`ComponentPresentation`は、アクティブなコンテキストに応じて、1つ以上の一致するコンポーネントがUIにどのように表示されるかを定義します。
これは、名前、アイコン、テーブル、概要およびハイライトページ、フィルター、メニュー項目の配置などの*プレゼンテーションの懸念*に専念しています。

高レベルでは、コンポーネントプレゼンテーションは：

* バインディング（シンプルなSTQLクエリ）を使用してコンポーネントを選択します。
* 特定のモード内で適用されます（例えば、監視）。
* 1つ以上のプレゼンテーションの側面（概要テーブルやハイライトなど）を定義します。
* プレゼンテーションプロパティを部分的に定義し、他の一致する定義と組み合わせることができます。

複数のコンポーネントプレゼンテーションが同じコンポーネントに適用される場合があります。そのような場合、最終的なプレゼンテーションを決定するために、それらの定義が組み合わされます。

endif::ss-ff-stackpacks2_enabled[]
