= Introducción a Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetry collector y 2 aplicaciones instrumentadas que envían métricas y trazas a SUSE Observability]

SUSE Observability soporta https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry es un conjunto de protocolos estandarizados y un marco de código abierto para recopilar, transformar y enviar datos de telemetría como trazas, métricas y registros. Open Telemetry soporta una amplia variedad de lenguajes de programación y plataformas.

SUSE Observability tiene soporte tanto para métricas como para trazas y añade las métricas y trazas de Open Telemetry a los datos de topología (Kubernetes) que proporciona el agente de SUSE Observability. Por lo tanto, también es necesario instalar el agente de SUSE Observability. El soporte para registros y el uso de Open Telemetry sin el agente de SUSE Observability llegará pronto.

Open Telemetry consiste en varios componentes diferentes. Para su uso con SUSE Observability, los xref:/setup/otel/languages/README.adoc[SDKs] para instrumentar tu aplicación y el xref:/setup/otel/collector.adoc[Open Telemetry collector] son las partes más importantes. Mostraremos cómo configurar ambos para su uso con SUSE Observability.

Si tu aplicación ya está instrumentada con Open Telemetry o con cualquier otra biblioteca que sea compatible con Open Telemetry, como Jaeger o Zipkin, se puede utilizar el colector para enviar esos datos a SUSE Observability y no se necesita instrumentación adicional.

SUSE Observability requiere que el colector esté configurado con procesadores específicos y autenticación para asegurarse de que todos los datos utilizados por SUSE Observability estén disponibles.

== Referencias

* https://opentelemetry.io/docs/collector/[Open Telemetry collector] en la documentación de Open Telemetry
* https://opentelemetry.io/docs/languages/[SDKs para instrumentar tu aplicación] en la documentación de Open Telemetry
