= Introducción a Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Colector de Open Telemetry y 2 aplicaciones instrumentadas que envían métricas y trazas a SUSE Observability]

SUSE Observability admite https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry es un conjunto de protocolos estandarizados y un marco de código abierto para recopilar, transformar y enviar datos de telemetría como trazas, métricas y registros. Open Telemetry admite una amplia variedad de lenguajes de programación y plataformas.

SUSE Observability admite tanto métricas como trazas. Cuando se utiliza en combinación con el stackpack de Kubernetes, los pods de Kubernetes se enriquecerán con trazas cuando estén disponibles. Al instalar el stackpack de Open Telemetry, se dispondrá de nuevas páginas de resumen para servicios e instancias de servicio que proporcionan acceso a trazas y métricas de span. Las métricas de Open Telemetry pueden ser utilizadas en monitores y enlaces de métricas. El stackpack viene con enlaces de métricas para métricas de span y métricas de memoria de .NET y JVM. También hay monitores listos para usar para tasas de error de span y duración.

La configuración recomendada para su uso con SUSE Observability es instrumentar aplicaciones con los SDKs de Open Telemetry xref:/setup/otel/instrumentation/README.adoc[SDKs] aplicables e instalar el xref:/setup/otel/collector.adoc[colector de Open Telemetry] cerca de sus aplicaciones instrumentadas para procesar previamente los datos (enriquecer con etiquetas de Kubernetes, muestreo en trazas, etc.) y enviar los datos a SUSE Observability. El colector de Open Telemetry también puede ser utilizado para recopilar métricas de muchos tipos de fuentes de telemetría sin instrumentar las aplicaciones utilizando los SDKs. Consulta las https://opentelemetry.io/ecosystem/registry/?language=collector[integraciones del colector de Open Telemetry] para más detalles y si tu base de datos o protocolo de telemetría es compatible.

Sigue la guía de xref:/setup/otel/getting-started/README.adoc[primeros pasos] para configurar todo de manera que funcione mejor con SUSE Observability.

== Referencias

* https://opentelemetry.io/docs/collector/[Colector de Open Telemetry] en la documentación de Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[Integraciones del colector de Open Telemetry]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs para instrumentar su aplicación] en la documentación de Open Telemetry
