= Node.jsアプリケーションの監視
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 自動監視

Node.jsの自動監視は、アプリケーションに自動監視用のJavaScriptライブラリを含めることで行われます。幅広いhttps://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node#_supported_instrumentations[ライブラリとフレームワークがサポートされています]。

自動監視は、アプリケーションの変更を必要としません。設定するには、次の手順に従ってください：

. アプリケーションにOpen Telemetry監視SDKを追加します：
+
[,bash]
----
npm install --save @opentelemetry/api
npm install --save @opentelemetry/auto-instrumentations-node
----

. SDKを読み込むためにアプリケーションを起動するコマンドを更新します。これは、Dockerイメージのエントリポイントやコマンドを更新するか、アプリケーションのKubernetesマニフェスト内の`command`を更新することで行います。`--require @opentelemetry/auto-instrumentations-node/register`を追加します：
+
[,bash]
----
node --require @opentelemetry/auto-instrumentations-node/register app.js
----

. サービス名とエクスポータエンドポイントを設定するための追加の環境変数xref:/setup/otel/languages/sdk-exporter-config.adoc[を使用してアプリケーションをデプロイします]。
. xref:/setup/otel/languages/verify.adoc[確認してください] SUSE Observabilityがトレースおよび/またはメトリクスを受信しているか確認します。

詳細については、https://opentelemetry.io/docs/languages/js/automatic/[Open Telemetryのドキュメント]を参照してください。

[CAUTION]
====
環境変数を介して設定された自動監視は、このhttps://github.com/open-telemetry/opentelemetry-js/issues/4551[Open Telemetryの問題]が解決されるまでトレースのみをサポートします。自動監視からメトリクスを有効にするには、コードの変更が必要です。これらの変更を行うには、https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetryのドキュメント]の指示に従ってください。
====


== 手動監視

手動監視は、自動監視でサポートされていないコードの部分からメトリクス、トレース、またはログが必要な場合に使用できます。例えば、サポートされていないライブラリ、社内コード、またはビジネスレベルのメトリクスです。

そのデータをキャプチャするには、アプリケーションを変更する必要があります。

. Open Telemetry SDKを依存関係として含めてください。
. アプリケーションにコードを追加して、必要に応じてメトリクス、スパン、またはログをキャプチャします。

これに関する詳細なドキュメントは、https://opentelemetry.io/docs/languages/js/instrumentation/[Open Telemetry Javascript SDK ドキュメントページ]にあります。

OTLP エクスポーターを使用し、コードからエクスポーターのエンドポイントを正しく設定することを確認してください。また、https://opentelemetry.io/docs/languages/js/exporters/#_usage_with_nodejs[Open Telemetry ドキュメント]も参照してください。エクスポーターをxref:/setup/otel/collector.adoc[文書化された通り]に設定したと仮定すると、設定する必要があるエンドポイントは`http://opentelemetry-collector.open-telemetry.svc.cluster.local:4317`で、gRPCを使用します。gRPCに問題がある場合は、xref:/setup/otel/languages/sdk-exporter-config.adoc#_grpc_vs_http[gRPC vs HTTP]も参照してください。
