= Répéter les instantanés
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

Cette page décrit les messages JSON exacts pouvant être envoyés dans le cadre du modèle de cohérence des instantanés répétés pour la synchronisation de la santé.

== Propriété JSON : "santé"

La santé peut être envoyée à l'API SUSE Observabilité Receiver en utilisant la propriété `"health"` de l'objet JSON xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[commun].

[tabs]
====
Exemple de santé `repeat_snapshots` JSON::
+
--
[,javascript]
----
{
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "health":[
      {
        "consistency_model": "REPEAT_SNAPSHOTS",
        "start_snapshot": {
          "repeat_interval_s": 50
          //"expiry_interval_s": 200 Optional
        },
        "stop_snapshot": {},
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ]
}
----
--
====

Chaque charge utile de données de santé des instantanés répétés contient les détails suivants :

* *start_snapshot* - Optional. Un début d'instantané doit être traité avant de traiter `check_states`. Cela permet à SUSE Observabilité de comparer un instantané de flux avec celui précédemment reçu et de supprimer les états de vérification qui ne sont plus présents dans l'instantané. Il contient les champs suivants en tant que métadonnées d'instantané :
 ** *intervalle_répétition_s* - Temps en secondes. La fréquence à laquelle la source externe enverra des données de santé à SUSE Observabilité. La valeur maximale autorisée est de 1800 (30 minutes).
 ** *intervalle_expiration_s* - Temps en secondes. Le temps à attendre après la dernière mise à jour avant qu'une vérification externe ne soit supprimée par SUSE Observability. Requis lors de l'utilisation de sous-flux.
* *interrompre_instantané* - Optionnel. L'arrêt d'un instantané sera traité après le traitement des ``états_de_vérification``.
* *flux* - Objet fournissant une identification permettant d'indiquer quels instantanés et `check_states` appartiennent ensemble. Il comprend les champs suivants :
 ** *urn* - Identifiant de la source de données et de flux encodé en tant que SUSE Observability xref:/configure/topology/identifiers.adoc[URN] qui correspond à la convention suivante : `urn:health:<sourceId>:<streamId>` où `<sourceId>` est le nom de la source de données externe et `<streamId>` est un identifiant unique pour le flux de données de santé.
 ** *sub_stream_id* - Optional. Identifiant pour un sous-ensemble des données de santé du flux. Lorsque les données du flux sont distribuées et rapportées par plusieurs agents, cela permet des cycles de vie des instantanés par `sub_stream_id`.
* *check_states* - Une liste d'états de vérification. Chaque état de vérification peut avoir les champs suivants :
 ** *checkStateId* - Identifiant de l'état de vérification dans le système externe.
 ** *message* - Optionnel. Message à afficher dans l'interface utilisateur de SUSE Observability. Les données seront interprétées comme du markdown permettant d'avoir des liens vers le système externe de vérification qui a généré l'état de vérification externe.
 ** *health* - L'une des valeurs d'état de santé de SUSE Observability suivantes : `Clear`, `Deviating`, `Critical`.
 ** *topologyElementIdentifier* - Utilisé pour lier l'état de vérification à un élément topologique de SUSE Observability.
 ** *name* - Nom de l'état de vérification externe.

== Envoyer la santé à SUSE Observability.

La santé peut être envoyée dans un seul message JSON via HTTP POST. Dans l'exemple ci-dessous, un instantané contenant deux états de vérification est envoyé à SUSE Observability depuis un seul système de surveillance externe.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_SNAPSHOTS",
      "start_snapshot": {
        "repeat_interval_s": 300
      },
      "stop_snapshot": {},
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
