= Secrets externes
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability : secrets externes

== Présentation

SUSE Observability peut prendre des secrets tels que la clé de licence, la clé API et les clés d'authentification via la commande helm install, mais peut également les récupérer à partir de secrets déjà provisionnés.

Voici comment configurer cela.

== Obtenir la clé de licence depuis un secret externe

Créez un secret dans l'espace de noms où SUSE Observability est installé, sous la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir le nom d'utilisateur et le mot de passe pour les notifications par e-mail depuis un secret externe

Créez un secret dans l'espace de noms où SUSE Observability est installé, sous la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir la clé API depuis un secret externe

Créez un secret dans l'espace de noms où SUSE Observability est installé, sous la forme suivante, en remplissant les blancs :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obtenir les données d'authentification depuis un secret externe

Créez un secret dans l'espace de noms où SUSE Observability est installé, sous la forme suivante.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Selon la méthode d'authentification choisie, le champ `default_password` sera remplacé par différentes données. Voir les xref:/setup/security/authentication/authentication_options.adoc[options d'authentification] pour plus d'informations. Dans cet exemple, la configuration xref:/setup/security/authentication/single_password.adoc[Mot de passe unique] est utilisée.

Ajoutez ce qui suit à votre commande helm install pour utiliser le secret :

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
