= v2.1.0 - 29/Oct/2024
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de version StackState version 7.0.0-snapshot.20241023133226-master-a9f30a7 Helm Chart version 2.1.0

=== Nouvelles fonctionnalités et améliorations :

* Il est désormais possible de mettre à niveau StackState 6.x vers SUSE Observability. Veuillez suivre le xref:/setup/upgrade-stackstate/migrate-from-6.adoc[guide de migration].
* Introduire un mécanisme de sauvegarde accessible en ligne de commande pour la configuration de SUSE Observability. Cette méthode remplace l'ancienne méthode de sauvegarde par exportation/importation, ce qui améliore la fiabilité du processus de restauration.
* Nous ne prenons en charge que Helm 3.13.1 et plus. C'était déjà le cas, mais ce n'était pas encore appliqué. Aujourd'hui, c'est le cas.
* Ajout d'événements sur les nœuds et les volumes persistants sur les ressources du cluster.
* La prise en charge d'OpenTelemetry est activée par défaut.
* Ajout des violations des règles de santé connexes aux moniteurs externes.

=== Corrections de bugs :

* Correction des sauvegardes StackGraph pour les déploiements mono.\NSupport de la classe de stockage globale pour StackGraph.
* Correction d'un problème majeur de performance. Le problème de performance est apparu lors du passage à suse-observability, qui comprenait une mise à jour de Hbase.

=== Changements en cours :

* Renommé auth-schema de OpenTelemetry Collector en `SuseObservability`

=== Mises à jour des agents

* Correction de l'injecteur de sidecar pour la Suse-Observabilité
* Ajout de la possibilité d'installer l'agent via un formulaire dans le Rancher App Catalog
* Correction d'un bogue qui empêchait le démarrage de l'agent de processus sous Rockylinux.

=== Changements d'agents

* Lors de la migration des contrôles python de stackstate 5.0/6.0 vers SUSE Observability, le code relatif aux schémas python doit être modifié en pydantique".
