= v2.2.0 - 09/Dec/2024
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

[CAUTION]
====
Cette version comporte un bogue où le graphique Helm utilise des URLs d'images invalides pour certains pods, utilisez plutôt la xref:/setup/release-notes/v2.2.1.adoc[version 2.2.1] ou une version plus récente.
====


== Notes de version StackState version 7.0.0-snapshot.20241204151219-master-db9515b Helm Chart version 2.2.0

=== Nouvelles fonctionnalités et améliorations

* Prise en charge d'OpenTelemetry via HTTP
* Ajout des violations des règles de santé connexes aux moniteurs externes.
* Ajout d'une option dans le diagramme helm pour obtenir la clé de licence, la clé api et les secrets d'authentification à partir d'un secret kubernetes externe.
* Suppression de l'api d'administration et de l'utilisateur administrateur de la plateforme qui l'accompagne
* Ajout d'un support pour la mise en évidence des travées qui correspondent aux critères de recherche dans la perspective de trace et l'explorateur de trace.
* Simplifier la configuration du serveur de messagerie sur les installations auto-hébergées.
* Mise à jour vers HDFS 3.4.1
* Utiliser un espace de noms par défaut pour les services Opentelemetry, afin qu'ils apparaissent tous comme des composants dans la topologie.

=== Corrections de bugs

* Correction d'un problème avec les déploiements nonHA où les StackPacks personnalisés n'étaient pas persistés.
* Correction pour respecter `global.storageClassName` sur tous les PVC demandés
* Un fichier supprimé `ServiceAccount`, pour le cronjob de sauvegarde, était encore référencé lors de la mise à jour d'une ancienne version de la carte Helm.
* Correction d'un problème où les couches sortantes et entrantes étaient inversées dans le visualisateur de topologie.
* Assurez-vous que l'option 'available service endpoints' se déclenche lorsque des pods ne sont pas prêts."
* Ne chargez que des ressources liées par type afin d'éviter une condition d'erreur dans le tiroir des ressources liées.

=== Changements en cours

* Les noms d'utilisateur autorisés lors de l'utilisation de l'xref:/setup/security/authentication/file.adoc[authentification basée sur les fichiers] sont limités aux caractères alphanumériques et à `_`.
