= v2.3.4 - 04/Jun/2025
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de mise à jour : SUSE Observability Helm Chart v2.3.4

=== Nouvelles fonctionnalités et améliorations

* *Elasticsearch Liveness Probe Timeout :* Le délai d'attente de `livenessProbe` pour Elasticsearch a été augmenté.
* *Installation de ClickHouse sur OpenShift :* Une documentation a été ajoutée pour guider les utilisateurs dans l'installation de ClickHouse (une des bases de données supportées) sur OpenShift.
* *Amélioration du filtrage des traces :* La fonctionnalité de filtrage des traces dans l'interface utilisateur Traces a été améliorée. Les filtres d'attributs sélectionnent désormais les traces dont au moins un span correspond à tous les attributs spécifiés.
* *Inclusion des traces sans portée racine :* Les traces qui n'ont pas de portée racine sont désormais incluses dans les résultats de la recherche de traces. Cela permet de répondre aux scénarios dans lesquels la portée racine peut être manquante en raison de dépassements de délais, de problèmes de connectivité réseau ou de mauvaises configurations d'un exportateur OTel.
* *Rompre avec le changement : API du canal de notification d'OpsGenie :* L'API du canal de notification d'OpsGenie applique désormais une correspondance enum stricte pour les demandes et les réponses, ce qui garantit une plus grande cohérence dans les interactions de l'API.
* *Métriques du protocole PostgreSQL :* De nouvelles mesures ont été ajoutées pour la latence et le débit du protocole PostgreSQL.

=== Corrections de bugs

* *Édition du moniteur d'état dérivé :* Correction d'un problème qui empêchait l'édition correcte de `componentTypes` pour la fonction de surveillance de l'état dérivé.
* *Affichage du dépassement de topologie :* La page d'aperçu affiche désormais correctement un message de débordement de la topologie au lieu d'une page d'erreur inattendue en cas de débordement.

== Correction des bugs de l'agent

* *Démarrage de l'agent sur des noyaux plus anciens :* Résolution d'un problème où l'agent ne démarrait pas sur les noyaux antérieurs à la version 5.8 en raison d'une erreur "bpf_probe_read not found".
