= v2.3.3 - 07/Mai/2025
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de mise à jour : SUSE Observability Helm Chart v2.3.3

=== Nouvelles fonctionnalités et améliorations

* *Configuration par défaut de l'ordonnancement des pods :* Le paramètre `requiredDuringSchedulingIgnoredDuringExecution` est désormais ajouté par défaut aux spécifications des pods.

=== Corrections de bugs

* *Gestion des dépassements de topologie :* La page d'aperçu affiche désormais un message de dépassement de topologie au lieu d'une page d'erreur inattendue lorsqu'un dépassement se produit.
* *Utilisation de la mémoire du moniteur d'état dérivé :* Correction d'un problème qui entraînait une consommation excessive de mémoire par le moniteur d'état dérivé.
* *Installation de ClickHouse sur OpenShift :* Ajout d'une documentation décrivant les étapes nécessaires à l'installation de ClickHouse, l'une des bases de données prises en charge, sur les environnements OpenShift.
