= v2.3.6 - 22/Jul/2025
:revdate: 2025-07-28
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

[CAUTION]
====
Cette version comporte un bogue qui peut faire échouer le démarrage. Veuillez passer immédiatement à la version 2.3.7.
====

== Notes de mise à jour : SUSE Observability Helm Chart v2.3.6

=== Nouvelles fonctionnalités et améliorations

* *Support de l'architecture de l'agent étendu :* L'agent de SUSE Observability est désormais conçu pour les architectures `x86_64` et `aarch64` (ARM). Elle étend la prise en charge aux serveurs ARM64, ce qui améliore considérablement les capacités d'observation dans l'environnement ARM64.
* *Amélioration des performances de la restauration de la sauvegarde de StackGraph :* La performance de la restauration d'une sauvegarde de StackGraph a été considérablement améliorée.

== Corrections de bugs

* *4000-HA Affichage de la limite du profil :* Correction d'un problème où le profil 4000-HA indiquait incorrectement que la limite de l'interface utilisateur était de 250.
* *StackGraph Console NullPointerException :* Résolution d'un problème `NullPointerException` survenu lors de la récupération des statistiques de stockage dans la console StackGraph.
* *État de blocage de la cosse de téphra dans la configuration HA :* Correction d'un bogue où le pod Tephra pouvait rester bloqué dans un état de non-fonctionnement pendant un ordre de redémarrage spécifique des pods Hadoop dans une configuration HA, en particulier pendant les mises à niveau.

=== Correction des bugs de l'agent

* *Prévention des fuites de mémoire (connexions TCP) :* Correction d'un problème de fuite de mémoire qui survenait lorsque les connexions n'avaient pas la séquence TCP.