= v2.3.2 - 22/Avril/2025
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de mise à jour : SUSE Observability Helm Chart v2.3.2

=== Nouvelles fonctionnalités et améliorations

* *Dépréciation de l'analyse :* La fonction d'analyse est désormais obsolète et désactivée par défaut pour tous les utilisateurs. Pour le réactiver, accordez les autorisations `access-analytics` et `execute-scripts` aux utilisateurs ou rôles concernés.
* *Réduction du bruit de la bille :* Implémentation d'un correctif pour supprimer les erreurs `x-forwarded-for` dans les journaux lorsqu'une combinaison IP:Port est utilisée dans la configuration du transfert.
* *Moniteur d'état dérivé :* Introduction d'une nouvelle fonction "Derived State Monitor", qui permet de dériver un état sur la base de l'état des composants logiques.

=== Corrections de bugs

* *Traces dans le profil HA :* Résolution d'un problème où la fonctionnalité Traces était partiellement désactivée dans le profil `4000-ha`.
* *Correction des liens brisés :* Correction de plusieurs liens brisés identifiés dans l'interface utilisateur et la documentation du produit.
* *Gestion des erreurs de la CLI STS :* La commande CLI STS pour le téléchargement d'un nouveau stackpack fournit désormais des messages d'erreur plus informatifs et plus facilement exploitables.
* *Dépôt d'agents privés dans Rancher :* Correction de divers problèmes liés à la configuration et à l'utilisation d'un référentiel privé pour l'agent dans l'interface utilisateur de Rancher.
* *Enregistre la clé de l'API via l'en-tête :* La clé API permettant d'accéder aux journaux est désormais transmise de manière sécurisée sous forme d'en-tête dans les requêtes API.

== Correction des bugs de l'agent

* *Static Pod Log Scraping (Récupération de logs) :* L'agent a été amélioré pour récupérer les logs pour les pods statiques. Pour ce faire, on utilise l'annotation `kubernetes.io/config.mirror` pour les pods du système.
* *Variables d'environnement secrètes :* Correction d'un problème pour assurer un support correct de la configuration `global.extraEnv.secret`, permettant l'ajout de variables d'environnement secrètes aux pods d'agents.
* *Compatibilité du noyau de l'agent de processus :* Permet à l'agent de traitement de fonctionner sur un plus grand nombre de versions du noyau Linux, en particulier entre 5.0 et 5.11 (inclus).
* *Private Image Registry* Correction de divers problèmes liés à la fourniture d'un dépôt docker privé dans l'interface utilisateur de rancher.
