= v2.3.1 - 17/Mars/2025
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de version SUSE Observability Helm Chart version 2.3.1

=== Nouvelles fonctionnalités et améliorations

* *Performance :* Amélioration significative des performances de la chronologie de la santé pour les environnements à grande échelle.
* *Notifications par webhook :* Le canal de notification Webhook accepte désormais tout code d'état HTTP 2xx comme réponse positive.
* *Visibilité de la ligne de temps :* Amélioration de la visibilité des changements subtils dans la ligne de temps.
* *Avertissements relatifs à l'expiration de la licence :*
 ** Un avertissement apparaît désormais dans l'interface utilisateur 7 jours avant l'expiration de la licence.
 ** Un avertissement supplémentaire s'affiche si la licence a expiré depuis 14 jours.
* *Affichage en ligne de l'événement Span :* Les événements relatifs aux travées sont désormais affichés en ligne, ce qui facilite l'analyse des travées de traçage.
* *Compatibilité de la carte de barre ArgoCD :* La carte Helm peut maintenant être installée à l'aide d'ArgoCD en réglant `.Values.deployment.compatibleWithArgoCD` sur `true`.
* *Configuration de la carte de barre :* Le site `ingressClassName` est désormais pris en charge dans la spécification d'entrée.

=== Corrections de bugs

* *Secret de la clé de licence :* Résolution d'un problème où le secret de la clé de licence n'était pas trouvé lorsque `stackstate.authentication.fromExternalSecret` était activé.
* *Animation de la réduction/expansion du widget :* Correction de l'animation de l'effondrement et de l'expansion des widgets.
* *Sélection de la latence de la trace :* Correction d'un bogue qui affectait la sélection de la latence de la trace.

== Correction des bugs de l'agent

* *Clé API requise :* Correction d'un bogue qui exigeait incorrectement `stackstate.apiKey` lorsque `stackstate.manageOwnSecrets=true` était défini.
* *Injecteur de tête :* Correction d'un problème avec l'injecteur d'en-tête lors de la gestion de noms de versions longs.
