= v2.6.2 - 03/Nov/2025
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de mise à jour : {stackstate-product-name} Tableau de bord v2.6.2

== Problèmes connus

* Cette version contient 2 versions du stackpack Open Telemetry utilisant le même logo. Survolez le sac à dos pour en voir le nom. Lors de l'installation ou de la mise à jour, utilisez le stackpack nommé "Open Telemetry" et n'installez pas le stackpack "Open Telemetry 2.0". Cette dernière ne fournit aucune fonctionnalité pour le moment et sera supprimée dans la prochaine version.

== Nouvelles fonctionnalités et améliorations

* *Chronologie de l'histoire du moniteur :* La chronologie du moniteur affiche désormais tous les états de santé historiques dans l'intervalle de temps.
** Les états de santé créés *avant la* mise à niveau apparaîtront sous forme d'entrées individuelles.
** Tous les statuts produits *après la* mise à jour seront intelligemment fusionnés en une seule ligne de statut pour une meilleure lisibilité.
* *Moniteurs : Référence de fonction par ID :* Les fonctions du moniteur peuvent désormais être référencées par leur identifiant unique lors des opérations d'importation et d'exportation.
* *Ouvrir la mise à niveau du collecteur de télémétrie :* Le collecteur Open Telemetry a été mis à jour.
* *OpenJDK et mises à jour des dépendances :* OpenJDK et diverses dépendances de bibliothèques ont été mises à jour.
* *Suppression des avertissements relatifs au tableau de bord :* Les avertissements qui apparaissaient précédemment lors de l'installation ou de la mise à jour de la carte SUSE Observability Helm ont été supprimés.
* *Agent : Améliorations de l'intégration Splunk :*
** Ajout de la prise en charge de différents **mécanismes d'authentification JWT** pour l'intégration de Splunk.
** Ajout d'options pour spécifier un **en-tête supplémentaire** pour l'authentification Splunk (`SPLUNK_AUTH_EXTRA_HEADER_NAME`/`VALUE`).
** Ajout d'une option pour spécifier l'**utilisateur de l'espace de noms par défaut** (`default_ns_user`) pour les recherches sauvegardées de Splunk.
* *Agent : Migration de l'API Dynatrace :* L'ingestion de données de l'intégration Dynatrace a été migrée de l **'API v1 à l'API v2**.
* *Alias de série temporelle Autocomplétion :* La fonction d'alias de séries temporelles fournit désormais une **auto-complétion pour les étiquettes métriques**, améliorant ainsi l'efficacité des requêtes.
* *Vues : Bouton "Enregistrer" amélioré :* Le ** bouton "Enregistrer" pour les vues** a maintenant une couleur distincte pour attirer clairement l'attention sur les modifications non enregistrées.
* *Rafraîchissement manuel des données :* Ajout d'une **option d'actualisation manuelle** (située à côté de l'actualisation en fonction du temps) pour les traces, les métriques, les journaux et d'autres affichages de données.
* *Gestion automatique des piles communes :* Le *Common StackPack* est maintenant automatiquement installé et mis à jour. Cela simplifie la création de StackPack personnalisés, car les paramètres fournis par le StackPack commun sont disponibles par défaut, sans qu'il soit nécessaire de configurer explicitement les dépendances.

== Corrections de bugs

* *Plate-forme : Limites de stockage éphémère :* Augmentation des limites de stockage éphémère à **1Gi par pod** pour éviter les évictions de pods sur les clusters qui conservent un grand volume de logs.
* *Cohérence de la configuration des jobs et des CronJob :* Nous nous sommes assurés que `podAnnotations`, `podLabels`, `nodeSelectors`, `affinity`, et `tolerations` s'appliquent désormais correctement à tous les Jobs et CronJobs.
* *Job et CronJob Image Pull Secrets :* S'assurer que tous les Jobs et CronJobs prennent en charge la configuration `global.imagePullSecrets`.
* *Correction de la session de l'extension Rancher :* L'extension Rancher ne réutilise plus la session existante du navigateur pour récupérer l'état de l'observabilité.
* *Plate-forme : Registre d'images de l'agent RBAC de Kubernetes :* Correction d'un problème où le site `kubernetes-rbac-agent` ne prenait pas en compte la valeur de `global.imageRegistry` Helm override.
* *Plate-forme : Support d'échange AMQP :* Correction de la prise en charge des échanges AMQP.
* *Ouvrir l'accès au composant de télémétrie :* Résolution d'un problème où les composants d'Open Telemetry étaient indisponibles pour les utilisateurs qui avaient les permissions de voir les données du cluster.
* *Tourne-disque des permissions topologiques manquantes :* Correction d'un problème où un utilisateur n'ayant pas les permissions de topologie rencontrait un spinner de chargement perpétuel.
* *Rancher Cluster Accès propriétaire :* Correction d'un bogue qui empêchait les utilisateurs ayant le rôle de **propriétaire de cluster** Rancher d'accéder aux données du cluster.

=== Correction des bugs de l'agent

* *Agent : Détection du protocole AMQP :* Correction d'un problème de lecture mal alignée dans la logique de détection du protocole AMQP.