= v2.6.3 - 25/Nov/2025
:revdate: 2025-11-25
:page-revdate: {revdate}
:description: SUSE Observability en mode auto-hébergé

== Notes de mise à jour : {stackstate-product-name} Tableau de bord v2.6.3

== Nouvelles fonctionnalités et améliorations

* *Mise à jour de HDFS :* HDFS (Hadoop Distributed File System) et ses dépendances associées ont été mises à jour.
* *StackPack : Moniteur de synchronisation de la topologie partielle :* Un nouveau moniteur a été ajouté au StackState StackPack pour alerter sur les **snapshots partiels de synchronisation de la topologie**.
* *Augmentation des ressources vmagent :* Les besoins en mémoire et en ressources CPU pour le composant `vmagent` ont été augmentés dans le profil `4000-ha`.
* *Améliorations de l'image :*
** L'image du conteneur **Kafka** a été mise à jour.
** L'image du conteneur **ClickHouse** a été mise à jour.

== Corrections de bugs

* *Portée de la métrique OpenTelemetry :* Correction d'un problème critique où les métriques ingérées via le collecteur OpenTelemetry manquaient le label `_scope_`. Cela a empêché **les utilisateurs scopés** d'observer ces mesures.
* *Explorateur métrique Tri :* L'**explorateur de métriques** utilise désormais le tri numérique pour les valeurs de la colonne "valeur".
* *Plate-forme : Corruption du StackGraph (transactions interrompues) :* Correction d'un **problème de corruption du StackGraph** où des données provenant de transactions expirées qui auraient dû être annulées pouvaient réapparaître par inadvertance.
* *Plate-forme : Validation du pod d'État :* Ajout d'**une validation des données et d'une journalisation supplémentaires** dans le pod d'état pour améliorer la stabilité et le débogage.
* *StackGraph : Invariant de suppression des bords :* Ajout d'un invariant pour éviter les références incohérentes aux arêtes lors de l'opération de suppression d'une arête dans **StackGraph**.
* *Vérificateur d'intégrité StackGraph :* Un **vérificateur d'intégrité perpétuel expérimental** a été ajouté pour StackGraph. Il peut être activé en réglant `hbase.console.integrity.enabled=true`.
* *Guides de remédiation StackPack :* Correction de plusieurs guides de remédiation dans le stackpack SUSE Observability qui faisaient incorrectement référence à `tags` au lieu du terme correct, **`labels`**.
* *Duplicata OpenTelemetry StackPack :* Suppression d'un doublon dans l'installation du **stackpack d'OpenTelemetry**.
* *Plate-forme : Agent Restart Snapshot Loop :* Correction d'un problème où le redémarrage d'un agent pouvait entraîner l'apparition continue de l **'"instantané actif".** 
* *Plate-forme : Correction de l'OOM JMX de Kafka :* Résolution d'un problème de mémoire défaillante pour le conteneur Kafka JMX sur les versions 1.31 et 1.30 de RKE2 Kubernetes.

=== Correction des bugs de l'agent

* *Agent : /proc/<pid>/stat Panique :* L'agent comprend désormais un correctif permettant d'éviter une panique lorsqu'un fichier `/proc/<pid>/stat` s'avère vide.