= カスタムメトリックチャートのトラブルシューティング
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概要

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,コンポーネントのハイライトページにメトリックチャートが表示されません>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,コンポーネントのメトリクスビューにメトリックチャートが表示されません>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,コンポーネントのメトリックチャートが空のままです（「データなし」）>>

== コンポーネントのハイライトページにメトリックチャートが表示されません

現在、コンポーネントのハイライトページに表示されるメトリックチャートをカスタマイズすることはできません。カスタムメトリックバインディングのチャートは、メトリクスビューにのみ表示されます。

== コンポーネントのメトリクスビューにメトリックチャートが表示されません

メトリックバインディングの`scope`クエリは、コンポーネントがメトリックバインディングを表示するかどうかを判断するために使用されます。コンポーネントがメトリックバインディングを表示しない場合は、スコープ内のトポロジークエリがコンポーネントと一致しているか確認してください。

まず、コンポーネントのハイライトページに期待されるラベルやコンポーネントタイプが実際にあるか確認してください。名前とタイプは上部にあり、ラベルは「概要」セクションにあります。ラベル名や値にスペルミスがないことを確認してください。

スコープクエリが正しい構文であることを確認してください：

. メニューの「ビュー」から「エクスプローラービュー」を開き、右側の青い「Explore」ボタンをクリックします。または、URLを直接使用して：`https://<your-stackstate-instance>/#/views/explore`
. フィルターを開き、`switch to STQL`を選択します。
. 次に、スコープからクエリをコピーしてSTQLフィールドに貼り付け、クエリを実行します。

概要には、クエリに一致し、チャートを取得するすべてのコンポーネントが表示されます。

== コンポーネントのメトリックチャートが空のままです（「データなし」）

データが期待されていたのにデータがないメトリックチャートについては、インスペクターを開いてください（チャートの右上隅にあるアイコン）。「クエリを表示」ボタンを切り替えて、クエリを表示します。

クエリにパラメータが含まれていないことを確認してください（すなわち、`${tags.cluster-name}`や`${name}`のようなすべての値がコンポーネントの値に置き換えられています）。クエリにパラメータが残っている場合、そのラベルはこのコンポーネントで利用できません。したがって、使用されている名前（この例では`cluster-name`）をコンポーネントで利用可能なラベルと照合してください。また、名前に誤字がないことを確認してください。

すべてのパラメータが入力されている場合、PromQLクエリに問題がある可能性があります。それを調査するために、PromQLクエリをコピーして、メトリクスエクスプローラーを開きます（{stackstate-product-name}のメインメニューから）。クエリをメトリクスエクスプローラーに貼り付けて、実行します。これでも空の結果が返されるはずです。

メトリクスが存在しないか、ラベルのいずれかが存在しないか、ラベルは存在するが、その値に一致する時系列がない可能性があります。これを解決する最も早い方法は、クエリをメトリクス名だけに書き換えて実行することです。結果があれば、メトリクスは存在します（したがって、誤字はありません）。テーブルの結果も、使用されているすべてのラベルが存在することを確認するために使用できます。ここにも誤字がないことを確認してください。

結果があるが、特定のラベルの特定の値（例えば`pod_name`ラベル）に対してだけない場合、クエリは問題ありませんが、この特定のコンポーネントのこの特定のメトリクスに対する時系列は存在しません。この場合に確認すべきことです。

* このコンポーネントのデータは収集されていますか（{stackstate-product-name}エージェントまたは他の手段を介して）？
* コンポーネントはメトリックを報告していますか？

これを行う方法は、データ収集がどのように構成されているかによります。
