= Gespeicherte Daten löschen
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Die Daten in SUSE Observability sind in vier verschiedene Datensätze aufgeteilt:

* Elasticsearch-Daten
* Kafka-Topic-Daten
* StackGraph-Daten
* Metrikdaten

Bei so vielen zu speichernden Daten ist es wichtig, die Mittel zu haben, um sie zu verwalten. In SUSE Observability ist eine standardmäßige Datenaufbewahrungsfrist von 30 Tagen festgelegt. Dies kann entsprechend Ihren Bedürfnissen mit der SUSE Observability Kommandozeilenschnittstelle konfiguriert werden. Erfahren Sie mehr über xref:/setup/data-management/data_retention.adoc[SUSE Observability-Datenaufbewahrung].

== Daten manuell löschen

Um gespeicherte Daten in SUSE Observability, das auf Kubernetes läuft, zu löschen, wird empfohlen, eine saubere Installation durchzuführen:

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Deinstallieren Sie SUSE Observability]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Alle PVCs entfernen]
. Installieren Sie SUSE Observability erneut mit der gleichen Konfiguration wie zuvor, auf xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] oder xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
