= Commencer avec Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Collecteur Open Telemetry et 2 applications instrumentées envoyant des métriques et des traces à SUSE Observability]

SUSE Observability prend en charge https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry est un ensemble de protocoles standardisés et un cadre Open Source pour collecter, transformer et expédier des données de télémétrie telles que des traces, des métriques et des journaux. Open Telemetry prend en charge une grande variété de langages de programmation et de plateformes.

SUSE Observability prend en charge à la fois les métriques et les traces et ajoute les métriques et les traces Open Telemetry aux données de topologie (Kubernetes) fournies par l'agent SUSE Observability. Il est donc toujours nécessaire d'installer également l'agent SUSE Observability. Le support des journaux et l'utilisation d'Open Telemetry sans l'agent SUSE Observability arrivent bientôt.

Open Telemetry se compose de plusieurs composants différents. Pour une utilisation avec SUSE Observability, les xref:/setup/otel/languages/README.adoc[SDKs] pour instrumenter votre application et le xref:/setup/otel/collector.adoc[collecteur Open Telemetry] sont les parties les plus importantes. Nous allons montrer comment configurer les deux pour une utilisation avec SUSE Observability.

Si votre application est déjà instrumentée avec Open Telemetry ou avec toute autre bibliothèque prise en charge par Open Telemetry, comme Jaeger ou Zipkin, le collecteur peut être utilisé pour expédier ces données à SUSE Observability et aucune instrumentation supplémentaire n'est nécessaire.

SUSE Observability nécessite que le collecteur soit configuré avec des processeurs spécifiques et une authentification pour s'assurer que toutes les données utilisées par SUSE Observability sont disponibles.

== Références

* https://opentelemetry.io/docs/collector/[Collecteur Open Telemetry] dans la documentation Open Telemetry
* https://opentelemetry.io/docs/languages/[SDKs pour instrumenter votre application] dans la documentation Open Telemetry
