= Commencer avec Open Telemetry
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Collecteur Open Telemetry et 2 applications instrumentées envoyant des métriques et des traces à SUSE Observability]

SUSE Observability prend en charge https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry est un ensemble de protocoles standardisés et un cadre Open Source pour collecter, transformer et expédier des données de télémétrie telles que des traces, des métriques et des journaux. Open Telemetry prend en charge une grande variété de langages de programmation et de plateformes.

SUSE Observability prend en charge à la fois les métriques et les traces. Lorsqu'il est utilisé en combinaison avec le stackpack Kubernetes, les pods Kubernetes seront enrichis de traces lorsque disponibles. En installant le stackpack Open Telemetry, de nouvelles pages de synthèse pour les services et les instances de service deviennent disponibles, fournissant un accès aux traces et aux métriques de span. Les métriques Open Telemetry peuvent être utilisées dans des moniteurs et des liaisons de métriques. Le stackpack est livré avec des liaisons de métriques pour les métriques de span et les métriques de mémoire .NET et JVM. Il existe également des moniteurs prêts à l'emploi pour les taux d'erreur de span et la durée.

La configuration recommandée pour une utilisation avec SUSE Observability est d'instrumenter les applications avec les xref:/setup/otel/instrumentation/README.adoc[SDKs] Open Telemetry applicables et d'installer le xref:/setup/otel/collector.adoc[collecteur Open Telemetry] près de vos applications instrumentées pour prétraiter les données (enrichir avec des étiquettes Kubernetes, échantillonnage sur les traces, etc.) et envoyer les données vers SUSE Observability. Le collecteur Open Telemetry peut également être utilisé pour collecter des métriques à partir de nombreux types de sources de télémétrie sans instrumenter les applications avec les SDKs. Consultez les https://opentelemetry.io/ecosystem/registry/?language=collector[intégrations du collecteur Open Telemetry] pour plus de détails et pour savoir si votre base de données ou votre protocole de télémétrie est pris en charge.

Suivez le guide xref:/setup/otel/getting-started/README.adoc[d'introduction] afin de tout configurer de manière à ce que cela fonctionne au mieux avec SUSE Observability.

== Références

* https://opentelemetry.io/docs/collector/[Collecteur Open Telemetry] dans la documentation Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[intégrations du collecteur Open Telemetry]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs pour instrumenter votre application] dans la documentation Open Telemetry
