= Collecteur OpenTelemetry en tant que proxy
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

La configuration normale du collecteur OpenTelemetry pour l'échantillonnage des traces peut être trouvée xref:/setup/otel/collector.adoc[ici]

La configuration ci-dessous décrit un déploiement qui effectue uniquement le traitement par lots, sans traitement supplémentaire des traces, des métriques ou des journaux.  Il est conçu comme un proxy de sécurité qui existe en dehors du cluster SUSE Observability, mais au sein d'une infrastructure réseau de confiance.  Les informations d'identification de sécurité pour le proxy et SUSE Observability peuvent être configurées séparément, ajoutant une couche d'authentification qui ne réside pas avec l'appelant, mais avec l'hôte.

image::otel/aws_nodejs_otel_proxy_collector_configuration.svg[Instrumentation AWS Lambda avec OpenTelemetry via le collecteur proxy]

[tabs]
====
Traefik (par défaut)::
+
--

.otel-collector.yaml
[,yaml]
----
mode: deployment
presets:
   kubernetesAttributes:
      enabled: true
      # You can also configure the preset to add all the associated pod's labels and annotations to you telemetry.
      # The label/annotation name will become the resource attribute's key.
      extractAllPodLabels: true
extraEnvsFrom:
   - secretRef:
        name: open-telemetry-collector
image:
   repository: "otel/opentelemetry-collector-k8s"

config:
   receivers:
      otlp:
         protocols:
            grpc:
               endpoint: 0.0.0.0:4317
            http:
               endpoint: 0.0.0.0:4318

   exporters:
      # Exporter for traces to traffic mirror (used by the common config)
      otlp:
         endpoint: <url for opentelemetry ingestion by suse observability>
         auth:
            authenticator: bearertokenauth

   extensions:
      bearertokenauth:
         scheme: SUSEObservability
         token: "${env:API_KEY}"

   service:
      extensions: [health_check, bearertokenauth]
      pipelines:
         traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-traefik-external
    traefik.ingress.kubernetes.io/ingress.class: ingress-traefik-external
    traefik.ingress.kubernetes.io/backend-protocol: GRPC
    # "12.34.56.78/32" IP address of NatGateway in the VPC where the otel data is originating from
    #  traefik.ingress.kubernetes.io/whitelist-source-range: "12.34.56.78/32"
  hosts:
    - host: "otlp-collector-proxy.${CLUSTER_NAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 4317
  tls:
    - secretName: ${CLUSTER_NODOT}-ecc-tls
      hosts:
        - "otlp-collector-proxy.${CLUSTER_NAME}"
----
--

Nginx::
+
--
[NOTE]
=====
Le projet Ingress Nginx est https://kubernetes.io/blog/2025/11/11/ingress-nginx-retirement/[en cours de retrait]. Les utilisateurs sont invités à envisager des alternatives telles que Traefik.
=====

.otel-collector.yaml
[,yaml]
----
mode: deployment
presets:
   kubernetesAttributes:
      enabled: true
      # You can also configure the preset to add all the associated pod's labels and annotations to you telemetry.
      # The label/annotation name will become the resource attribute's key.
      extractAllPodLabels: true
extraEnvsFrom:
   - secretRef:
        name: open-telemetry-collector
image:
   repository: "otel/opentelemetry-collector-k8s"

config:
   receivers:
      otlp:
         protocols:
            grpc:
               endpoint: 0.0.0.0:4317
            http:
               endpoint: 0.0.0.0:4318

   exporters:
      # Exporter for traces to traffic mirror (used by the common config)
      otlp:
         endpoint: <url for opentelemetry ingestion by suse observability>
         auth:
            authenticator: bearertokenauth

   extensions:
      bearertokenauth:
         scheme: SUSEObservability
         token: "${env:API_KEY}"

   service:
      extensions: [health_check, bearertokenauth]
      pipelines:
         traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
         logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/ingress.class: ingress-nginx-external
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    # "12.34.56.78/32" IP address of NatGateway in the VPC where the otel data is originating from
    #  nginx.ingress.kubernetes.io/whitelist-source-range: "12.34.56.78/32"
  hosts:
    - host: "otlp-collector-proxy.${CLUSTER_NAME}"
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 4317
  tls:
    - secretName: ${CLUSTER_NODOT}-ecc-tls
      hosts:
        - "otlp-collector-proxy.${CLUSTER_NAME}"
----
--
====

[discrete]
=== Liste blanche des plages d'adresses sources d'entrée

Pour souligner le rôle du collecteur proxy en tant que mesure de sécurité, il est recommandé d'utiliser une liste blanche de plages d'adresses sources pour filtrer les données provenant de sources non fiables et/ou inconnues. En revanche, le collecteur d'ingestion SUSE Observability peut devoir accepter des données provenant de plusieurs sources ; le maintien d'une liste blanche à ce niveau n'est pas évolutif.
