ifdef::ss-ff-stackpacks2_enabled[]
= Topología de OpenTelemetry
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topología de OpenTelemetry

{stackstate-product-name} puede derivar automáticamente la topología de aplicación e infraestructura a partir de los datos de telemetría de OpenTelemetry (OTel).
Esto se logra a través de los mapeos de topología de OpenTelemetry que transforman de manera declarativa las señales de trazas y métricas en componentes de topología (vértices) y relaciones (edges).

== Descripción general

A un alto nivel, la generación de topología a partir de OpenTelemetry funciona de la siguiente manera:

* La telemetría de OpenTelemetry (métricas y/o trazas) es recibida por el Collector.
* El Collector de OTel utiliza un conector de topología que evalúa los mapeos configurados contra la telemetría.
* Cuando las condiciones de mapeo coinciden con la telemetría, se producen componentes y/o relaciones.
* Estos objetos de topología son consumidos por el servicio `sync` y se fusionan en el grafo de topología.
* Los mapeos son declarativos, basados en YAML, y se evalúan continuamente a medida que la telemetría fluye a través del sistema.

Señales actualmente soportadas:

* Métricas
* Trazas

[NOTE]
====
La generación de topología basada en registros aún no es compatible.
====

Para más información sobre los mapeos de componentes y relaciones, consulta la página xref:/setup/custom-integrations/otelmappings/concepts.adoc[conceptos].

endif::ss-ff-stackpacks2_enabled[]
