= Welcome to the new home of SUSE Observability docs!
:cover: .gitbook/assets/gitbook-cover.jpg
:coverY: 0

You are viewing the latest version of our documentation. Select topics from the content menu on the left. 

To refer to older versions of the documentation, use the https://archivedocs.stackstate.com[archive].

[discrete]
=== SUSE Observability Kubernetes Troubleshooting (v6.0)

Use SUSE Observability to troubleshoot your Kubernetes cluster.

xref:./README.adoc[SUSE Observability docs]

[discrete]
=== SUSE Observability Self-hosted

Use SUSE Observability Self-hosted to observe an extensive set of technologies that originate either in your own data centers or in the cloud.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability Self-hosted] - *latest self-hosted release!*

[discrete]
=== SUSE Observability SaaS

Use SUSE Observability SaaS to observe cloud technologies, such as Kubernetes and AWS services.

xref:/saas/user-management.adoc[SUSE Observability SaaS docs]