= Initial run guide
:description: SUSE Observability Self-hosted

== Overview

This page provides all the information you need to install and run SUSE Observability.

== Installation instructions

{% tabs %}
{% tab title="Kubernetes" %}
Install SUSE Observability on link:kubernetes_openshift/[Kubernetes].
{% endtab %}

{% tab title="OpenShift" %}
Install SUSE Observability on xref:kubernetes_openshift/openshift_install.adoc[OpenShift].
{% endtab %}
{% endtabs %}

== Address and port

{% tabs %}
{% tab title="Kubernetes" %}
To access the SUSE Observability UI:

. link:kubernetes_openshift/kubernetes_install.adoc#access-the-suse-observability-ui[Enable a port-forward].
. Access the SUSE Observability UI at: https://localhost:8080
{% endtab %}

{% tab title="OpenShift" %}
To access the SUSE Observability UI:

. link:kubernetes_openshift/openshift_install.adoc#access-the-suse-observability-ui[Enable a port-forward].
. Access the SUSE Observability UI at: https://localhost:8080
{% endtab %}
{% endtabs %}

== Default username and password

{% tabs %}
{% tab title="Kubernetes" %}
SUSE Observability is configured by default with the following administrator account:

* *username:* `admin`
* *password:* Set during installation. This is collected by the `generate_values.sh` script and stored in MD5 hash format in `values.yaml`
{% endtab %}

{% tab title="OpenShift" %}
SUSE Observability is configured by default with the following administrator account:

* *username:* `admin`
* *password:* Set during installation. This is collected by the `generate_values.sh` script and stored in MD5 hash format in `values.yaml`
{% endtab %}
{% endtabs %}

== Troubleshooting

If you run into any problems during the installation of SUSE Observability or first run, check the xref:troubleshooting.adoc[SUSE Observability installation troubleshooting guide].

== Next steps

Once you have SUSE Observability up and running, you can get started setting up integrations

* xref:../../k8s-quick-start-guide.adoc[Install StackPacks to integrate with external systems]
* xref:../../use/views/k8s-views.adoc[Explore your Kubernetes cluster]
