= Initial run guide
:description: SUSE Observability Self-hosted

== Overview

This page provides all the information you need to install and run SUSE Observability.

== Installation instructions

[tabs]
====
Kubernetes::
+
--
Install SUSE Observability on link:kubernetes_openshift/[Kubernetes].
--

OpenShift::
+
--
Install SUSE Observability on xref:kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Address and port

[tabs]
====
Kubernetes::
+
--
To access the SUSE Observability UI:

. link:kubernetes_openshift/kubernetes_install.adoc#access-the-suse-observability-ui[Enable a port-forward].
. Access the SUSE Observability UI at: https://localhost:8080
--

OpenShift::
+
--
To access the SUSE Observability UI:

. link:kubernetes_openshift/openshift_install.adoc#access-the-suse-observability-ui[Enable a port-forward].
. Access the SUSE Observability UI at: https://localhost:8080
--
====

== Default username and password

[tabs]
====
Kubernetes::
+
--
SUSE Observability is configured by default with the following administrator account:

* *username:* `admin`
* *password:* Set during installation. This is collected by the `generate_values.sh` script and stored in MD5 hash format in `values.yaml`
--

OpenShift::
+
--
SUSE Observability is configured by default with the following administrator account:

* *username:* `admin`
* *password:* Set during installation. This is collected by the `generate_values.sh` script and stored in MD5 hash format in `values.yaml`
--
====

== Troubleshooting

If you run into any problems during the installation of SUSE Observability or first run, check the xref:troubleshooting.adoc[SUSE Observability installation troubleshooting guide].

== Next steps

Once you have SUSE Observability up and running, you can get started setting up integrations

* xref:../../k8s-quick-start-guide.adoc[Install StackPacks to integrate with external systems]
* xref:../../use/views/k8s-views.adoc[Explore your Kubernetes cluster]
