= Analytics-Seite
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Die Analytics-Seite bietet eine leistungsstarke und flexible Schnittstelle, um Ihre Einblicksdaten mithilfe von xref:/develop/reference/k8sTs-stql_reference.adoc[STQL-Abfragen] abzufragen und zu analysieren.
Diese interaktive Umgebung ermöglicht es Ihnen, über vorgefertigte Dashboards hinauszugehen und tiefere Einblicke in die Gesundheit, Leistung und Abhängigkeiten Ihrer dynamischen Umgebung zu gewinnen.

[CAUTION]
====
*Die Analytics-Seite wird auslaufen, aber Sie können sie weiterhin aktivieren, indem Sie spezifische Berechtigungen konfigurieren. Wir empfehlen jedoch dringend, StackPacks für einen verbesserten Einblick und Analyse zu nutzen, da sie eine robustere und aktiv unterstützte Alternative bieten.*

Zwei Berechtigungen sind erforderlich, um die Analytics-Seite zu aktivieren:

* `access-analytics`
* `execute-scripts`

Weitere Details: xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungsmanagement]

====

