= Fehlerbehebung bei Monitoren
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Übersicht

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,Das Ergebnis des Monitors wird nicht auf einer Komponente angezeigt>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,Der Monitor zeigt einen Fehler in der Übersicht des Monitorstatus an>>

=== Das Ergebnis des Monitors wird nicht auf einer Komponente angezeigt

Überprüfen Sie zunächst, ob der Monitor xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[Ergebnisse produziert]. Wenn dies der Fall ist, die Monitorergebnisse jedoch nicht auf den Komponenten angezeigt werden, könnte ein Problem mit der Bindung vorliegen. Verwenden Sie zunächst den folgenden Befehl zur Überprüfung:

[,bash]
----
sts monitor status --id <id>
----

Wenn die Ausgabe `Monitor health states with identifier which has no matching topology element (<nr>): ....` hat, zeigt dies, dass der `urnTemplate` möglicherweise keinen Identifikator erzeugt, der mit der Topologie übereinstimmt. Um dies zu beheben, xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[überprüfen Sie Ihre urnTemplate erneut].

=== Der Monitor zeigt einen Fehler in der Übersicht des Monitorstatus an

Holen Sie den Status des Monitors über die Kommandozeilenschnittstelle ab

[,bash]
----
sts monitor status --id <id>
----

Der Abschnitt `Monitor Stream errors:` zeigt die Fehler an, die im Monitor auftreten, und bietet weitere Hilfe.

