= Documentação do SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}

Esta é a documentação mais recente do SUSE Observability. Selecione os tópicos do menu de conteúdo à esquerda.

Para versões mais antigas da documentação, use o https://archivedocs.stackstate.com[arquivo].

== Comece agora mesmo

Visite o xref:/k8s-suse-rancher-prime.adoc[guia de início rápido do Rancher Prime] se você for um usuário do Rancher Prime, se você for um usuário do SUSE Cloud Observability, visite o xref:/k8s-quick-start-guide.adoc[guia de início rápido], se você estiver executando o SUSE Cloud Observability na AWS, visite o xref:/suse-cloud-observability-quick-start-guide.adoc[guia de início rápido do SUSE Cloud Observability].

== Não consegue encontrar algo?

Use a barra de pesquisa no canto superior direito. Se você achar que alguma documentação está faltando, nos avise no https://scc.suse.com/[site de suporte do SUSE Observability].

== Solução de problemas e suporte

Perguntas? Nós podemos ajudá-lo. Encontre a equipe de suporte no https://scc.suse.com/[site de suporte do SUSE Observability].

== SUSE Observability Auto-hospedado

Use o SUSE Observability Auto-hospedado para observar um extenso conjunto de tecnologias a partir de seus próprios data centers ou da nuvem.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability Auto-hospedado]

== SUSE Cloud Observability

Use o SUSE Cloud Observability para observar tecnologias em nuvem, como Kubernetes e serviços da AWS.

xref:/suse-cloud-observability/user-management.adoc[Documentação do SUSE Cloud Observability]
