= Guias de início rápido do SUSE Observability
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability
:doctype: book

== Visão Geral

Quando sua instância SaaS do SUSE Observability estiver configurada, você receberá um e-mail do SUSE Observability com os detalhes de login necessários. Este guia de início rápido ajudará você a começar e a inserir seus próprios dados na sua instância SaaS do SUSE Observability.

Para integrar seu(s) cluster(s) ao SUSE Observability, você pode seguir um destes guias para o seu ambiente apropriado.

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Auto-hospedado>>


== Kubernetes

Configure uma integração Kubernetes para coletar dados de topologia, eventos, logs, alterações e métricas de um cluster Kubernetes e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Versão Kubernetes suportada

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para Kubernetes

Para configurar uma integração Kubernetes do SUSE Observability, você precisa ter:

* Um cluster Kubernetes em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes SUSE Observability precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configure uma integração com o Kubernetes

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_kubernetes,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os Agentes tenham sido implantados, eles começarão a coletar dados e enviar isso para o SUSE Observability

[CAUTION]
====
Ao operar em um ambiente self-hosted air-gapped, prepare primeiramente a instalação do agente com as xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[instruções air-gapped].
====


== OpenShift

Configure uma integração com o OpenShift para coletar topologia, eventos, logs, dados de mudanças e métricas de um cluster OpenShift e disponibilizar isso no SUSE Observability.

=== Versões suportadas

|===
| Versão do OpenShift | Versão Kubernetes suportada | Fim do Suporte do OpenShift

| OpenShift 4.17
| Kubernetes 1.30
| 1 de abril de 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27 de dezembro de 2025

| OpenShift 4.15
| Kubernetes 1.28
| 27 de agosto de 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1º de maio de 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17 de novembro de 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17 de julho de 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10 de fevereiro de 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10 de setembro de 2023

| OpenShift 4.9
| Kubernetes 1.22
| 18 de abril de 2023
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para OpenShift

Para configurar uma integração do SUSE Observability com OpenShift, você precisa ter:

* Um cluster OpenShift em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes do SUSE Observability precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configurar uma integração do OpenShift

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_openshift,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os Agentes tenham sido implantados, eles começarão a coletar dados e enviar isso para o SUSE Observability


== Amazon EKS

Configure uma integração do Amazon EKS para coletar dados de topologia, eventos, logs, alterações e métricas de um cluster Amazon EKS e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes version | Lançamento do Amazon EKS | Fim do Suporte do Amazon EKS | Fim do Suporte Estendido do Amazon EKS

| 1.32
| 23 de janeiro de 2025
| 23 de março de 2026
| 23 de março de 2027

| 1.31
| 26 de setembro de 2024
| 26 de novembro de 2025
| 26 de novembro de 2026

| 1.30
| 23 de maio de 2024
| 23 de julho de 2025
| 23 de julho de 2026

| 1.29
| 23 de janeiro de 2024
| 23 de março de 2025
| 23 de março de 2026

| 1.28
| 26 de setembro de 2023
| 01 de novembro de 2024
| 26 de novembro de 2025

| 1.27
| 24 de maio de 2023
| julho de 2024
| 24 de julho de 2025

| 1.26
| 11 de abril de 2023
| Junho de 2024
| 11 de junho de 2025

| 1.25
| 21 de fevereiro de 2023
| maio de 2024
| 1º de maio de 2025

| 1.24
| 15 de novembro de 2022
| janeiro de 2024
| 31 de janeiro de 2025

| 1.23
| 11 de agosto de 2022
| 11 de outubro de 2023
| 11 de outubro de 2024

| 1.22
| 4 de abril de 2022
| 4 de junho de 2023
| 1 de setembro de 2024

| 1.21
| 19 de julho de 2021
| 15 de fevereiro de 2023
| 15 de julho de 2024

| 1.20
| 18 de maio de 2021
| 1º de novembro de 2022
| N/A

| 1.19
| 16 de fevereiro de 2021
| 1º de agosto de 2022
| N/A

| 1.18
| 13 de outubro de 2020
| 15 de agosto de 2022
| N/A
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para o Amazon EKS

Para configurar uma integração do SUSE Observability com o Amazon EKS, você precisa ter:

* Um cluster Amazon EKS em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes do SUSE Observability precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configure uma integração do Amazon EKS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_amazon_eks,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os Agentes tenham sido implantados, eles começarão a coletar dados e enviá-los para o SUSE Observability


== Google GKE

Configurar uma integração do Google GKE para coletar dados de topologia, eventos, logs, alterações e métricas de um cluster Google GKE e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes Version | Lançamento do Google GKE | Fim do Suporte do Google GKE | Fim do Suporte Estendido do Google GKE

| 1.32
| Fevereiro de 2025
| Q2, 2026
| Q1, 2027

| 1.31
| 22 de outubro de 2024
| 22 de dezembro de 2025
| 22 de outubro de 2026

| 1.30
| 30 de julho de 2024
| 30 de setembro de 2025
| 30 de julho de 2026

| 1.29
| 25 de janeiro de 2024
| 21 de março de 2025
| 25 de janeiro de 2026

| 1.28
| 4 de dezembro de 2023
| 4 de fevereiro de 2025
| 4 de dezembro de 2025

| 1.27
| 14 de junho de 2023
| 31 de agosto de 2024
| 14 de junho de 2025

| 1.26
| 14 de abril de 2023
| 30 de junho de 2024
| N/A
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para o Google GKE

Para configurar uma integração do SUSE Observability com o Google GKE, você precisa ter:

* Um cluster Google GKE em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes de Observabilidade da SUSE precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configurar uma integração do Google GKE

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_google_gke,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os Agentes tenham sido implantados, eles começarão a coletar dados e enviá-los para o SUSE Observability


== Azure AKS

Configurar uma integração do Azure AKS para coletar topologia, eventos, logs, dados de alterações e métricas de um cluster Azure AKS e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Kubernetes Version | AKS GA | Fim do serviço do Azure AKS | Suporte de plataforma

| 1.32
| Junho de 2024
| Março de 2026
| Até 1.36 GA

| 1.31
| Novembro de 2024
| Novembro de 2025
| Até 1.35 GA

| 1.30
| Junho de 2024
| Julho de 2025
| Até 1.34 GA

| 1.29
| Março de 2024
| Janeiro de 2025
| Até 1.33 GA

| 1.28
| Novembro de 2023
| Novembro de 2024
| Até 1.32 GA

| 1.27
| Julho de 2023
| Julho de 2024
| Julho de 2025
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para o Azure AKS

Para configurar uma integração do SUSE Observability com o Azure AKS, você precisa ter:

* Um cluster Azure AKS em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes de Observabilidade da SUSE precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configurar uma integração do Azure AKS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_azure_aks,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os Agentes tenham sido implantados, eles começarão a coletar dados e enviar isso para o SUSE Observability


== KOPS

Configurar uma integração do KOPS para coletar dados de topologia, eventos, logs, alterações e métricas de um cluster KOPS e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Versão do Kubernetes suportada

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para o KOPS

Para configurar uma integração do SUSE Observability com o KOPS, você precisa ter:

* Um cluster KOPS em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para conceder permissões aos Agentes do SUSE Observability para acessar a API do Kubernetes.
 ** Os Agentes de Observabilidade da SUSE precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configurar uma integração do KOPS

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_kops,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes no SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o Agente de Observabilidade da SUSE, o Agente do Cluster, o Agente de Verificações e o kube-state-metrics no seu Cluster usando o comando helm fornecido na interface do SUSE Observability após ter instalado o StackPack.
 ** Uma vez que os agentes tenham sido implantados, eles começarão a coletar dados e enviá-los para o SUSE Observability


== Auto-hospedado

Configurar uma integração auto-hospedada para coletar dados de topologia, eventos, logs, alterações e métricas de um cluster auto-hospedado e disponibilizá-los no SUSE Observability.

=== Versões suportadas

|===
| Versão Kubernetes suportada

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Runtime suportado

|===
| Runtime suportado

| ContainerD
| CRI-O
|===

=== Pré-requisitos para auto-hospedado

Para configurar uma integração do SUSE Observability auto-hospedada, você precisa ter:

* Um cluster auto-hospedado em funcionamento.
* Versão do Helm 3.13.1 ou superior.
* Um usuário com permissão para `create privileged pods`, `ClusterRoles` e `ClusterRoleBindings`:
 ** ClusterRole e ClusterRoleBinding são necessários para:
  *** Conceder permissões aos agentes do SUSE Observability para acessar a API do Kubernetes
  *** Gerar um segredo para o webhook de validação mutável que faz parte de xref:/setup/agent/k8sTs-agent-request-tracing.adoc[rastreamento de requisições]
 ** Os agentes do SUSE Observability precisam ser executados em um pod privilegiado para poder coletar informações sobre conexões de rede e informações do host.

=== Configurar uma integração auto-hospedada

[CAUTION]
====
Antes de começar, verifique os <<_prerequisites_for_self_hosted,pré-requisitos para o Kubernetes>>.
====


Para obter dados de um cluster Kubernetes para o SUSE Observability, siga os passos descritos abaixo:

. Adicione o repositório helm do SUSE Observability ao cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Na interface do SUSE Observability, abra o menu principal clicando no canto superior esquerdo da tela e vá para `StackPacks` > `Integrations` > `Kubernetes`.
. Instale uma nova instância do Kubernetes StackPack:
 ** Especifique um *Nome do Cluster Kubernetes*
  *** Este nome será usado para identificar o cluster no SUSE Observability
 ** Clique em *instalar*.
. Implante o agente do SUSE Observability, o agente do cluster, o agente de verificações e o kube-state-metrics no seu cluster usando o comando helm fornecido na interface do SUSE Observability após instalar o StackPack.
 ** Uma vez que os agentes tenham sido implantados, eles começarão a coletar dados e enviá-los para SUSE Observability


== Próximos passos

* xref:/k8s-getting-started.adoc[Passo a passo do SUSE Observability]
