= Documentation SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}

Ceci est la dernière documentation SUSE Observability. Sélectionnez des sujets dans le menu à gauche.

Pour les versions plus anciennes de la documentation, utilisez l'https://archivedocs.stackstate.com[archive].

== Lancez-vous dès aujourd'hui.

Visitez le xref:/k8s-suse-rancher-prime.adoc[guide de démarrage de Rancher Prime] si vous êtes un utilisateur de Rancher Prime, si vous êtes un utilisateur de SUSE Cloud Observability, visitez le xref:/k8s-quick-start-guide.adoc[guide de démarrage rapide], si vous exécutez SUSE Cloud Observability sur AWS, consultez le xref:/suse-cloud-observability-quick-start-guide.adoc[guide de démarrage rapide de SUSE Cloud Observability].

== Vous ne trouvez pas quelque chose ?

Utilisez la barre de recherche en haut à droite. Si vous pensez qu'il manque de documentation, faites-le nous savoir sur le https://scc.suse.com/[site de support SUSE Observability].

== Dépannage et support

Des questions ? Nous pouvons vous prêter main forte. Trouvez l'équipe de support sur le https://scc.suse.com/[site de support SUSE Observability].

== SUSE Observability auto-hébergé

Utilisez SUSE Observability Auto-hébergé pour observer un ensemble étendu de technologies depuis vos propres centres de données ou le cloud.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability en auto-hébergement]

== SUSE Cloud Observability

Utilisez SUSE Cloud Observability pour observer des technologies cloud, telles que Kubernetes et les services AWS.

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observability docs]
