= Guides de démarrage rapide pour SUSE Observability
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability
:doctype: book

== Présentation

Lorsque votre instance SUSE Observability SaaS est configurée, vous recevrez un e-mail de SUSE Observability avec les détails de connexion requis. Ce guide de démarrage rapide vous aidera à commencer et à intégrer vos propres données dans votre instance SUSE Observability SaaS.

Pour intégrer vos clusters avec SUSE Observability, vous pouvez suivre l'un de ces guides pour votre environnement approprié :

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Auto-hébergé>>


== Kubernetes

Configurez une intégration Kubernetes pour collecter la topologie, les événements, les journaux, les modifications et les données de métriques d'un cluster Kubernetes et rendez cela disponible dans SUSE Observability.

=== Versions prises en charge

|===
| Version Kubernetes prise en charge

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Conditions préalables pour Kubernetes

Pour configurer une intégration SUSE Observability Kubernetes, vous devez disposer de :

* Un cluster Kubernetes opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les permissions d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration Kubernetes

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_kubernetes,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *Nom de Cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez l'agent d'observabilité SUSE, l'agent de cluster, l'agent de vérification et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur d'observabilité SUSE après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.

[CAUTION]
====
Lors de l'exécution dans un environnement auto-hébergé isolé physiquement, préparez d'abord l'installation de l'agent en suivant les xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[instructions isolées physiquement].
====


== OpenShift

Configurez une intégration OpenShift pour collecter des données de topologie, d'événements, de journaux, de changements et de métriques d'un cluster OpenShift et rendez cela disponible dans SUSE Observability.

=== Versions prises en charge

|===
| Version OpenShift | Version Kubernetes prise en charge | Fin de support OpenShift

| OpenShift 4.17
| Kubernetes 1.30
| 1er avril 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27 décembre 2025

| OpenShift 4.15
| Kubernetes 1.28
| 27 août 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1er mai 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17 novembre 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17 juillet 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10 février 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10 septembre 2023

| OpenShift 4.9
| Kubernetes 1.22
| 18 avril 2023
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Conditions préalables pour OpenShift

Pour configurer une intégration SUSE Observability avec OpenShift, vous devez disposer de :

* Un cluster OpenShift opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les permissions d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration OpenShift

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_openshift,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *Nom de Cluster Kubernetes* :
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez l'agent d'observabilité SUSE, l'agent de cluster, l'agent de vérification et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur d'observabilité SUSE après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== Amazon EKS

Configurez une intégration Amazon EKS pour collecter des données de topologie, d'événements, de journaux, de modifications et de métriques d'un cluster Amazon EKS et les rendre disponibles dans SUSE Observability.

=== Versions prises en charge

|===
| Version de Kubernetes | Version d'Amazon EKS | Fin de support d'Amazon EKS | Fin de support prolongé d'Amazon EKS

| 1.32
| 23 janvier 2025
| 23 mars 2026
| 23 mars 2027

| 1.31
| 26 septembre 2024
| 26 novembre 2025
| 26 novembre 2026

| 1.30
| 23 mai 2024
| 23 juillet 2025
| 23 juillet 2026

| 1.29
| 23 janvier 2024
| 23 mars 2025
| 23 mars 2026

| 1.28
| 26 septembre 2023
| 01 novembre 2024
| 26 novembre 2025

| 1.27
| 24 mai 2023
| juillet 2024
| 24 juillet 2025

| 1.26
| 11 avril 2023
| Juin 2024
| 11 juin 2025

| 1.25
| 21 février 2023
| Mai 2024
| 1er mai 2025

| 1.24
| 15 novembre 2022
| Janvier 2024
| 31 janvier 2025

| 1.23
| 11 août 2022
| 11 octobre 2023
| 11 octobre 2024

| 1.22
| 4 avril 2022
| 4 juin 2023
| 1 septembre 2024

| 1.21
| 19 juillet 2021
| 15 février 2023
| 15 juillet 2024

| 1.20
| 18 mai 2021
| 1er novembre 2022
| S/O

| 1.19
| 16 février 2021
| 1er août 2022
| S/O

| 1.18
| 13 octobre 2020
| 15 août 2022
| S/O
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Conditions préalables pour Amazon EKS

Pour configurer une intégration SUSE Observability avec Amazon EKS, vous devez disposer de :

* Un cluster Amazon EKS opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les permissions d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration Amazon EKS

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_amazon_eks,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *Nom du cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez l'Agent SUSE Observability, l'Agent de cluster, l'Agent de vérification et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur de SUSE Observability après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== Google GKE

Configurer une intégration Google GKE pour collecter des données de topologie, d'événements, de journaux, de modifications et de métriques d'un cluster Google GKE et les rendre disponibles dans SUSE Observability.

=== Versions prises en charge

|===
| Kubernetes Version | Version de Google GKE | Fin de support de Google GKE | Fin du support prolongé de Google GKE

| 1.32
| Février 2025
| T2 2026
| T1 2027

| 1.31
| 22 octobre 2024
| 22 décembre 2025
| 22 octobre 2026

| 1.30
| 30 juillet 2024
| 30 septembre 2025
| 30 juillet 2026

| 1.29
| 25 janvier 2024
| 21 mars 2025
| 25 janvier 2026

| 1.28
| 4 décembre 2023
| 4 février 2025
| 4 décembre 2025

| 1.27
| 14 juin 2023
| 31 août 2024
| 14 juin 2025

| 1.26
| 14 avril 2023
| 30 juin 2024
| S/O
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Prérequis pour Google GKE

Pour configurer une intégration SUSE Observability avec Google GKE, vous devez avoir :

* Un cluster Google GKE opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les autorisations d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration Google GKE

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_google_gke,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *Nom du cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez l'agent SUSE Observability, l'agent de cluster, l'agent de vérification et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur de SUSE Observability après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== Azure AKS

Configurer une intégration Azure AKS pour collecter des données de topologie, d'événements, de journaux, de modifications et de métriques à partir d'un cluster Azure AKS et les rendre disponibles dans SUSE Observability.

=== Versions prises en charge

|===
| Kubernetes Version | AKS GA | Fin du service d'Azure AKS | Prise en charge des plates-formes

| 1.32
| Juin 2024
| Mars 2026
| Jusqu'à 1.36 GA

| 1.31
| Novembre 2024
| Novembre 2025
| Jusqu'à 1.35 GA

| 1.30
| Juin 2024
| Juillet 2025
| Jusqu'à 1.34 GA

| 1.29
| Mars 2024
| Janvier 2025
| Jusqu'à 1.33 GA

| 1.28
| Novembre 2023
| Novembre 2024
| Jusqu'à 1.32 GA

| 1.27
| Juillet 2023
| Juillet 2024
| Juillet 2025
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Prérequis pour Azure AKS

Pour configurer une intégration SUSE Observability avec Azure AKS, vous devez disposer de :

* Un cluster Azure AKS opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les permissions d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration Azure AKS

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_azure_aks,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *Nom du cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez l'agent SUSE Observability, l'agent de cluster, l'agent de vérification et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur de SUSE Observability après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== KOPS

Configurer une intégration KOPS pour collecter des données de topologie, d'événements, de journaux, de modifications et de métriques d'un cluster KOPS et les rendre disponibles dans SUSE Observability.

=== Versions prises en charge

|===
| Version Kubernetes prise en charge

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Prérequis pour KOPS

Pour configurer une intégration SUSE Observability KOPS, vous devez disposer de :

* Un cluster KOPS opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour accorder aux agents SUSE Observability les permissions d'accéder à l'API Kubernetes.
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration KOPS

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_kops,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *nom du cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez le SUSE Observability Agent, le Cluster Agent, le Checks Agent et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur SUSE Observability après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== Auto-hébergé

Configurer une intégration auto-hébergée pour collecter des données de topologie, d'événements, de journaux, de modifications et de métriques d'un cluster auto-hébergé et les rendre disponibles dans SUSE Observability.

=== Versions prises en charge

|===
| Version Kubernetes prise en charge

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Composant d'exécution pris en charge

|===
| Composant d'exécution pris en charge

| ContainerD
| CRI-O
|===

=== Conditions préalables pour l'auto-hébergement

Pour configurer une intégration SUSE Observability auto-hébergée, vous devez disposer de :

* Un cluster auto-hébergé opérationnel.
* Helm version 3.13.1 ou supérieure.
* Un utilisateur ayant la permission de `create privileged pods`, `ClusterRoles` et `ClusterRoleBindings` :
 ** ClusterRole et ClusterRoleBinding sont nécessaires pour :
  *** Accorder aux SUSE Observability Agents l'accès à l'API Kubernetes
  *** Générer un secret pour le webhook de validation mutante qui fait partie de xref:/setup/agent/k8sTs-agent-request-tracing.adoc[la traçabilité des requêtes]
 ** Les agents SUSE Observability doivent s'exécuter dans un pod privilégié pour pouvoir collecter des informations sur les connexions réseau et les informations sur l'hôte.

=== Configurer une intégration auto-hébergée

[CAUTION]
====
Avant de commencer, vérifiez les <<_prerequisites_for_self_hosted,conditions préalables pour Kubernetes>>.
====


Pour obtenir des données d'un cluster Kubernetes dans SUSE Observability, suivez les étapes décrites ci-dessous :

. Ajoutez le dépôt helm SUSE Observability au client helm local :
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Dans l'interface utilisateur de SUSE Observability, ouvrez le menu principal en cliquant en haut à gauche de l'écran et allez à `StackPacks` > `Integrations` > `Kubernetes`.
. Installez une nouvelle instance du StackPack Kubernetes :
 ** Spécifiez un *nom du cluster Kubernetes*
  *** Ce nom sera utilisé pour identifier le cluster dans SUSE Observability.
 ** Cliquez sur *installer*.
. Déployez le SUSE Observability Agent, le Cluster Agent, le Checks Agent et kube-state-metrics sur votre cluster en utilisant la commande helm fournie dans l'interface utilisateur SUSE Observability après avoir installé le StackPack.
 ** Une fois les agents déployés, ils commenceront à collecter des données et à les envoyer à SUSE Observability.


== Opérations suivantes

* xref:/k8s-getting-started.adoc[Présentation de SUSE Observability]
