= Configurando o SUSE Observability para notificações por e-mail
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Auto-hospedado

[CAUTION]
====
Usuários de SaaS do SUSE Observability podem usar notificações por e-mail sem configuração adicional. Este guia é aplicável apenas para instalações do SUSE Observability auto-hospedadas que planejam usar o canal de notificação por e-mail.
====


Antes de usar o canal de notificação por e-mail no SUSE Observability, você precisa seguir os seguintes passos:

== Configure o SUSE Observability com a configuração SMTP

O SUSE Observability precisa ser configurado com credenciais para se conectar ao servidor SMTP. Você pode fazer isso adicionando o seguinte ao arquivo `values.yaml` da sua instalação do SUSE Observability:

[,yaml]
----
stackstate:
  email:
    enabled: true
    sender: "<stackstate@example.com>"
    server:
      host: "<smtp.example.com>"
      auth:
        username: "<user name>"
        password: "<user password>"
----

Isso usará a porta `587` no servidor SMTP e utiliza o comando `STARTTLS` para estabelecer uma conexão segura. Estas são todas as outras opções que podem ser personalizadas:

[,yaml]
----
stackstate:
  email:
    additionalProperties:
      # Add needed Java email properties for your mail server (use string values), defaults are:
      "mail.smtp.auth": "true"
      "mail.smtp.starttls.enable": "true"
    server:
      protocol: smtp
      port: 587
----

=== Usando um segredo externo

Quando o nome de usuário e a senha não puderem ser fornecidos nos valores, mas devem vir de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_username_and_password_for_email_sending_from_an_external_secret[estes passos]
