= k8sカスタムシークレットの設定（廃止）
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概要

SUSE Observabilityエージェントは、APIキーとクラスター認証トークンを含むカスタムシークレットの名前を指定することをサポートしています。この機能は、自分のシークレットを管理し、Helmチャートによるシークレットの自動作成を避けたいユーザーにとって便利です。

[CAUTION]
====
*このシークレットのカスタマイズ方法は廃止されており、RBAC機能と互換性がありません。*

外部シークレットを使用するには、xref:/setup/agent/k8s-custom-secrets-setup.adoc[新しい方法]を使用してください。
====


== Helmチャート

=== 設定オプション

* `stackstate.manageOwnSecrets`:ユーザーが自分のシークレットを管理したいかどうかを決定するブール値。デフォルト値は`false`です。
* `stackstate.customSecretName`:（オプション）ユーザーによって作成されるカスタムシークレットの名前。`stackstate.manageOwnSecrets`が`true`に設定されている場合は必須です。
* `stackstate.customApiKeySecretKey`:（オプション）カスタムシークレット内のAPIキーのキー名。`stackstate.manageOwnSecrets`が`true`に設定されている場合は必須です。
* `stackstate.customClusterAuthTokenSecretKey`:（オプション）カスタムシークレット内のクラスター認証トークンのキー名。`stackstate.manageOwnSecrets`が`true`に設定されている場合は必須です。

=== 動作説明

* *自動シークレット作成*：デフォルトでは、`stackstate.manageOwnSecrets`が`false`に設定されている場合、チャートは以前と同様にシークレットを自動的に作成し続けます。
* *カスタムシークレット管理*：`stackstate.manageOwnSecrets`が`true`に設定されている場合、チャートはユーザーがカスタムシークレットの名前（`stackstate.customSecretName`）と、APIキーおよびクラスター認証トークンのキー（それぞれ`stackstate.customApiKeySecretKey`と`stackstate.customClusterAuthTokenSecretKey`）を提供することを期待します。
* *暗黙の省略*：自分のシークレットを管理したいと指定した場合、チャートは`stackstate.apiKey`と`stackstate.cluster.authToken`の値を無視します。
+
== values.yamlでのハウツー

. *自動シークレット作成の使用（デフォルト）*：
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *自分のシークレットを管理する*
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
