= k8sカスタムシークレット管理
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概要

SUSE Observabilityエージェントは、APIキーとクラスター認証トークンを含むカスタムシークレットの名前を指定することをサポートしています。この機能は、自分自身のシークレットを管理し、Helmチャートによるシークレットの自動作成を避けたいユーザーにとって便利です。

NOTE: *以前はこれを指定する方法がありましたが、現在は廃止されています。xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[廃止された方法]を参照してください。*

== Helmチャート

=== 設定オプション

* `global.apiKey.fromSecret`:同じネームスペースに存在する事前に作成されたシークレット名を指定し、そのシークレットにはAPIキーを含む`STS_API_KEY`フィールドが含まれている必要があります。
* `global.clusterAgentAuthToken.fromSecret`:同じネームスペースに存在する事前に作成されたシークレット名を指定し、そのシークレットにはクラスターとノードエージェント間の接続を保護するためのトークンを含む`STS_CLUSTER_AGENT_AUTH_TOKEN`フィールドが含まれている必要があります。

=== 動作説明

* *自動シークレット作成*:デフォルトでは、チャートは`stackstate.apiKey`を指定する必要があり、自動的にシークレットを作成します。`STS_CLUSTER_AGENT_AUTH_TOKEN`は自動的に生成されます。
* *カスタムシークレット管理*:`fromSecret`フィールドをオーバーライドする場合、APIキーとクラスター認証トークンはそれらのシークレットから取得されます。
* *暗黙の省略*:自分自身のシークレットを管理したいと指定した場合、チャートは`stackstate.apiKey`と`stackstate.cluster.authToken`の値を無視します。

== values.yamlでの使用方法

. *自動シークレット作成の使用（デフォルト）*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *自分自身のシークレットの管理*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
