= SUSE Observability-Dokumentation
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}

Dies ist die neueste SUSE Observability-Dokumentation. Wählen Sie Themen aus dem Inhaltsmenü auf der linken Seite aus.

Für ältere Versionen der Dokumentation verwenden Sie das https://archivedocs.stackstate.com[Archiv].

== Worauf warten Sie noch?

Besuchen Sie die xref:/k8s-suse-rancher-prime.adoc[Rancher Prime Kurzanleitung], wenn Sie Rancher Prime-Nutzer sind. Wenn Sie SUSE Cloud Observability-Nutzer sind, besuchen Sie die xref:/k8s-quick-start-guide.adoc[Kurzanleitung]. Wenn Sie SUSE Cloud Observability auf AWS verwenden, sehen Sie sich die xref:/suse-cloud-observability-quick-start-guide.adoc[SUSE Cloud Observability Kurzanleitung] an.

== Fehlt etwas?

Verwenden Sie die Suchleiste oben rechts. Wenn Sie denken, dass Dokumentation fehlt, lassen Sie es uns auf der https://scc.suse.com/[SUSE Observability-Supportseite] wissen.

== Fehlerbehebung und Unterstützung

Haben Sie Fragen? Dann können wir Sie beruhigen. Finden Sie das Support-Team auf der https://scc.suse.com/[SUSE Observability-Supportseite].

== SUSE Observability Selbstgehostet

Verwenden Sie SUSE Observability Self-hosted, um eine umfangreiche Reihe von Technologien aus eigenen Rechenzentren oder der Cloud zu beobachten.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability Selbstgehostet]

== SUSE Cloud Observability

Verwenden Sie SUSE Cloud Observability, um Cloud-Technologien wie Kubernetes und AWS-Dienste zu beobachten.

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observability-Dokumentation]
