= SUSE Observability Kurzanleitungen
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability
:doctype: book

== Übersicht

Wenn Ihre SUSE Observability SaaS-Instanz eingerichtet und konfiguriert ist, erhalten Sie eine E-Mail von SUSE Observability mit den erforderlichen Anmeldedaten. Diese Kurzanleitung hilft Ihnen, loszulegen und Ihre eigenen Daten in Ihre SUSE Observability SaaS-Instanz zu bringen.

Um Ihre(n) Cluster mit SUSE Observability zu integrieren, können Sie eine dieser Anleitungen für Ihre entsprechende Umgebung befolgen.

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Selbst gehostet>>


== Kubernetes

Richten Sie eine Kubernetes-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Kubernetes-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Kubernetes

Um eine SUSE Observability Kubernetes-Integration einzurichten, benötigen Sie:

* Ein funktionierendes Kubernetes-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine Kubernetes-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_kubernetes,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu erhalten, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie auf *install*.
. Stellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl bereit, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese an SUSE Observability.

[CAUTION]
====
Wenn Sie in einer selbst gehosteten Air-Gapped-Umgebung arbeiten, bereiten Sie zuerst die Agenteninstallation mit den xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[Air-Gapped-Anweisungen] vor.
====


== OpenShift

Richten Sie eine OpenShift-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem OpenShift-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| OpenShift-Version | Unterstützte Kubernetes-Version | Ende des Supports für OpenShift

| OpenShift 4.17
| Kubernetes 1.30
| 1. April 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27. Dezember 2025

| OpenShift 4.15
| Kubernetes 1.28
| 27. August 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1. Mai 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17. November 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17. Juli 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10. Februar 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10. September 2023

| OpenShift 4.9
| Kubernetes 1.22
| 18. April 2023
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für OpenShift

Um eine SUSE Observability OpenShift-Integration einzurichten, benötigen Sie:

* Ein funktionierendes OpenShift-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine OpenShift-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_openshift,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu erhalten, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie auf *install*.
. Stellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl bereit, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese Daten an SUSE Observability.


== Amazon EKS

Richten Sie eine Amazon EKS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Amazon EKS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes-Version | Amazon EKS-Version | Ende der Unterstützung für Amazon EKS | Ende der erweiterten Unterstützung für Amazon EKS

| 1.32
| 23. Januar 2025
| 23. März 2026
| 23. März 2027

| 1.31
| 26. September 2024
| 26. November 2025
| 26. November 2026

| 1.30
| 23. Mai 2024
| 23. Juli 2025
| 23. Juli 2026

| 1.29
| 23. Januar 2024
| 23. März 2025
| 23. März 2026

| 1.28
| 26. September 2023
| 01. November 2024
| 26. November 2025

| 1.27
| 24. Mai 2023
| Juli 2024
| 24. Juli 2025

| 1.26
| 11. April 2023
| Juni 2024
| 11. Juni 2025

| 1.25
| 21. Februar 2023
| Mai 2024
| 1. Mai 2025

| 1.24
| 15. November 2022
| Januar 2024
| 31. Januar 2025

| 1.23
| 11. August 2022
| 11. Oktober 2023
| 11. Oktober 2024

| 1.22
| 4. April 2022
| 4. Juni 2023
| 1. September 2024

| 1.21
| 19. Juli 2021
| 15. Februar 2023
| 15. Juli 2024

| 1.20
| 18. Mai 2021
| 1. November 2022
| Nicht zutreffend

| 1.19
| 16. Februar 2021
| 1. August 2022
| Nicht zutreffend

| 1.18
| 13. Oktober 2020
| 15. August 2022
| Nicht zutreffend
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Amazon EKS

Um eine SUSE Observability Amazon EKS-Integration einzurichten, benötigen Sie:

* Ein funktionierender Amazon EKS-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine Amazon EKS-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_amazon_eks,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu erhalten, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie *installieren*.
. Bereitstellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese an SUSE Observability.


== Google GKE

Richten Sie eine Google GKE-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Google GKE-Cluster zu sammeln und in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes Version | Google GKE-Version | Google GKE Ende der Unterstützung | Google GKE Ende der erweiterten Unterstützung

| 1.32
| Februar 2025
| Q2, 2026
| Q1 2027

| 1.31
| 22. Oktober 2024
| 22. Dezember 2025
| 22. Oktober 2026

| 1.30
| 30. Juli 2024
| 30. September 2025
| 30. Juli 2026

| 1.29
| 25. Januar 2024
| 21. März 2025
| 25. Januar 2026

| 1.28
| 4. Dezember 2023
| 4. Februar 2025
| 4. Dezember 2025

| 1.27
| 14. Juni 2023
| 31. August 2024
| 14. Juni 2025

| 1.26
| 14. April 2023
| 30. Juni 2024
| Nicht zutreffend
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Google GKE

Um eine SUSE Observability Google GKE-Integration einzurichten, benötigen Sie:

* Einen funktionierenden Google GKE-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine Google GKE-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_google_gke,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu erhalten, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie *installieren*.
. Bereitstellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese an SUSE Observability.


== Azure AKS

Richten Sie eine Azure AKS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem Azure AKS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Kubernetes Version | AKS GA | Azure AKS Lebenszyklusende | UNTERSTÜTZTE PLATTFORMEN

| 1.32
| Juni 2024
| März 2026
| Bis 1.36 GA

| 1.31
| November 2024
| November 2025
| Bis 1.35 GA

| 1.30
| Juni 2024
| Juli 2025
| Bis 1.34 GA

| 1.29
| März 2024
| Januar 2025
| Bis 1.33 GA

| 1.28
| November 2023
| November 2024
| Bis 1.32 GA

| 1.27
| Juli 2023
| Juli 2024
| Juli 2025
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für Azure AKS

Um eine SUSE Observability Azure AKS-Integration einzurichten, benötigen Sie:

* Ein funktionierendes Azure AKS-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine Azure AKS-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_azure_aks,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu erhalten, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie *installieren*.
. Bereitstellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese an SUSE Observability.


== KOPS

Richten Sie eine KOPS-Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem KOPS-Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für KOPS

Um eine SUSE Observability KOPS-Integration einzurichten, benötigen Sie:

* Ein funktionierendes KOPS-Cluster.
* Helm Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um den SUSE Observability Agents Berechtigungen zum Zugriff auf die Kubernetes-API zu gewähren.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine KOPS-Integration ein

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_kops,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen, befolgen Sie die nachstehenden Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie *installieren*.
. Stellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mit dem Helm-Befehl bereit, der in der SUSE Observability UI bereitgestellt wird, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt wurden, beginnen sie damit, Daten zu sammeln und senden diese an SUSE Observability.


== selbstgehostet

Richten Sie eine selbstgehostete Integration ein, um Topologie-, Ereignis-, Protokoll-, Änderungs- und Metrikdaten von einem selbstgehosteten Cluster zu sammeln und diese in SUSE Observability verfügbar zu machen.

=== Unterstützte Versionen

|===
| Unterstützte Kubernetes-Version

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Unterstützte Laufzeit

|===
| Unterstützte Laufzeit

| ContainerD
| CRI-O
|===

=== Voraussetzungen für selbstgehostete Integrationen

Um eine SUSE Observability selbstgehostete Integration einzurichten, benötigen Sie:

* Ein funktionierender selbstgehosteter Cluster.
* Helm-Version 3.13.1 oder höher.
* Ein Benutzer mit den Berechtigungen für `create privileged pods`, `ClusterRoles` und `ClusterRoleBindings`:
 ** ClusterRole und ClusterRoleBinding sind erforderlich, um:
  *** Den SUSE Observability Agents die Berechtigung zu erteilen, auf die Kubernetes-API zuzugreifen.
  *** Ein Geheimnis für das mutierende Validierungs-Webhook zu generieren, das Teil der xref:/setup/agent/k8sTs-agent-request-tracing.adoc[Anforderungsverfolgung] ist.
 ** SUSE Observability Agents müssen in einem privilegierten Pod ausgeführt werden, um Informationen über Netzwerkverbindungen und Hostinformationen sammeln zu können.

=== Richten Sie eine selbstgehostete Integration ein.

[CAUTION]
====
Bevor Sie beginnen, überprüfen Sie die <<_prerequisites_for_self_hosted,Voraussetzungen für Kubernetes>>.
====


Um Daten aus einem Kubernetes-Cluster in SUSE Observability zu übertragen, befolgen Sie die unten beschriebenen Schritte:

. Fügen Sie das SUSE Observability Helm-Repository zum lokalen Helm-Client hinzu:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. Öffnen Sie in der SUSE Observability UI das Hauptmenü, indem Sie oben links auf dem Bildschirm klicken, und gehen Sie zu `StackPacks` > `Integrations` > `Kubernetes`.
. Installieren Sie eine neue Instanz des Kubernetes StackPack:
 ** Geben Sie einen *Kubernetes-Cluster-Namen* an.
  *** Dieser Name wird verwendet, um den Cluster in SUSE Observability zu identifizieren
 ** Klicken Sie *installieren*.
. Stellen Sie den SUSE Observability Agent, Cluster Agent, Checks Agent und kube-state-metrics auf Ihrem Cluster mithilfe des in der SUSE Observability UI bereitgestellten Helm-Befehls bereit, nachdem Sie das StackPack installiert haben.
 ** Sobald die Agenten bereitgestellt sind, beginnen sie mit der Datensammlung und senden diese an SUSE Observability.


== Weitere Schritte

* xref:/k8s-getting-started.adoc[SUSE Observability Anleitung]
