= Envio de Logs
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Instalação do Agente

=== Openshift

Soluções de envio de logs de terceiros não são prontamente suportadas no Openshift, cuja plataforma dispõe de opções para encaminhamento de logs utilizadas em vez da configuração do promtail incluída no gráfico helm do SUSE Observability.  Para instruções detalhadas sobre como configurar isso, consulte a documentação do stackpack do Kubernetes em sua instância do SUSE Observability em execução.

=== Kubernetes

A configuração padrão do gráfico helm do agente k8s do SUSE Observability define o envio de logs como habilitado através dos valores helm fornecidos com o gráfico:

[,yaml]
----
logsAgent:
  # logsAgent.enabled -- Enable / disable k8s pod log collection
  enabled: true
----

O acima garantirá que um contêiner promtail seja implantado em cada nó para coletar logs e enviá-los ao SUSE Observability.  Para implantações onde não é desejável enviar logs para o SUSE Observability, defina o valor acima como `false`.

=== Executando Pods Promtail Adicionais

O SUSE Observability utiliza uma configuração ajustada para ingestão de logs, e isso geralmente não está alinhado com requisitos auxiliares.  Portanto, não é possível executar uma configuração separada para a ingestão de logs em outros pontos de destino; recomenda-se, em vez disso, executar um segundo pod promtail que trate desses requisitos como uma responsabilidade separada daquele promtail implantado pelo gráfico helm do agente.
