= About StackPacks
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted v5.1.x

== Overview

StackPacks extend SUSE Observability functionality and offer automated integration with external systems. They can be easily installed and uninstalled from the StackPacks page in SUSE Observability.

There are two types of StackPack - Add-ons and Integrations. The available StackPack add-ons and integrations can be found on the *StackPacks* page in the SUSE Observability UI.

== Install or uninstall a StackPack

StackPacks can be installed and uninstalled from the *StackPacks* page in SUSE Observability. Full instructions to install and uninstall the StackPack are provided.

[NOTE]
====
*Note that:*

* A StackPack may require *manual* installation steps or configuration of the external system. Please read the instructions provided carefully.
* When a StackPack or StackPack instance is uninstalled, *all data received via the StackPack (instance) will be removed from SUSE Observability.*
* Any (manual) configuration or installation of StackPack components in an external system may need to be uninstalled separately.

====


=== StackPack instances

Some StackPacks allow you to connect to multiple accounts on an external system. Each account is configured in a separate instance of the StackPack.

For example, the AWS StackPack can connect to multiple AWS accounts and combine information from all accounts in SUSE Observability. For each account, a separate SUSE Observability instance is configured with the information required to receive data from that AWS account.

== Upgrade a StackPack

[CAUTION]
====
When a StackPack is upgraded, *any changes made to configuration items from that StackPack will be overwritten*. For details, see xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[locked configuration items].
====


If a new StackPack version is available, an alert will be displayed on the SUSE Observability UI StackPack page and you will have the option to view the upgrade details and read the release notes. If the new release is a minor upgrade from the currently installed version, you can also upgrade the StackPack from here.

=== New minor StackPack version

To upgrade to a new minor version of a StackPack, click *UPGRADE NOW* on the StackPack page in the SUSE Observability UI.

Note that all StackPack configuration items will be overwritten when you upgrade. To continue using any changes made to these, choose to *KEEP* the existing configuration when you upgrade the StackPack. For details, see xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[locked configuration items].

=== New major StackPack version

[CAUTION]
====
When a StackPack is upgraded, *any changes made to configuration items from that StackPack will be overwritten*. For details, see xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[locked configuration items].
====


To upgrade to a new major version of a StackPack, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[uninstall and reinstall] the StackPack.

[TIP]
====

Continue using changes made to customized StackPack configuration items after upgrade:

. Before you upgrade, export each customized item:
 ** Go to the *Settings* page in the SUSE Observability UI.
 ** Click *Export* in the *...* menu for each customized item.
. Upgrade the StackPack (uninstall and reinstall).
. Change the `name` and `identifier` for each exported item:
 ** Open the export file in a text editor.
 ** Edit the top-level `name` and `identifier` fields.
 ** Save the export.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Import] the updated export file(s).
. The customized configuration items will now be available in SUSE Observability and can be copied to the newly installed StackPack configuration items.

====


== Downgrade a StackPack

If a newer StackPack version does not behave as expected, you can go back to an older version. Downgrading is done with the xref:/setup/cli/cli-sts.adoc[SUSE Observability CLI (`sts`)].

The way you downgrade depends on the StackPack packaging format:

* *v2 StackPacks* can be downgraded in place with the dedicated `sts stackpack downgrade` command.
* *v1 StackPacks* cannot be downgraded in place and must be uninstalled and reinstalled at the older version.

=== List the available versions

To see which versions of a StackPack are available and which one is currently in use, run:

[source,bash]
----
sts stackpack list-versions --name <stackpack-name>
----

The output lists every available version with the following columns:

* `version` - the version string, for example `1.2.3`.
* `dev` - whether it is a development version.
* `in use` - whether the version is currently installed.

=== Downgrade a v2 StackPack

For StackPacks that use the v2 packaging format, downgrade all installed instances to an older version with the `sts stackpack downgrade` command:

[source,bash]
----
sts stackpack downgrade --name <stackpack-name> --stackpack-version <older-version>
----

The target version must be *lower* than the currently installed version. Wait for the downgrade to complete with the `--wait` flag:

[source,bash]
----
sts stackpack downgrade --name <stackpack-name> --stackpack-version <older-version> --wait
----

[NOTE]
====
The downgrade is rejected if:

* The requested version does not exist. Use `sts stackpack list-versions --name <stackpack-name>` to see the available versions.
* The requested version is not lower than the currently installed version.
* The requested version is a v1 StackPack. In that case, downgrade using the uninstall and reinstall procedure below.
====

=== Downgrade a v1 StackPack

StackPacks that use the v1 packaging format cannot be downgraded in place. To go back to an older version of a v1 StackPack:

. xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[Uninstall] the StackPack.
. Uninstall the all instances of the stackpack:
+
[source,bash]
----
sts stackpack uninstall --name <stackpack-name> --id <stackpack_instance_id>
----

. Install the specific older version:
+
[source,bash]
----
sts stackpack install --name <stackpack-name> --stackpack-version <older-version>
----


== Locked configuration items

StackPacks contain configuration information for SUSE Observability that's installed when the StackPack (instance) is installed. Amongst other things, this could be component templates, functions, component actions and views. When a StackPack is upgraded, *the configuration items installed by the previous version of the StackPack will be overwritten by those from the newer StackPack.* This means that any manual change made to these configuration items will be overwritten when the StackPack is upgraded.

To prevent a user from making changes to configuration items installed by a StackPack that will be overwritten on upgrade, these configuration items are *locked* by default. This means that they're protected from being changed by the user and must explicitly be *unlocked* before they can be changed.

[TIP]
====

You can xref:/setup/data-management/backup_restore/configuration_backup.adoc[make a back-up of configuration items]. Note that the lock status of configuration items won't be exported as part of a configuration backup.
====
