= Identificadores
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Descripción general

Los identificadores se utilizan en SUSE Observability para identificar objetos, como elementos de topología (componentes y relaciones) y funciones. Esta página describe los diferentes tipos de identificadores utilizados para elementos de topología y cómo se estructuran los identificadores de ámbito global en SUSE Observability.

== Identificadores de topología

Los elementos de topología utilizan dos tipos de identificadores en SUSE Observability:

* *Identificadores de ámbito de integración* - utilizados para identificar componentes y relaciones dentro de una integración. Cada componente o relación tiene solo un identificador de ámbito de integración. El identificador es arbitrario, pero debe ser consistente dentro del ámbito de la propia integración.
* *Identificadores de ámbito global* - utilizados para fusionar componentes entre integraciones, por ejemplo, ServiceNow y el Agente de SUSE Observability. Cada componente puede tener múltiples identificadores de ámbito global, mientras que las relaciones no tienen identificadores globales. Se asignan por SUSE Observability y se formatean de acuerdo con la xref:/configure/topology/identifiers.adoc#_global_scope_identifiers[convención de identificadores globales de SUSE Observability].

El siguiente ejemplo de código muestra un componente con ambos tipos de identificadores.

* Identificador de ámbito de integración - `this-host-unique-identifier`
* Identificador de ámbito global - `urn:host:/this-host-fqdn`


[,text]
----
self.component("this-host-unique-identifier", "Host", {
    "name": "this-host",
    "domain": "Webshop",
    "layer": "Machines",
    "identifiers": ["urn:host:/this-host-fqdn"],
    "labels": ["host:this-host", "region:eu-west-1"],
    "environment": "Production"
})
----


== Identificadores del Agente de SUSE Observability

Los identificadores de ámbito global utilizados por el Agente de SUSE Observability para identificar elementos de topología sincronizados se enumeran en la tabla a continuación.

|===
| Tipo de recurso | Formato de identificador URN

| Host
| `urn:host:/[hostName]`

| Proceso
| `urn:process:/[hostName]:[pid]:[createTime]`

| Contenedor
| `urn:container:/[hostName]:[containerId]`

| Servicio descubierto con trazas
| `urn:service:/[serviceName]`

| Instancia de servicio descubierta con trazas
| `urn:service-instance:/[serviceName]:/[hostName]`
|===

Consulta los xref:/configure/topology/identifiers.adoc#_stackstate_agent[identificadores de ámbito global de ejemplo del Agente de SUSE Observability].

== Identificadores de ámbito global

Cuando SUSE Observability recibe componentes con identificadores de ámbito global coincidentes de diferentes fuentes externas, los componentes y sus propiedades (etiquetas, flujos, comprobaciones) se fusionan en un único componente. Esto permite combinar datos de diferentes fuentes en un único panorama de TI.

Los identificadores de ámbito global en SUSE Observability son un URN globalmente único que coincide con la siguiente convención:

[,text]
----
urn:<prefix>:<type-name>:<free-form>
----

Ten en cuenta que no todos los caracteres están permitidos en un identificador URN. Puedes comprobar tus identificadores con la siguiente expresión regular de URN:

[,text]
----
^urn:[a-z0-9][a-z0-9-]{0,31}:[a-z0-9()+,\-.:=@;$_!*'%/?#]+$
----

El formato de los segmentos `<prefix>` y `<type-name>:<free-form>` se describe a continuación.

=== Prefijo

El segmento `prefix` es una parte obligatoria de un identificador global. Nombra el ámbito al que pertenece el identificador y se utiliza únicamente con fines organizativos.

[NOTE]
====
Cuando el prefijo incluye un nombre de StackPack, el objeto estará bajo el control de ese StackPack. Esto significa que el objeto se desinstalará cuando se desinstale el StackPack.
====


Los prefijos de URN reconocidos son:

* `stackpack:<name>` - objetos que pertenecen a StackPacks.
* `stackpack:<name>:shared` - objetos compartidos entre instancias de un StackPack.
* `stackpack:<name>:instance:{{instanceId}}` - objetos que pertenecen a una instancia específica de un StackPack, donde `{{instanceId}}` es un handlebar que devuelve el ID proporcionado durante el proceso de instalación del StackPack para cada instancia específica del StackPack.
* `system:auto` - objetos creados por el sistema que no pertenecen a ningún StackPack específico.

=== Nombre de tipo y formato libre

El identificador se identifica de manera única por los `<type-name>:<free-form>` segmentos.

* `<type-name>` coincide con el tipo de objeto de dominio del objeto al que se le asigna el identificador (no distingue entre mayúsculas y minúsculas).
* `<free-form>` es arbitrario, pero debe ser único para el tipo. El formato del segmento de forma libre es decidido por el usuario. No necesita coincidir con el nombre del objeto (si es que hay alguno presente) y puede consistir en múltiples segmentos.

== Identificadores de ejemplo

=== StackPack Común

Identificadores de ámbito global URN de ejemplo del StackPack común. Los objetos se desinstalarán cuando se desinstale el StackPack común.

* Tipo de componente servidor:
 ** `urn:stackpack:common:component-type:server`

=== Agente de SUSE Observability

Identificadores de ámbito global URN de ejemplo del Agente de SUSE Observability.

* Host:
 ** `urn:host:/example.org`
* Proceso:
 ** `urn:process:/db.infra.company.org:161841:1602158335000`
* Contenedor:
 ** `urn:container:/compnode5.k8s.example.org:8b18c68a820904c55b4909d7f5a9a52756d45e866c07c92bf478bcf6cd240901`
* Servicio descubierto con trazas:
 ** `urn:service:/prod-db`
* Instancia de servicio descubierta con trazas:
 ** `urn:service-instance:/prod-db:/main.example.org`

=== Otros StackPacks

Identificadores de ámbito global URN de ejemplo de varios StackPacks. Los objetos se desinstalarán cuando se desinstale el StackPack nombrado.

* Comprueba la función AWS Event Run State compartida entre instancias de StackPack de AWS:
 ** `urn:stackpack:aws:shared:check-function:aws-event-run-state`
* Tipo de componente cmdb_ci_netgear en el StackPack de ServiceNow:
 ** `urn:stackpack:servicenow:componenttype:cmdb_ci_netgear`
