= Contrôle d'accès en fonction du rôle (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

La gestion des accès vous aide à gérer qui a accès aux éléments de topologie spécifiques, aux données métriques, aux traces, aux éléments de l'interface utilisateur et aux API qu'ils peuvent appeler.

Le RBAC est un système d'autorisation qui fournit une gestion des accès granulaire aux ressources de SUSE Observability, une manière claire et simple d'auditer les privilèges des utilisateurs et de corriger les problèmes identifiés liés aux droits d'accès.

== Que pouvez-vous faire avec le RBAC ?

Voici des exemples de ce que vous pouvez faire avec le RBAC :

* Permettre à un utilisateur d'accéder uniquement au cluster de développement, à un autre d'accéder à la fois au cluster de production et au cluster de développement, et un troisième peut accéder au cluster de développement et à un seul espace de noms dans le cluster de production.
* Attribuez à un petit groupe d'utilisateurs un rôle d'administrateur pour configurer SUSE Observability. Tout en attribuant à tous les développeurs un rôle de dépanneur leur permettant de visualiser l'ensemble de la topologie, des métriques, des traces, des journaux et des événements, avec des capacités de configuration limitées.

== Qu'est-ce qu'un rôle dans SUSE Observability ?

Un rôle dans SUSE Observability est une combinaison d'un sujet configuré et d'un ensemble de xref:/setup/security/rbac/rbac_permissions.adoc[permissions]. Le processus de configuration d'un rôle dans SUSE Observability est décrit dans xref:/setup/security/rbac/rbac_roles.adoc[Comment configurer des rôles].

== Sources des rôles RBAC

Vous pouvez définir des rôles de plusieurs manières.  Tous utilisent les mêmes xref:/setup/security/rbac/rbac_permissions.adoc[permissions].

* **Configuration** - dans les xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[valeurs Helm] pour SUSE Observability
* **Dynamique** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[utiliser le `sts` CLI]
* **Cartographié depuis Kubernetes** - xref:/setup/security/rbac/rbac_rancher.adoc[mapper Kubernetes `Roles` et `RoleBindings`]

== Plus d'informations sur la configuration du RBAC

* xref:/setup/security/rbac/rbac_permissions.adoc[Autorisations]
* xref:/setup/security/rbac/rbac_roles.adoc[Comment configurer des rôles]
* xref:/setup/security/rbac/rbac_rancher.adoc[Utiliser avec Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Étendues]
* xref:/setup/security/authentication/README.adoc[Comment configurer l'authentification]
