= Control de acceso basado en funciones (RBAC)
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojada

La gestión de acceso te ayuda a gestionar quién tiene acceso a los elementos específicos de la topología, datos métricos, trazas, elementos de la interfaz de usuario y qué APIs pueden llamar.

RBAC es un sistema de autorización que proporciona una gestión de acceso detallada de los recursos de SUSE Observabilidad, una forma clara y sencilla de auditar los privilegios de los usuarios y de solucionar problemas identificados con los derechos de acceso.

== ¿Qué puedes hacer con RBAC?

Aquí tienes ejemplos de lo que puedes hacer con RBAC:

* Permite que un usuario tenga acceso únicamente al clúster de desarrollo, que otro tenga acceso tanto al clúster de producción como al de desarrollo, y que un tercero pueda acceder al clúster de desarrollo y a un único espacio de nombres en el clúster de producción.
* Dar a un pequeño grupo de usuarios un rol de administrador para configurar SUSE Observability. Al mismo tiempo, se otorga a todos los desarrolladores un rol de solucionador de problemas que les permite ver toda la topología, métricas, trazas, registros y eventos, pero con una capacidad de configuración limitada.

== ¿Qué es un rol en SUSE Observabilidad?

Un rol en SUSE Observabilidad es una combinación de un sujeto configurado y un conjunto de xref:/setup/security/rbac/rbac_permissions.adoc[permisos]. El proceso de configuración de un rol en SUSE Observabilidad se describe en xref:/setup/security/rbac/rbac_roles.adoc[Cómo configurar roles].

== Fuentes de roles de RBAC

Puedes definir roles de varias maneras.  Todos utilizan los mismos xref:/setup/security/rbac/rbac_permissions.adoc[permisos].

* **Configuración** - en los xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[valores de helm] para SUSE Observabilidad
* **Dinámico** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[utiliza la `sts` CLI]
* **Mapeado desde Kubernetes** - xref:/setup/security/rbac/rbac_rancher.adoc[mapea Kubernetes `Roles` y `RoleBindings`]

== Más sobre la configuración de RBAC

* xref:/setup/security/rbac/rbac_permissions.adoc[Autorizaciones]
* xref:/setup/security/rbac/rbac_roles.adoc[Cómo configurar roles]
* xref:/setup/security/rbac/rbac_rancher.adoc[Usar con Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Ámbitos]
* xref:/setup/security/authentication/README.adoc[Cómo configurar la autenticación]
