= v2.2.0 - 09/Dec/2024
:description: SUSE Observability Self-hosted

[CAUTION]
====
This release has a bug where the Helm chart is using invalid image URLs for some pods, instead use xref:./v2.2.1.adoc[version 2.2.1] or newer.
====


== Release Notes StackState version 7.0.0-snapshot.20241204151219-master-db9515b Helm Chart version 2.2.0

=== New Features & Enhancements

* Support OpenTelemetry over HTTP
* Added related health violations to external monitors.
* Added option to the helm chart to get the license key, api key and authentication secrets from an external kubernetes secret.
* Removed the admin api and accompanying platform admin user
* Added support for highlighting of Spans which match the search criteria in the Trace perspective and Trace explorer.
* Simplify email server configuration on self-hosted installations.
* Upgrade to HDFS 3.4.1
* Use a default namespace for Opentelemetry services, so they all show up as components in the topology

=== Bug Fixes

* Fixed issue with nonHA deployments where custom StackPacks were not persisted.
* Fix to respect `global.storageClassName` on all requested PVCs
* A removed `ServiceAccount`, for the backup cronjob, was still referenced when upgrading from an older Helm chart version
* Fixed issue where outgoing and incoming layers were reversed in the topology visualizer.
* Make sure the 'available service endpoints' fires when there are pods which are not in ready state."
* Only load related resources per type to avoid an error condition in the related resources drawer.

=== Breaking changes

* The allowed usernames when using xref:/setup/security/authentication/file.adoc[file based authenticated] is restricted to alphanumeric characters and `_`.
