= 身份验证选项
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自托管

开箱即用，SUSE Observability 配置了 xref:/setup/security/authentication/file.adoc[单密码认证]，使用管理员用户和在安装期间 xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[配置的随机密码]。它通过服务器上的简单密钥验证用户身份。然而，这并不是一个可用于生产用途的设置。

为了更好的安全性，SUSE Observability 可以配置为使用以下认证机制中的一个（替换标准管理员用户）：

* xref:/setup/security/authentication/single_password.adoc[单一密码]
* xref:/setup/security/authentication/file.adoc[基于文件的]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[开放ID连接 (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak（OIDC 的专用版本）]

[NOTE]
====
身份验证配置是 Helm 图表的一部分，任何更改将自动触发需要该更改的 Pod 重启。
====


== 用户角色

当用户经过身份验证后，通常会根据用户的角色分配该用户的权限。特定身份验证机制的文档还包含如何将外部系统中的角色或组映射到 SUSE Observability 的 4 个标准角色的示例：

* *访客* - 能够查看信息但无法进行更改。
* *Kubernetes 故障排除者* - 能够查看所有信息，并对监视器和指标配置进行查看与更改。
* *高级用户* - 能够查看和更改所有配置并安装 StackPacks。
* *管理员* - 能够查看和更改 SUSE Observability 的内容。例如，查看所有配置，安装 StackPacks，授予和撤销用户权限以及上传（新版本的）StackPacks。

在决定分配给用户的角色时，强烈建议仅有一小组平台管理员和管理员。例如，仅限于负责安装 SUSE Observability 和进行初始配置的工程师。管理员用户可以管理对 SUSE Observability 的访问，并决定可以使用哪些 StackPacks。您可以将 StackPacks 的安装和其他配置的微调委托给更多具有高级用户角色的用户。平台管理员用户可以清除数据库，改变数据保留设置，查看日志并执行其他平台管理任务。

也可以添加更多角色，请参见页面 xref:/setup/security/rbac/rbac_roles.adoc[角色（RBAC）] 和其他 xref:/setup/security/rbac/README.adoc[RBAC 文档页面]
