= 单一密码
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} 自托管

开箱即用，{stackstate-product-name} 配置为单一密码配置，xref:/k8s-suse-rancher-prime.adoc#_installation[在安装期间配置]。这通过一个必须在安装期间提供的单一密码来验证用户。

这是开始使用 {stackstate-product-name} 的最简单方法，但对于生产环境，建议使用其他 xref:/setup/security/authentication/authentication_options.adoc[认证选项]。

== 从外部秘密获取密码

当默认密码应来自外部秘密时，请遵循 xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[这些步骤]，但填写以下数据：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

密码编码可以是以下之一： +
* 对于明文密码，请提供：`$plain$your-password`（`$plain$` 是指示明文的前缀） +
* 对于 bcrypted 密码，请提供：`bcrypt-hashed-password`。创建密码的 bcrypted 哈希可以使用 `htpasswd -bnBC 10 "" <password> | tr -d ':\n'` 完成。

== 另请参见

* xref:/setup/security/authentication/authentication_options.adoc[认证选项]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[预定义 {stackstate-product-name} 角色的权限]
* xref:/setup/security/rbac/rbac_roles.adoc[创建 RBAC 角色]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[外部秘密]
