= Introdução ao Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Coletor do Open Telemetry e 2 aplicativos instrumentados enviando métricas e rastreamentos para a SUSE Observability]

A SUSE Observability suporta https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry é um conjunto de protocolos padronizados e uma estrutura de código aberto para coletar, transformar e enviar dados de telemetria, como rastreamentos, métricas e logs. Open Telemetry suporta uma ampla variedade de linguagens de programação e plataformas.

A SUSE Observability tem suporte tanto para métricas quanto para rastreamentos e adiciona as métricas e rastreamentos do Open Telemetry aos dados de topologia (Kubernetes) fornecidos pelo agente da SUSE Observability. Portanto, ainda é necessário instalar o agente da SUSE Observability. O suporte para logs e o uso do Open Telemetry sem o agente da SUSE Observability está chegando em breve.

Open Telemetry consiste em vários componentes diferentes. Para uso com a SUSE Observability, os xref:/setup/otel/languages/README.adoc[SDKs] para instrumentar seu aplicativo e o xref:/setup/otel/collector.adoc[coletor do Open Telemetry] são as partes mais importantes. Mostraremos como configurar ambos para uso com a SUSE Observability.

Se seu aplicativo já estiver instrumentado com Open Telemetry ou com qualquer outra biblioteca suportada pelo Open Telemetry, como Jaeger ou Zipkin, o coletor pode ser usado para enviar esses dados para a SUSE Observability e nenhuma instrumentação adicional é necessária.

A SUSE Observability requer que o coletor seja configurado com processadores específicos e autenticação para garantir que todos os dados utilizados pela SUSE Observability estejam disponíveis.

== Referências

* https://opentelemetry.io/docs/collector/[Coletor do Open Telemetry] na documentação do Open Telemetry
* https://opentelemetry.io/docs/languages/[SDKs para instrumentar seu aplicativo] na documentação do Open Telemetry
