= Introdução ao Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Coletor Open Telemetry e 2 aplicativos instrumentados enviando métricas e rastros para o SUSE Observability]

O SUSE Observability suporta https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry é um conjunto de protocolos padronizados e uma estrutura de código aberto para coletar, transformar e enviar dados de telemetria, como rastros, métricas e logs. Open Telemetry suporta uma ampla variedade de linguagens de programação e plataformas.

O SUSE Observability tem suporte tanto para métricas quanto para rastros. Quando usado em combinação com o stackpack do Kubernetes, os pods do Kubernetes serão enriquecidos com rastros quando disponíveis. Ao instalar o stackpack Open Telemetry, novas páginas de visão geral para serviços e instâncias de serviço ficam disponíveis, fornecendo acesso a rastros e métricas de span. As métricas do Open Telemetry podem ser usadas em monitores e vinculações de métricas. O stackpack vem com vinculações de métricas para métricas de span e métricas de memória .NET e JVM. Há também monitores prontos para taxas de erro de span e duração.

A configuração recomendada para uso com o SUSE Observability é instrumentar aplicativos com os xref:/setup/otel/instrumentation/README.adoc[SDKs Open Telemetry] aplicáveis e instalar o xref:/setup/otel/collector.adoc[coletor Open Telemetry] próximo aos seus aplicativos instrumentados para pré-processar os dados (enriquecer com rótulos do Kubernetes, amostragem em rastros, etc.) e enviar os dados para o SUSE Observability. O Coletor Open Telemetry também pode ser usado para coletar métricas de muitos tipos de fontes de telemetria sem instrumentar os aplicativos usando os SDKs. Veja as https://opentelemetry.io/ecosystem/registry/?language=collector[integrações do Coletor Open Telemetry] para mais detalhes e se seu banco de dados ou protocolo de telemetria é suportado.

Siga o guia de xref:/setup/otel/getting-started/README.adoc[introdução] para configurar tudo de forma que funcione melhor com o SUSE Observability.

== Referências

* https://opentelemetry.io/docs/collector/[Coletor Open Telemetry] na documentação do Open Telemetry
* https://opentelemetry.io/ecosystem/registry/?language=collector[Integrações do Coletor Open Telemetry]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs para instrumentar seu aplicativo] na documentação do Open Telemetry
