= k8s Custom Secrets Setup (Deprecated)
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== Overview

The SUSE Observability agent supports specifying the name of a custom secret that contains the service token and cluster authorization token. This feature is useful for users who wish to manage their own secrets and avoid the automatic creation of secrets by the Helm chart.

[CAUTION]
====
*This method of customizing secrets is deprecated and is incompatible with the RBAC feature.*

Please use xref:/setup/agent/k8s-custom-secrets-setup.adoc[the new method] for using external secrets.
====


== The Helm Chart

=== Configuration Options

* `stackstate.manageOwnSecrets`: A boolean flag that determines whether the user wishes to manage their own secrets. Default value is `false`.
* `stackstate.customSecretName`: (Optional) Name of the custom secret to be created by the user. Required if `stackstate.manageOwnSecrets` is set to `true`.
* `stackstate.customApiKeySecretKey`: (Optional) Service token within the custom secret. Required if `stackstate.manageOwnSecrets` is set to `true`.
* `stackstate.customClusterAuthTokenSecretKey`: (Optional) Key name for the cluster authorization token within the custom secret. Required if `stackstate.manageOwnSecrets` is set to `true`.

=== Behavior Description

* *Automatic Secret Creation*: By default, the chart continues to automatically create secrets as before if `stackstate.manageOwnSecrets` is set to `false`.
* *Custom Secret Management*: If `stackstate.manageOwnSecrets` is set to `true`, the chart expects the user to provide the name of the custom secret (`stackstate.customSecretName`) along with the service token and authorization token (`stackstate.customApiKeySecretKey` and `stackstate.customClusterAuthTokenSecretKey`, respectively).
* *Implied Omission*: When specifying that you would like to manage your own secrets, the chart ignores values for `stackstate.apiKey` and `stackstate.cluster.authToken`.
+
== How to Use in values.yaml

[IMPORTANT]
====
API key is synonymous with service token. Even though the environment variable refers to API_KEY, a service token must be used instead.
====

. *Using Automatic Secret Creation (Default)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your service token>"
----

. *Managing Own Secrets*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
