= Segredos Externos
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Segredos Externos do SUSE Observability

== Visão Geral

O SUSE Observability pode receber segredos como chave de licença, chave de API e chaves de autenticação através da instalação do Helm, mas também pode obtê-los a partir de segredos já provisionados.

Aqui está descrito como configurar isso.

== Obtendo a chave de licença de um segredo externo

Crie um segredo no namespace onde o SUSE Observability está instalado, do seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Adicione o seguinte ao seu comando de instalação do Helm para usar o segredo:

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obtendo nome de usuário e senha para notificações por e-mail de um segredo externo

Crie um segredo no namespace onde o SUSE Observability está instalado, do seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Adicione o seguinte ao seu comando de instalação do Helm para usar o segredo:

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obtendo a chave de API de um segredo externo

Crie um segredo no namespace onde o SUSE Observability está instalado, do seguinte formato, preenchendo os espaços em branco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Adicione o seguinte ao seu comando de instalação do Helm para usar o segredo:

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obtendo dados de autenticação de um segredo externo

Crie um segredo no namespace onde o SUSE Observability está instalado, do seguinte formato.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Dependendo do método de autenticação escolhido, o campo `default_password` é substituído por dados diferentes. Veja as xref:/setup/security/authentication/authentication_options.adoc[opções de autenticação] para mais informações. Neste exemplo, a configuração xref:/setup/security/authentication/single_password.adoc[Senha única] é utilizada.

Adicione o seguinte ao seu comando de instalação do Helm para usar o segredo:

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
