= Secretos Externos
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: Secretos Externos de SUSE Observability

== Descripción general

SUSE Observability puede tomar secretos como la clave de licencia, la clave API y las claves de autenticación a través de la instalación de helm, pero también puede tomar esos de secretos ya aprovisionados.

Aquí se describe cómo configurar esto.

== Obteniendo la clave de licencia de un secreto externo

Crea un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Añade lo siguiente a tu comando de instalación de helm para usar el secreto:

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Obteniendo el nombre de usuario y la contraseña para notificaciones por correo electrónico de un secreto externo

Crea un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Añade lo siguiente a tu comando de instalación de helm para usar el secreto:

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== Obteniendo la clave API de un secreto externo

Crea un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma, rellenando los espacios en blanco:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Añade lo siguiente a tu comando de instalación de helm para usar el secreto:

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Obteniendo datos de autenticación de un secreto externo

Crea un secreto en el espacio de nombres en el que está instalado SUSE Observability, de la siguiente forma.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Dependiendo del método de autenticación elegido, el campo `default_password` se reemplaza con diferentes datos. Consulta las xref:/setup/security/authentication/authentication_options.adoc[opciones de autenticación] para más información. En este ejemplo se utiliza la configuración de xref:/setup/security/authentication/single_password.adoc[Contraseña única].

Añade lo siguiente a tu comando de instalación de helm para usar el secreto:

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
