= Referências de métricas 
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: SUSE Observability

== Visão Geral

Esta página define métricas comuns relacionadas ao Kubernetes coletadas pela SUSE Observability e explica como elas são calculadas.

=== container_memory_usage

[horizontal]
Nome:: `container_memory_usage`
Tipo:: medidor
Unidade:: bytes
Origem:: Leitura direta da hierarquia de cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `memory.usage_in_bytes`
|v2 | `memory.current`
|===

Resumo:: A quantidade total de memória atualmente sendo usada pelo cgroup e seus descendentes. Esta é uma soma que inclui Memória Anônima (RSS), Cache de Página e Memória do Kernel. Use uma das seguintes métricas para obter mais detalhes sobre uma área específica de memória.

=== container_memory_kernel

[horizontal]
Nome:: `container_memory_kernel`
Tipo:: medidor
Unidade:: bytes
Origem:: Leitura direta da hierarquia de cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `memory.kmem.usage_in_bytes`
|v2 | `memory.stat` -> `kernel` campo dentro do arquivo
|===
Resumo:: Quantidade total de memória do kernel, incluindo (kernel_stack, tabelas de páginas, percpu, vmalloc, slab)

=== container_memory_rss

[horizontal]
Nome:: `container_memory_rss`
Tipo:: medidor
Unidade:: bytes
Origem:: Leitura direta da hierarquia de cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `memory.stat` -> `total_rss` campo dentro do arquivo
|v2 | `memory.stat` -> `anon` campo dentro do arquivo
|===
Resumo:: O Tamanho do Conjunto Residencial (RSS) da Memória Anônima. Esta é a memória que não é respaldada por arquivos (heap e stack) e é utilizada ativamente pelos processos dentro do cgroup. Este valor frequentemente reflete o verdadeiro "conjunto de trabalho" do aplicativo. 

=== container_memory_cache

[horizontal]
Nome:: `container_memory_cache`
Tipo:: medidor
Unidade:: bytes
Origem:: Leitura direta da hierarquia de cgroup do contêiner.

[cols="1,3"]
|===
|versão do cgroup | Arquivo de origem

|v1 | `memory.stat` -> `total_cache` campo dentro do arquivo
|v2 | `memory.stat` -> `file` campo dentro do arquivo
|===
Resumo:: O Cache de Página (memória usada para armazenar em cache dados do sistema de arquivos, incluindo tmpfs e memória compartilhada).
