= Anleitung zur ersten Ausführung
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== Übersicht

Diese Seite bietet alle Informationen, die Sie benötigen, um SUSE Observability zu installieren und auszuführen.

== Installationsanweisungen

[tabs]
====
Kubernetes::
+
--
Installieren Sie SUSE Observability auf xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Installieren Sie SUSE Observability auf xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Adresse und Port

[tabs]
====
Kubernetes::
+
--
Um auf die SUSE Observability-Benutzeroberfläche zuzugreifen:

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Aktivieren Sie eine Portweiterleitung].
. Greifen Sie auf die SUSE Observability-Benutzeroberfläche unter https://localhost:8080 zu.
--

OpenShift::
+
--
Um auf die SUSE Observability-Benutzeroberfläche zuzugreifen:

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Aktivieren Sie eine Portweiterleitung].
. Greifen Sie auf die SUSE Observability-Benutzerfläche unter https://localhost:8080 zu.
--
====

== Standardbenutzername und -passwort

[tabs]
====
Kubernetes::
+
--
SUSE Observability ist standardmäßig mit folgendem Administratorkonto konfiguriert:

* *Benutzername:* `admin`
* *Passwort:* Wird während der Installation festgelegt. Dies wird vom `generate_values.sh` Skript gesammelt und im MD5-Hash-Format in `values.yaml` gespeichert.
--

OpenShift::
+
--
SUSE Observability ist standardmäßig mit folgendem Administratorkonto konfiguriert:

* *Benutzername:* `admin`
* *Passwort:* Wird während der Installation festgelegt. Dies wird vom `generate_values.sh` Skript gesammelt und im MD5-Hash-Format in `values.yaml` gespeichert.
--
====

== Fehlerbehebung

Wenn Sie während der Installation von SUSE Observability oder der ersten Ausführung auf Probleme stoßen, überprüfen Sie das xref:/setup/install-stackstate/troubleshooting.adoc[SUSE Observability Installations-Fehlerbehebungs-Handbuch].

== Nächste Schritte

Sobald Sie SUSE Observability in Betrieb genommen haben, können Sie mit der Einrichtung von Integrationen beginnen.

* xref:/k8s-quick-start-guide.adoc[Installieren Sie StackPacks, um die Integration mit externen Systemen einzurichten]
* xref:/use/views/k8s-views.adoc[Erkunden Sie Ihren Kubernetes-Cluster]
