= Utiliser la CLI pour les liaisons de métriques
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

Vous pouvez utiliser {stackstate-product-name} la CLI pour inspecter et modifier les liaisons de métriques.  Celles-ci sont gérées comme d'autres paramètres en utilisant la commande `sts settings`.

== Inspection des liaisons de métriques

=== Liste des liaisons de métriques

La commande `sts settings` peut lister toutes les liaisons de métriques :

[,bash]
----
sts settings list --type MetricBinding
TYPE          | ID              | IDENTIFIER         | NAME               | OWNED BY           | LAST UPDATED
MetricBinding | 190567588459765 | urn:stackpack:kube | .NET GC Allocated  | urn:stackpack:kube | Sun Jan 11 01:28:2
              |                 | rnetes-v2:shared:m |                    | rnetes-v2:shared   | 8 2026 CET
              |                 | etric-binding:pod: |                    |                    |
              |                 | dotnet-gc-allocate |                    |                    |
              |                 | d                  |                    |                    |
MetricBinding | 247972504900226 | urn:stackpack:kube | .NET GC Allocated  | urn:stackpack:kube | Sun Jan 11 01:28:2
              |                 | rnetes-v2:shared:m |                    | rnetes-v2:shared   | 8 2026 CET
              |                 | etric-binding:depl |                    |                    |
              |                 | oyment:dotnet-gc-a |                    |                    |
              |                 | llocated           |                    |                    |
MetricBinding | 109239589408271 | urn:stackpack:open | .NET GC Allocated  | urn:stackpack:open | Wed Jan 7 00:20:48
              |                 | -telemetry:shared: |                    | -telemetry:shared  |  2026 CET
              |                 | metric-binding:ser |                    |                    |
              |                 | vice:dotnet-gc-all |                    |                    |
              |                 | ocated             |                    |                    |
...
----

=== Description des liaisons de métriques

Vous pouvez obtenir la définition d'une liaison de métriques existante en utilisant la commande `describe` :

[,bash]
----
sts settings describe --ids 190567588459765
_version: 1.0.93
nodes:
- _type: MetricBinding
  chartType: line
  description: Bytes allocated to GC Heap
  enabled: true
  id: -1
  identifier: urn:stackpack:kubernetes-v2:shared:metric-binding:pod:dotnet-gc-allocated
  layout:
    metricPerspective:
      section: GC
      tab: .NET
      weight: 3
  name: .NET GC Allocated
  priority: high
  queries:
  - alias: allocated
    expression: rate(process_runtime_dotnet_gc_allocations_size_bytes_total{k8s_cluster_name="${tags.cluster-name}", k8s_namespace_name="${tags.namespace}", k8s_pod_name="${name}"}[${__rate_interval}])
  scope: (label = "stackpack:kubernetes" and type = "pod")
  unit: bytes(IEC)
timestamp: 2026-01-14T13:11:07.575662922Z[Etc/UTC]
----

== Modification des liaisons de métriques

[NOTE]
====
La manière recommandée de travailler est de stocker les liaisons de métriques (et toutes les autres ressources personnalisées créées dans {stackstate-product-name}) sous forme de fichiers YAML dans xref:/setup/custom-integrations/overview.adoc[a StackPack]. À partir de là, les modifications peuvent être appliquées manuellement ou entièrement automatisées en utilisant le CLI SUSE Observability dans un système CI/CD comme GitHub Actions ou GitLab Pipelines.
====

=== Créer/mettre à jour une liaison de métriques
Créez un fichier `metric-bindings.yaml` qui ressemble à ceci :

[source,bash]
----
nodes:
- _type: MetricBinding
  chartType: line
  enabled: true
  tags: {}
  unit: short
  name: Replica counts
  priority: MEDIUM
  identifier: urn:stackpack:my-stackpack:metric-binding:my-deployment-replica-counts
  queries:
    - expression: max_over_time(kubernetes_state_deployment_replicas{cluster_name="${tags.cluster-name}", namespace="${tags.namespace}", deployment="${name}"}[${__interval}])
      alias: Total replicas
  scope: type = "deployment" and label = "stackpack:kubernetes"
----

Utilisez le xref:/setup/cli/cli-sts.adoc[SUSE Observability CLI] pour créer la liaison de métrique :

[,bash]
----
sts settings apply -f metric-bindings.yaml
----

Vérifiez les résultats dans SUSE Observability en ouvrant la perspective des métriques pour un déploiement. Si vous n'êtes pas satisfait du résultat, il vous suffit de modifier la liaison de métrique dans le fichier YAML et de relancer la commande pour la mettre à jour. La liste des nœuds prend en charge l'ajout de nombreuses liaisons de métrique. Ajoutez simplement une autre entrée de liaison de métrique au tableau YAML en utilisant les mêmes étapes qu'auparavant.

[CAUTION]
====
L'identifiant est utilisé comme clé unique d'une liaison de métrique. Changer l'identifiant créera une nouvelle liaison de métrique au lieu de mettre à jour l'existante.
====

=== Supprimer une liaison de métriques

Enfin, pour supprimer une liaison de métrique, utilisez

[,bash]
----
sts settings delete --ids <id>
----

Le `<id>` dans cette commande n'est pas l'identifiant mais le nombre dans la colonne `Id` de la sortie `sts settings list`.

