= Opciones de autenticación
:revdate: 10-07-2025
:page-revdate: {revdate}
:description: SUSE Observability Autoalojado

De forma predeterminada, SUSE Observability está configurado con xref:/setup/security/authentication/file.adoc[autenticación de una sola contraseña] con el usuario administrador y una contraseña aleatoria xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[configurada durante la instalación]. Esto autentica a los usuarios con un secreto simple en el servidor. Sin embargo, esta no es una configuración lista para producción.

Para una mejor seguridad, SUSE Observability se puede configurar para usar exactamente uno de los siguientes mecanismos de autenticación (reemplazando al usuario administrador estándar):

* xref:/setup/security/authentication/single_password.adoc[Autenticación de una sola contraseña]
* xref:/setup/security/authentication/file.adoc[Basada en archivos]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (una versión especializada de OIDC)]

[NOTE]
====
La configuración de autenticación forma parte del chart de Helm, por lo que cualquier cambio desencadenará automáticamente el reinicio de los pods que lo requieran.
====


== Funciones del usuario

Cuando un usuario ha sido autenticado, los permisos para ese usuario suelen asignarse en función de los roles que tiene el usuario. La documentación de los mecanismos de autenticación específicos también contiene ejemplos sobre cómo mapear los roles o grupos de los sistemas externos a los 4 roles estándar de SUSE Observability:

* *Invitado* - puede ver información pero no hacer cambios.
* *Solucionador de problemas de Kubernetes* - puede ver toda la información y ver y cambiar la configuración de monitores y métricas.
* *Usuario avanzado* - puede ver y cambiar toda la configuración e instalar StackPacks.
* *Administrador* - puede ver y cambiar el contenido de SUSE Observability. Por ejemplo, ver toda la configuración, instalar StackPacks, otorgar y revocar permisos de usuario y subir (nuevas versiones de) StackPacks.

Al decidir sobre los roles a asignar a tus usuarios, se aconseja encarecidamente tener solo un pequeño grupo de Administradores de Plataforma y Administradores. Por ejemplo, solo los ingenieros responsables de instalar SUSE Observability y realizar la configuración inicial. Los usuarios administradores pueden gestionar el acceso a SUSE Observability y decidir qué StackPacks se pueden utilizar. Puedes delegar la instalación de StackPacks y otros ajustes de la configuración a un mayor número de usuarios con el rol de Usuario Avanzado. Los usuarios Administradores de Plataforma pueden limpiar la base de datos, cambiar la configuración de retención de datos, ver registros y realizar otras tareas de gestión de la plataforma.

También es posible añadir más roles, consulta la página xref:/setup/security/rbac/rbac_roles.adoc[Roles (RBAC)] y las otras xref:/setup/security/rbac/README.adoc[páginas de documentación de RBAC].
