= Contraseña única
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Autoalojado

De forma predeterminada, {stackstate-product-name} está configurado con una única configuración de contraseña, xref:/k8s-suse-rancher-prime.adoc#_installation[configurada durante la instalación]. Esto autentica a los usuarios con una única contraseña que debe ser proporcionada durante la instalación. 

Esta es la forma más sencilla de empezar con {stackstate-product-name}, pero para producción se recomienda una de las otras xref:/setup/security/authentication/authentication_options.adoc[opciones de autenticación].

== Obtén la contraseña de un secreto externo

Cuando la contraseña predeterminada debe provenir de un secreto externo, sigue xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estos pasos] pero completa los siguientes datos:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

La codificación de la contraseña puede ser una de estas:
* Para una contraseña en texto plano proporciona: `$plain$your-password` (`$plain$` es un prefijo que indica texto plano)
* Para una contraseña bcrypted proporciona: `bcrypt-hashed-password`. Crear un hash bcrypted de la contraseña se puede hacer utilizando `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== Consulte también

* xref:/setup/security/authentication/authentication_options.adoc[Opciones de autenticación]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permisos para {stackstate-product-name} roles predefinidos]
* xref:/setup/security/rbac/rbac_roles.adoc[Crear roles RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Secretos Externos]
