= Guía de ejecución inicial
:revdate: 10-07-2025
:page-revdate: {revdate}
:description: SUSE Observability autohospedado

== Descripción general

Esta página proporciona toda la información que necesitas para instalar y ejecutar SUSE Observability.

== Instrucciones de instalación

[tabs]
====
Kubernetes::
+
--
Instala SUSE Observability en xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Instala SUSE Observability en xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Dirección y puerto

[tabs]
====
Kubernetes::
+
--
Para acceder a la interfaz de usuario de SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Habilita un reenvío de puerto].
. Accede a la interfaz de usuario de SUSE Observability en: https://localhost:8080
--

OpenShift::
+
--
Para acceder a la interfaz de usuario de SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Habilita un reenvío de puerto].
. Accede a la interfaz de usuario de SUSE Observability en: https://localhost:8080
--
====

== Nombre de usuario y contraseña predeterminados

[tabs]
====
Kubernetes::
+
--
SUSE Observability está configurado por defecto con la siguiente cuenta de administrador:

* *nombre de usuario:* `admin`
* *password (contraseña):* Se establece durante la instalación. Esto se recopila mediante el guion `generate_values.sh` y se almacena en formato hash MD5 en `values.yaml`
--

OpenShift::
+
--
SUSE Observability está configurado por defecto con la siguiente cuenta de administrador:

* *nombre de usuario:* `admin`
* *password (contraseña):* Se establece durante la instalación. Esto se recopila mediante el guion `generate_values.sh` y se almacena en formato hash MD5 en `values.yaml`
--
====

== Solución de problemas

Si encuentras algún problema durante la instalación de SUSE Observability o la primera ejecución, consulta la xref:/setup/install-stackstate/troubleshooting.adoc[guía de solución de problemas de instalación de SUSE Observability].

== Pasos siguientes

Una vez que tengas SUSE Observability en funcionamiento, puedes comenzar a configurar integraciones

* xref:/k8s-quick-start-guide.adoc[Instala StackPacks para que puedas integrarte con sistemas externos]
* xref:/use/views/k8s-views.adoc[Explora tu clúster de Kubernetes]
