ifdef::ss-ff-stackpacks2_enabled[]
= UI-Präsentationskonzepte
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-01-08
:page-revdate: {revdate}
:description: UI-Präsentationskonzepte

[IMPORTANT]
====
*Status:* In aktiver Entwicklung.

*Verfügbarkeit:* Hinter dem StackPacks 2.0-Feature-Flag. Siehe xref:/setup/custom-integrations/overview.adoc[Übersicht über benutzerdefinierte Integrationen], um die Funktion zu aktivieren.

Diese Dokumentation beschreibt die aktuelle Designabsicht und die hochrangige Konfigurationsoberfläche.

Hinweis: Es wurden noch weder Verhalten noch Funktionen implementiert.

Da sich diese Funktion in aktiver Entwicklung befindet, können sich Verhalten, Schemata und Funktionen ändern, während sich das Modell weiterentwickelt.
====

Dies ist eine Zusammenfassung der wichtigsten Konzepte im Zusammenhang mit der UI-Präsentation und sollte ausreichen, um zu beginnen.

== Komponentenpräsentation

Das zentrale Konzept des UI-Präsentationsmodells ist die *Komponentenpräsentation*.

Eine `ComponentPresentation` definiert, wie ein oder mehrere übereinstimmende Komponenten in der UI präsentiert werden, abhängig vom aktiven Kontext.
Es konzentriert sich ausschließlich auf *Präsentationsaspekte*, wie Benennung, Symbole, Tabellen, Übersichts- und Hervorhebungsseiten, Filter und die Platzierung von Menüelementen.

Auf hoher Ebene beschreibt eine Komponentenpräsentation:

* Wählt Komponenten mithilfe einer Bindung (einer einfachen STQL-Abfrage) aus.
* Wird in einem bestimmten Modus angewendet (zum Beispiel Einblick).
* Definiert einen oder mehrere Präsentationsaspekte (wie Übersichts- oder Hervorhebungstabellen).
* Kann teilweise Präsentationseigenschaften definieren und mit anderen übereinstimmenden Definitionen kombinieren.

Mehrere Komponentenpräsentationen können auf dieselbe Komponente angewendet werden. In solchen Fällen werden ihre Definitionen kombiniert, um die endgültige Präsentation zu bestimmen.

endif::ss-ff-stackpacks2_enabled[]
