= Documentación de SUSE Observability
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 10-07-2025
:page-revdate: {revdate}

Esta es la última documentación de SUSE Observability. Selecciona temas del menú de contenido a la izquierda.

Para versiones anteriores de la documentación, utiliza el https://archivedocs.stackstate.com[archivo].

== Comience a conocer el sistema.

Visita la xref:/k8s-suse-rancher-prime.adoc[guía de inicio de Rancher Prime] si eres usuario de Rancher Prime, si eres usuario de SUSE Cloud Observability visita la xref:/k8s-quick-start-guide.adoc[guía de inicio rápido], si estás ejecutando SUSE Cloud Observability en AWS consulta la xref:/suse-cloud-observability-quick-start-guide.adoc[guía de inicio rápido de SUSE Cloud Observability].

== ¿No encuentras algo?

Utiliza la barra de búsqueda en la parte superior derecha. Si crees que falta alguna documentación, háznoslo saber en el https://scc.suse.com/[sitio de soporte de SUSE Observability].

== Resolución de problemas y soporte

¿Tienes alguna pregunta? En Novell, podemos ayudarle. Encuentra al equipo de soporte en el https://scc.suse.com/[sitio de soporte de SUSE Observability].

== SUSE Observability Autoalojado

Utiliza SUSE Observability Autoalojado para observar un conjunto extenso de tecnologías desde tus propios centros de datos o la nube.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability Autoalojado]

== SUSE Cloud Observability

Utiliza SUSE Cloud Observability para observar tecnologías en la nube, como Kubernetes y servicios de AWS.

xref:/suse-cloud-observability/user-management.adoc[Documentación de SUSE Cloud Observability]
