= Guías de inicio rápido de SUSE Observability
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability
:doctype: book

== Descripción general

Cuando tu instancia de SUSE Observability SaaS esté configurada y lista, recibirás un correo electrónico de SUSE Observability con los detalles de inicio de sesión requeridos. Esta guía rápida te ayudará a comenzar y a introducir tus propios datos en tu instancia de SUSE Observability SaaS.

Para integrar tu(s) clúster(es) con SUSE Observability, puedes seguir una de estas guías para tu entorno correspondiente.

* <<_amazon_eks,Amazon EKS>>
* <<_azure_aks,Azure AKS>>
* <<_google_gke,Google GKE>>
* <<_kubernetes,Kubernetes>>
* <<_kops,KOPS>>
* <<_openshift,OpenShift>>
* <<_self_hosted,Self-hosted>>


== Kubernetes

Configura una integración de Kubernetes para recopilar topología, eventos, registros, cambios y datos de métricas de un clúster de Kubernetes y hacerlo disponible en SUSE Observability.

=== Versiones compatibles

|===
| Versión de Kubernetes compatible

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para Kubernetes

Para configurar una integración de Kubernetes con SUSE Observability, necesitas tener:

* Un clúster de Kubernetes en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los Agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configurar una integración de Kubernetes

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_kubernetes,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de usuario de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el Agente de SUSE Observability, el Agente del Clúster, el Agente de Checks y kube-state-metrics en tu Clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los Agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability

[CAUTION]
====
Cuando se ejecute en un entorno Self-hosted y aislado, prepara primero la instalación del agente con las xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[instrucciones para entornos aislados].
====


== OpenShift

Configura una integración de OpenShift para recopilar datos de topología, eventos, registros, cambios y métricas de un clúster de OpenShift y ponerlos a disposición en SUSE Observability.

=== Versiones compatibles

|===
| Versión de OpenShift | Versión de Kubernetes compatible | Fin de soporte de OpenShift

| OpenShift 4.17
| Kubernetes 1.30
| 1 de abril de 2026

| OpenShift 4.16
| Kubernetes 1.29
| 27 de diciembre de 2025

| OpenShift 4.15
| Kubernetes 1.28
| 27 de agosto de 2025

| OpenShift 4.14
| Kubernetes 1.27
| 1 de mayo de 2025

| OpenShift 4.13
| Kubernetes 1.26
| 17 de noviembre de 2024

| OpenShift 4.12
| Kubernetes 1.25
| 17 de julio de 2024

| OpenShift 4.11
| Kubernetes 1.24
| 10 de febrero de 2024

| OpenShift 4.10
| Kubernetes 1.23
| 10 de septiembre de 2023

| OpenShift 4.9
| Kubernetes 1.22
| 18 de abril de 2023
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para OpenShift

Para configurar una integración de SUSE Observability con OpenShift, necesitas tener:

* Un clúster de OpenShift en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los Agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configurar una integración de OpenShift

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_openshift,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de usuario de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el Agente de SUSE Observability, el Agente del Clúster, el Agente de Checks y kube-state-metrics en tu Clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los Agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability


== Amazon EKS

Configura una integración de Amazon EKS para recopilar topología, eventos, registros, cambios y datos de métricas de un clúster de Amazon EKS y hacerlo disponible en SUSE Observability.

=== Versiones compatibles

|===
| Kubernetes version | Versión de Amazon EKS | Fin del soporte de Amazon EKS | Fin del soporte extendido de Amazon EKS

| 1.32
| 23 de enero de 2025
| 23 de marzo de 2026
| 23 de marzo de 2027

| 1.31
| 26 de septiembre de 2024
| 26 de noviembre de 2025
| 26 de noviembre de 2026

| 1.30
| 23 de mayo de 2024
| 23 de julio de 2025
| 23 de julio de 2026

| 1.29
| 23 de enero de 2024
| 23 de marzo de 2025
| 23 de marzo de 2026

| 1.28
| 26 de septiembre de 2023
| 01 de noviembre de 2024
| 26 de noviembre de 2025

| 1.27
| 24 de mayo de 2023
| Julio de 2024
| 24 de julio de 2025

| 1.26
| 11 de abril de 2023
| Junio de 2024
| 11 de junio de 2025

| 1.25
| 21 de febrero de 2023
| Mayo de 2024
| 1 de mayo de 2025

| 1.24
| 15 de noviembre de 2022
| Enero de 2024
| 31 de enero de 2025

| 1.23
| 11 de agosto de 2022
| 11 de octubre de 2023
| 11 de octubre de 2024

| 1.22
| 4 de abril de 2022
| 4 de junio de 2023
| 1 de septiembre de 2024

| 1.21
| 19 de julio de 2021
| 15 de febrero de 2023
| 15 de julio de 2024

| 1.20
| 18 de mayo de 2021
| 1 de noviembre de 2022
| N/D

| 1.19
| 16 de febrero de 2021
| 1 de agosto de 2022
| N/D

| 1.18
| 13 de octubre de 2020
| 15 de agosto de 2022
| N/D
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para Amazon EKS

Para configurar una integración de SUSE Observability con Amazon EKS, necesitas tener:

* Un clúster de Amazon EKS en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los Agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configurar una integración de Amazon EKS

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_amazon_eks,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el Agente de SUSE Observability, el Agente del Clúster, el Agente de Checks y kube-state-metrics en tu Clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los Agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability


== Google GKE

Configurar una integración de Google GKE para recopilar topología, eventos, registros, cambios y datos métricos de un clúster de Google GKE y hacer esto disponible en SUSE Observability.

=== Versiones compatibles

|===
| Kubernetes Version | Lanzamiento de Google GKE | Fin de soporte de Google GKE | Fin de soporte ampliado de Google GKE

| 1.32
| Febrero de 2025
| 2.º trimestre de 2026
| 1.er trimestre de 2027

| 1.31
| 22 de octubre de 2024
| 22 de diciembre de 2025
| 22 de octubre de 2026

| 1.30
| 30 de julio de 2024
| 30 de septiembre de 2025
| 30 de julio de 2026

| 1.29
| 25 de enero de 2024
| 21 de marzo de 2025
| 25 de enero de 2026

| 1.28
| 4 de diciembre de 2023
| 4 de febrero de 2025
| 4 de diciembre de 2025

| 1.27
| 14 de junio de 2023
| 31 de agosto de 2024
| 14 de junio de 2025

| 1.26
| 14 de abril de 2023
| 30 de junio de 2024
| N/D
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para Google GKE

Para configurar una integración de SUSE Observability con Google GKE, necesitas tener:

* Un clúster de Google GKE en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los Agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configurar una integración de Google GKE

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_google_gke,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el Agente de SUSE Observability, el Agente del Clúster, el Agente de Checks y kube-state-metrics en tu Clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los Agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability.


== Azure AKS

Configurar una integración de Azure AKS para recopilar topología, eventos, registros, cambios y datos de métricas de un clúster de Azure AKS y hacer esto disponible en SUSE Observability.

=== Versiones compatibles

|===
| Kubernetes Version | AKS GA | Fin de vida de Azure AKS | Soporte de plataforma

| 1.32
| Junio de 2024
| Marzo de 2026
| Hasta 1.36 GA

| 1.31
| Noviembre de 2024
| Noviembre de 2025
| Hasta 1.35 GA

| 1.30
| Junio de 2024
| Julio de 2025
| Hasta 1.34 GA

| 1.29
| Marzo de 2024
| Enero de 2025
| Hasta 1.33 GA

| 1.28
| Noviembre de 2023
| Noviembre de 2024
| Hasta 1.32 GA

| 1.27
| Julio de 2023
| Julio de 2024
| Julio de 2025
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para Azure AKS

Para configurar una integración de SUSE Observability con Azure AKS, necesitas tener:

* Un clúster de Azure AKS en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los Agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configurar una integración de Azure AKS

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_azure_aks,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el Agente de SUSE Observability, el Agente del Clúster, el Agente de Checks y kube-state-metrics en tu Clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los Agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability


== KOPS

Configurar una integración de KOPS para recopilar topología, eventos, registros, cambios y datos de métricas de un clúster de KOPS y hacer esto disponible en SUSE Observability.

=== Versiones compatibles

|===
| Versión de Kubernetes compatible

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para KOPS

Para configurar una integración de SUSE Observability con KOPS, necesitas tener:

* Un clúster de KOPS en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** ClusterRole y ClusterRoleBinding son necesarios para otorgar permisos a los Agentes de SUSE Observability para acceder a la API de Kubernetes.
 ** Los agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configura una integración de KOPS

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_kops,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el agente de SUSE Observability, el agente del clúster, el agente de checks y kube-state-metrics en tu clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability


== Autoalojado

Configura una integración autoalojada para recopilar topología, eventos, registros, cambios y datos de métricas de un clúster autoalojado y hacer esto disponible en SUSE Observability.

=== Versiones compatibles

|===
| Versión de Kubernetes compatible

| Kubernetes 1.32
| Kubernetes 1.31
| Kubernetes 1.30
| Kubernetes 1.29
| Kubernetes 1.28
| Kubernetes 1.27
| Kubernetes 1.26
| Kubernetes 1.25
| Kubernetes 1.24
| Kubernetes 1.23
| Kubernetes 1.22
| Kubernetes 1.21
| Kubernetes 1.20
| Kubernetes 1.19
| Kubernetes 1.18
| Kubernetes 1.17
| Kubernetes 1.16
|===

=== Tiempo de ejecución soportado

|===
| Tiempo de ejecución soportado

| ContainerD
| CRI-O
|===

=== Requisitos previos para entornos autoalojados

Para configurar una integración autoalojada de SUSE Observability necesitas tener:

* Un clúster autoalojado en funcionamiento.
* Helm versión 3.13.1 o superior.
* Un usuario con permiso para `create privileged pods`, `ClusterRoles` y `ClusterRoleBindings`:
 ** Se necesitan ClusterRole y ClusterRoleBinding para:
  *** Conceder permisos a los agentes de SUSE Observability para acceder a la API de Kubernetes
  *** Generar un secreto para el webhook de validación mutante que es parte de xref:/setup/agent/k8sTs-agent-request-tracing.adoc[trazado de solicitudes]
 ** Los agentes de SUSE Observability necesitan ejecutarse en un pod privilegiado para poder recopilar información sobre conexiones de red e información del host.

=== Configura una integración autoalojada

[CAUTION]
====
Antes de comenzar, revisa los <<_prerequisites_for_self_hosted,requisitos previos para Kubernetes>>.
====


Para obtener datos de un clúster de Kubernetes en SUSE Observability, sigue los pasos descritos a continuación:

. Añade el repositorio helm de SUSE Observability al cliente helm local:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. En la interfaz de SUSE Observability, abre el menú principal haciendo clic en la parte superior izquierda de la pantalla y ve a `StackPacks` > `Integrations` > `Kubernetes`.
. Instala una nueva instancia del Kubernetes StackPack:
 ** Especifica un *Nombre del Clúster de Kubernetes*
  *** Este nombre se utilizará para identificar el clúster en SUSE Observability
 ** Haz clic en *instalar*.
. Despliega el agente de SUSE Observability, el agente del clúster, el agente de checks y kube-state-metrics en tu clúster utilizando el comando helm proporcionado en la interfaz de usuario de SUSE Observability después de haber instalado el StackPack.
 ** Una vez que los agentes hayan sido desplegados, comenzarán a recopilar datos y enviarlos a SUSE Observability.


== Pasos siguientes

* xref:/k8s-getting-started.adoc[Guía de SUSE Observability]
