= Überprüfen Sie, ob die Instrumentierung funktioniert.
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Wenn der Collector und das Instrumentation setup erfolgreich waren, sollten innerhalb von etwa ein bis zwei Minuten Daten in SUSE Observability verfügbar sein.

Sie können überprüfen, ob SUSE Observability Traces empfängt:

. Öffnen Sie SUSE Observability in einem Browser.
. Finden Sie (einen der) Pods, die instrumentiert sind.
. Wählen Sie den Pod aus, um die Highlights-Seite zu öffnen.
. Öffnen Sie die Trace-Perspektive. Wenn der Pod Verkehr bedient, sollte jetzt Traces angezeigt werden.

Um zu überprüfen, ob SUSE Observability Metriken empfängt:

. Öffnen Sie SUSE Observability in einem Browser.
. Öffnen Sie den Metriken-Explorer aus dem Menü.
. Suchen Sie nach den von Ihrer Anwendung bereitgestellten Metriken.

Wenn nach 5 Minuten immer noch keine Metriken vorhanden sind, ist wahrscheinlich etwas falsch konfiguriert. Siehe xref:/setup/otel/troubleshooting.adoc[Fehlerbehebung] für Hilfe.
