= Moniteurs
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

SUSE Observability intègre les meilleures pratiques via des moniteurs. Les moniteurs de SUSE Observability surveillent non seulement les métriques, les événements ou les journaux, mais peuvent également surveiller la topologie et les métadonnées pour détecter des problèmes courants, garantissant ainsi la conformité et le respect des normes de l'industrie.
En combinant les moniteurs avec notre intelligence unique en matière de dépannage, SUSE Observability détecte rapidement les problèmes connexes et conseille sur la manière de les remédier. Cette approche proactive réduit le risque de problèmes non détectés et aide à maintenir un environnement Kubernetes sain et robuste.
Les moniteurs sont accompagnés de guides de remédiation spécifiques à la ressource sur laquelle une alerte est émise et à l'état surveillé pour guider nos utilisateurs dans leur dépannage.

== Surveille les résultats

Les résultats des moniteurs sont affichés à deux endroits :

. Sur les pages de mise en évidence de toutes les ressources pour voir immédiatement ce qui se passe et comment y remédier.
. Dans le volet latéral droit, si vous sélectionnez un élément dans la topologie, cela vous donne une indication rapide des problèmes pour ce composant.

== Guides de remédiation

Les guides de remédiation sont affichés dans le tiroir de statut du moniteur qui s'ouvre si vous cliquez sur le message dans la perspective de mise en évidence d'une ressource.

== Reportez-vous également à la section

* xref:/use/alerting/kubernetes-monitors.adoc[Moniteurs prêts à l'emploi pour Kubernetes]
