= 故障排除自定义指标图表。
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 概述

* <<_the_metric_chart_doesnt_show_on_the_highlights_page_of_a_component,指标图表未在组件的高亮页面上显示>>
* <<_the_metric_chart_doesnt_show_on_the_metrics_perspective_of_a_component,指标图表未在组件的指标视图上显示>>
* <<_the_metric_chart_on_a_component_remains_empty_no_data,组件上的指标图表保持为空（"无数据"）>>

== 指标图表未在组件的高亮页面上显示。

目前无法自定义在组件高亮页面上显示的指标图表。自定义指标绑定的图表仅会在指标视图中显示。

== 指标图表未在组件的指标视图上显示。

`scope`指标绑定上的查询用于确定组件是否显示该指标绑定。如果组件未显示指标绑定，请检查范围中的拓扑查询是否与组件匹配。

首先检查组件在高亮页面上是否确实具有预期的标签和/或组件类型，名称和类型位于顶部，标签在"关于"部分。确保标签名称或值中没有拼写错误。

检查范围查询的语法是否正确：

. 通过菜单中的视图和右侧的蓝色"探索"按钮打开探索视图。或直接通过URL访问：`https://<your-stackstate-instance>/#/views/explore`
. 打开过滤器并选择`switch to STQL`
. 现在将范围中的查询复制/粘贴到STQL字段中并运行查询

概览现在显示所有匹配查询的组件，并将获得图表。

== 组件上的指标图表保持为空（"无数据"）。

对于预期有数据但没有数据的指标图表，请打开检查器（图表右上角的图标）。切换 "显示查询" 按钮以显示查询内容。

确保查询中不再包含任何参数（即所有像 `${tags.cluster-name}` 或 `${name}` 的值）都已被组件的值替换。如果查询中仍然留有一些参数，则这些标签在该组件上不可用。因此，请交叉检查使用的名称（在此示例中为 `cluster-name`）与组件上可用的标签。还要确保名称中没有拼写错误。

如果所有参数都已填写，可能会出现 PromQL 查询的问题。要调查此问题，请复制 PromQL 查询并打开指标浏览器（通过 {stackstate-product-name} 的主菜单）。将查询粘贴到指标浏览器中并运行。这仍然应该返回空结果。

要么指标不存在，要么它没有某个标签，或者标签确实存在但没有与该值匹配的时间序列。解决此问题的最快方法是将查询重写为仅包含其指标名称并运行，如果有结果则说明指标存在（没有拼写错误）。表格结果也可以用来验证所有使用的标签是否存在。确保这里也没有拼写错误。

如果有结果，但只是对于某个标签的特定值（例如 `pod_name` 标签），则查询是正确的，但该特定组件的该特定指标没有时间序列。在这种情况下需要检查的事项：

* 是否为该组件收集了数据（无论是通过 {stackstate-product-name} 代理还是其他方式）？
* 该组件是否有报告该指标？

如何做到这一点取决于数据收集的配置方式。
