ifdef::ss-ff-stackpacks2_enabled[]
= Open Telemetrie-Mapping-Konzepte
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Open Telemetrie-Mapping-Konzepte

== Komponenten-Mappings

Ein `OtelComponentMapping` beschreibt, wie eine Topologiekomponente aus Open Telemetrie-Daten erstellt (oder aktualisiert) wird.

Typische Beispiele für aus Open Telemetrie erstellte Komponenten sind (diese sind Teil des Standard-Open Telemetrie-StackPacks):

* Dienste (abgeleitet von `service.name` / `service.namespace`)
* Service-Instanzen (abgeleitet von `service.instance.id`)
* Datenbanken
* Hosts und Kubernetes-Ressourcen (Knoten, Namespaces, Pods)
* Funktionen und Aufgaben in serverlosen oder Batch-Umgebungen

== Beziehungs-Mappings

Ein `OtelRelationMapping` beschreibt, wie eine Beziehung zwischen zwei Komponenten aus Open Telemetrie-Daten erstellt wird.

Häufige Beispiele für Beziehungen sind (diese sind Teil des Standard-Open Telemetrie-StackPacks):

* Synchrone Dienstaufrufe (Client -> Server)
* Asynchrone Nachrichtenflüsse (Produzent -> Verbraucher, Verbraucher -> Peer, Produzent -> Peer)
* Verbindungen von Diensten zu Datenbanken
* Service-Instanz bereitgestellt von Dienst
* Ausführungsbeziehungen (Dienst oder Funktion führt Aufgabe, Host oder Funktion aus)

== Ausdrücke und die Common Expression Language (CEL)

Topologiemappings basieren auf der https://cel.dev/[Common Expression Language (CEL)], um Telemetrie auszuwählen, Werte zu extrahieren und Komponenten- und Beziehungsfelder zu konstruieren.

Sie benötigen keine vorherige CEL-Expertise, um zu beginnen - die meisten Ausdrücke sind einfache boolesche Überprüfungen, Attributabfragen oder Zeichenfolgenkonstruktionen. Fortgeschrittenere Ausdrücke können nach Bedarf schrittweise eingeführt werden.

Für weitere Informationen darüber, wie man CEL in den Topologiemappings nutzen kann, siehe die Seite xref:/setup/custom-integrations/otelmappings/schemas-ref.adoc[schemas].

endif::ss-ff-stackpacks2_enabled[]
