ifdef::ss-ff-stackpacks2_enabled[]
= Topologie aus OpenTelemetry
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topologie aus OpenTelemetry

{stackstate-product-name} kann automatisch die Anwendungs- und Infrastrukturtopologie aus den Telemetriedaten von OpenTelemetry (OTel) ableiten.
Dies wird durch die Topologiemappings von OpenTelemetry erreicht, die deklarativ Trace- und Metriksignale in Topologiekomponenten (Knoten) und Beziehungen (Kanten) umwandeln.

== Übersicht

Auf hoher Ebene funktioniert die Topologiegenerierung aus OpenTelemetry wie folgt:

* Die Telemetriedaten von OpenTelemetry (Metriken und/oder Traces) werden vom Collector empfangen.
* Der OTel-Collector verwendet einen Topologie-Connector, der konfigurierte Mappings gegen die Telemetriedaten auswertet.
* Wenn die Mapping-Bedingungen mit der Telemetrie übereinstimmen, werden Komponenten und/oder Beziehungen erzeugt.
* Diese Topologieobjekte werden vom `sync` Dienst konsumiert und in den Topologiegraphen integriert.
* Mappings sind deklarativ, YAML-basiert und werden kontinuierlich ausgewertet, während die Telemetrie durch das System fließt.

Derzeit unterstützte Signale:

* Metriken
* Traces

[NOTE]
====
Die logbasierte Topologiegenerierung wird derzeit noch nicht unterstützt.
====

Weitere Informationen zu Komponenten- und Beziehungsmappings finden Sie auf der xref:/setup/custom-integrations/otelmappings/concepts.adoc[concepts]-Seite.

endif::ss-ff-stackpacks2_enabled[]
