= Clear stored data
:description: SUSE Observability Self-hosted

The data in SUSE Observability is divided into four different sets:

* Elasticsearch data
* Kafka Topic data
* StackGraph data
* Metrics data

With this much data to store, it's important to have the means to manage it. There is a standard 30 days data retention period set in SUSE Observability. This can be configured according to your needs using the SUSE Observability CLI. Find out more about xref:/setup/data-management/data_retention.adoc[SUSE Observability data retention].

== Clear data manually

To clear stored data in SUSE Observability running on Kubernetes, it's recommended to run a clean install:

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Uninstall SUSE Observability]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Remove all PVC's]
. Install SUSE Observability again using the same configuration as before, on xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] or xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
