= Monitores de limite dinĂąmico
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== VisĂŁo Geral

Para mĂ©tricas que variam significativamente ao longo do tempo e diferem de serviĂ§o para serviĂ§o, um monitor de limite dinĂąmico fornece detecĂ§ĂŁo de anomalias simples e eficiente.  Ele usa dados de 1, 2 ou 3 semanas atrĂĄs, alĂ©m do passado recente, como contexto para comparar os dados atuais.

Os dados da "janela de verificaĂ§ĂŁo" sĂŁo comparados com os fornecidos pelo contexto histĂłrico usando o teste de Anderson-Darling.  Isso impĂ”e muito poucas suposiĂ§Ă”es sobre a distribuiĂ§ĂŁo dos dados.  O teste Ă© particularmente sensĂ­vel a outliers nas extremidades superior e inferior da distribuiĂ§ĂŁo.  A mĂ©trica pode ser suave, espinhosa ou ter alguns "nĂ­veis" - como os valores dos dados sĂŁo comparados diretamente, sem ajuste de modelo, o monitor de limite dinĂąmico Ă© muito robusto.

Para mĂ©tricas que variam suavemente ao longo do tempo (por exemplo, em uma escala de cinco minutos), o nĂșmero efetivo de pontos de dados Ă© menor do que o nĂșmero bruto.  O monitor de limite dinĂąmico compensa isso, de modo que o mesmo monitor possa ser usado para uma ampla gama de mĂ©tricas sem a necessidade de ajustar seus parĂąmetros.

Existem alguns parĂąmetros que podem ser definidos para a funĂ§ĂŁo do monitor:

* `falsePositiveRate`: diga `!!float 1e-8` - a sensibilidade do monitor ao comportamento desviado.  Um valor mais baixo suprime mais (falsos) positivos, mas tambĂ©m pode levar a falsos negativos (anomalias nĂŁo percebidas).
* `checkWindowMinutes`: diga `10` minutos - a janela de verificaĂ§ĂŁo precisa ser equilibrada entre alertas rĂĄpidos (valores pequenos) e anomalias corretamente identificadas (valores altos).  Um punhado de pontos de dados funciona bem na prĂĄtica.
* `historicWindowMinutes`: por exemplo, `120` (2 horas) - delimitado em torno do tempo atual, mas tambĂ©m uma ou mais semanas atrĂĄs - ou seja, de uma hora antes do tempo atual atĂ© uma hora depois.  AlĂ©m disso, as duas horas antes da janela de verificaĂ§ĂŁo sĂŁo utilizadas.  O monitor de limite dinĂąmico compara a distribuiĂ§ĂŁo desses dados histĂłricos com os pontos de dados na janela de verificaĂ§ĂŁo.
* `historySizeWeeks`: diga `2` - o nĂșmero de semanas que os dados sĂŁo retirados para contexto histĂłrico.  Pode ser `1`, `2` ou `3`.
* `removeTrend`: para mĂ©tricas que apresentam comportamento de tendĂȘncia (por exemplo, nĂșmero de solicitaĂ§Ă”es), de modo que o valor absoluto difira de semana para semana, essa tendĂȘncia (o valor mĂ©dio) pode ser considerada.
* `includePreviousDay`: tipicamente `false` - para mĂ©tricas que nĂŁo tĂȘm um padrĂŁo semanal, mas apenas um diĂĄrio, isso permite o uso de dados mais recentes.

== Exemplo de monitor de limite dinĂąmico

Um monitor implementado usando a funĂ§ĂŁo de limite dinĂąmico se parece com:

----
  - _type: "Monitor"
    name: "<name of the monitor>"
    identifier: "urn:stackpack:<stackpack-name>:monitor:<identifier for the monitor>"
    status: "DISABLED"
    description: "<description>"
    function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
    arguments:
      telemetryQuery:
        query: "<metric to bind to component>"
        unit: s
        aliasTemplate: "<name for the metric>"
      topologyQuery: <topology query for the components to bind to>
      falsePositiveRate: <floating point number, e.g. !!float 1e-8>
      checkWindowMinutes: <integer, e.g. 10>
      historicWindowMinutes: <integer, e.g. 120>
      historySizeWeeks: <integer: 1, 2 or 3>
      includePreviousDay: <boolean>
      removeTrend: <boolean>
    intervalSeconds: 60
    remediationHint: "<how to remediate deviating states>"
----

O monitor pode ser implementado usando o guia em xref:use/alerting/k8s-dynamic-threshold-monitors.adoc[Adicionar um monitor de limite aos componentes usando a CLI]
