= Monitore
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Übersicht

SUSE Observability hat die besten Praktiken mithilfe von Monitoren kodifiziert. SUSE Observability-Monitore überwachen nicht nur Metriken, Ereignisse oder Protokolle, sondern können auch die Topologie und Metadaten überwachen, um häufige Probleme zu erkennen und die Einhaltung von Branchenstandards sicherzustellen.
Durch die Kombination von Monitoren mit unserer einzigartigen Fehlerbehebungsintelligenz erkennt SUSE Observability schnell zusammenhängende Probleme und gibt Ratschläge zur Behebung. Dieser proaktive Ansatz verringert das Risiko unentdeckter Probleme und hilft, eine gesunde und robuste Kubernetes-Umgebung aufrechtzuerhalten.
Monitore werden von spezifischen Leitfäden zur Behebung begleitet, die sich auf die Ressource beziehen, die alarmiert wird, und den überwachten Zustand, um unseren Benutzern bei der Fehlersuche zu helfen.

== Überwachen von Ergebnissen

Die Ergebnisse der Monitore werden an zwei Stellen angezeigt:

. Auf den Highlight-Seiten aller Ressourcen, um sofort zu sehen, was vor sich geht und wie man es beheben kann.
. Im rechten seitlichen Fenster, wenn Sie ein Element in der Topologie auswählen, erhalten Sie umgehend einen Überblick über eventuelle Probleme dieser Komponente.

== Leitfäden zur Behebung

Leitfäden zur Behebung werden im Monitor-Statusbereich angezeigt, der erscheint, wenn Sie einen Monitor öffnen, indem Sie auf die Nachricht in der Highlight-Perspektive einer Ressource klicken.

== Siehe auch

* xref:/use/alerting/kubernetes-monitors.adoc[Vorgefertigte Monitore für Kubernetes]
