= Dépannage des notifications
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Lorsque un canal de notification échoue à envoyer des notifications, l'aperçu des notifications affichera un statut d'erreur. Pour inspecter les erreurs :

. Cliquez sur la notification
. Le haut de la page affiche une bannière avec un résumé des erreurs
. Faites défiler vers le bas jusqu’aux canaux, puis cliquez sur le lien « erreur » pour le ou les canaux concernés afin d’ouvrir les détails de l’erreur.

== Erreurs fréquentes

=== Slack

Les erreurs Slack contiennent généralement un code d'erreur :

* `token_revoked`, `token_expired` ou `missing_scope` : Ces codes d'erreur indiquent tous un problème avec l'autorisation de SUSE Observability pour publier des messages sur Slack. Pour résoudre ces problèmes, recréez le canal pour réautoriser SUSE Observability avec Slack afin que toutes les autorisations requises soient accordées.
* Pour d'autres codes d'erreur, voir https://api.slack.com/automation/cli/errors[codes d'erreur de l'API Slack].

=== HTTP

La plupart des canaux, en particulier le webhook, attendent une réponse HTTP avec le statut 200 OK. D'autres réponses sont considérées comme une erreur. Les erreurs HTTP contiennent un message, généralement court, et le code d'état qui a été reçu au lieu de 200 OK.

Vérifiez que toutes les URL et les tokens configurés sont corrects et, dans le cas du webhook, que les requêtes POST sont traitées correctement et renvoient une réponse 200 OK.

=== Autre

Dans le cas où l'erreur est de type "Autre", il est très probable que SUSE Observability ne puisse même pas se connecter au service externe ou au webhook. Vérifiez que l'URL est correcte, peut être résolue et peut être accessible par SUSE Observability.
