= Page d'analytique
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

La page d'analytique fournit une interface puissante et flexible pour interroger et analyser vos données d'observabilité en utilisant xref:/develop/reference/k8sTs-stql_reference.adoc[des requêtes STQL].
Cet environnement interactif vous permet d'aller au-delà des tableaux de bord préconçus et d'obtenir des informations plus approfondies sur la santé, la performance et les dépendances de votre environnement dynamique.

[CAUTION]
====
*La page d'analytique n'est plus prise en charge, mais vous pouvez toujours l'activer en configurant des autorisations spécifiques. Cependant, nous recommandons fortement d'utiliser les StackPacks pour une observabilité et une analyse améliorées, car ils offrent une alternative plus robuste et activement supportée.*

Deux autorisations sont requises pour activer la page d'analytique :

* `access-analytics`
* `execute-scripts`

Plus de détails : xref:/setup/security/rbac/rbac_permissions.adoc[Gestion des autorisations]

====

