= Steps to upgrade
:description: SUSE Observability Self-hosted

[CAUTION]
====
Upgrading from StackState 6.0 to SUSE Observability is not yet supported.
====


== Overview

This document describes the upgrade procedure for SUSE Observability.

== Before you upgrade

When executing a SUSE Observability upgrade, be aware of the following:

[CAUTION]
====
*Always read the* xref:version-specific-upgrade-instructions.adoc[*version-specific upgrade notes*] *before upgrading SUSE Observability.*
====


[CAUTION]
====
When upgrading a StackPack, *any changes you have made to configuration items from that StackPack will be overwritten*. See link:../../stackpacks/about-stackpacks.adoc#locked-configuration-items[Configuration Locking] for more information.
====


[WARNING]
====
If there are *hotfixes* installed in your SUSE Observability installation, contact SUSE Observability technical support prior to upgrading.
====


== Steps to upgrade

=== Minor or maintenance SUSE Observability release

A minor release of SUSE Observability is indicated by a change in the second digit of the version number, for example 4.1.0. Maintenance releases are identified by a change in the third digit of the version number, for example 4.1.1.

If you are upgrading to a new *minor* SUSE Observability release or a *maintenance* release, SUSE Observability itself and the StackPacks will be compatible with the current installation.

A minor upgrade consists of the following steps:

. <<create-a-backup,Create a backup>>
. <<upgrade-stackstate,Upgrade SUSE Observability>>
. <<verify-the-new-installation,Verify the new installation>>
. Check if any installed StackPacks require an upgrade

=== Major SUSE Observability release

A major release of SUSE Observability is indicated by a change in the first digit of the version number, for example 4.0.0.

If you upgrade to a new *major* SUSE Observability release, SUSE Observability and the installed StackPacks may be incompatible with the current installation. For details, check the xref:version-specific-upgrade-instructions.adoc[version-specific upgrade notes].

A major upgrade consists of the following steps:

. link:steps-to-upgrade.adoc#create-a-backup[Create a backup]
. Optional: link:steps-to-upgrade.adoc#uninstall-stackpacks-optional[Uninstall StackPacks]
. link:steps-to-upgrade.adoc#upgrade-stackstate[Upgrade SUSE Observability]
. Optional: link:steps-to-upgrade.adoc#install-stackpacks-optional[Install StackPacks]
. link:steps-to-upgrade.adoc#verify-the-new-installation[Verify the new installation]

== Walkthrough of an upgrade

=== Create a backup

Before upgrading SUSE Observability it's recommended to back up your configuration and topology data:

* xref:../data-management/backup_restore/kubernetes_backup.adoc[Kubernetes backup]
* xref:../data-management/backup_restore/configuration_backup.adoc[Configuration backup]

[NOTE]
====
Note that it won't be possible to restore the backup on the upgraded version of SUSE Observability. The SUSE Observability backup can only be restored in the SUSE Observability version before the upgrade.
====


=== Upgrade SUSE Observability

Be sure to check the release notes and any optional upgrade notes before running the upgrade.

{% tabs %}

{% tab title="Kubernetes" %}

. Get the latest helm chart by running `helm repo update`.
. Check the xref:version-specific-upgrade-instructions.adoc[version specific upgrade notes] for all changes between your current version and the version that you will upgrade to. If there have been changes made to configuration items specified in your `values.yaml` file, the file should be updated.
. To upgrade, use the same helm command as for the link:../install-stackstate/kubernetes_openshift/kubernetes_install.adoc#deploy-suse-observability-with-helm[first time Kubernetes installation]. The new helm chart will pull newer versions of Docker images and handle the upgrade.
{% endtab %}

{% tab title="OpenShift" %}

. Get the latest helm chart by running `helm repo update`.
. Check the xref:version-specific-upgrade-instructions.adoc[version specific upgrade notes] for all changes between your current version and the version that you will upgrade to. If there have been changes made to configuration items specified in your `values.yaml` file, the file should be updated.
. link:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#additional-openshift-values-file[Update the `openshift-values.yaml`] file.
. To upgrade, use the same helm command as for the link:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#deploy-suse-observability-with-helm[first time OpenShift installation]. The new helm chart will pull newer versions of Docker images and handle the upgrade.
{% endtab %}

{% endtabs %}

=== Verify the new installation

Once SUSE Observability has been upgraded and started, verify that the new installation of SUSE Observability is reachable and that the application is running.

== See also

* link:../../stackpacks/about-stackpacks.adoc#upgrade-a-stackpack[Manually upgrade a StackPack]
* xref:version-specific-upgrade-instructions.adoc[Version-specific upgrade notes]
