= Monitores de Limiar DinĂ˘mico
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== VisĂŁo Geral

Para mĂŠtricas que variam significativamente ao longo do tempo e diferem de serviĂ§o para serviĂ§o, um monitor de Limiar DinĂ˘mico fornece detecĂ§ĂŁo de anomalias simples e eficiente.  Ele utiliza dados de 1, 2 ou 3 semanas atrĂĄs, alĂŠm do passado recente, como contexto para comparar os dados atuais.

Os dados da "janela de verificaĂ§ĂŁo" sĂŁo comparados com os fornecidos pelo contexto histĂłrico usando o teste de Anderson-Darling.  Isso impĂľe muito poucas suposiĂ§Ăľes sobre a distribuiĂ§ĂŁo dos dados.  O teste ĂŠ particularmente sensĂ­vel a outliers nas extremidades superior e inferior da distribuiĂ§ĂŁo.  A mĂŠtrica pode ser suave, espinhosa ou ter alguns "nĂ­veis" - como os valores dos dados sĂŁo comparados diretamente, sem ajuste de modelo, o monitor de Limiar DinĂ˘mico ĂŠ muito robusto.

Para mĂŠtricas que variam suavemente ao longo do tempo (por exemplo, em uma escala de 5 minutos), o nĂşmero efetivo de pontos de dados ĂŠ menor do que o nĂşmero bruto.  O DT compensa isso, de modo que o mesmo monitor pode ser usado para uma ampla gama de mĂŠtricas sem a necessidade de ajustar seus parĂ˘metros.

Existem alguns parĂ˘metros que podem ser configurados para a funĂ§ĂŁo do monitor:

* `falsePositiveRate`: diga `!!float 1e-8` - a sensibilidade do monitor ao comportamento desviado.  Um valor mais baixo suprime mais (falsos) positivos, mas tambĂŠm pode levar a falsos negativos (anomalias nĂŁo percebidas).
* `checkWindowMinutes`: diga `10` minutos - a janela de verificaĂ§ĂŁo precisa ser equilibrada entre alertas rĂĄpidos (valores pequenos) e anomalias corretamente identificadas (valores altos).  Um punhado de pontos de dados funciona bem na prĂĄtica.
* `historicWindowMinutes`: diga `120` (2 horas) - delimitado em torno do tempo atual, mas entĂŁo uma ou mais semanas atrĂĄs - entĂŁo de 1 hora antes do tempo atual atĂŠ 1 hora depois.  AlĂŠm disso, as 2 horas antes da janela de verificaĂ§ĂŁo sĂŁo utilizadas.  O monitor de limite dinĂ˘mico compara a distribuiĂ§ĂŁo desses dados histĂłricos com os pontos de dados na janela de verificaĂ§ĂŁo.
* `historySizeWeeks`: diga `2` - o nĂşmero de semanas que os dados sĂŁo retirados para contexto histĂłrico.  Pode ser `1`, `2` ou `3`.
* `removeTrend`: para mĂŠtricas que apresentam comportamento de tendĂŞncia (por exemplo, nĂşmero de solicitaĂ§Ăľes), de modo que o valor absoluto difira de semana para semana, essa tendĂŞncia (o valor mĂŠdio) pode ser considerada.
* `includePreviousDay`: tipicamente `false` - para mĂŠtricas que nĂŁo tĂŞm um padrĂŁo semanal, mas apenas um diĂĄrio, isso permite o uso de dados mais recentes.

== Exemplo de Monitor de Limiar DinĂ˘mico

Um Monitor implementado usando a funĂ§ĂŁo de Limiar DinĂ˘mico se parece com:

----
  - _type: "Monitor"
    name: "<name of the monitor>"
    identifier: "urn:custom:monitor:<identifier for the monitor>"
    status: "DISABLED"
    description: "<description>"
    function: {{ get "urn:stackpack:aad-v2:shared:monitor-function:dt" }}
    arguments:
      telemetryQuery:
        query: "<metric to bind to component>"
        unit: s
        aliasTemplate: "<name for the metric>"
      topologyQuery: <topology query for the components to bind to>
      falsePositiveRate: <floating point number, e.g. !!float 1e-8>
      checkWindowMinutes: <integer, e.g. 10>
      historicWindowMinutes: <integer, e.g. 120>
      historySizeWeeks: <integer: 1, 2 or 3>
      includePreviousDay: <boolean>
      removeTrend: <boolean>
    intervalSeconds: 60
    remediationHint: "<how to remediate deviating states>"
----

xref:/use/alerting/k8s-add-monitors-cli.adoc[O monitor pode ser implementado usando o guia em Adicionar um monitor de limite a componentes usando a CLI]
