= Monitores
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Visão Geral

O SUSE Observability possui as melhores práticas codificadas por meio de monitores. Os monitores do SUSE Observability não apenas monitoram métricas, eventos ou logs, mas também podem monitorar a topologia e os metadados para detectar problemas comuns, garantindo conformidade e adesão aos padrões da indústria.
Combinando monitores com nossa inteligência única de resolução de problemas, o SUSE Observability detecta rapidamente problemas relacionados e aconselha sobre como remediá-los. Essa abordagem proativa reduz o risco de problemas não detectados e ajuda a manter um ambiente Kubernetes saudável e robusto.
Os monitores são acompanhados por guias de remediação específicos para o recurso que gerou o alerta e a condição monitorada, para orientar nossos usuários em sua resolução de problemas.

== Monitore os resultados

Os resultados dos monitores são exibidos em dois lugares:

. Nas páginas de destaque de todos os recursos, para ver imediatamente o que está acontecendo e como remediar isso.
. No painel lateral direito, ao selecionar um elemento na topologia, você recebe uma indicação rápida de problemas para aquele componente.

== Guias de remediação

Os guias de remediação são exibidos na gaveta de Status do Monitor, que é mostrada se você abrir um monitor clicando na mensagem na perspectiva de Destaque de um recurso.

== Consulte também

* xref:/use/alerting/kubernetes-monitors.adoc[Monitores prontos para uso para Kubernetes]
