= .NET 应用程序
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== 自动仪器化

对于 .NET，自动仪器化可以自动捕获各种 https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/internal/instrumentation-libraries.md[库和框架] 的跟踪和指标。

自动仪器化不需要对应用程序进行任何修改。要设置它，请按照以下步骤操作：

. 从 opentelemetry-dotnet-instrumentation 储存库的 https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases[发布] 下载 https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-glibc.zip[glibc] 或 https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/latest/download/opentelemetry-dotnet-instrumentation-linux-musl.zip[musl] 版本的仪器化库（musl 用于 Alpine，glibc 用于大多数其他 docker 镜像）。解压文件并将其包含在您的应用程序 Docker 镜像中的一个目录中，这里我们使用 `/autoinstrumentation`。
. 设置以下环境变量，这里我们通过 Kubernetes pod 规格中的容器 `env` 来完成：
+
[,yaml]
----
env:
- name: CORECLR_ENABLE_PROFILING
  value: "1"
- name: CORECLR_PROFILER
  value: "{918728DD-259F-4A6A-AC2B-B85E1B658318}"
- name: CORECLR_PROFILER_PATH
  # for glibc:
  value: "/autoinstrumentation/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
  # For musl use instead:
  # value: "/autoinstrumentation/linux-musl-x64/OpenTelemetry.AutoInstrumentation.Native.so"
- name: DOTNET_ADDITIONAL_DEPS
  value: "/autoinstrumentation/AdditionalDeps"
- name: DOTNET_SHARED_STORE
  value: "/autoinstrumentation/store"
- name: DOTNET_STARTUP_HOOKS
  value: "/autoinstrumentation/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
- name: OTEL_DOTNET_AUTO_HOME
  value: "/autoinstrumentation"
----

. 还要在 pod 上添加额外的环境变量 xref:/setup/otel/languages/sdk-exporter-config.adoc[以配置服务名称和出口端点]。
. 使用这些更改部署您的应用程序
. xref:/setup/otel/languages/verify.adoc[验证] SUSE Observability 是否正在接收跟踪和/或指标

有关更多详细信息，请参阅 https://opentelemetry.io/docs/languages/java/automatic/[Open Telemetry 文档]。

== 手动仪器化

当您需要从不受自动仪器化支持的代码部分获取指标、跟踪或日志时，可以使用手动仪器化。例如，不受支持的库、自研代码或业务级指标。

要捕获该数据，您需要修改您的应用程序。

. 将 Open Telemetry SDK 作为依赖项包含
. 在需要的地方向您的应用程序添加代码以捕获指标、跨度或日志

有关此内容的详细文档，请参阅 https://opentelemetry.io/docs/languages/net/instrumentation/[Open Telemetry .NET SDK 文档页面]。

确保使用 OTLP 导出器（这是默认设置）和 https://opentelemetry.io/docs/languages/java/instrumentation/#_autoconfiguration[自动配置]。在部署应用程序时，服务名称和导出器是通过环境变量xref:/setup/otel/languages/sdk-exporter-config.adoc[配置的]。

== SUSE Observability 中的指标

ifdef::ss-ff-stackpacks2_enabled[]
对于某些 .NET 指标，例如垃圾收集器指标，SUSE Observability 已在相关组件上定义了图表。对于 Kubernetes，图表可在 pod 上获取。可以xref:/setup/custom-integrations/metric-bindings/index.adoc[添加更多指标的图表]，这适用于自动仪器化的指标，也适用于手动仪器化的特定于应用程序的指标。
endif::[]


ifndef::ss-ff-stackpacks2_enabled[]
对于某些 .NET 指标，例如垃圾收集器指标，SUSE Observability 已在相关组件上定义了图表。对于 Kubernetes，图表可在 pod 上获取。可以xref:/use/metrics/k8s-add-charts.adoc[添加更多指标的图表]，这适用于自动仪器化的指标，也适用于手动仪器化的特定于应用程序的指标。
endif::[]

