= K8s Custom Secrets Setup (veraltet)
:revdate: 2025-10-27
:page-revdate: {revdate}

== Übersicht

Der SUSE Observability-Agent unterstützt die Angabe des Namens eines benutzerdefinierten Geheimnisses, das den API-Schlüssel und das Cluster-Autorisierungstoken enthält. Dieses Feature ist nützlich für Benutzer, die ihre eigenen Geheimnisse verwalten und die automatische Erstellung von Geheimnissen durch das Helm-Chart vermeiden möchten.

[CAUTION]
====
*Diese Methode zur Anpassung von Geheimnissen ist veraltet und mit der RBAC-Funktion nicht kompatibel.*

Bitte verwenden Sie xref:/setup/agent/k8s-custom-secrets-setup.adoc[die neue Methode] zur Verwendung externer Geheimnisse.
====


== Das Helm-Chart

=== Konfigurationsoptionen

* `stackstate.manageOwnSecrets`: Ein boolescher Datentyp, der bestimmt, ob der Benutzer seine eigenen Geheimnisse verwalten möchte. Die Standardeinstellung ist `false`.
* `stackstate.customSecretName`: (Optional) Name des benutzerdefinierten Geheimnisses, das vom Benutzer erstellt werden soll. Erforderlich, wenn `stackstate.manageOwnSecrets` auf `true` gesetzt ist.
* `stackstate.customApiKeySecretKey`: (Optional) Schlüsselname für den API-Schlüssel innerhalb des benutzerdefinierten Geheimnisses. Erforderlich, wenn `stackstate.manageOwnSecrets` auf `true` gesetzt ist.
* `stackstate.customClusterAuthTokenSecretKey`: (Optional) Schlüsselname für das Cluster-Autorisierungstoken innerhalb des benutzerdefinierten Geheimnisses. Erforderlich, wenn `stackstate.manageOwnSecrets` auf `true` gesetzt ist.

=== Verhaltensbeschreibung

* *Automatische Geheimniserstellung*: Standardmäßig erstellt das Chart weiterhin automatisch Geheimnisse wie zuvor, wenn `stackstate.manageOwnSecrets` auf `false` gesetzt ist.
* *Verwaltung benutzerdefinierter Geheimnisse*: Wenn `stackstate.manageOwnSecrets` auf `true` gesetzt ist, erwartet das Chart, dass der Benutzer den Namen des benutzerdefinierten Geheimnisses (`stackstate.customSecretName`) sowie die Schlüssel für den API-Schlüssel und das Cluster-Autorisierungstoken (`stackstate.customApiKeySecretKey` und `stackstate.customClusterAuthTokenSecretKey`, jeweils) angibt.
* *Implizierte Auslassung*: Wenn Sie angeben, dass Sie Ihre eigenen Geheimnisse verwalten möchten, ignoriert das Chart die Werte für `stackstate.apiKey` und `stackstate.cluster.authToken`.
+
== So verwenden Sie es in values.yaml

. *Verwendung der automatischen Geheimniserstellung (Standard)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *Eigene Geheimnisse verwalten*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
