= K8s Benutzerdefinierte Geheimnisverwaltung
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== Übersicht

Der SUSE Observability Agent unterstützt die Angabe des Namens eines benutzerdefinierten Geheimnisses, das den API-Schlüssel und das Cluster-Autorisierungstoken enthält. Dieses Feature ist nützlich für Benutzer, die ihre eigenen Geheimnisse verwalten und die automatische Erstellung von Geheimnissen durch das Helm-Chart vermeiden möchten.

NOTE: *Es gab eine vorherige Methode zur Angabe, die jetzt ausgelaufen ist, siehe die xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[ausgelaufene Methode].*

== Das Helm-Chart

=== Konfigurationsoptionen

* `global.apiKey.fromSecret`: Geben Sie den Namen eines bereits vorhandenen Geheimnisses an, das sich im selben Namespace befindet und ein `STS_API_KEY`-Feld mit dem API-Schlüssel enthält.
* `global.clusterAgentAuthToken.fromSecret`: Geben Sie den Namen eines bereits vorhandenen Geheimnisses an, das sich im selben Namespace befindet und ein `STS_CLUSTER_AGENT_AUTH_TOKEN`-Feld mit einem Token zur Sicherung der Verbindungen zwischen dem Cluster und den Knotenagenten enthält.

=== Verhaltensbeschreibung

* *Automatische Geheimniserstellung*: Standardmäßig erfordert das Chart, dass ein `stackstate.apiKey` angegeben wird, und erstellt ein Geheimnis selbst. Das `STS_CLUSTER_AGENT_AUTH_TOKEN` wird automatisch generiert.
* *Benutzerdefinierte Geheimnisverwaltung*: Beim Überschreiben der `fromSecret` Felder werden der API-Schlüssel und das Cluster-Autorisierungstoken aus diesen Geheimnissen entnommen.
* *Implizite Auslassung*: Wenn Sie angeben, dass Sie Ihre eigenen Geheimnisse verwalten möchten, ignoriert das Chart die Werte für `stackstate.apiKey` und `stackstate.cluster.authToken`.

== Anleitung zur Verwendung in values.yaml

. *Verwendung der automatischen Geheimniserstellung (Standard)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Eigene Geheimnisse verwalten*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
