= Einführung in Open Telemetrie
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetrie-Collector und 2 instrumentierte Anwendungen, die Metriken und Traces an SUSE Observability senden]

SUSE Observability unterstützt https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetrie]. Open Telemetrie ist eine Sammlung standardisierter Protokolle und eines Open-Source-Frameworks zum Sammeln, Transformieren und Versenden von Telemetriedaten wie Traces, Metriken und Logs. Open Telemetrie unterstützt eine Vielzahl von Programmiersprachen und Plattformen.

SUSE Observability unterstützt sowohl Metriken als auch Traces und fügt die Open Telemetrie-Metriken und -Traces zu den (Kubernetes-)Topologiedaten hinzu, die vom SUSE Observability-Agent bereitgestellt werden. Daher ist es weiterhin erforderlich, auch den SUSE Observability-Agent zu installieren. Unterstützung für Protokolle und die Verwendung von Open Telemetrie ohne den SUSE Observability-Agent wird bald verfügbar sein.

Open Telemetrie besteht aus mehreren verschiedenen Komponenten. Für die Verwendung mit SUSE Observability sind die xref:/setup/otel/languages/README.adoc[SDKs], um Ihre Anwendung zu instrumentieren, und der xref:/setup/otel/collector.adoc[Open Telemetrie-Collector] die wichtigsten Teile. Wir zeigen, wie man beide für die Verwendung mit SUSE Observability konfiguriert.

Wenn Ihre Anwendung bereits mit Open Telemetrie oder mit einer anderen von Open Telemetrie unterstützten Bibliothek wie Jaeger oder Zipkin instrumentiert ist, kann der Collector verwendet werden, um diese Daten an SUSE Observability zu senden, und es ist keine zusätzliche Instrumentierung erforderlich.

SUSE Observability erfordert, dass der Collector mit spezifischen Prozessoren und Authentifizierung konfiguriert wird, um sicherzustellen, dass alle von SUSE Observability verwendeten Daten verfügbar sind.

== Hinweise

* https://opentelemetry.io/docs/collector/[Open Telemetrie-Collector] in der Open Telemetrie-Dokumentation
* https://opentelemetry.io/docs/languages/[SDKs zur Instrumentierung Ihrer Anwendung] in der Open Telemetrie-Dokumentation
