= Einführung in Open Telemetrie
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetrie-Collector und 2 instrumentierte Anwendungen, die Metriken und Traces an SUSE Observability senden]

SUSE Observability unterstützt https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetrie]. Open Telemetrie ist eine Sammlung standardisierter Protokolle und eines Open-Source-Frameworks zum Sammeln, Transformieren und Versenden von Telemetriedaten wie Traces, Metriken und Logs. Open Telemetrie unterstützt eine Vielzahl von Programmiersprachen und Plattformen.

SUSE Observability unterstützt sowohl Metriken als auch Traces. In Kombination mit dem Kubernetes-Stackpack werden die Kubernetes-Pods mit Traces angereichert, wenn verfügbar. Durch die Installation des Open Telemetry-Stackpacks werden neue Übersichtsseiten für Dienste und Dienstinstanzen verfügbar, die Zugriff auf Traces und Span-Metriken bieten. Open Telemetry-Metriken können in Monitoren und Metrikbindungen verwendet werden. Das Stackpack enthält Metrikbindungen für Span-Metriken sowie .NET- und JVM-Speichermetriken. Es gibt auch sofort einsatzbereite Monitore für Span-Fehlerquoten und -Dauer.

Die empfohlene Einrichtung für die Verwendung mit SUSE Observability besteht darin, Anwendungen mit den entsprechenden Open Telemetry xref:/setup/otel/instrumentation/README.adoc[SDKs] zu instrumentieren und den xref:/setup/otel/collector.adoc[Open Telemetry Collector] in der Nähe Ihrer instrumentierten Anwendungen zu installieren, um die Daten vorzuverarbeiten (mit Kubernetes-Labels anreichern, Sampling bei Traces usw.) und die Daten an SUSE Observability zu senden. Der Open Telemetry Collector kann auch verwendet werden, um Metriken aus vielen Arten von Telemetriequellen zu sammeln, ohne die Anwendungen mit den SDKs zu instrumentieren. Siehe die https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry Collector-Integrationen] für weitere Details und ob Ihre Datenbank oder Ihr Telemetrieprotokoll unterstützt wird.

Befolgen Sie den xref:/setup/otel/getting-started/README.adoc[Getting Started]-Leitfaden, um alles so einzurichten, dass es am besten mit SUSE Observability funktioniert.

== Hinweise

* https://opentelemetry.io/docs/collector/[Open Telemetrie-Collector] in der Open Telemetrie-Dokumentation
* https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry Collector-Integrationen]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs zur Instrumentierung Ihrer Anwendung] in der Open Telemetry-Dokumentation
