ifdef::ss-ff-stackpacks2_enabled[]
= Topologie d'OpenTelemetry
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topologie d'OpenTelemetry

{stackstate-product-name} peut dériver automatiquement la topologie des applications et des infrastructures à partir des données de télémétrie d'OpenTelemetry (OTel).
Cela est réalisé grâce aux mappages de topologie d'OpenTelemetry qui transforment de manière déclarative les signaux de trace et de métriques en composants de topologie (sommets) et en relations (arêtes).

== Présentation

À un niveau élevé, la génération de topologie à partir d'OpenTelemetry fonctionne comme suit :

* La télémétrie d'OpenTelemetry (métriques et/ou traces) est reçue par le Collecteur.
* Le collecteur OTel utilise un connecteur de topologie qui évalue les mappages configurés par rapport à la télémétrie.
* Lorsque les conditions de mappage correspondent à la télémétrie, des composants et/ou des relations sont produits.
* Ces objets de topologie sont consommés par le service `sync` et fusionnés dans le graphe de topologie.
* Les mappages sont déclaratifs, basés sur YAML, et évalués en continu à mesure que la télémétrie circule dans le système.

Signaux actuellement pris en charge :

* Métriques
* Traces

[NOTE]
====
La génération de topologie basée sur les journaux n'est pas encore prise en charge.
====

Pour plus d'informations sur les mappages de composants et de relations, consultez la page xref:/setup/custom-integrations/otelmappings/concepts.adoc[concepts].

endif::ss-ff-stackpacks2_enabled[]
