ifdef::ss-ff-stackpacks2_enabled[]
= Topologia do OpenTelemetry
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Topologia do OpenTelemetry

{stackstate-product-name} pode derivar automaticamente a topologia de aplicativo e infraestrutura a partir dos dados de telemetria do OpenTelemetry (OTel).
Isso é alcançado por meio de mapeamentos de topologia do OpenTelemetry que transformam de forma declarativa sinais de rastreamento e métricas em componentes de topologia (vértices) e relações (arestas).

== Visão Geral

Em um nível alto, a geração de topologia a partir do OpenTelemetry funciona da seguinte maneira:

* A telemetria do OpenTelemetry (métricas e/ou rastreamentos) é recebida pelo Collector.
* O coletor OTel utiliza um conector de topologia que avalia os mapeamentos configurados em relação à telemetria.
* Quando as condições de mapeamento correspondem à telemetria, componentes e/ou relações são produzidos.
* Esses objetos de topologia são consumidos pelo serviço `sync` e mesclados no gráfico de topologia.
* Os mapeamentos são declarativos, baseados em YAML, e avaliados continuamente à medida que a telemetria flui pelo sistema.

Sinais atualmente suportados:

* Métricas
* Rastreamentos

[NOTE]
====
A geração de topologia baseada em logs ainda não é suportada.
====

Para mais informações sobre mapeamentos de componentes e relações, consulte a página xref:/setup/custom-integrations/otelmappings/concepts.adoc[concepts].

endif::ss-ff-stackpacks2_enabled[]
