= Vérifiez que l'instrumentation fonctionne
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Si le collecteur et la configuration de l'instrumentation ont réussi, les données devraient être disponibles dans SUSE Observability dans environ une minute ou deux.

Vous pouvez vérifier que SUSE Observability reçoit des traces :

. Ouvrez SUSE Observability dans un navigateur
. Trouvez l'un des pods instrumentés
. Sélectionnez le pod pour ouvrir la page des points saillants
. Ouvrez la perspective des traces. Si le pod reçoit du trafic, il devrait maintenant afficher des traces

Pour vérifier que SUSE Observability reçoit des métriques :

. Ouvrez SUSE Observability dans un navigateur
. Ouvrez l'explorateur de métriques depuis le menu
. Recherchez les métriques exposées par votre application

S'il n'y a toujours pas de métriques après 5 minutes, quelque chose est probablement mal configuré. Voir xref:/setup/otel/troubleshooting.adoc[dépannage] pour obtenir de l'aide.
