= 开始使用 Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetry collector 和 2 个已仪表化的应用程序将指标和追踪发送到 SUSE Observability]

SUSE Observability 支持 https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]。Open Telemetry 是一套标准化协议和开源框架，用于收集、转换和传输遥测数据，如追踪、指标和日志。Open Telemetry 支持多种编程语言和平台。

SUSE Observability 同时支持指标和追踪，并将 Open Telemetry 的指标和追踪添加到 SUSE Observability agent 提供的 (Kubernetes) 拓扑数据中。因此，仍然需要安装 SUSE Observability agent。对日志的支持以及在没有 SUSE Observability agent 的情况下使用 Open Telemetry 的功能即将推出。

Open Telemetry 由几个不同的组件组成。对于与 SUSE Observability 一起使用，xref:/setup/otel/languages/README.adoc[SDKs] 用于仪表化您的应用程序，xref:/setup/otel/collector.adoc[Open Telemetry collector] 是最重要的部分。我们将展示如何配置这两者以便与 SUSE Observability 一起使用。

如果您的应用程序已经使用 Open Telemetry 或任何其他受 Open Telemetry 支持的库（如 Jaeger 或 Zipkin）进行了仪表化，则可以使用 collector 将该数据传输到 SUSE Observability，无需额外的仪表化。

SUSE Observability 要求 collector 配置特定的处理器和身份验证，以确保 SUSE Observability 使用的所有数据均可用。

== 参考资料

* https://opentelemetry.io/docs/collector/[Open Telemetry collector] 在 Open Telemetry 文档中
* https://opentelemetry.io/docs/languages/[用于仪表化您的应用程序的 SDKs] 在 Open Telemetry 文档中
