= SUSE Observability OpenTelemetry 协议支持
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

SUSE Observability 支持 2 个版本的 OTLP 协议，`grpc` 版本（也称为 OTLP）和 `http/protobuf`（也称为 OTLP HTTP 协议）。在收集器配置中，您可以选择使用哪个导出器，但请确保为 SUSE Observability 配置正确的 URL。建议使用 `grpc` 版本的协议，因为它支持更大的负载和更高的吞吐量。但如果您的基础设施对 `grpc` 的支持较差，您可以切换到 OTLP HTTP 协议。另请参见 xref:/setup/otel/troubleshooting.adoc#_some_proxies_and_firewalls_dont_work_well_with_grpc[故障排除]

== SUSE Cloud Observability

SUSE Cloud Observability 的端点为：

* OTLP：`otlp-<your-suse-observability>.app.stackstate.io:443`（不带 URL 方案）
* OTLP HTTP 协议: `https://otlp-http-<your-suse-observability>.app.stackstate.io`（带 URL 方案：`https`）

== 自托管 SUSE Observability

对于自托管安装，您需要通过将 SUSE Observability 的 Ingress 入口配置为 xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc#_configure_ingress_rule_for_open_telemetry[如本处所述] 来启用其中一个或两个端点。

当 SUSE Observability 与收集器运行在同一集群中时，您也可通过使用服务端点而无需 ingress，但这仅适用于 HTTP 协议。

* OTLP HTTP 协议: `http://suse-observability-otel-collector.<namespace>.svc.cluster.local:4318`

请确保在收集器配置中设置 `insecure: true`（参见下一部分），以允许使用普通 HTTP 端点而非 HTTPS。

GRPC 协议不支持通过不安全连接发送凭据，因此您只能在与安全 Ingress 入口设置结合使用时使用它。

== 收集器配置

=== OTLP 协议

收集器配置中的示例使用 OTLP 协议，如下所示：

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlp/suse-observability:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp endpoint, for example otlp-suse-observability.my.company.com:443
    endpoint: <otlp-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

=== OTLP HTTP 协议

要使用 OTLP HTTP 协议，请使用 `otlphttp` 导出器。另外，请将管道中所有导出器引用从 `otlp/suse-observability` 更新为 `otlphttp/suse-observability`！请使用查找/替换功能，以确保更改所有出现的内容。

----
extensions:
  bearertokenauth:
    scheme: SUSEObservability
    token: "${env:API_KEY}"
exporters:
  otlphttp/stackstate:
    auth:
      authenticator: bearertokenauth
    # Put in your own otlp-http endpoint, for example https://otlp-http-suse-observability.my.company.com:443
    endpoint: <otlp-http-suse-observability-endpoint>
    # Optional TLS configurations:
    #tls:
    # To disable TLS entirely:
    #  insecure: true
    # To disalbe certificate verification (but still use TLS):
    #  insecure_skip_verify: true
----

还有更多配置可用于控制导出器的具体需求和行为。例如，还可以使用自定义 CA 根证书或启用客户端证书。有关详细信息，请参阅 https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md[OTLP 导出器文档]。
