= 开始使用 Open Telemetry
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetry collector 和 2 个已仪表化的应用程序将指标和追踪发送到 SUSE Observability]

SUSE Observability 支持 https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]。Open Telemetry 是一套标准化协议和开源框架，用于收集、转换和传输遥测数据，如追踪、指标和日志。Open Telemetry 支持多种编程语言和平台。

SUSE Observability 支持指标和跟踪。与 Kubernetes stackpack 结合使用时，Kubernetes pod 将在可用时增强跟踪。通过安装 Open Telemetry stackpack，可以获得服务和服务实例的新概览页面，提供对跟踪和跨度指标的访问。Open Telemetry 指标可以在监视器和指标绑定中使用。该 stackpack 附带了用于跨度指标和 .NET 及 JVM 内存指标的指标绑定。还有现成的监视器用于跨度错误率和持续时间。

与 SUSE Observability 一起使用的推荐设置是使用适用的 Open Telemetry xref:/setup/otel/instrumentation/README.adoc[SDKs] 对应用程序进行仪表化，并在靠近您的仪表化应用程序的地方安装 xref:/setup/otel/collector.adoc[Open Telemetry collector] 以预处理数据（用 Kubernetes 标签增强、对跟踪进行采样等）并将数据发送到 SUSE Observability。Open Telemetry Collector 还可以用于从多种类型的遥测源收集指标，而无需使用 SDK 对应用程序进行仪表化。有关更多详细信息，请参见 https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry collector integrations]，以查看您的数据库或遥测协议是否受支持。

请遵循 xref:/setup/otel/getting-started/README.adoc[getting started] 指南进行设置，以便与 SUSE Observability 最佳配合。

== 参考资料

* https://opentelemetry.io/docs/collector/[Open Telemetry collector] 在 Open Telemetry 文档中
* https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry collector integrations]
* 在 Open Telemetry 文档中，https://opentelemetry.io/docs/instrumentation/README.md[用于仪表化您的应用程序的 SDKs]
