= 外部シークレット
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability外部シークレット

== 概要

SUSE Observabilityは、ヘルムインストールを通じてライセンスキー、APIキー、認証キーなどのシークレットを取得できますが、すでにプロビジョニングされたシークレットからも取得できます。

ここでは、これを構成する方法について説明します。

== 外部シークレットからライセンスキーを取得する

以下の形式で、SUSE Observabilityがインストールされているネームスペースにシークレットを作成し、空欄を埋めてください：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

シークレットを使用するために、ヘルムインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== 外部シークレットからメール通知のためのユーザー名とパスワードを取得する

以下の形式で、SUSE Observabilityがインストールされているネームスペースにシークレットを作成し、空欄を埋めてください：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

シークレットを使用するために、ヘルムインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== 外部シークレットからAPIキーを取得する

以下の形式で、SUSE Observabilityがインストールされているネームスペースにシークレットを作成し、空欄を埋めてください：

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

シークレットを使用するために、ヘルムインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== 外部シークレットから認証データを取得する

以下の形式で、SUSE Observabilityがインストールされているネームスペースにシークレットを作成してください。

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

選択した認証方法に応じて、`default_password`フィールドは異なるデータに置き換えられます。詳細については、xref:/setup/security/authentication/authentication_options.adoc[認証オプション]を参照してください。この例では、xref:/setup/security/authentication/single_password.adoc[シングルパスワード]のセットアップが使用されています。

シークレットを使用するために、ヘルムインストールコマンドに以下を追加してください：

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
