= Solução de Problemas de Extensão
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability Auto-hospedado

Esta seção fornece etapas de solução de problemas para quaisquer problemas de interoperabilidade entre {stackstate-product-name} e a extensão da interface do Rancher.

== Coletar um HAR (Http ARchive)

Http ARchive coleta detalhes sobre as requisições que são enviadas pelo navegador para o Rancher e {stackstate-product-name}.  Ele também registra as respostas recebidas.
Este arquivo é específico para a página/aba do navegador com o erro.  Não é necessário ter acesso às instâncias de suporte do Rancher ou {stackstate-product-name} (embora seus logs possam ser úteis em uma fase posterior).

* Abra a aba *Rede* no painel "Ferramentas de Desenvolvedor".  Você pode acessar isso usando `F12`.  A aba de rede mostra um registro de todas as requisições que são feitas.
* Limpe o registro e faça um (hard) refresh da página que está exibindo o comportamento problemático.
* Agora deve haver um grande número de requisições visíveis tanto para o Rancher quanto para o SUSE Observability.
* Exportar/Download/Salvar o HAR - navegadores diferentes usam nomes diferentes aqui.

== Cluster não observado

Para que o status de saúde do cluster seja visível no Rancher, deve haver alinhamento entre essas configurações:

* O nome (de exibição) do cluster na interface do Rancher.
* O `stackstate.cluster.name` definido no agente implantado no cluster
* O nome do cluster na configuração do stackpack Kubernetes no SUSE Observability

Uma incompatibilidade tende a aparecer como "nenhum dado recebido" na visão geral do cluster no Rancher.

== Falha na conexão

A configuração para o SUSE Observability pode, às vezes, não gerar uma conexão válida na interface do Rancher devido aos seguintes motivos:

* O host do Rancher não está configurado como uma origem permitida para o SUSE Observability.  Você pode corrigir isso adicionando-o à lista `stackstate.allowedOrigins` nos valores do helm, ou passando `--set stackstate.allowedOrigins={"https://<rancher-url>"}` para o comando de implantação.
* O SUSE Observability não é acessível a partir do navegador. Por exemplo, o certificado raiz não foi instalado.