= Guia de execução inicial
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hospedado

== Visão Geral

Esta página fornece todas as informações necessárias para instalar e executar o SUSE Observability.

== Instruções de instalação

[tabs]
====
Kubernetes::
+
--
Instale o SUSE Observability no xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Instale o SUSE Observability no xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Endereço e porta

[tabs]
====
Kubernetes::
+
--
Para acessar a interface do usuário do SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Ative um port-forward].
. Acesse a interface do usuário do SUSE Observability em: https://localhost:8080
--

OpenShift::
+
--
Para acessar a interface do usuário do SUSE Observability:

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Ative um port-forward].
. Acesse a interface do usuário do SUSE Observability em: https://localhost:8080
--
====

== Nome de usuário e senha padrão

[tabs]
====
Kubernetes::
+
--
O SUSE Observability é configurado por padrão com a seguinte conta de administrador:

* *nome de usuário:* `admin`
* *Senha:* Definido durante a instalação. Isso é coletado pelo script `generate_values.sh` e armazenado em formato de hash MD5 em `values.yaml`
--

OpenShift::
+
--
O SUSE Observability é configurado por padrão com a seguinte conta de administrador:

* *nome de usuário:* `admin`
* *Senha:* Definido durante a instalação. Isso é coletado pelo script `generate_values.sh` e armazenado em formato de hash MD5 em `values.yaml`
--
====

== Solução de problemas

Se você encontrar algum problema durante a instalação do SUSE Observability ou na primeira execução, consulte o xref:/setup/install-stackstate/troubleshooting.adoc[guia de solução de problemas da instalação do SUSE Observability].

== Próximas etapas

Uma vez que você tenha o SUSE Observability em funcionamento, pode começar a configurar integrações

* xref:/k8s-quick-start-guide.adoc[Instale StackPacks para integrar com sistemas externos]
* xref:/use/views/k8s-views.adoc[Explore seu cluster Kubernetes]
