= Borrar datos almacenados
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability autoalojada

Los datos en SUSE Observability se dividen en cuatro conjuntos diferentes:

* Datos de Elasticsearch
* Datos de Kafka Topic
* Datos de StackGraph
* Datos de métricas

Con esta cantidad de datos para almacenar, es importante tener los medios para gestionarlos. Hay un período de retención de datos estándar de 30 días establecido en SUSE Observability. Esto se puede configurar según sus necesidades utilizando la CLI de SUSE Observability. Descubre más sobre xref:/setup/data-management/data_retention.adoc[retención de datos de SUSE Observability].

== Borrar datos manualmente

Para borrar datos almacenados en SUSE Observability que se ejecuta en Kubernetes, se recomienda realizar una instalación limpia:

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Desinstalar SUSE Observability]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Eliminar todos los PVC]
. Instalar SUSE Observability de nuevo utilizando la misma configuración que antes, en xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] o xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
