= Authentifizierungsoptionen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Out of the box ist SUSE Observability mit xref:/setup/security/authentication/file.adoc[einzelner Passwortauthentifizierung] über den Administrator und einem zufällig generierten Passwort xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[konfiguriert, das während der Installation eingerichtet wurde]. Dies authentifiziert Benutzer mit einem einfachen Geheimnis auf dem Server. Allerdings ist dies keine produktionsbereite Konfiguration.

Für bessere Sicherheit kann SUSE Observability so konfiguriert werden, dass genau eines der folgenden Authentifizierungsmechanismen verwendet wird (anstatt des Standard-Administrators):

* xref:/setup/security/authentication/single_password.adoc[Einzelnes Passwort]
* xref:/setup/security/authentication/file.adoc[Dateibasiert]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (eine spezialisierte Version von OIDC)]

[NOTE]
====
Die Authentifizierungskonfiguration ist Teil des Helm-Charts, Änderungen lösen automatisch einen Neustart der Pods aus, die dies erfordern.
====


== Benutzerrollen

Wenn ein Benutzer authentifiziert wurde, werden die Berechtigungen für diesen Benutzer normalerweise basierend auf den Rollen, die der Benutzer hat, zugewiesen. Die Dokumentation für die spezifischen Authentifizierungsmechanismen enthält auch Beispiele, wie die Rollen oder Gruppen aus den externen Systemen den 4 Standardrollen von SUSE Observability zugeordnet werden können:

* *Gast* - kann Informationen sehen, aber keine Änderungen vornehmen.
* *Kubernetes Troubleshooter* - kann alle Informationen sehen und Monitore sowie Metrik-Konfigurationen sehen und ändern.
* *Power User* - kann alle Konfigurationen sehen und ändern sowie StackPacks installieren.
* *Administrator* - kann den Inhalt von SUSE Observability sehen und ändern. Zum Beispiel, alle Konfigurationen sehen, StackPacks installieren, Benutzerberechtigungen gewähren und widerrufen sowie (neue Versionen von) StackPacks hochladen.

Bei der Entscheidung über die Rollen, die Ihren Benutzern zugewiesen werden sollen, wird dringend empfohlen, nur eine kleine Gruppe von Plattform-Administratoren und Administratoren zu haben. Zum Beispiel nur die Ingenieure, die für die Installation von SUSE Observability und die erste Konfiguration verantwortlich sind. Administratoren können den Zugriff auf SUSE Observability verwalten und entscheiden, welche StackPacks verwendet werden können. Sie können die Installation von StackPacks und andere Feinabstimmungen der Konfiguration an eine größere Anzahl von Benutzern mit der Rolle des Power Users delegieren. Plattform-Administratoren können die Datenbank leeren, die Datenspeicherungseinstellungen ändern, Protokolle anzeigen und andere Aufgaben zur Plattformverwaltung durchführen.

Es ist auch möglich, weitere Rollen hinzuzufügen. Siehe die Seite xref:/setup/security/rbac/rbac_roles.adoc[Rollen (RBAC)] und die anderen xref:/setup/security/rbac/README.adoc[RBAC-Dokumentationsseiten].
