= Einzelnes Passwort
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Selbst gehostet

Out of the box ist {stackstate-product-name} mit einer einzigen Passwortkonfiguration ausgestattet, xref:/k8s-suse-rancher-prime.adoc#_installation[die während der Installation eingerichtet wurde]. Dies authentifiziert Benutzer mit einem einzelnen Passwort, das während der Installation angegeben werden muss. 

Dies ist der einfachste Weg, um mit {stackstate-product-name} zu beginnen, aber für die Produktion wird eine der anderen xref:/setup/security/authentication/authentication_options.adoc[Authentifizierungsoptionen] empfohlen.

== Holen Sie das Passwort aus einem externen Geheimnis

Wenn das Standardpasswort aus einem externen Geheimnis stammen soll, folgen Sie xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[diesen Schritten], fügen Sie jedoch die folgenden Daten ein:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

Die Passwortkodierung kann eine der folgenden sein:
* Für ein Klartextpasswort geben Sie an: `$plain$your-password` (`$plain$` ist ein Präfix, das Klartext angibt)
* Für ein bcrypted Passwort geben Sie an: `bcrypt-hashed-password`. Das Erstellen eines bcrypted Hashes des Passworts kann mit `htpasswd -bnBC 10 "" <password> | tr -d ':\n'` erfolgen.

== Siehe auch

* xref:/setup/security/authentication/authentication_options.adoc[Authentifizierungsoptionen]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Berechtigungen für vordefinierte {stackstate-product-name} Rollen]
* xref:/setup/security/rbac/rbac_roles.adoc[RBAC-Rollen erstellen]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Externe Geheimnisse]
