= Références de métriques 
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: SUSE Observability

== Présentation

Cette page définit les métriques courantes liées à Kubernetes collectées par SUSE Observability et explique comment elles sont calculées.

=== utilisation_mémoire_conteneur

[horizontal]
Nom:: `container_memory_usage`
Type:: indicateur
Unité:: octets
Source:: Lecture directe à partir de la hiérarchie cgroup du conteneur.

[cols="1,3"]
|===
|version cgroup | Fichier source

|v1 | `memory.usage_in_bytes`
|v2 | `memory.current`
|===

Résumé:: La quantité totale de mémoire actuellement utilisée par le cgroup et ses descendants. Ceci est une somme qui inclut la mémoire anonyme (RSS), le cache de pages et la mémoire du noyau Linux. Utilisez l'une des métriques suivantes pour obtenir plus de détails sur une zone mémoire spécifique.

=== container_memory_kernel

[horizontal]
Nom:: `container_memory_kernel`
Type:: indicateur
Unité:: octets
Source:: Lecture directe à partir de la hiérarchie cgroup du conteneur.

[cols="1,3"]
|===
|version cgroup | Fichier source

|v1 | `memory.kmem.usage_in_bytes`
|v2 | `memory.stat` -> `kernel` champ à l'intérieur du fichier
|===
Résumé:: Montant total de la mémoire du noyau Linux, y compris (pile du noyau, tables de pages, percpu, vmalloc, slab)

=== utilisation_mémoire_rss_conteneur

[horizontal]
Nom:: `container_memory_rss`
Type:: indicateur
Unité:: octets
Source:: Lecture directe à partir de la hiérarchie cgroup du conteneur.

[cols="1,3"]
|===
|version cgroup | Fichier source

|v1 | `memory.stat` -> `total_rss` champ à l'intérieur du fichier
|v2 | `memory.stat` -> `anon` champ à l'intérieur du fichier
|===
Résumé:: La taille de l'ensemble résident (RSS) de la mémoire anonyme. Ceci est la mémoire non associée à un fichier (tas et pile) utilisée activement par les processus au sein du cgroup. Cette valeur reflète souvent le véritable "ensemble de travail" de l'application. 

=== container_memory_cache

[horizontal]
Nom:: `container_memory_cache`
Type:: indicateur
Unité:: octets
Source:: Lecture directe à partir de la hiérarchie cgroup du conteneur.

[cols="1,3"]
|===
|version cgroup | Fichier source

|v1 | `memory.stat` -> `total_cache` champ à l'intérieur du fichier
|v2 | `memory.stat` -> `file` champ à l'intérieur du fichier
|===
Résumé:: Le cache de pages (mémoire utilisée pour mettre en cache les données du système de fichiers, y compris tmpfs et la mémoire partagée).
