= Solução de problemas de notificações
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Quando um canal de notificação falha ao enviar notificações, a visão geral de notificações mostrará um status de erro. Para inspecionar os erros:

. Clique na notificação
. O topo da página mostra um banner com um resumo dos erros
. Role para baixo até os canais, clique no link "erro" para o(s) canal(is) afetado(s) para abrir os detalhes do erro.

== Erros comuns

=== Slack

Os erros do Slack geralmente contêm um código de erro:

* `token_revoked`, `token_expired` ou `missing_scope`: Esses códigos de erro indicam todos um problema com a autorização do SUSE Observability para enviar mensagens ao Slack. Para resolver isso, recrie o canal para reautorizar o SUSE Observability com o Slack, de modo que todas as permissões necessárias sejam concedidas.
* Para outros códigos de erro, veja https://api.slack.com/automation/cli/errors[códigos de erro da API do Slack].

=== HTTP

A maioria dos canais, especificamente o webhook, espera uma resposta HTTP com status 200 OK. Outras respostas são consideradas um erro. Erros HTTP contêm uma mensagem, geralmente curta, e o código de status que foi recebido em vez de 200 OK.

Verifique se quaisquer URLs e tokens configurados estão corretos e, no caso do webhook, se as requisições POST estão sendo tratadas corretamente e retornam uma resposta 200 OK.

=== Outros

Caso o erro seja do tipo "Outro", é muito provável que o SUSE Observability não consiga nem mesmo se conectar ao serviço externo ou webhook. Verifique se a URL está correta, pode ser resolvida e pode ser acessada pelo SUSE Observability.
