= OpenMetrics
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Übersicht

Der SUSE Observability Agent V2 kann so konfiguriert werden, dass er Metriken von einem OpenMetrics-Endpunkt abruft und diese an SUSE Observability überträgt.

== Einrichtung

=== Installation

Die OpenMetrics-Prüfung ist im [Agent V2 StackPack] enthalten.

=== Konfiguration

Um die OpenMetrics-Integration zu aktivieren und mit dem Sammeln von Metrikdaten von einem OpenMetrics-Endpunkt zu beginnen, muss die OpenMetrics-Prüfung auf dem SUSE Observability Agent V2 konfiguriert werden. Die Konfiguration der Prüfung liefert alle Details, die erforderlich sind, damit der Agent eine Verbindung zu Ihrem OpenMetrics-Endpunkt herstellen und die verfügbaren Metriken abrufen kann.

[tabs]
====
Kubernetes, OpenShift::
+
--

. Stellen Sie den Agenten in Ihrem Kubernetes- oder OpenShift-Cluster bereit.
. Fügen Sie die folgenden Annotationen hinzu, wenn Sie einen Pod starten, der Metriken über einen OpenMetrics-Endpunkt bereitstellt. Fügen Sie Folgendes hinzu:
 ** **+++<CONTAINER_NAME>+++** - der Name des Containers, der die OpenMetrics bereitstellt. Es ist möglich, mehrere Endpunkte in einem einzigen Pod zu verarbeiten (deshalb gibt es eine Liste im JSON).+++</CONTAINER_NAME>+++
 ** *prometheus_url* - der Pfad (oft nur `metrics`) und der Port, an dem der OpenMetrics-Endpunkt bereitgestellt wird.
 ** *namespace* - alle hier gesammelten Metriken erhalten dies als durch Punkte getrennten Präfix.
 ** *metrics* - verwenden Sie `["*"]`, um alle verfügbaren Metriken zu sammeln. Es ist auch möglich, eine Liste von Metriken anzugeben, die abgerufen werden sollen. Dies sollte entweder eine Zeichenfolge sein, die den Metriknamen darstellt, oder eine Zuordnung, um die Metrik umzubenennen``<EXPOSED_METRIC>:<SENT_METRIC>``
+
[,yaml]
----
 ...
 metadata:
   annotations:
     ad.stackstate.com/<CONTAINER_NAME>.check_names: '["openmetrics"]'
     ad.stackstate.com/<CONTAINER_NAME>.init_configs: '[{}]'
     ad.stackstate.com/<CONTAINER_NAME>.instances: |
       [
         {
           "prometheus_url": "http://%%host%%:<METRICS_PORT>/<METRICS_PATH>",
           "namespace": "<METRICS_NAMESPACE>",
           "metrics": ["*"]
         }
       ]
 ...
 # This already exists in the pod spec, the container name needs to match the container that is exposing the openmetrics endpoint
 spec:
   containers:
    - name: <CONTAINER_NAME>
 ...
----
. Sie können auch optionale Konfiguration und Filter hinzufügen:
 ** *prometheus_metrics_prefix* - Präfix, das den bereitgestellten OpenMetrics-Metriken hinzugefügt werden soll.
 ** *health_service_check* - senden Sie einen Service-Check `<NAMESPACE>.prometheus.health`, der den Status des OpenMetrics-Endpunkts meldet. Standard `true`.
 ** *label_to_hostname* - überschreiben Sie den Hostnamen mit dem Wert eines Labels.
 ** *label_joins* - zielen Sie auf eine Metrik ab und rufen Sie deren Label über eine 1:1-Zuordnung ab.
 ** *labels_mapper* - benennen Sie Labels um. Das Format ist `<LABEL_TO_RENAME>: <NEW_LABEL_NAME>`.
 ** *type_overrides* - überschreiben Sie einen Typ im OpenMetrics-Payload oder typisieren Sie eine untypisierte Metrik (diese würden standardmäßig ignoriert werden). Unterstützte `<METRIC_TYPE>` sind `gauge`, `count` und `rate`. Das Format ist `<METRIC_NAME>: <METRIC_TYPE>`.
 ** *tags* - Liste von Tags, die an jede Metrik, jedes Ereignis und jeden Service-Check angehängt werden, die von dieser Integration ausgegeben werden.
 ** *send_histograms_buckets* - senden Sie die Histogramm-Buckets. Standard `true`.
 ** *send_monotonic_counter* - setzen Sie auf `true`, um Zähler in eine Rate umzuwandeln (beachten Sie, dass zwei Durchläufe erforderlich sind, um das erste Ergebnis zu erzeugen). Setzen Sie auf `false`, um Zähler als monotonen Zähler zu senden. Standard `true`.
 ** *exclude_labels* - Liste von Labels, die ausgeschlossen werden sollen.
 ** *prometheus_timeout* - setzen Sie ein Timeout für die OpenMetrics-Abfrage.
 ** *ssl_cert* - Wenn Ihr OpenMetrics-Endpunkt gesichert ist, geben Sie den Pfad zum Zertifikat an und spezifizieren Sie den privaten Schlüssel im `ssl_private_key`-Parameter oder geben Sie den Pfad zu einer Datei an, die sowohl das Zertifikat als auch den privaten Schlüssel enthält.
 ** *ssl_private_key* - erforderlich, wenn das in `ssl_cert` verlinkte Zertifikat den privaten Schlüssel nicht enthält. Beachten Sie, dass der private Schlüssel Ihres lokalen Zertifikats unverschlüsselt sein muss.
 ** *ssl_ca_cert* - der Pfad zur vertrauenswürdigen CA, die zur Erstellung benutzerdefinierter Zertifikate verwendet wird.
 ** *extra_headers* - ein Wörterbuch, das HTTP-Headernamen ihren entsprechenden Werten zuordnet, die in Abfragen an den OpenMetrics-Endpunkt gesendet werden. Die Werte können dynamisch Umgebungsvariablen mit der `%%env_VARIABLE%%` Syntax einbeziehen. Zum Beispiel ersetzt `"Authorization: Bearer %%env_TOKEN%%"` automatisch den Wert der `TOKEN` Umgebungsvariable.
. Warten Sie, bis der Agent Daten vom OpenMetrics-Endpunkt gesammelt hat und sie an SUSE Observability sendet.

--
====

== Gesammelte Daten

=== Metriken

Standardmäßig werden alle Metriken vom angegebenen OpenMetrics-Endpunkt abgerufen. Um die Leistung zu optimieren, werden maximal 2000 Metriken abgerufen. Wenn der Check versucht, mehr als 2000 Metriken abzurufen, fügen Sie einen `metrics` Filter zur <<_configuration,Konfiguration>> hinzu, um sicherzustellen, dass alle wichtigen Metriken innerhalb des Limits abgerufen werden können.

Abgerufene Metriken werden nicht automatisch den Topologieelementen zugeordnet, können jedoch mit dem xref:/use/metrics/k8sTs-explore-metrics.adoc[Telemetrieinspektor] durchsucht und gegebenenfalls xref:/use/metrics/k8s-add-charts.adoc[über eine Metrikbindung zu Komponenten hinzugefügt] werden.

=== Ereignisse

Die OpenMetrics-Integration ruft keine Ereignisdaten ab.

=== Spuren

Die OpenMetrics-Integration ruft keine Trace-Daten ab.
