= Referencias de métricas 
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-11-07
:page-revdate: {revdate}
:description: SUSE Observability

== Descripción general

Esta página define métricas comunes relacionadas con Kubernetes recopiladas por SUSE Observability y explica cómo se calculan.

=== container_memory_usage

[horizontal]
Nombre:: `container_memory_usage`
Tipo:: medidor
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|versión de cgroup | Archivo de origen

|v1 | `memory.usage_in_bytes`
|v2 | `memory.current`
|===

Resumen:: La cantidad total de memoria que está siendo utilizada actualmente por el cgroup y sus descendientes. Esta es una suma que incluye Memoria Anónima (RSS), caché de páginas y Memoria del núcleo de Linux. Utiliza una de las siguientes métricas para obtener más detalles sobre un área de memoria específica.

=== container_memory_kernel

[horizontal]
Nombre:: `container_memory_kernel`
Tipo:: medidor
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|versión de cgroup | Archivo de origen

|v1 | `memory.kmem.usage_in_bytes`
|v2 | `memory.stat` -> `kernel` campo dentro del archivo
|===
Resumen:: Cantidad total de memoria del núcleo de Linux, incluyendo (kernel_stack, pagetables, percpu, vmalloc, slab)

=== container_memory_rss

[horizontal]
Nombre:: `container_memory_rss`
Tipo:: medidor
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|versión de cgroup | Archivo de origen

|v1 | `memory.stat` -> `total_rss` campo dentro del archivo
|v2 | `memory.stat` -> `anon` campo dentro del archivo
|===
Resumen:: El Tamaño del Conjunto Residente (RSS) de Memoria Anónima. Esta es la memoria no respaldada por archivos (heap y stack) que utilizan activamente los procesos dentro del cgroup. Este valor a menudo refleja el verdadero "conjunto de trabajo" de la aplicación. 

=== container_memory_cache

[horizontal]
Nombre:: `container_memory_cache`
Tipo:: medidor
Unidad:: bytes
Fuente:: Lectura directa de la jerarquía cgroup del contenedor.

[cols="1,3"]
|===
|versión de cgroup | Archivo de origen

|v1 | `memory.stat` -> `total_cache` campo dentro del archivo
|v2 | `memory.stat` -> `file` campo dentro del archivo
|===
Resumen:: La caché de páginas (memoria utilizada para almacenar en caché datos del sistema de archivos, incluyendo tmpfs y memoria compartida).
