= OpenMetrics
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Descripción general

El Agente de Observabilidad de SUSE V2 se puede configurar para recuperar métricas de un endpoint OpenMetrics y enviarlas a SUSE Observability.

== Configuración

=== Instalación

La verificación de OpenMetrics está incluida en el [Agent V2 StackPack].

=== Configuración

Para habilitar la integración de OpenMetrics y comenzar a recopilar datos de métricas de un endpoint OpenMetrics, la verificación de OpenMetrics debe configurarse en el Agente de Observabilidad de SUSE V2. La configuración de la verificación proporciona todos los detalles necesarios para que el Agente se conecte a su endpoint OpenMetrics y recupere las métricas disponibles.

[tabs]
====
Kubernetes, OpenShift::
+
--

. Despliegue el Agente en su clúster de Kubernetes o OpenShift.
. Añada las anotaciones a continuación al lanzar un pod que exponga métricas a través de un endpoint OpenMetrics. Añada lo siguiente:
 ** **+++<CONTAINER_NAME>+++** - el nombre del contenedor que expone OpenMetrics. Es posible procesar múltiples endpoints en un solo pod (por eso hay una lista en el JSON).+++</CONTAINER_NAME>+++
 ** *prometheus_url* - la vía (a menudo solo `metrics`) y el puerto en el que se expone el endpoint OpenMetrics.
 ** *namespace* - todas las métricas recopiladas aquí tendrán esto como un prefijo separado por puntos.
 ** *metrics* - use `["*"]` para recopilar todas las métricas disponibles. También es posible especificar una lista de métricas a ser recuperadas. Esto debe ser una cadena que represente el nombre de la métrica o un mapeo para renombrar la métrica``<EXPOSED_METRIC>:<SENT_METRIC>``
+
[,yaml]
----
 ...
 metadata:
   annotations:
     ad.stackstate.com/<CONTAINER_NAME>.check_names: '["openmetrics"]'
     ad.stackstate.com/<CONTAINER_NAME>.init_configs: '[{}]'
     ad.stackstate.com/<CONTAINER_NAME>.instances: |
       [
         {
           "prometheus_url": "http://%%host%%:<METRICS_PORT>/<METRICS_PATH>",
           "namespace": "<METRICS_NAMESPACE>",
           "metrics": ["*"]
         }
       ]
 ...
 # This already exists in the pod spec, the container name needs to match the container that is exposing the openmetrics endpoint
 spec:
   containers:
    - name: <CONTAINER_NAME>
 ...
----
. También puede añadir configuración y filtros opcionales:
 ** *prometheus_metrics_prefix* - prefijo a añadir a las métricas OpenMetrics expuestas.
 ** *health_service_check* - enviar una verificación de servicio `<NAMESPACE>.prometheus.health` informando sobre la salud del endpoint OpenMetrics. Por defecto `true`.
 ** *label_to_hostname* - sobrescribir el nombre de host con el valor de una etiqueta.
 ** *label_joins* - dirigirse a una métrica y recuperar su etiqueta a través de un mapeo 1:1.
 ** *labels_mapper* - renombrar etiquetas. El formato es `<LABEL_TO_RENAME>: <NEW_LABEL_NAME>`.
 ** *type_overrides* - sobrescribir un tipo en el payload de OpenMetrics o asignar un tipo a una métrica sin tipo (estas se ignoran por defecto). Los `<METRIC_TYPE>` soportados son `gauge`, `count` y `rate`. El formato es `<METRIC_NAME>: <METRIC_TYPE>`.
 ** *tags* - lista de etiquetas para adjuntar a cada métrica, evento y verificación de servicio emitidos por esta integración.
 ** *send_histograms_buckets* - enviar el bucket de histogramas. Por defecto `true`.
 ** *send_monotonic_counter* - establecer en `true` para convertir contadores a una tasa (ten en cuenta que se requieren dos ejecuciones para producir el primer resultado). Establecer en `false` para enviar contadores como un contador monótono. Por defecto `true`.
 ** *exclude_labels* - lista de etiquetas a excluir.
 ** *prometheus_timeout* - establecer un tiempo de espera para la consulta de OpenMetrics.
 ** *ssl_cert* - Si tu endpoint de OpenMetrics está asegurado, introduce la ruta al certificado y especifica la clave privada en el parámetro `ssl_private_key`, o da la ruta a un archivo que contenga tanto el certificado como la clave privada.
 ** *ssl_private_key* - requerido si el certificado vinculado en `ssl_cert` no incluye la clave privada. Ten en cuenta que la clave privada de tu certificado local debe estar sin cifrar.
 ** *ssl_ca_cert* - la ruta a la CA de confianza utilizada para generar certificados personalizados.
 ** *extra_headers* - un diccionario que mapea los nombres de los encabezados HTTP a sus valores correspondientes para enviar en consultas al endpoint de OpenMetrics. Los valores pueden incluir dinámicamente variables de entorno utilizando la sintaxis `%%env_VARIABLE%%`. Por ejemplo, `"Authorization: Bearer %%env_TOKEN%%"` sustituye automáticamente el valor de la variable de entorno `TOKEN`.
. Espera a que el Agente recoja datos del endpoint de OpenMetrics y los envíe a SUSE Observability.

--
====

== Datos recogidos

=== Métricas

Por defecto, todas las métricas se recuperan del endpoint de OpenMetrics especificado. Para optimizar el rendimiento, se recuperará un máximo de 2000 métricas. Si la comprobación intenta recuperar más de 2000 métricas, añade un filtro `metrics` a la <<_configuration,configuración>> para asegurar que todas las métricas importantes se puedan recuperar dentro del límite.

Las métricas recuperadas no se mapearán automáticamente a los elementos de topología, pero se pueden explorar utilizando el xref:/use/metrics/k8sTs-explore-metrics.adoc[inspector de telemetría] y eventualmente xref:/use/metrics/k8s-add-charts.adoc[añadidas a componentes a través de un enlace de métrica].

=== Eventos

La integración de OpenMetrics no recupera ningún dato de eventos.

=== Trazas

La integración de OpenMetrics no recupera datos de trazas.
