= IDs
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Übersicht

Identifikatoren werden in SUSE Observability verwendet, um Objekte wie Topologieelemente (Komponenten und Beziehungen) sowie Funktionen zu identifizieren. Diese Seite beschreibt die verschiedenen Arten von Identifikatoren, die für Topologieelemente verwendet werden, und wie globale Scope-Identifikatoren in SUSE Observability strukturiert sind.

== Topologieidentifikatoren

Topologieelemente verwenden zwei Arten von Identifikatoren in SUSE Observability:

* *Integrationsbereichsidentifikatoren* - verwendet zur Identifizierung von Komponenten und Beziehungen innerhalb einer Integration. Jede Komponente oder Beziehung hat nur einen Integrationsbereichsidentifikator. Der Identifikator ist willkürlich, muss jedoch innerhalb des Integrationsbereichs selbst konsistent sein.
* *Globale Scope-Identifikatoren* - verwendet zum Zusammenführen von Komponenten zwischen Integrationen, beispielsweise ServiceNow und dem SUSE Observability Agent. Jede Komponente kann mehrere globale Scope-Identifikatoren haben, während Beziehungen keine globalen Identifikatoren haben. Sie werden von SUSE Observability zugewiesen und im Einklang mit der xref:/configure/topology/identifiers.adoc#_global_scope_identifiers[SUSE Observability globalen Identifikator-Konvention] formatiert.

Das folgende Codebeispiel zeigt eine Komponente mit beiden Arten von Identifikatoren.

* Integrationsbereichsidentifikator - `this-host-unique-identifier`
* Globaler Scope-Identifikator - `urn:host:/this-host-fqdn`


[,text]
----
self.component("this-host-unique-identifier", "Host", {
    "name": "this-host",
    "domain": "Webshop",
    "layer": "Machines",
    "identifiers": ["urn:host:/this-host-fqdn"],
    "labels": ["host:this-host", "region:eu-west-1"],
    "environment": "Production"
})
----


== SUSE Observability Agent-Identifikatoren

Die globalen Scope-Identifikatoren, die vom SUSE Observability Agent verwendet werden, um synchronisierte Topologieelemente zu identifizieren, sind in der folgenden Tabelle aufgeführt.

|===
| Ressourcentyp | URN-Identifikatorformat

| Host
| `urn:host:/[hostName]`

| Vorgang
| `urn:process:/[hostName]:[pid]:[createTime]`

| Container
| `urn:container:/[hostName]:[containerId]`

| Dienst mit Traces entdeckt
| `urn:service:/[serviceName]`

| Dienstinstanz mit Traces entdeckt
| `urn:service-instance:/[serviceName]:/[hostName]`
|===

Siehe die xref:/configure/topology/identifiers.adoc#_stackstate_agent[Beispiel-URN-Identifikatoren im globalen Scope vom SUSE Observability Agent].

== Globale Scope-Identifikatoren

Wenn SUSE Observability Komponenten mit übereinstimmenden globalen Scope-Identifikatoren aus verschiedenen externen Quellen erhält, werden die Komponenten und ihre Eigenschaften (Labels, Streams, Checks) zu einer einzigen Komponente zusammengeführt. Dies ermöglicht es, Daten aus verschiedenen Quellen zu einem einheitlichen Bild einer IT-Landschaft zu kombinieren.

Globale Scope-Identifikatoren in SUSE Observability sind eine global eindeutige URN, die der folgenden Konvention entspricht:

[,text]
----
urn:<prefix>:<type-name>:<free-form>
----

Beachten Sie, dass nicht alle Zeichen in einem URN-Bezeichner erlaubt sind. Sie können Ihre Bezeichner mit dem folgenden URN-Regulärausdruck überprüfen:

[,text]
----
^urn:[a-z0-9][a-z0-9-]{0,31}:[a-z0-9()+,\-.:=@;$_!*'%/?#]+$
----

Das Format der `<prefix>` und `<type-name>:<free-form>` Segmente wird im Folgenden beschrieben.

=== Präfix

Das `prefix` Segment ist ein erforderlicher Teil eines globalen Bezeichners. Es benennt den Geltungsbereich, zu dem der Bezeichner gehört, und wird ausschließlich zu organisatorischen Zwecken verwendet.

[NOTE]
====
Wenn das Präfix einen StackPack-Namen enthält, wird das Objekt unter der Kontrolle dieses StackPacks stehen. Das bedeutet, dass das Objekt deinstalliert wird, wenn das StackPack deinstalliert wird.
====


Anerkannte URN-Präfixe sind:

* `stackpack:<name>` - Objekte, die zu StackPacks gehören.
* `stackpack:<name>:shared` - Objekte, die zwischen Instanzen eines StackPacks geteilt werden.
* `stackpack:<name>:instance:{{instanceId}}`- Objekte, die zu einer bestimmten Instanz eines StackPacks gehören, wobei `{{instanceId}}` ein Handlebar ist, der die während des Installationsprozesses des StackPacks für jede spezifische Instanz bereitgestellte ID zurückgibt.
* `system:auto` - Objekte, die vom System erstellt wurden und zu keinen spezifischen StackPacks gehören.

=== Typ-Name und Freiform

Der Bezeichner wird eindeutig durch die `<type-name>:<free-form>` Segmente identifiziert.

* `<type-name>` entspricht dem Domänenobjekttyp des Objekts, dem der Bezeichner zugewiesen ist (nicht groß-/kleinschreibungsempfindlich).
* `<free-form>` ist willkürlich, muss jedoch für den Typ eindeutig sein. Das Format des freien Segments wird vom Benutzer festgelegt. Es muss nicht mit dem Namen des Objekts übereinstimmen (sofern vorhanden) und kann selbst aus mehreren Segmenten bestehen.

== Beispiel-Identifikatoren

=== Gemeinsamer StackPack

Beispiel-URN-Identifikatoren im globalen Geltungsbereich aus dem gemeinsamen StackPack. Die Objekte werden deinstalliert, wenn der gemeinsame StackPack deinstalliert wird.

* Komponententyp Server:
 ** `urn:stackpack:common:component-type:server`

=== SUSE Observability Agent

Beispiel-URN-Identifikatoren im globalen Geltungsbereich aus dem SUSE Observability Agent.

* Host:
 ** `urn:host:/example.org`
* Vorgang:
 ** `urn:process:/db.infra.company.org:161841:1602158335000`
* Container:
 ** `urn:container:/compnode5.k8s.example.org:8b18c68a820904c55b4909d7f5a9a52756d45e866c07c92bf478bcf6cd240901`
* Dienst mit Traces entdeckt:
 ** `urn:service:/prod-db`
* Dienstinstanz mit Traces entdeckt:
 ** `urn:service-instance:/prod-db:/main.example.org`

=== Weitere StackPacks

Beispiel-URN-Identifikatoren im globalen Geltungsbereich aus verschiedenen StackPacks. Die Objekte werden deinstalliert, wenn der benannte StackPack deinstalliert wird.

* Überprüfungsfunktion AWS Event Run State, die über AWS StackPack-Instanzen geteilt wird:
 ** `urn:stackpack:aws:shared:check-function:aws-event-run-state`
* Komponententyp cmdb_ci_netgear im ServiceNow StackPack:
 ** `urn:stackpack:servicenow:componenttype:cmdb_ci_netgear`
