= Fehlerbehebung von Benachrichtigungen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Wenn ein Benachrichtigungskanal keine Benachrichtigungen senden kann, zeigt die Benachrichtigungsübersicht einen Fehlerstatus an. Um die Fehler zu überprüfen:

. Klicken Sie auf die Benachrichtigung
. Oben auf der Seite wird ein Banner mit einer Zusammenfassung der Fehler angezeigt
. Scrollen Sie nach unten zu den Kanälen und klicken Sie auf den 'Fehler'-Link des betroffenen Kanals bzw. der betroffenen Kanäle, um die Fehlerdetails zu öffnen.

== Übliche Fehler

=== Slack

Slack-Fehler enthalten normalerweise einen Fehlercode:

* `token_revoked`, `token_expired` oder `missing_scope`: Diese Fehlercodes weisen alle auf ein Problem mit der Autorisierung von SUSE Observability hin, um Nachrichten an Slack zu senden. Um diese zu beheben, erstellen Sie den Kanal neu, um SUSE Observability mit Slack erneut zu autorisieren, sodass alle erforderlichen Berechtigungen erteilt werden.
* Für andere Fehlercodes siehe https://api.slack.com/automation/cli/errors[Slack API-Fehlercodes].

=== HTTP

Die meisten Kanäle, insbesondere der Webhook, erwarten eine HTTP-Antwort mit dem Status 200 OK. Andere Antworten werden als Fehler betrachtet. HTTP-Fehler enthalten eine, normalerweise kurze, Nachricht und den Statuscode, der anstelle von 200 OK empfangen wurde.

Überprüfen Sie, ob alle konfigurierten URLs und Token korrekt sind und, im Fall des Webhooks, dass POST-Anfragen ordnungsgemäß verarbeitet werden und eine 200 OK-Antwort zurückgeben.

=== Sonstiges

Falls der Fehler vom Typ "Sonstiges" ist, kann SUSE Observability höchstwahrscheinlich nicht einmal eine Verbindung zum externen Dienst oder Webhook herstellen. Überprüfen Sie, ob die URL korrekt ist, aufgelöst werden kann und von SUSE Observability erreicht werden kann.
