= Repeat States
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}
:description: SUSE Observability

== Visão Geral

Esta página descreve as mensagens JSON exatas que podem ser enviadas para o modelo de consistência do Repeat States de sincronização de saúde.

== Propriedade JSON: "health"

A saúde pode ser enviada para a API do SUSE Observability Receiver usando a propriedade `"health"` do objeto JSON xref:/configure/health/send-health-data/send-health-data.adoc#_common_json_object[comum].

[tabs]
====
Exemplo de saúde `repeat_states` JSON::
+
--

[,javascript]
----
   "apiKey":"<STACKSTATE_RECEIVER_API_KEY>",
   "collection_timestamp":1585818978,
   "internalHostname":"lnx-343242.srv.stackstate.com",
   "events":{},
   "metrics":[],
   "service_checks":[],
   "health":[
      {
        "consistency_model": "REPEAT_STATES",
        "expiry": {
          "repeat_interval_s": 50,
          "expiry_interval_s": 100
        },
        "stream": {
          "urn": "urn:health:sourceId:streamId"
          //"sub_stream_id": "subStreamId" Optional
        },
        "check_states": [
          {
            "checkStateId": "checkStateId1",
            "message": "Server Running out of disk space",
            "health": "Deviating",
            "topologyElementIdentifier": "server-1",
            "name": "Disk Usage"
          },
          {
            "checkStateId": "checkStateId2",
            "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
            "health": "critical",
            "topologyElementIdentifier": "server-2",
            "name": "Health monitor"
          }
        ]
      }
   ],
   "topologies":[]
----

--
====

Cada carga de dados de saúde do Repeat States possui os seguintes detalhes:

* *expiração* - Opcional. Uma atualização de expiração precisa ser processada antes de processar `check_states`. Isso permite que o SUSE Observability rastreie quanto tempo as verificações externas devem estar presentes no sistema se não forem enviadas novamente. Ela contém os seguintes campos como metadados de expiração:
 ** *repeat_interval_s* - Tempo em segundos. A frequência com que a fonte externa enviará dados de saúde para o SUSE Observability. O valor máximo permitido é 1800 (30 minutos).
 ** *expiry_interval_s* - Tempo em segundos. O tempo a esperar após a última atualização antes que uma verificação externa seja excluída pelo SUSE Observability se a verificação externa não for observada novamente.
* *stream* - Objeto que fornece identificação sobre quais instantâneos e `check_states` pertencem juntos. Ela contém os seguintes campos:
 ** *urn* - Fonte de dados e ID do fluxo codificados como um xref:/configure/topology/identifiers.adoc[URN] do SUSE Observability que corresponde à seguinte convenção: `urn:health:<sourceId>:<streamId>` onde `<sourceId>` é o nome da fonte de dados externa e `<streamId>` é um identificador único para o fluxo de dados de saúde.
 ** *sub_stream_id* - Optional. Identificador para um subconjunto dos dados de saúde do stream. Quando os dados do stream são distribuídos e relatados por vários agentes, isso permite ciclos de vida de instantâneos por `sub_stream_id`.
* *check_states* - Uma lista de estados de verificação. Cada estado de verificação pode ter os seguintes campos:
 ** *checkStateId* - Identificador para o estado de verificação no sistema externo
 ** *message* - Opcional. Mensagem a ser exibida na interface do SUSE Observability. Os dados serão interpretados como markdown, permitindo ter links para o sistema externo de verificação que gerou o estado de verificação externo.
 ** *health* - Um dos seguintes valores de estado de saúde do SUSE Observability: `Clear`, `Deviating`, `Critical`.
 ** *topologyElementIdentifier* - Usado para vincular o estado de verificação a um elemento de topologia do SUSE Observability.
 ** *name* - Nome do estado de verificação externo.

== Enviar saúde para o SUSE Observability

A saúde pode ser enviada em uma mensagem JSON via HTTP POST. No exemplo abaixo, um instantâneo contendo dois estados de verificação é enviado ao SUSE Observability a partir de um único sistema de monitoramento externo.

[,bash]
----
curl -X POST \
 '<STACKSTATE_RECEIVER_API_ADDRESS>' \
 -H 'Content-Type: application/json' \
 -d '{
  "collection_timestamp": 1548857167,
  "internalHostname": "local.test",
  "health": [
    {
      "consistency_model": "REPEAT_STATES",
      "expiry": {
        "repeat_interval_s": 300,
        "expiry_interval_s": 600
      },
      "stream": {
        "urn": "urn:health:sourceId:streamId"
      },
      "check_states": [
        {
          "checkStateId": "checkStateId1",
          "message": "Server Running out of disk space",
          "health": "Deviating",
          "topologyElementIdentifier": "server-1",
          "name": "Disk Usage"
        },
        {
          "checkStateId": "checkStateId2",
          "message": "Provisioning failed. [Learn more](https://www.any-link.com)",
          "health": "critical",
          "topologyElementIdentifier": "server-2",
          "name": "Health monitor"
        }
      ]
    }
  ]
}'
----
