= Über StackPacks
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet v5.1.x

== Übersicht

StackPacks erweitern die Funktionalität von SUSE Observability und bieten eine automatisierte Integration mit externen Systemen. Sie können einfach von der StackPacks-Seite in SUSE Observability installiert und deinstalliert werden.

Es gibt zwei Arten von StackPacks - Add-ons und Integrationen. Die verfügbaren StackPack-Add-ons und Integrationen finden Sie auf der *StackPacks*-Seite in der SUSE Observability Benutzeroberfläche.

== Installieren oder deinstallieren Sie ein StackPack

StackPacks können von der *StackPacks*-Seite in SUSE Observability installiert und deinstalliert werden. Vollständige Anweisungen zur Installation und Deinstallation des StackPacks sind verfügbar.

[NOTE]
====
*Hinweis:*

* Ein StackPack kann *manuelle* Installationsschritte oder die Konfiguration des externen Systems erfordern. Bitte lesen Sie die bereitgestellten Anweisungen sorgfältig.
* Wenn ein StackPack oder eine StackPack-Instanz deinstalliert wird, *werden alle über das StackPack (Instanz) empfangenen Daten aus SUSE Observability entfernt.*
* Jede (manuelle) Konfiguration oder Installation von StackPack-Komponenten in einem externen System muss möglicherweise separat deinstalliert werden.

====


=== StackPack-Instanzen

Einige StackPacks ermöglichen es Ihnen, sich mit mehreren Konten in einem externen System zu verbinden. Jedes Konto wird in einer separaten Instanz des StackPacks konfiguriert.

Zum Beispiel kann das AWS StackPack mit mehreren AWS-Konten verbunden werden und Informationen aus allen Konten in SUSE Observability kombinieren. Für jedes Konto wird eine separate SUSE Observability-Instanz mit den Informationen konfiguriert, die erforderlich sind, um Daten von diesem AWS-Konto zu empfangen.

== Ein StackPack upgraden

[CAUTION]
====
Wenn ein StackPack geupgradet wird, *werden alle Änderungen an den Konfigurationselementen dieses StackPacks überschrieben*. Für Details siehe xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[gesperrte Konfigurationselemente].
====


Wenn eine neue StackPack-Version verfügbar ist, wird eine Benachrichtigung auf der StackPack-Seite der SUSE Observability UI angezeigt, und Sie haben die Möglichkeit, die Upgrade-Details anzuzeigen und die Versionshinweise zu lesen. Wenn die neue Version ein kleines Upgrade der derzeit installierten Version ist, können Sie das StackPack auch von hier aus upgraden.

=== Neue kleine StackPack-Version

Um auf eine neue kleine Version eines StackPacks zu upgraden, klicken Sie auf *JETZT UPGRADEN* auf der StackPack-Seite in der SUSE Observability UI.

Bitte beachten Sie, dass beim Upgrade alle StackPack-Konfigurationselemente überschrieben werden. Um alle Änderungen, die an diesen vorgenommen wurden, weiterhin zu verwenden, wählen Sie beim Upgrade des StackPacks die Option *BEIBEHALTEN* der bestehenden Konfiguration. Für Details siehe xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[gesperrte Konfigurationselemente].

=== Neue große StackPack-Version

[CAUTION]
====
Wenn ein StackPack geupgradet wird, *werden alle Änderungen an den Konfigurationselementen dieses StackPacks überschrieben*. Für Details siehe xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[gesperrte Konfigurationselemente].
====


Um auf eine neue große Version eines StackPacks zu aktualisieren, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[deinstallieren und neu installieren] Sie das StackPack.

[TIP]
====

Verwenden Sie weiterhin Änderungen, die an benutzerdefinierten StackPack-Konfigurationselementen nach dem Upgrade vorgenommen wurden:

. Bevor Sie upgraden, exportieren Sie jedes benutzerdefinierte Element:
 ** Gehen Sie zur *Einstellungen*-Seite in der SUSE Observability UI.
 ** Klicken Sie auf *Export* im *...*-Menü für jedes benutzerdefinierte Element.
. Upgraden Sie das StackPack (deinstallieren und neu installieren).
. Ändern Sie die `name` und `identifier` für jedes exportierte Element:
 ** Öffnen Sie die Exportdatei in einem Texteditor.
 ** Bearbeiten Sie die obersten `name` und `identifier` Felder.
 ** Speichern Sie den Export.
. Klicken Sie auf xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Import] für die aktualisierte(n) Exportdatei(en).
. Die benutzerdefinierten Konfigurationselemente sind jetzt in SUSE Observability verfügbar und können in die neu installierten StackPack-Konfigurationselemente kopiert werden.

====


== Gesperrte Konfigurationselemente

StackPacks enthalten Konfigurationsinformationen für SUSE Observability, die installiert werden, wenn der StackPack (Instanz) installiert wird. Unter anderem könnten dies Komponenten-Vorlagen, Funktionen, Komponentenaktionen und Ansichten sein. Wenn ein StackPack geupgradet wird, *werden die Konfigurationselemente, die von der vorherigen Version des StackPacks installiert wurden, durch die der neueren Version des StackPacks überschrieben*. Das bedeutet, dass jede manuelle Änderung, die an diesen Konfigurationselementen vorgenommen wird, überschrieben wird, wenn das StackPack geupgradet wird.

Um zu verhindern, dass ein Benutzer Änderungen an Konfigurationselementen vornimmt, die von einem StackPack installiert wurden und beim Upgrade überschrieben werden, sind diese Konfigurationselemente standardmäßig *gesperrt*. Das bedeutet, dass sie vor Änderungen durch den Benutzer geschützt sind und ausdrücklich *entsperrt* werden müssen, bevor sie geändert werden können.

[TIP]
====

Sie können xref:/setup/data-management/backup_restore/configuration_backup.adoc[eine Sicherung der Konfigurationselemente erstellen]. Beachten Sie, dass der Sperrstatus der Konfigurationselemente nicht als Teil einer Konfigurationssicherung exportiert wird.
====

