= Protokollversand
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

== Agenteninstallation

=== OpenShift

Drittanbieter-Protokollversender werden auf OpenShift nicht direkt unterstützt, die Plattform bietet Optionen für die Protokollweiterleitung, die anstelle der im SUSE Observability Helm-Chart enthaltenen Promtail-Konfiguration verwendet werden.  Für detaillierte Anweisungen zur Konfiguration verweisen Sie bitte auf die Kubernetes-Stackpack-Dokumentation Ihrer laufenden SUSE Observability-Instanz.

=== Kubernetes

Die Standardkonfiguration des SUSE Observability k8s Agent Helm-Charts aktiviert den Protokollversand über die mit dem Chart bereitgestellten Helm-Werte:

[,yaml]
----
logsAgent:
  # logsAgent.enabled -- Enable / disable k8s pod log collection
  enabled: true
----

Das oben Genannte stellt sicher, dass ein Promtail-Container auf jedem Knoten bereitgestellt wird, um Protokolle zu sammeln und an SUSE Observability zu senden.  Für Bereitstellungen, bei denen es nicht wünschenswert ist, Protokolle an SUSE Observability zu versenden, setzen Sie den oben genannten Wert auf `false`.

=== Zusätzliche Promtail-Pods starten

SUSE Observability verwendet eine optimierte Konfiguration für die Protokollaufnahme, die in der Regel nicht mit zusätzlichen Anforderungen übereinstimmt.  Es ist daher nicht möglich, eine separate Konfiguration für die Protokollaufnahme an andere Zielendpunkte einzurichten; stattdessen wird empfohlen, einen zweiten Promtail-Pod zu betreiben, der diese Anforderungen eigenständig bearbeitet – getrennt von dem Promtail, der durch das Agent Helm-Chart bereitgestellt wird.
