= Limpar dados armazenados
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Auto-hospedado

Os dados no SUSE Observability estão divididos em quatro conjuntos diferentes:

* dados do Elasticsearch
* dados do Kafka Topic
* dados do StackGraph
* dados de métricas

Com essa quantidade de dados para armazenar, é importante ter meios para gerenciá-los. Há um período padrão de retenção de dados de 30 dias definido no SUSE Observability. Isso pode ser configurado de acordo com suas necessidades usando o SUSE Observability CLI. Saiba mais sobre xref:/setup/data-management/data_retention.adoc[retenção de dados do SUSE Observability].

== Limpar dados manualmente

Para limpar dados armazenados no SUSE Observability rodando no Kubernetes, é recomendado realizar uma instalação limpa:

. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_un_install_the_helm_chart[Desinstalar o SUSE Observability]
. xref:/setup/install-stackstate/kubernetes_openshift/uninstall.adoc#_remove_remaining_resources[Remover todos os PVCs]
. Instale o SUSE Observability novamente usando a mesma configuração de antes, no xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Kubernetes] ou xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_deploy_suse_observability_with_helm[OpenShift].
