= Configuration de SUSE Observability pour les notifications par e-mail
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

[CAUTION]
====
Les utilisateurs de SUSE Observability en mode SaaS peuvent utiliser les notifications par e-mail sans configuration supplémentaire. Ce guide s'applique uniquement aux installations de SUSE Observability auto-hébergées qui prévoient d'utiliser le canal de notification par e-mail.
====


Avant de pouvoir utiliser le canal de notification par e-mail dans SUSE Observability, vous devez d'abord suivre les étapes suivantes :

== Configurer SUSE Observability avec la configuration SMTP

SUSE Observability doit être configuré avec des identifiants pour se connecter au serveur SMTP. Vous pouvez le faire en ajoutant ce qui suit au fichier `values.yaml` de votre installation de SUSE Observability :

[,yaml]
----
stackstate:
  email:
    enabled: true
    sender: "<stackstate@example.com>"
    server:
      host: "<smtp.example.com>"
      auth:
        username: "<user name>"
        password: "<user password>"
----

Cela utilisera le port `587` sur le serveur SMTP et utilise la commande `STARTTLS` pour établir une connexion sécurisée. Voici toutes les autres options qui peuvent être personnalisées :

[,yaml]
----
stackstate:
  email:
    additionalProperties:
      # Add needed Java email properties for your mail server (use string values), defaults are:
      "mail.smtp.auth": "true"
      "mail.smtp.starttls.enable": "true"
    server:
      protocol: smtp
      port: 587
----

=== Utiliser un secret externe

Lorsque le nom d'utilisateur et le mot de passe ne peuvent pas être fournis dans les valeurs mais doivent provenir d'un secret externe, suivez xref:/setup/security/external-secrets.adoc#_getting_username_and_password_for_email_sending_from_an_external_secret[ces étapes]
