= Configurando o Agente de Observabilidade Kubernetes da SUSE para usar proxy nas conexões
:revdate: 2025-07-10
:page-revdate: {revdate}

O Agente de Observabilidade Kubernetes da SUSE permite que você configure as configurações de proxy HTTP ou HTTPS para as conexões que ele inicia.

== Proxy para comunicação com SUSE Observability

Para configurar o agente para usar proxy nas conexões com o backend do SUSE Observability, você pode usar a configuração do Helm.

=== Configuração do Helm

==== Via `values.yaml` arquivo

. Abra o arquivo do chart `values.yaml` do Helm.
. Localize a `global.proxy.url` configuração e especifique a URL do proxy:
+
[,yaml]
----
 global:
   proxy:
     url: "https://proxy.example.com:8080"
----

. Opcionalmente, se o proxy não tiver um certificado assinado, desative a verificação SSL definindo `global.skipSslValidation` como `true`:
+
[,yaml]
----
 global:
   skipSslValidation: true
----

==== Via flag de linha de comando

. Durante a instalação do chart do Helm, use a `--set` flag para especificar a URL do proxy:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.proxy.url="https://proxy.example.com:8080"
----

. Para desativar a validação SSL via linha de comando, use:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.skipSslValidation=true
----
