= Gerenciamento de Segredos Personalizados do k8s
:revdate: 2025-10-27
:page-revdate: {revdate}

== Visão Geral

O agente SUSE Observability suporta especificar o nome de um segredo personalizado que contém a chave da API e o token de autorização do cluster. Esse recurso é útil para usuários que desejam gerenciar seus próprios segredos e evitar a criação automática de segredos pelo Helm chart.

NOTE: *Havia um método anterior de especificar isso que agora está descontinuado, veja o xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[método descontinuado].*

== O Helm chart

=== Opções de configuração

* `global.apiKey.fromSecret`: Especifique um nome de segredo pré-existente que reside no mesmo namespace e que contém um campo `STS_API_KEY` com a chave da API.
* `global.clusterAgentAuthToken.fromSecret`: Especifique um nome de segredo pré-existente que reside no mesmo namespace e que contém um campo `STS_CLUSTER_AGENT_AUTH_TOKEN` com um token para garantir conexões entre o cluster e os agentes de nó.

=== Descrição do Comportamento

* *Criação Automática de Segredos*: Por padrão, o Helm chart requer que um `stackstate.apiKey` seja especificado e criará um segredo por conta própria. O `STS_CLUSTER_AGENT_AUTH_TOKEN` é gerado automaticamente.
* *Gerenciamento de Segredos Personalizados*: Ao substituir os campos `fromSecret`, a chave da API e o token de autorização do cluster serão retirados desses segredos.
* *Omissão Implícita*: Ao especificar que você gostaria de gerenciar seus próprios segredos, o Helm chart ignorará os valores para `stackstate.apiKey` e `stackstate.cluster.authToken`.

== Como usar no values.yaml

. *Usando Criação Automática de Segredos (Padrão)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Gerenciando Próprios Segredos*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
