= Configuração de Segredos Personalizados do k8s (Descontinuada)
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== Visão Geral

O agente SUSE Observability suporta especificar o nome de um segredo personalizado que contém a chave da API e o token de autorização do cluster. Esse recurso é útil para usuários que desejam gerenciar seus próprios segredos e evitar a criação automática de segredos pelo Helm chart.

[CAUTION]
====
*Este método de personalização de segredos está descontinuado e é incompatível com o recurso RBAC.*

Por favor, use xref:/setup/agent/k8s-custom-secrets-setup.adoc[o novo método] para utilizar segredos externos.
====


== O Helm chart

=== Opções de configuração

* `stackstate.manageOwnSecrets`: Uma flag booleana que determina se o usuário deseja gerenciar seus próprios segredos. O valor padrão é `false`.
* `stackstate.customSecretName`: (Opcional) Nome do segredo personalizado a ser criado pelo usuário. Requerido se `stackstate.manageOwnSecrets` for definido como `true`.
* `stackstate.customApiKeySecretKey`: (Opcional) Nome da chave associada à chave da API dentro do segredo personalizado. Requerido se `stackstate.manageOwnSecrets` for definido como `true`.
* `stackstate.customClusterAuthTokenSecretKey`: (Opcional) Nome da chave para o token de autorização do cluster dentro do segredo personalizado. Requerido se `stackstate.manageOwnSecrets` for definido como `true`.

=== Descrição do Comportamento

* *Criação Automática de Segredos*: Por padrão, o chart continua a criar segredos automaticamente como antes se `stackstate.manageOwnSecrets` for definido como `false`.
* *Gerenciamento de Segredos Personalizados*: Se `stackstate.manageOwnSecrets` for definido como `true`, o chart espera que o usuário forneça o nome do segredo personalizado (`stackstate.customSecretName`) juntamente com as chaves para a chave da API e para o token de autorização (`stackstate.customApiKeySecretKey` e `stackstate.customClusterAuthTokenSecretKey`, respectivamente).
* *Omissão Implícita*: Ao especificar que você gostaria de gerenciar seus próprios segredos, o Helm chart ignorará os valores para `stackstate.apiKey` e `stackstate.cluster.authToken`.
+
== Como usar no values.yaml

. *Usando Criação Automática de Segredos (Padrão)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *Gerenciando Próprios Segredos*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
