= Certificados para injeção de sidecar para rastreamento de solicitações
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

O xref:/setup/agent/k8sTs-agent-request-tracing.adoc#_enabling_the_trace_header_injection_sidecar[mecanismo de injeção de sidecar], que é ativado ao usar `--set httpHeaderInjectorWebhook.enabled=true` ao instalar o agente, cria um certificado autoassinado e utiliza um `ClusterRole` que concede acesso de gravação aos objetos `Secret` e `MutatingWebhookConfiguration` no cluster Kubernetes.

Se por motivos de segurança não for desejável criar `ClusterRoles` que concedam direitos de gravação em todo o cluster, ou se houver maneiras alternativas de fornecer um certificado:

. Gere um certificado autoassinado <<_generate_a_certificate_locally,localmente>>.
. Use o https://cert-manager.io/[cert-manager] k8s  (se já estiver no cluster) <<_generate_a_certificate_using_the_cert_manager,com um `ClusterIssuer`>>.

== Gere um certificado localmente

Para gerar um certificado localmente, siga os seguintes passos:

. Baixe o script de geração de certificado e execute-o para produzir um arquivo de valores helm (`tls_values.yaml`) com o certificado correto:
+
----
wget https://raw.githubusercontent.com/StackVista/http-header-injector/main/scripts/generate_ca_cert.sh
chmod +x generate_ca_cert.sh
./generate_ca_cert.sh <helm-agent-release-name> <helm-agent-namespace>
----
+
Certifique-se de usar o nome do release que será utilizado no comando helm e o namespace, caso contrário, o certificado será inválido.

. Instale o agente adicionando a configuração adicional ao adicionar `--set httpHeaderInjectorWebhook.enabled=true -f tls_values.yaml` no comando de invocação do helm

== Gere um certificado usando o cert-manager

Se seu cluster tiver o https://cert-manager.io/[cert-manager] instalado e um `ClusterIssuer` configurado, é possível usar o certificado emitido pelo `ClusterIssuer` no agente para o injetor de sidecar. Para fazer isso, adicione os seguintes argumentos de linha de comando para instalar o agente: `--set httpHeaderInjectorWebhook.enabled=true --set-string httpHeaderInjectorWebhook.webhook.tls.mode="cert-manager" --set-string httpHeaderInjectorWebhook.webhook.tls.certManager.issuer="<my-cluster-issuer>"`. Certifique-se de substituir my-cluster-issuer pelo nome do emissor em seu cluster.
