= SUSE Observability documentation
:revdate: 2025-07-10
:page-revdate: {revdate}

This is the latest SUSE Observability documentation. Select topics from the content menu on the left.

For older versions of the documentation, use the https://archivedocs.stackstate.com[archive].

== Get started

Visit the xref:/k8s-suse-rancher-prime.adoc[Rancher Prime getting started
guide] if you're a Rancher Prime user, if you're a SaaS user visit the
xref:/k8s-quick-start-guide.adoc[quick start guide], if you are running SUSE
Cloud Observability on AWS check the
xref:/suse-cloud-observability-quick-start-guide.adoc[SUSE Cloud Observability
quick start guide].

== Can't find something?

Use the search bar on the top right. If you think any documentation is
missing, let us know on the https://scc.suse.com/[SUSE Observability
support site].

== Troubleshooting and support

Any questions? We can help. Find the support team on the
https://scc.suse.com/[SUSE Observability support site].

== SUSE Observability Self-hosted

Use SUSE Observability Self-hosted to observe an extensive set of technologies
from own data centers or the cloud.

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability Self-hosted]

== SUSE Observability SaaS

Use SUSE Observability SaaS to observe cloud technologies, such as Kubernetes
and AWS services.

xref:/saas/user-management.adoc[SUSE Observability SaaS docs]
