= Quick start guide
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name}
:doctype: book

== Overview

To integrate your cluster(s) with {stackstate-product-name} you can follow one of these guides for your appropriate environment.

* <<amazon-eks,Amazon EKS>>
* <<azure-aks,Azure AKS>>
* <<google-gke,Google GKE>>
* <<kubernetes,Kubernetes>>
* <<kops,KOPS>>
* <<openshift,OpenShift>>
* <<self-hosted,Self-hosted>>

[#kubernetes]
== Kubernetes

Set up a Kubernetes integration to collect topology, events, logs, change and metrics data from a Kubernetes cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Supported Kubernetes Version

| Kubernetes 1.35
| Kubernetes 1.34
| Kubernetes 1.33
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-kubernetes]
=== Prerequisites for Kubernetes

To set up a {stackstate-product-name} Kubernetes integration you need to have:

* An up-and-running Kubernetes Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up a Kubernetes integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-kubernetes,Prerequisites for Kubernetes>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. If you previously installed the Agent into namespace `suse-observability`, follow the migration guidance in the StackPack instructions to remove the old Agent installation separately before installing into the new namespace.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[CAUTION]
====
When running on a self-hosted air-gapped environment prepare the agent installation first with the xref:/k8s-suse-rancher-prime-agent-air-gapped.adoc[air-gapped instructions].
====

[#openshift]
== OpenShift

Set up an OpenShift integration to collect topology, events, logs, change and metrics data from a OpenShift cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| OpenShift Version | Supported Kubernetes Version | OpenShift End of Support

| OpenShift 4.17
| Kubernetes 1.30
| April 1, 2026

| OpenShift 4.16
| Kubernetes 1.29
| December 27, 2025

| OpenShift 4.15
| Kubernetes 1.28
| August 27, 2025

| OpenShift 4.14
| Kubernetes 1.27
| May 1, 2025

| OpenShift 4.13
| Kubernetes 1.26
| November 17, 2024

| OpenShift 4.12
| Kubernetes 1.25
| July 17, 2024

| OpenShift 4.11
| Kubernetes 1.24
| February 10, 2024

| OpenShift 4.10
| Kubernetes 1.23
| September 10, 2023

| OpenShift 4.9
| Kubernetes 1.22
| April 18, 2023
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-openshift]
=== Prerequisites for OpenShift

To set up a {stackstate-product-name} OpenShift integration you need to have:

* An up-and-running OpenShift Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up an OpenShift integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-openshift,Prerequisites for Openshift>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[#amazon-eks]
== Amazon EKS

Set up an Amazon EKS integration to collect topology, events, logs, change and metrics data from an Amazon EKS cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Kubernetes version | Amazon EKS release | Amazon EKS End of Support | Amazon EKS End of Extended Support

| 1.35
| January 28, 2026
| March 27, 2027
| March 27, 2028

| 1.34
| October 6, 2025
| December 2, 2026
| December 2, 2027

| 1.33
| May 28, 2025
| July 29, 2026
| July 29, 2027
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-amazoneks]
=== Prerequisites for Amazon EKS

To set up a {stackstate-product-name} Amazon EKS integration you need to have:

* An up-and-running Amazon EKS Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up an Amazon EKS integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-amazoneks,Prerequisites for Amazon EKS>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[#google-gke]
== Google GKE

Set up a Google GKE integration to collect topology, events, logs, change and metrics data from an Google GKE cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Kubernetes Version | Google GKE release | Google GKE End of Support | Google GKE End of Extended Support

| 1.35
| February 11, 2026
| April 11, 2027
| N/A

| 1.34
| September 30, 2025
| October 1, 2026
| N/A

| 1.33
| June 3, 2025
| August 3, 2026
| N/A
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-googlegke]
=== Prerequisites for Google GKE

To set up a {stackstate-product-name} Google GKE integration you need to have:

* An up-and-running Google GKE Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up a Google GKE integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-googlegke,Prerequisites for Google GKE>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[#azure-aks]
== Azure AKS

Set up an Azure AKS integration to collect topology, events, logs, change and metrics data from an Azure AKS cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Kubernetes Version | AKS GA | Azure AKS End of Life | Platform support

| 1.35
| March 5, 2026
| March 31, 2027
| March 31, 2028

| 1.34
| January 4, 2026
| November 30, 2026
| November 30, 2027

| 1.33
| June 17, 2025
| July 31, 2026
| July 31, 2027
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-azureaks]
=== Prerequisites for Azure AKS

To set up a {stackstate-product-name} Azure AKS integration you need to have:

* An up-and-running Azure AKS Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up a Azure AKS integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-azureaks,Prerequisites for Azure AKS>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[#kops]
== KOPS

Set up a KOPS integration to collect topology, events, logs, change and metrics data from an KOPS cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Supported Kubernetes Version

| Kubernetes 1.35
| Kubernetes 1.34
| Kubernetes 1.33
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-kops]
=== Prerequisites for KOPS

To set up a {stackstate-product-name} KOPS integration you need to have:

* An up-and-running KOPS Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to grant {stackstate-product-name} Agents permissions to access the Kubernetes API.
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up a KOPS integration

[CAUTION]
====
Before you begin, check the <<-prerequisites-for-kops,Prerequisites for KOPS>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}

[#self-hosted]
== Self-hosted

Set up a Self-hosted integration to collect topology, events, logs, change and metrics data from an Self-hosted cluster and make this available in {stackstate-product-name}.

=== Supported versions

|===
| Supported Kubernetes Version

| Kubernetes 1.35
| Kubernetes 1.34
| Kubernetes 1.33
|===

=== Supported runtime

|===
| Supported runtime

| ContainerD
| CRI-O
|===

[#prerequisites-for-selfhosted]
=== Prerequisites for Self-hosted

To set up a {stackstate-product-name} Self-hosted integration you need to have:

* An up-and-running Self-hosted Cluster.
* Helm version 3.13.1 or higher.
* A user with the permission to `create privileged pods`, `ClusterRoles` and `ClusterRoleBindings`:
 ** ClusterRole and ClusterRoleBinding are needed to:
  *** Grant {stackstate-product-name} Agents permissions to access the Kubernetes API
  *** Generate a secret for the mutating validation webhook which is part of xref:/setup/agent/k8sTs-agent-request-tracing.adoc[request tracing]
 ** {stackstate-product-name} Agents need to run in a privileged pod to be able to gather information on network connections and host information.

=== Set up a self-hosted integration

[CAUTION]
====
Before you begin, check the <<prerequisites-for-selfhosted,Prerequisites for Self-hosted>>.
====


To get data from a Kubernetes cluster into {stackstate-product-name}, follow the steps described below:

. Add the {stackstate-product-name} helm repository to the local helm client:
+
[,buildoutcfg]
----
 helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
 helm repo update
----

. In the {stackstate-product-name} UI, open the main menu by clicking in the top left of the screen and go to `StackPacks` > `Integrations` > `Kubernetes`.
. Install a new instance of the Kubernetes StackPack:
 ** Specify a *Kubernetes Cluster Name*
  *** This name will be used to identify the cluster in {stackstate-product-name}
 ** Click *install*.
. Deploy the {stackstate-product-name} Agent, Cluster Agent, Checks Agent and kube-state-metrics on your Cluster using the helm command provided in the {stackstate-product-name} UI after you have installed the StackPack. The default namespace for the agent is `suse-observability-agent`. The UI instructions remove a previous agent release from `suse-observability` before installing into the new namespace, `suse-observability-agent`, to avoid running duplicate agents.
 ** Once the Agents have been deployed, they will begin collecting data and push this to {stackstate-product-name}


== What's next?

* xref:/k8s-getting-started.adoc[SUSE Observability walk-through]
