= Controle de acesso com base em função (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

O gerenciamento de acesso ajuda você a gerenciar quem tem acesso aos elementos específicos da topologia, dados de métricas, rastros, elementos da interface do usuário e quais APIs eles podem chamar.

RBAC é um sistema de autorização que fornece gerenciamento de acesso detalhado aos recursos do SUSE Observability, uma maneira limpa e fácil de auditar privilégios de usuário e corrigir problemas identificados com direitos de acesso.

== O que você pode fazer com o RBAC?

Aqui estão exemplos do que você pode fazer com o RBAC:

* Permitir que um usuário tenha acesso apenas ao cluster de desenvolvimento, outro tenha acesso aos clusters de produção e desenvolvimento, e um terceiro possa acessar o cluster de desenvolvimento e apenas um namespace no cluster de produção.
* Dar a um pequeno grupo de usuários uma função de administrador para configurar o SUSE Observability. Ao mesmo tempo, concede a todos os desenvolvedores uma função de solucionador de problemas para visualizar toda a topologia, métricas, rastros, logs e eventos, mas com capacidade de configuração limitada.

== O que é uma função no SUSE Observability?

Uma função no SUSE Observability é uma combinação de um sujeito configurado e um conjunto de xref:/setup/security/rbac/rbac_permissions.adoc[permissões]. O processo de configuração de uma função no SUSE Observability é descrito em xref:/setup/security/rbac/rbac_roles.adoc[Como configurar funções].

== Fontes de funções do RBAC

Você pode definir funções de várias maneiras.  Todos usam as mesmas xref:/setup/security/rbac/rbac_permissions.adoc[Permissões].

* **Configuração** - nos xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[valores helm] para SUSE Observability
* **Dinâmico** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[use o `sts` CLI]
* **Mapeado do Kubernetes** - xref:/setup/security/rbac/rbac_rancher.adoc[mapear Kubernetes `Roles` e `RoleBindings`]

== Mais sobre configuração do RBAC

* xref:/setup/security/rbac/rbac_permissions.adoc[Permissões]
* xref:/setup/security/rbac/rbac_roles.adoc[Como configurar funções]
* xref:/setup/security/rbac/rbac_rancher.adoc[Usar com o Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Escopos]
* xref:/setup/security/authentication/README.adoc[Como configurar a autenticação]
