= Rollenbasierte Zugriffskontrolle (RBAC)
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Das Zugriffsmanagement hilft Ihnen dabei, zu verwalten, wer Zugriff auf die spezifischen Topologieelemente, Metrikdaten, Traces, UI-Elemente hat und welche APIs sie aufrufen können.

RBAC ist ein Autorisierungssystem, das eine feingranulare Zugriffsverwaltung der SUSE Observability-Ressourcen bietet, eine saubere und einfache Möglichkeit, Benutzerprivilegien zu überprüfen und identifizierte Probleme mit Zugriffsrechten zu beheben.

== Was können Sie mit RBAC tun?

Hier sind Beispiele dafür, was Sie mit RBAC tun können:

* Einem Benutzer den Zugriff ausschließlich auf den Entwicklungscluster zu gewähren, einem anderen sowohl auf den Produktions- als auch auf den Entwicklungscluster und einem dritten den Zugriff auf den Entwicklungscluster und nur auf einen Namespace im Produktionscluster.
* Eine kleine Gruppe von Benutzern mit einer Administratorrolle auszustatten, um SUSE Observability einzurichten und zu konfigurieren. Während alle Entwickler eine Troubleshooter-Rolle erhalten, um alle Topologien, Metriken, Traces, Protokolle und Ereignisse zu sehen, jedoch mit eingeschränkten Konfigurationsmöglichkeiten.

== Was ist eine Rolle in SUSE Observability?

Eine Rolle in SUSE Observability ist eine Kombination aus einem konfigurierten Subjekt und einer Reihe von xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen]. Der Prozess zur Einrichtung einer Rolle in SUSE Observability wird in xref:/setup/security/rbac/rbac_roles.adoc[Wie man Rollen einrichtet] beschrieben.

== Quellen der RBAC-Rollen

Sie können Rollen auf verschiedene Weise definieren.  Alle verwenden die gleichen xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen].

* **Konfiguration** - in den xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[Helm-Werten] für SUSE Observability
* **Dynamisch** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[verwenden Sie die `sts` Kommandozeilenschnittstelle]
* **Von Kubernetes abgebildet** - xref:/setup/security/rbac/rbac_rancher.adoc[Kubernetes `Roles` und `RoleBindings` abbilden]

== Mehr zur RBAC-Konfiguration

* xref:/setup/security/rbac/rbac_permissions.adoc[Berechtigungen]
* xref:/setup/security/rbac/rbac_roles.adoc[Wie man Rollen einrichtet]
* xref:/setup/security/rbac/rbac_rancher.adoc[Verwendung mit Rancher]
* xref:/setup/security/rbac/rbac_scopes.adoc[Bereiche]
* xref:/setup/security/authentication/README.adoc[Wie man die Authentifizierung konfiguriert]
