= Sobrescribir la configuración por defecto
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Autoalojado

Se pueden establecer varios valores en el https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} chart de Helm]. Por ejemplo, es posible personalizar el `tolerations` y el `nodeSelectors` para cada uno de los componentes. También puedes añadir configuración personalizada e incluir variables de entorno

== Configuración personalizada para {stackstate-product-name} `api`

Para el servicio {stackstate-product-name} `api`, la configuración personalizada se puede incluir directamente en el chart de Helm. Esta es la forma recomendada de sobrescribir la configuración por defecto con la que {stackstate-product-name} viene y es especialmente conveniente para personalizar la autenticación. La configuración establecida de esta manera estará disponible en el archivo de configuración {stackstate-product-name} en formato https://github.com/lightbend/config/blob/master/HOCON.md[HOCON].

Por ejemplo, puedes establecer un enlace personalizado para restablecer la contraseña en la página de inicio de sesión de {stackstate-product-name}:

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      config: |
        stackstate.api.authentication.forgotPasswordLink =
        "https://www.stackstate.com/forgotPassword.html"
----

--
====

[NOTE]
====
Ten en cuenta que la configuración personalizada establecida aquí será sobrescrita por xref:/setup/install-stackstate/kubernetes_openshift/customize_config.adoc#_environment_variables[variables de entorno].
====


== Variables de entorno

La configuración para todos los servicios de {stackstate-product-name} (`receiver`, `k2es-*`, `correlation` y `api`) se puede personalizar utilizando variables de entorno. Las variables de entorno se especifican en el archivo `values.yaml` y pueden ser `secret` (como contraseñas) o `open` (para valores normales). Para convertir un elemento de configuración en un nombre de variable de entorno, reemplaza `.` con `_` y añade el prefijo `CONFIG_FORCE_`.

[,text]
----
# configuration item
stackstate.api.authentication.forgotPasswordLink

# environment variable name
CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink
----

Por ejemplo, puedes establecer un enlace personalizado para restablecer la contraseña en la página de inicio de sesión de {stackstate-product-name}:

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      extraEnv:
        # The value for open env vars is defined on the deployment
        open:
          CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink: "https://www.stackstate.com/forgotPassword.html"
        # The value for secret env vars is defined in a secret and referenced from the deployment
        secret:
          CONFIG_FORCE_some_config_with_sensitive_data: "data-stored-in-secret"
----

--
====

[NOTE]
====
Para el servicio {stackstate-product-name} `api`, las variables de entorno sobrescribirán <<_custom_configuration_for_suse_observability_api,la configuración personalizada establecida utilizando `config`>>.
====


* Los detalles completos sobre la nomenclatura de todos los diferentes servicios se pueden encontrar en el https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} archivo README del chart de Helm.]
* Encuentra más detalles sobre xref:/setup/security/authentication/README.adoc[la personalización de la autenticación].
