= Dépannage des extensions
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-11-03
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

Cette section fournit des étapes de dépannage pour tout problème d'interopérabilité entre {stackstate-product-name} et l'extension Rancher UI.

== Collecter un HAR (Http ARchive)

Http ARchive collecte des détails sur les requêtes envoyées par le navigateur à Rancher et {stackstate-product-name}.  Il enregistre également les réponses reçues.
Cette archive est spécifique à la page/onglet du navigateur avec l'erreur.  Il n'est pas nécessaire d'accéder aux instances de Rancher ou {stackstate-product-name} sous-jacentes (bien que leurs journaux puissent être utiles à un stade ultérieur).

* Ouvrez l'onglet *Réseau* dans le panneau "Outils de développement".  Vous pouvez y accéder en utilisant `F12`.  L'onglet réseau montre un journal de toutes les requêtes effectuées.
* Effacez le journal et effectuez un rafraîchissement (complet) de la page affichant le comportement problématique.
* Il devrait maintenant y avoir un grand nombre de requêtes visibles à la fois vers Rancher et SUSE Observability.
* Exporter/Télécharger/Enregistrer le HAR - différents navigateurs utilisent des noms différents ici.

== Le cluster est non observé

Pour que l'état de santé du cluster soit visible dans Rancher, il doit y avoir un alignement entre ces configurations :

* Le nom (d'affichage) du cluster dans l'interface Rancher.
* Le `stackstate.cluster.name` défini sur l'agent déployé sur le cluster
* Le nom du cluster dans la configuration du stackpack Kubernetes dans SUSE Observability

Un décalage apparaîtra généralement comme "aucune donnée reçue" dans l'aperçu du cluster dans Rancher.

== Echec de la connexion

La configuration pour SUSE Observability peut parfois ne pas établir une connexion valide dans l'interface Rancher pour les raisons suivantes :

* L'hôte Rancher n'est pas configuré comme une origine autorisée pour SUSE Observability.  Vous pouvez résoudre ce problème en l'ajoutant à la liste `stackstate.allowedOrigins` dans les valeurs helm, ou en passant `--set stackstate.allowedOrigins={"https://<rancher-url>"}` à la commande de déploiement.
* SUSE Observability n'est pas accessible depuis le navigateur. Par exemple, le certificat racine n'a pas été installé.