= Guide de démarrage initial
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergée

== Présentation

Cette page fournit toutes les informations nécessaires pour installer et exécuter SUSE Observability.

== Instructions d'installation

[tabs]
====
Kubernetes::
+
--
Installez SUSE Observability sur xref:/setup/install-stackstate/kubernetes_openshift/README.adoc[Kubernetes].
--

OpenShift::
+
--
Installez SUSE Observability sur xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift].
--
====

== Adresse et port

[tabs]
====
Kubernetes::
+
--
Pour accéder à l'interface utilisateur de SUSE Observability :

. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Activez un port-forward].
. Accédez à l'interface utilisateur de SUSE Observability à : https://localhost:8080
--

OpenShift::
+
--
Pour accéder à l'interface utilisateur de SUSE Observability :

. xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc#_access_the_suse_observability_ui[Activez un port-forward].
. Accédez à l'interface utilisateur de SUSE Observability à : https://localhost:8080
--
====

== Nom d'utilisateur et mot de passe par défaut

[tabs]
====
Kubernetes::
+
--
SUSE Observability est configuré par défaut avec le compte administrateur suivant :

* *nom d'utilisateur :* `admin`
* *Mot de passe :* Défini lors de l'installation. Ceci est collecté par le script `generate_values.sh` et stocké au format de hachage MD5 dans `values.yaml`
--

OpenShift::
+
--
SUSE Observability est configuré par défaut avec le compte administrateur suivant :

* *nom d'utilisateur :* `admin`
* *Mot de passe :* Défini lors de l'installation. Ceci est collecté par le script `generate_values.sh` et stocké au format de hachage MD5 dans `values.yaml`
--
====

== Dépannage

Si vous rencontrez des problèmes lors de l'installation de SUSE Observability ou du premier démarrage, consultez le xref:/setup/install-stackstate/troubleshooting.adoc[guide de dépannage de l'installation de SUSE Observability].

== Étapes suivantes

Une fois que vous avez SUSE Observability opérationnel, vous pouvez commencer à configurer des intégrations

* xref:/k8s-quick-start-guide.adoc[Installez des StackPacks pour intégrer des systèmes externes]
* xref:/use/views/k8s-views.adoc[Explorez votre cluster Kubernetes]
