ifdef::ss-ff-stackpacks2_enabled[]
= Open Telemetry Mappings Concepts
:revdate: 2025-12-23
:page-revdate: {revdate}
:description: Open Telemetry Mappings Concepts

== Component mappings

An `OtelComponentMapping` describes how a topology component is created (or updated) from OpenTelemetry data.

Typical examples of components created from OpenTelemetry include (these are a part of the default OpenTelemetry StackPack):

* Services (derived from `service.name` / `service.namespace`)
* Service instances (derived from `service.instance.id`)
* Databases
* Hosts and Kubernetes resources (nodes, namespaces, pods)
* Functions and tasks in serverless or batch environments

== Relation mappings

An `OtelRelationMapping` describes how a relationship between two components is created from OpenTelemetry data.

Common examples of relations include (these are a part of the default OpenTelemetry StackPack):

* Synchronous service calls (client -> server)
* Asynchronous messaging flows (producer -> consumer, consumer -> peer, producer -> peer)
* Service-to-database connections
* Service instance provided-by service
* Execution relationships (service or function executes task, host, or function)

== Expressions and the Common Expression Language (CEL)

Topology mappings rely on the https://cel.dev/[Common Expression Language (CEL)] to select telemetry, extract values, and construct component and relation fields.

You do not need prior CEL expertise to get started - most expressions are simple boolean checks, attribute lookups, or string constructions. More advanced expressions can be introduced incrementally as needed.

For more information on how to leverage CEL in the topology mappings, see xref:/setup/custom-integrations/otelmappings/schemas-ref.adoc[schemas] page.

endif::ss-ff-stackpacks2_enabled[]
