= SUSE Observability 文档
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}

这是最新的 SUSE Observability 文档。从左侧的内容菜单中选择主题。

对于旧版本的文档，请使用 https://archivedocs.stackstate.com[存档]。

== 开始使用

如果您是 Rancher Prime 用户，请访问 xref:/k8s-suse-rancher-prime.adoc[Rancher Prime 快速入门指南]，如果您是 SUSE Cloud Observability 用户，请访问 xref:/k8s-quick-start-guide.adoc[快速入门指南]，如果您在 AWS 上运行 SUSE Cloud Observability，请查看 xref:/suse-cloud-observability-quick-start-guide.adoc[SUSE Cloud Observability 快速入门指南]。

== 找不到某些内容？

请使用右上角的搜索栏。如果您认为有任何文档缺失，请在 https://scc.suse.com/[SUSE Observability 支持网站] 上告知我们。

== 故障排除和支持

还有疑问？我们可以帮忙。在 https://scc.suse.com/[SUSE Observability 支持网站] 上找到支持团队。

== SUSE Observability 自托管

使用 SUSE Observability Self-hosted 对来自自有数据中心或云的各种技术进行监控。

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability 自托管]

== SUSE Cloud Observability

使用 SUSE Cloud Observability 监控云技术，例如 Kubernetes 和 AWS 服务。

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observability 文档]
