= Resolución de problemas de monitores
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Descripción general

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,El resultado del monitor no se muestra en un componente>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,El monitor está mostrando un error en la vista general del estado del monitor.>>

=== El resultado del monitor no se muestra en un componente

Primero verifica si el monitor está xref:use/alerting/k8s-add-monitors-cli.adoc#_verify_the_execution_of_the_monitor[produciendo resultados]. Si este es el caso pero los resultados del monitor no aparecen en los componentes, puede haber un problema con la vinculación. Primero utiliza el siguiente comando para verificar:

[,bash]
----
sts monitor status --id <id>
----

Si la salida tiene `Monitor health states with identifier which has no matching topology element (<nr>): ....`, esto indica que el `urnTemplate` puede no generar un identificador que coincida con la topología. Para remediar esto xref:use/alerting/k8s-add-monitors-cli.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[revisa tu urnTemplate].

=== El monitor está mostrando un error en la vista general del estado del monitor.

Obtén el estado del monitor a través de la CLI

[,bash]
----
sts monitor status --id <id>
----

La sección `Monitor Stream errors:` mostrará los errores que ocurren en el monitor y ofrecerá más ayuda.

