= Configurando el agente de Kubernetes de SUSE Observability para hacer de proxy en las conexiones
:revdate: 2025-07-10
:page-revdate: {revdate}

El Agente de Kubernetes de SUSE Observability te permite configurar ajustes de proxy HTTP o HTTPS para las conexiones que inicia.

== Proxy para la comunicación con SUSE Observability

Para configurar el agente para que haga proxy de conexiones al backend de SUSE Observability, puedes utilizar la configuración de Helm.

=== Configuración de Helm

==== A través del archivo `values.yaml`

. Abre tu archivo `values.yaml` del chart de Helm.
. Localiza `global.proxy.url` la configuración y especifica la URL del proxy:
+
[,yaml]
----
 global:
   proxy:
     url: "https://proxy.example.com:8080"
----

. Opcionalmente, si el proxy no tiene un certificado firmado, desactiva la verificación SSL estableciendo `global.skipSslValidation` en `true`:
+
[,yaml]
----
 global:
   skipSslValidation: true
----

==== A través de la opción de línea de comandos

. Durante la instalación del chart de Helm, utiliza la opción `--set` para especificar la URL del proxy:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.proxy.url="https://proxy.example.com:8080"
----

. Para desactivar la validación SSL a través de la línea de comandos, utiliza:
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.skipSslValidation=true
----
