= Configuración de secretos personalizados de k8s (Queda obsoleta)
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== Descripción general

El agente de observabilidad de SUSE admite especificar el nombre de un secreto personalizado que contiene la clave API y el token de autorización del clúster. Esta función es útil para los usuarios que desean gestionar sus propios secretos y evitar la creación automática de secretos por el chart de Helm.

[CAUTION]
====
*Este método de personalizar secretos queda obsoleto y es incompatible con la función RBAC.*

Por favor, utiliza xref:/setup/agent/k8s-custom-secrets-setup.adoc[el nuevo método] para usar secretos externos.
====


== El Chart de Helm

=== Opciones de configuración

* `stackstate.manageOwnSecrets`: Una bandera booleana que determina si el usuario desea gestionar sus propios secretos. El valor por defecto es `false`.
* `stackstate.customSecretName`: (Opcional) Nombre del secreto personalizado que debe ser creado por el usuario. Requerido si `stackstate.manageOwnSecrets` está establecido en `true`.
* `stackstate.customApiKeySecretKey`: (Opcional) Nombre de la clave para la clave API dentro del secreto personalizado. Requerido si `stackstate.manageOwnSecrets` está establecido en `true`.
* `stackstate.customClusterAuthTokenSecretKey`: (Opcional) Nombre de la clave para el token de autorización del clúster dentro del secreto personalizado. Requerido si `stackstate.manageOwnSecrets` está establecido en `true`.

=== Descripción del Comportamiento

* *Creación Automática de Secretos*: Por defecto, el chart continúa creando secretos automáticamente como antes si `stackstate.manageOwnSecrets` está establecido en `false`.
* *Gestión de Secretos Personalizados*: Si `stackstate.manageOwnSecrets` está establecido en `true`, el chart espera que el usuario proporcione el nombre del secreto personalizado (`stackstate.customSecretName`) junto con las claves para la clave API y el token de autorización (`stackstate.customApiKeySecretKey` y `stackstate.customClusterAuthTokenSecretKey`, respectivamente).
* *Omisión Implícita*: Al especificar que deseas gestionar tus propios secretos, el chart ignorará los valores para `stackstate.apiKey` y `stackstate.cluster.authToken`.
+
== Cómo usar en values.yaml

. *Usando la Creación Automática de Secretos (Por Defecto)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *Gestionando Propios Secretos*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
