= Gestión de Secretos Personalizados de k8s
:revdate: 2025-10-27
:page-revdate: {revdate}

== Descripción general

El Agente de Observabilidad de SUSE admite especificar el nombre de un secreto personalizado que contiene la clave API y el token de autorización del clúster. Esta función es útil para los usuarios que desean gestionar sus propios secretos y evitar la creación automática de secretos por el chart de Helm.

NOTE: *Hubo un método anterior para especificar esto que ahora queda obsoleto, consulta el xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[método obsoleto].*

== El Chart de Helm

=== Opciones de configuración

* `global.apiKey.fromSecret`: Especifica un nombre de secreto preexistente que resida en el mismo espacio de nombres y que contenga un campo `STS_API_KEY` que contenga la clave API.
* `global.clusterAgentAuthToken.fromSecret`: Especifica un nombre de secreto preexistente que resida en el mismo espacio de nombres y que contenga un campo `STS_CLUSTER_AGENT_AUTH_TOKEN` que contenga un token para asegurar las conexiones entre el clúster y los agentes de nodo.

=== Descripción del Comportamiento

* *Creación Automática de Secretos*: Por defecto, el chart requiere que se especifique un `stackstate.apiKey` y creará un secreto por sí mismo. El `STS_CLUSTER_AGENT_AUTH_TOKEN` se genera automáticamente.
* *Gestión de Secretos Personalizados*: Al sobrescribir los campos `fromSecret`, la clave API y el token de autorización del clúster se tomarán de esos secretos.
* *Omisión Implícita*: Al especificar que deseas gestionar tus propios secretos, el chart ignorará los valores para `stackstate.apiKey` y `stackstate.cluster.authToken`.

== Cómo usar en values.yaml

. *Usando la Creación Automática de Secretos (Por Defecto)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Gestionando Propios Secretos*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
