= k8s 自定义密钥设置（已弃用）
:revdate: 2025-10-27
:page-revdate: {revdate}

== 概述

SUSE Observability 代理支持指定包含 API 密钥和集群授权令牌的自定义密钥名称。此功能对希望管理自己的密钥并避免 Helm 图表自动创建密钥的用户非常有用。

[CAUTION]
====
*此自定义密钥的方法已弃用，并与 RBAC 功能不兼容。*

请使用 xref:/setup/agent/k8s-custom-secrets-setup.adoc[新方法] 来使用外部密钥。
====


== Helm 图表

=== 配置选项

* `stackstate.manageOwnSecrets`：一个布尔标志，用于确定用户是否希望管理自己的密钥。默认值是 `false`。
* `stackstate.customSecretName`：（可选）用户创建的自定义密钥的名称。如果 `stackstate.manageOwnSecrets` 设置为 `true`，则为必填项。
* `stackstate.customApiKeySecretKey`：（可选）自定义密钥中 API 密钥的键名称。如果 `stackstate.manageOwnSecrets` 设置为 `true`，则为必填项。
* `stackstate.customClusterAuthTokenSecretKey`：（可选）自定义密钥中集群授权令牌的键名称。如果 `stackstate.manageOwnSecrets` 设置为 `true`，则为必填项。

=== 行为描述

* *自动密钥创建*：默认情况下，如果 `stackstate.manageOwnSecrets` 设置为 `false`，则图表将继续像以前一样自动创建密钥。
* *自定义密钥管理*：如果 `stackstate.manageOwnSecrets` 设置为 `true`，则图表期望用户提供自定义密钥的名称（`stackstate.customSecretName`）以及 API 密钥和授权令牌的键（分别为 `stackstate.customApiKeySecretKey` 和 `stackstate.customClusterAuthTokenSecretKey`）。
* *隐含省略*：当指定希望管理自己的密钥时，图表将忽略 `stackstate.apiKey` 和 `stackstate.cluster.authToken` 的值。
+
== 如何在 values.yaml 中使用

. *使用自动密钥创建（默认）*：
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *管理自己的密钥*：
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
