= Opções de autenticação
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

Fora da caixa, o SUSE Observability é configurado com xref:/setup/security/authentication/file.adoc[autenticação de senha única] com usuário administrador e senha aleatória xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[configurada durante a instalação]. Isso autentica os usuários com um segredo simples no servidor. No entanto, essa não é uma configuração pronta para produção.

Para melhor segurança, o SUSE Observability pode ser configurado para usar exatamente um dos seguintes mecanismos de autenticação (substituindo o usuário administrador padrão):

* xref:/setup/security/authentication/single_password.adoc[Senha única]
* xref:/setup/security/authentication/file.adoc[Baseado em arquivo]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (uma versão especializada do OIDC)]

[NOTE]
====
A configuração de autenticação faz parte do Helm chart; qualquer alteração acionará automaticamente a reinicialização dos pods necessários.
====


== Funções de usuário

Quando um usuário foi autenticado, as permissões para esse usuário geralmente são atribuídas com base nos papéis que o usuário possui. A documentação para os mecanismos de autenticação específicos também contém exemplos de como mapear os papéis ou grupos dos sistemas externos para os 4 papéis padrão do SUSE Observability:

* *Convidado* - capaz de ver informações, mas não fazer alterações.
* *Solucionador de Problemas do Kubernetes* - capaz de ver todas as informações e ver e alterar monitores e configuração de métricas.
* *Usuário Avançado* - capaz de ver e alterar toda a configuração e instalar StackPacks.
* *Administrador* - capaz de ver e alterar o conteúdo do SUSE Observability. Por exemplo, ver toda a configuração, instalar StackPacks, conceder e revogar permissões de usuário e fazer upload (novas versões de) StackPacks.

Ao decidir sobre os papéis a serem atribuídos aos seus usuários, é fortemente aconselhável ter apenas um pequeno grupo de Administradores de Plataforma e Administradores. Por exemplo, apenas os engenheiros responsáveis pela instalação do SUSE Observability e pela configuração inicial. Usuários Administradores podem gerenciar o acesso ao SUSE Observability e decidir quais StackPacks podem ser usados. Você pode delegar a instalação de StackPacks e outras configurações de ajuste fino para um número maior de usuários com o papel de Usuário Avançado. Usuários Administradores da Plataforma podem limpar o banco de dados, alterar as configurações de retenção de dados, visualizar logs e realizar outras tarefas de gerenciamento da plataforma.

Também é possível adicionar mais papéis, veja a página xref:/setup/security/rbac/rbac_roles.adoc[Papéis (RBAC)] e as outras xref:/setup/security/rbac/README.adoc[páginas de documentação do RBAC]
