= Senha única
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hospedado

Fora da caixa, {stackstate-product-name} é configurado com uma única configuração de senha, xref:/k8s-suse-rancher-prime.adoc#_installation[configuração definida durante a instalação]. Isso autentica usuários com uma única senha que deve ser fornecida durante a instalação. 

Esta é a maneira mais simples de começar com {stackstate-product-name}, mas para produção, uma das outras xref:/setup/security/authentication/authentication_options.adoc[opções de autenticação] é recomendada.

== Obtenha a senha de um segredo externo

Quando a senha padrão deve vir de um segredo externo, siga xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[estas etapas] mas preencha os seguintes dados:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

A codificação da senha pode ser uma das seguintes:
* Para uma senha em texto simples, forneça: `$plain$your-password` (`$plain$` é um prefixo indicando texto simples)
* Para uma senha bcrypted, forneça: `bcrypt-hashed-password`. Criar um hash bcrypted da senha pode ser feito usando `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== Consulte também

* xref:/setup/security/authentication/authentication_options.adoc[Opções de autenticação]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissões para {stackstate-product-name} funções predefinidas]
* xref:/setup/security/rbac/rbac_roles.adoc[Criar papéis RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Segredos Externos]
