= Solução de problemas de autenticação e autorização
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Auto-hospedado

Quando a autenticação ou autorização falha, geralmente é devido a uma incompatibilidade na configuração do provedor e do SUSE Observability. Para facilitar a solução de problemas, é possível habilitar o registro de depuração no SUSE Observability especificamente para autenticação e autorização.

[CAUTION]
====
Desative o registro de depuração assim que terminar a solução de problemas, pois é muito provável que o registro de depuração contenha segredos e/ou informações pessoais.
====


Para habilitar o registro de depuração, copie/cole o seguinte trecho de yaml em um arquivo `debug-auth.yaml`.

[,yaml]
----
stackstate:
  components:
    server:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
    api:
      additionalLogging: |
        <logger name="org.pac4j.core.engine" level="DEBUG"/>
        <logger name="org.pac4j.oidc.profile.creator" level="DEBUG"/>
        <logger name="org.pac4j.oidc.credentials.authenticator" level="DEBUG"/>
----

Agora execute o comando `helm upgrade` que você usou antes, mas inclua este arquivo yaml extra (ou seja, `helm upgrade .... --values debug-auth.yaml`) para habilitar o registro de depuração. Nenhum pod será reiniciado, as alterações na configuração de registro serão carregadas automaticamente após cerca de 30 segundos.

Para desativar o registro de depuração, execute o comando `helm upgrade ....` novamente, mas omita o `--values debug-auth.yaml`. Após 30 segundos, a configuração de registro atualizada é carregada e o registro de depuração é interrompido.


== Solução de problemas com permissões

* xref:/setup/security/rbac/rbac_permissions.adoc#_list_subjects_for_a_user[Inspecione os sujeitos do usuário] (usuário e funções) e verifique a configuração dependendo do modelo de autenticação utilizado.
* xref:/setup/security/rbac/rbac_permissions.adoc#_show_granted_permissions[Inspecione a permissão de um sujeito] e verifique a configuração dependendo do modelo de autorização utilizado.