ifdef::ss-ff-suppressions_enabled[]
= Silencing rules
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026--8-19
:page-revdate: {revdate}
:description: SUSE Observability



Silencing rules let you acknowledge health violations that are already known or being actively worked on, so that ongoing incidents don't generate noise for your team. A Silencing rules can be applied to a single health violation directly from the UI, with an optional note and an expiry window. Suppressed states remain visible but are visually distinguished from non silenced violations; they are also reflected in notifications, which can be configured to include or exclude silencing events. External monitoring sources can carry silencing information directly on the health stream..

== Install Platform

Follow the xref:installing-suse-obs.adoc[Installing SUSE Observability] guide to install {stackstate-product-name}. Since silencing rules are still under a feature flag you do need to enable that by enabling
`global.features.enableSilencing` in the deployment command:

[bash,]
----
helm upgrade --install \
    --namespace suse-observability \
    --create-namespace \
    --values values.yaml \
    --set global.features.enableSilencing=true \
    suse-observability \
    suse-observability/suse-observability
----
endif::ss-ff-suppressions_enabled[]