= OpenTelemetry入門
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[OpenTelemetryコレクターと2つの計装されたアプリケーションがSUSE Observabilityにメトリクスとトレースを送信する]

SUSE Observabilityはhttps://opentelemetry.io/docs/what-is-opentelemetry/[OpenTelemetry]をサポートしています。OpenTelemetryは、トレース、メトリクス、ログなどのテレメトリデータを収集、変換、送信するための標準化されたプロトコルとオープンソースフレームワークのセットです。OpenTelemetryは、さまざまなプログラミング言語とプラットフォームをサポートしています。

SUSE Observabilityはメトリクスとトレースの両方をサポートし、SUSE Observabilityエージェントによって提供される(Kubernetes)トポロジーデータにOpenTelemetryのメトリクスとトレースを追加します。したがって、SUSE Observabilityエージェントをインストールする必要があります。ログのサポートとSUSE ObservabilityエージェントなしでのOpenTelemetryの使用は近日中に提供される予定です。

OpenTelemetryは、いくつかの異なるコンポーネントで構成されています。SUSE Observabilityでの使用のために、xref:/setup/otel/languages/README.adoc[SDKs]を使ってアプリケーションを計装し、xref:/setup/otel/collector.adoc[OpenTelemetryコレクター]が最も重要な部分です。SUSE Observabilityでの使用のために、両方の設定方法を示します。

アプリケーションがすでにOpenTelemetryまたはJaegerやZipkinなどのOpenTelemetryにサポートされている他のライブラリで計装されている場合、コレクターを使用してそのデータをSUSE Observabilityに送信でき、追加の計装は必要ありません。

SUSE Observabilityは、すべてのデータが利用可能であることを確認するために、特定のプロセッサと認証でコレクターを設定する必要があります。

== 参考資料

* https://opentelemetry.io/docs/collector/[OpenTelemetryコレクター]はOpenTelemetryのドキュメントにあります。
* https://opentelemetry.io/docs/languages/[アプリケーションを計装するためのSDKs]はOpenTelemetryのドキュメントにあります。
