= OpenTelemetry入門
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

image::otel/open-telemetry.svg[OpenTelemetryコレクターと2つの計装されたアプリケーションがSUSE Observabilityにメトリクスとトレースを送信する]

SUSE Observabilityはhttps://opentelemetry.io/docs/what-is-opentelemetry/[OpenTelemetry]をサポートしています。OpenTelemetryは、トレース、メトリクス、ログなどのテレメトリデータを収集、変換、送信するための標準化されたプロトコルとオープンソースフレームワークのセットです。OpenTelemetryは、さまざまなプログラミング言語とプラットフォームをサポートしています。

SUSE Observabilityは、メトリクスとトレースの両方をサポートしています。Kubernetesスタックパックと組み合わせて使用すると、Kubernetesポッドは利用可能な場合にトレースで強化されます。Open Telemetryスタックパックをインストールすることで、サービスおよびサービスインスタンスの新しい概要ページが利用可能になり、トレースやスパンメトリクスにアクセスできます。Open Telemetryメトリクスは、モニターやメトリクスバインディングで使用できます。スタックパックには、スパンメトリクスおよび.NETおよびJVMメモリメトリクスのためのメトリクスバインディングが付属しています。スパンエラーレートと持続時間のためのアウトオブボックスモニターもあります。

SUSE Observabilityでの使用に推奨されるセットアップは、適切なOpen Telemetry xref:/setup/otel/instrumentation/README.adoc[SDKs]でアプリケーションを計装し、計装されたアプリケーションの近くにxref:/setup/otel/collector.adoc[Open Telemetry collector]をインストールしてデータを前処理（Kubernetesラベルでの強化、トレースのサンプリングなど）し、SUSE Observabilityにデータを送信することです。Open Telemetry Collectorは、SDKを使用してアプリケーションを計装することなく、多くの種類のテレメトリソースからメトリクスを収集するためにも使用できます。詳細については、https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry collector integrations]を参照し、データベースやテレメトリプロトコルがサポートされているか確認してください。

xref:/setup/otel/getting-started/README.adoc[getting started]ガイドに従って、SUSE Observabilityで最適に動作するようにすべてをセットアップしてください。

== 参考資料

* https://opentelemetry.io/docs/collector/[OpenTelemetryコレクター]はOpenTelemetryのドキュメントにあります。
* https://opentelemetry.io/ecosystem/registry/?language=collector[Open Telemetry collector integrations]
* https://opentelemetry.io/docs/instrumentation/README.md[SDKs to instrument your application]はOpen Telemetryのドキュメントにあります。
