ifdef::ss-ff-stackpacks2_enabled[]
= Tutorial: Create a Custom Integration (StackPack)
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-01-08
:page-revdate: {revdate}
:description:  Develop a Custom Integration (StackPack)

== Goal

As a devops developer, you want to customize SUSE Observability to monitor your own applications you have deployed.

[NOTE]
====
This page is about developing a custom integration. Installing an already built integration is described here: xref:/setup/[TODO]
====

== Prerequisites

- Access to the xref:/setup/cli/cli-sts.adoc[SUSE Observability CLI]
- Access to a running SUSE Observability instance xref:/setup/install[TODO]

=== Scaffold a New StackPack

The `scaffold` subcommand creates a new StackPack project structure from a template, getting you started with all concepts that are relevant.

- Create a new StackPack project using the CLI:
+
[source,bash]
----
sts stackpack scaffold --name my-stackpack
...
...

✅ ✓ Scaffold complete!

Next steps:
1. Review the generated files in: ./my-stackpack
2. Check the ./my-stackpack/README.md for instructions on what to do next.
----

=== Test Deploy StackPack

The `test` subcommand command that streamlines the stackpack development workflow by automating the package → upload → install/upgrade sequence with automatic version management for testing iterations.

- Rapidly test your StackPack in a pre-production environment (requires a running Suse Observability instance):
+
[source,bash]
----
sts stackpack test-deploy -d ./my-stackpack --yes
...
...
✅ StackPack instance installed
ID             | NAME | STATUS      | VERSION         | LAST UPDATED
274027256960772 | -    | PROVISIONING | 0.0.1-cli-test.1 | Fri Aug 29 09:10
                |      |              | 0000             | :26 2025 CEST
✅ ✓ Stackpack installed successfully

✅ 🎉 Test sequence completed successfully!
----

- The `test-deploy` subcommand packages, uploads, and installs your StackPack with a test version suffix.
- Iterate on your StackPack, using the `test-deploy` command for rapid feedback, make changes and observe the install/upgrade process to be successfully executed. Review the ingested topology and telemetry in the Suse Observability UI.

[NOTE]
====
You installed the example stackpack, this will show a new item in the main menu (my-stackpack), but clicking it will show no data yet, as long as no data is flowing. Follow the steps xref:./demo-environment.adoc[Demo Environment] to get all data
in to see the example in action.
====

=== Customize

The StackPack scaffold includes an example of all customizations that can be made in a StackPack. At this point, you can customize those to fit your application.

The following concepts can be customized:
- Overview page
- Component Highlight page
- Dashboards (is there a reference?)
  - xref:https://github.com/StackVista/stackpack-templates/blob/main/templates/generic/settings/presentations/microservice.sty[]

TODO fill this in based on https://github.com/StackVista/stackpack-templates/blob/main/templates/generic/README.md and add links to reference docs. Not much detail, just a lot of links.


- Edit `stackpack.yaml` and other files to define your integration logic. TODO: Link to stackpacks file layout reference
  * Integrating data. To map components and ingest metrics see xref:setup/custom-integrations/otelmappings/README.adoc[Adding Otel Telemetry Mappings]
  * Monitors: xref:use/alerting/.adoc[TODO: Refer to schemas-ref.adoc] aswell as cli for debugging


=== Example customizations

TODO example extra monitor (with a copy-pasteable monitor into an extra file)
TODO extract some data from a mapping and show it on a highlight and overview

=== Wrapping it up

TODO: Give a version, run the actual publish/upload/install commands to complete.
Link to stackpacks page for publish/install and also link to versioning (to be written for more info

endif::ss-ff-stackpacks2_enabled[]
