= Sobre StackPacks
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Auto-hospedado v5.1.x

== Visão Geral

StackPacks estendem a funcionalidade do SUSE Observability e oferecem integração automatizada com sistemas externos. Eles podem ser facilmente instalados e desinstalados na página de StackPacks do SUSE Observability.

Existem dois tipos de StackPack - Complementos e Integrações. Os complementos e integrações de StackPack disponíveis podem ser encontrados na página *StackPacks* na interface do SUSE Observability.

== Instalar ou desinstalar um StackPack

StackPacks podem ser instalados e desinstalados na página *StackPacks* do SUSE Observability. Instruções completas para instalar e desinstalar o StackPack são fornecidas.

[NOTE]
====
*Observe o seguinte:*

* Um StackPack pode exigir etapas de instalação *manual* ou configuração do sistema externo. Por favor, leia as instruções fornecidas com atenção.
* Quando um StackPack ou instância de StackPack é desinstalado, *todos os dados recebidos via StackPack (instância) serão removidos do SUSE Observability.*
* Qualquer configuração ou instalação (manual) de componentes do StackPack em um sistema externo pode precisar ser desinstalada separadamente.

====


=== Instâncias de StackPack

Alguns StackPacks permitem que você se conecte a várias contas em um sistema externo. Cada conta é configurada em uma instância separada do StackPack.

Por exemplo, o StackPack AWS pode se conectar a várias contas da AWS e combinar informações de todas as contas no SUSE Observability. Para cada conta, uma instância separada do SUSE Observability é configurada com as informações necessárias para receber dados daquela conta da AWS.

== Fazer upgrade de um StackPack

[CAUTION]
====
Quando um StackPack é feito upgrade, *quaisquer alterações feitas nos itens de configuração desse StackPack serão sobrescritas*. Para detalhes, veja xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[itens de configuração bloqueados].
====


Se uma nova versão do StackPack estiver disponível, um alerta será exibido na página do StackPack da interface do usuário do SUSE Observability e você terá a opção de visualizar os detalhes do upgrade e ler as notas de lançamento. Se o novo lançamento for um upgrade menor em relação à versão atualmente instalada, você também pode fazer upgrade do StackPack a partir daqui.

=== Nova versão menor do StackPack

Para fazer upgrade para uma nova versão menor de um StackPack, clique em *UPGRADE NOW* na página do StackPack na interface do usuário do SUSE Observability.

Observe que todos os itens de configuração do StackPack serão sobrescritos quando você fizer upgrade. Para continuar usando quaisquer alterações feitas a esses itens, escolha *MANTER* a configuração existente ao fazer upgrade do StackPack. Para detalhes, veja xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[itens de configuração bloqueados].

=== Nova versão principal do StackPack

[CAUTION]
====
Quando um StackPack é feito upgrade, *quaisquer alterações feitas nos itens de configuração desse StackPack serão sobrescritas*. Para detalhes, veja xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[itens de configuração bloqueados].
====


Para fazer upgrade para uma nova versão principal de um StackPack, xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[desinstale e reinstale] o StackPack.

[TIP]
====

Continue usando as alterações feitas nos itens de configuração personalizados do StackPack após o upgrade:

. Antes de fazer upgrade, exporte cada item personalizado:
 ** Vá para a página *Configurações* na interface do usuário do SUSE Observability.
 ** Clique em *Exportar* no menu *...* para cada item personalizado.
. Faça upgrade do StackPack (desinstale e reinstale).
. Altere o `name` e `identifier` para cada item exportado:
 ** Abra o arquivo de exportação em um editor de texto.
 ** Edite os campos `name` e `identifier` de nível superior.
 ** Salve a exportação.
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[Importar] o(s) arquivo(s) de exportação atualizado(s).
. Os itens de configuração personalizados agora estarão disponíveis no SUSE Observability e podem ser copiados para os novos itens de configuração do StackPack instalado.

====


== Itens de configuração bloqueados

Os StackPacks contêm informações de configuração para o SUSE Observability que são instaladas quando o StackPack (instância) é instalado. Entre outras coisas, isso pode incluir modelos de componentes, funções, ações de componentes e visualizações. Quando um StackPack é feito upgrade, *os itens de configuração instalados pela versão anterior do StackPack serão sobrescritos pelos itens da nova versão do StackPack.* Isso significa que qualquer alteração manual feita nesses itens de configuração será sobrescrita quando o StackPack for feito upgrade.

Para evitar que um usuário faça alterações em itens de configuração instalados por um StackPack que serão sobrescritos no upgrade, esses itens de configuração são *bloqueados* por padrão. Isso significa que eles estão protegidos contra alterações pelo usuário e devem ser explicitamente *desbloqueados* antes que possam ser alterados.

[TIP]
====

Você pode xref:/setup/data-management/backup_restore/configuration_backup.adoc[fazer um backup dos itens de configuração]. Observe que o status de bloqueio dos itens de configuração não será exportado como parte de um backup de configuração.
====

