= Options d'authentification
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability auto-hébergé

Par défaut, SUSE Observability est configuré avec xref:/setup/security/authentication/file.adoc[une authentification par mot de passe unique], utilisant l'administrateur et un mot de passe aléatoire xref:/setup/install-stackstate/initial_run_guide.adoc#_default_username_and_password[configuré lors de l'installation]. Cela authentifie les utilisateurs avec un simple secret sur le serveur. Cependant, ce n'est pas une configuration prête pour la production.

Pour une meilleure sécurité, SUSE Observability peut être configuré pour utiliser exactement l'un des mécanismes d'authentification suivants (remplaçant l'administrateur standard) :

* xref:/setup/security/authentication/single_password.adoc[Mot de passe unique]
* xref:/setup/security/authentication/file.adoc[Basé sur les fichiers]
* xref:/setup/security/authentication/ldap.adoc[LDAP]
* xref:/setup/security/authentication/oidc.adoc[Open ID Connect (OIDC)]
* xref:/setup/security/authentication/keycloak.adoc[KeyCloak (une version spécialisée de l'OIDC)]

[NOTE]
====
La configuration de l'authentification fait partie du chart Helm ; toute modification déclenchera automatiquement le redémarrage des pods concernés.
====


== Rôles utilisateur

Lorsqu'un utilisateur a été authentifié, les permissions pour cet utilisateur sont généralement attribuées en fonction des rôles que l'utilisateur possède. La documentation pour les mécanismes d'authentification spécifiques contient également des exemples sur la façon de mapper les rôles ou groupes des systèmes externes aux 4 rôles standard de SUSE Observability :

* *Invité* – peut consulter les informations sans pouvoir apporter de modifications.
* *Dépanneur Kubernetes* – peut consulter toutes les informations et modifier la configuration des moniteurs et des métriques.
* *Utilisateur avancé* – peut consulter et modifier l'ensemble de la configuration et installer des StackPacks.
* *Administrateur* - capable de voir et de changer le contenu de SUSE Observability. Par exemple, consulter l'ensemble de la configuration, installer des StackPacks, attribuer et révoquer les permissions des utilisateurs, et télécharger (de nouvelles versions de) StackPacks.

Lorsqu'il s'agit de choisir les rôles à attribuer à vos utilisateurs, il est fortement recommandé de limiter le nombre d'Administrateurs de Plateforme et d'Administrateurs à un petit groupe. Par exemple, seulement les ingénieurs responsables de l'installation de SUSE Observability et de la configuration initiale. Les administrateurs peuvent gérer l'accès à SUSE Observability et décider quels StackPacks peuvent être utilisés. Vous pouvez déléguer l'installation de StackPacks et d'autres ajustements fins de la configuration à un plus grand nombre d'utilisateurs avec le rôle d'Utilisateur avancé. Les utilisateurs Administrateurs de Plateforme peuvent vider la base de données, changer les paramètres de conservation des données, consulter les journaux et effectuer d'autres tâches de gestion de la plateforme.

Il est également possible d'ajouter d'autres rôles, voir la page xref:/setup/security/rbac/rbac_roles.adoc[Rôles (RBAC)] et les autres xref:/setup/security/rbac/README.adoc[pages de documentation RBAC]
