= Mot de passe unique
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hébergé

Par défaut, {stackstate-product-name} est configuré avec une configuration de mot de passe unique, xref:/k8s-suse-rancher-prime.adoc#_installation[configuré lors de l'installation]. Cela authentifie les utilisateurs avec un mot de passe unique qui doit être fourni lors de l'installation. 

C'est la manière la plus simple de commencer avec {stackstate-product-name}, mais pour la production, l'une des autres xref:/setup/security/authentication/authentication_options.adoc[options d'authentification] est recommandée.

== Obtenez le mot de passe d'un secret externe

Lorsque le mot de passe par défaut doit provenir d'un secret externe, suivez xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[ces étapes] mais remplissez les données suivantes :

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  default_password: <base64 of the encoded password>
----

L'encodage du mot de passe peut être l'un de ceux-ci : +
* Pour un mot de passe en texte clair, fournissez : `$plain$your-password` (`$plain$` est un préfixe indiquant du texte clair) +
* Pour un mot de passe bcrypted, fournissez : `bcrypt-hashed-password`. Créer un hachage bcrypted du mot de passe peut être fait en utilisant `htpasswd -bnBC 10 "" <password> | tr -d ':\n'`.

== Reportez-vous également à la section

* xref:/setup/security/authentication/authentication_options.adoc[Options d'authentification]
* xref:/setup/security/rbac/rbac_permissions.adoc#_predefined_roles[Permissions pour les rôles {stackstate-product-name} prédéfinis]
* xref:/setup/security/rbac/rbac_roles.adoc[Créer des rôles RBAC]
* xref:/setup/security/external-secrets.adoc#_getting_authentication_data_from_an_external_secret[Secrets externes]
