= ロールベースのアクセス制御（RBAC）
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自己ホスト型

アクセス管理は、特定のトポロジ要素、メトリックデータ、トレース、UI要素へのアクセスや、呼び出せるAPIの管理に役立ちます。

RBACは、SUSE Observabilityリソースの詳細なアクセス管理を提供する認可システムであり、ユーザー権限の監査やアクセス権の問題修正を簡単に行う方法です。

== RBACを使用して何ができますか？

RBACを使用してできることの例を以下に示します：

* 1人のユーザーには開発クラスターのみへのアクセスを許可し、別のユーザーには本番クラスターと開発クラスターの両方へのアクセスを許可、3人目のユーザーには開発クラスターと本番クラスター内の1つのネームスペースへのアクセスを許可します。
* 少数のユーザーにSUSE Observabilityのセットアップと設定を行う管理者ロールを付与します。すべての開発者にトラブルシューティングロールを付与し、すべてのトポロジ、メトリック、トレース、ログ、イベントを表示できるようにしますが、設定機能は制限されます。

== SUSE Observabilityにおけるロールとは何ですか？

SUSE Observabilityにおけるロールは、構成された主体と一連のxref:/setup/security/rbac/rbac_permissions.adoc[権限]の組み合わせです。SUSE Observabilityにおけるロールのセットアッププロセスは、xref:/setup/security/rbac/rbac_roles.adoc[ロールのセットアップ方法]に記載されています。

== RBACロールのソース

ロールは複数の方法で定義できます。 すべてが同じxref:/setup/security/rbac/rbac_permissions.adoc[権限]を使用します。

* **設定** - SUSE Observabilityのxref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_configuration_file[helm values]内
* **動的** - xref:setup/security/rbac/rbac_roles.adoc#_custom_roles_via_the_cli[`sts` CLI を使用する]
* **Kubernetesからマッピングされた** - xref:/setup/security/rbac/rbac_rancher.adoc[Kubernetesの`Roles`と`RoleBindings`をマッピングする]

== RBACの設定に関する詳細

* xref:/setup/security/rbac/rbac_permissions.adoc[権限]
* xref:/setup/security/rbac/rbac_roles.adoc[ロールのセットアップ方法]
* xref:/setup/security/rbac/rbac_rancher.adoc[Rancherとの併用]
* xref:/setup/security/rbac/rbac_scopes.adoc[スコープ]
* xref:/setup/security/authentication/README.adoc[認証を設定する方法]
