= SUSE Observability ドキュメント
:revdate: 2025-07-10
:page-revdate: {revdate}

これは最新の SUSE Observability ドキュメントです。左側のコンテンツメニューからトピックを選択してください。

古いバージョンのドキュメントについては、https://archivedocs.stackstate.com[アーカイブ]を使用してください。

== はじめに

Rancher Prime ユーザーの場合は xref:/k8s-suse-rancher-prime.adoc[Rancher Prime はじめにガイド] を、SUSE Cloud Observability ユーザーの場合は xref:/k8s-quick-start-guide.adoc[クイックスタートガイド] を、AWS で SUSE Cloud Observability を実行している場合は xref:/suse-cloud-observability-quick-start-guide.adoc[SUSE Cloud Observability クイックスタートガイド] をご覧ください。

== 何か見つかりませんか？

右上の検索バーを使用してください。ドキュメントが不足していると思われる場合は、https://scc.suse.com/[SUSE Observability サポートサイト] にお知らせください。

== トラブルシューティングとサポート

不明な点はありますか？ノベルがお手伝いします。https://scc.suse.com/[SUSE Observability サポートサイト] でサポートチームを見つけてください。

== SUSE Observability 自己ホスト型

SUSE Observability Self-hosted を使用して、独自のデータセンターやクラウドから広範な技術を監視します。

xref:/setup/install-stackstate/requirements.adoc[SUSE Observability 自己ホスト型]

== SUSE Cloud Observability

SUSE Cloud Observability を使用して、Kubernetes や AWS サービスなどのクラウド技術を監視します。

xref:/suse-cloud-observability/user-management.adoc[SUSE Cloud Observability ドキュメント]
