= Gestion personnalisée des secrets k8s
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-10-27
:page-revdate: {revdate}

== Présentation

L'agent SUSE Observability prend en charge la spécification du nom d'un secret personnalisé contenant la clé API et le token d'autorisation du cluster. Cette fonctionnalité est utile pour les utilisateurs qui souhaitent gérer leurs propres secrets et éviter la création automatique de secrets par le chart Helm.

NOTE: *Il existait une méthode précédente pour spécifier cela qui n'est plus prise en charge, voir la xref:/setup/agent/k8s-custom-secrets-setup-deprecated.adoc[méthode dont la prise en charge a été cessée].*

== Le chart Helm

=== Options de configuration

* `global.apiKey.fromSecret` : Spécifiez un nom de secret préexistant résidant dans le même espace de noms qui contient un champ `STS_API_KEY` contenant la clé API.
* `global.clusterAgentAuthToken.fromSecret` : Spécifiez un nom de secret préexistant résidant dans le même espace de noms qui contient un champ `STS_CLUSTER_AGENT_AUTH_TOKEN` contenant un token pour sécuriser les connexions entre le cluster et les agents de nœuds.

=== Behavior Description

* *Création automatique de secrets*: Par défaut, le chart nécessite qu'un `stackstate.apiKey` soit spécifié et créera un secret par lui-même. Le `STS_CLUSTER_AGENT_AUTH_TOKEN` est généré automatiquement.
* *Gestion personnalisée des secrets*: Lors de la substitution des champs `fromSecret`, la clé API et le token d'autorisation du cluster seront pris à partir de ces secrets.
* *Omission implicite*: Lorsque vous spécifiez que vous souhaitez gérer vos propres secrets, le chart ignorera les valeurs pour `stackstate.apiKey` et `stackstate.cluster.authToken`.

== Comment utiliser dans values.yaml

. *Utilisation de la création automatique de secrets (par défaut)*:
+
[,yaml]
----
 stackstate:
   apiKey: "<your api key>"
----

. *Gestion de ses propres secrets*:
+
[,yaml]
----
 global:
   apiKey:
     fromSecret: "name-of-my-api-key-secret"
   clusterAgentAuthToken:
     fromSecret: "name-of-my-cluster-agent-auth-token-secret"
----
