= Configuration des secrets personnalisés k8s (Cesser la prise en charge)
:revdate: 2025-10-27
:page-revdate: {revdate}

== Présentation

L'agent SUSE Observability prend en charge la spécification du nom d'un secret personnalisé contenant la clé API et le token d'autorisation du cluster. Cette fonctionnalité est utile pour les utilisateurs qui souhaitent gérer leurs propres secrets et éviter la création automatique de secrets par le chart Helm.

[CAUTION]
====
*Cette méthode de personnalisation des secrets n'est plus prise en charge et est incompatible avec la fonctionnalité RBAC.*

Veuillez utiliser xref:/setup/agent/k8s-custom-secrets-setup.adoc[la nouvelle méthode] pour utiliser des secrets externes.
====


== Le chart Helm

=== Options de configuration

* `stackstate.manageOwnSecrets` : Un indicateur booléen qui détermine si l'utilisateur souhaite gérer ses propres secrets. La valeur par défaut est `false`.
* `stackstate.customSecretName` : (Optionnel) Nom du secret personnalisé à créer par l'utilisateur. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.
* `stackstate.customApiKeySecretKey` : (Optionnel) Nom de la clé pour la clé API dans le secret personnalisé. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.
* `stackstate.customClusterAuthTokenSecretKey` : (Optionnel) Nom de la clé pour le jeton d'autorisation du cluster dans le secret personnalisé. Requis si `stackstate.manageOwnSecrets` est défini sur `true`.

=== Behavior Description

* *Création automatique de secrets* : Par défaut, le chart continue de créer automatiquement des secrets comme auparavant si `stackstate.manageOwnSecrets` est défini sur `false`.
* *Gestion de secrets personnalisés* : Si `stackstate.manageOwnSecrets` est défini sur `true`, le chart s'attend à ce que l'utilisateur fournisse le nom du secret personnalisé (`stackstate.customSecretName`) ainsi que les clés pour la clé API et le jeton d'autorisation (`stackstate.customApiKeySecretKey` et `stackstate.customClusterAuthTokenSecretKey`, respectivement).
* *Omission implicite* : Lors de la spécification que vous souhaitez gérer vos propres secrets, le chart ignorera les valeurs pour `stackstate.apiKey` et `stackstate.cluster.authToken`.
+
== Comment utiliser dans values.yaml

. *Utilisation de la création automatique de secrets (par défaut)*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: false
   apiKey: "<your api key>"
----

. *Gestion de ses propres secrets*:
+
[,yaml]
----
 stackstate:
   manageOwnSecrets: true
   customSecretName: my-custom-secret
   customApiKeySecretKey: api-key
   customClusterAuthTokenSecretKey: auth-token
----
