= Configuration de l'agent Kubernetes SUSE Observability pour les connexions proxy
:revdate: 2025-07-10
:page-revdate: {revdate}

L'agent Kubernetes SUSE Observability vous permet de configurer les paramètres de proxy HTTP ou HTTPS pour les connexions qu'il initie.

== Proxy pour la communication avec SUSE Observability

Pour configurer l’agent afin qu’il utilise un proxy pour les connexions vers le backend SUSE Observability, vous pouvez utiliser la configuration Helm.

=== Configuration Helm

==== Via le fichier `values.yaml`

. Ouvrez votre fichier de chart Helm `values.yaml`.
. Localisez la configuration `global.proxy.url` et spécifiez l'URL du proxy :
+
[,yaml]
----
 global:
   proxy:
     url: "https://proxy.example.com:8080"
----

. En option, si le proxy n'a pas de certificat signé, désactivez la vérification SSL en définissant `global.skipSslValidation` sur `true` :
+
[,yaml]
----
 global:
   skipSslValidation: true
----

==== Via le drapeau de ligne de commande

. Lors de l'installation du chart Helm, utilisez le drapeau `--set` pour spécifier l'URL du proxy :
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.proxy.url="https://proxy.example.com:8080"
----

. Pour désactiver la validation SSL via la ligne de commande, utilisez :
+
[,bash]
----
 helm install suse-observability-agent suse-observability/suse-observability-agent --set global.skipSslValidation=true
----
