= Certificats pour l'injection d'un sidecar permettant le traçage des requêtes
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability

Le xref:/setup/agent/k8sTs-agent-request-tracing.adoc#_enabling_the_trace_header_injection_sidecar[mécanisme d'injection de sidecar], qui s'active lors de l'utilisation de `--set httpHeaderInjectorWebhook.enabled=true` lors de l'installation de l'agent, crée un certificat auto-signé et utilise un `ClusterRole` qui accorde un accès en écriture aux objets `Secret` et `MutatingWebhookConfiguration` dans le cluster Kubernetes.

Si, pour des raisons de sécurité, il est indésirable de créer `ClusterRoles` qui accordent des droits d'écriture à l'échelle du cluster, ou s'il existe des moyens alternatifs de fournir un certificat :

. Générez un certificat auto-signé <<_generate_a_certificate_locally,localement>>.
. Utilisez le k8s https://cert-manager.io/[cert-manager] (s'il est déjà présent dans le cluster) <<_generate_a_certificate_using_the_cert_manager,avec un `ClusterIssuer`>>.

== Générez un certificat localement

Pour générer un certificat localement, suivez les étapes suivantes :

. Téléchargez le script de génération de certificat et exécutez-le pour produire un fichier de valeurs helm (`tls_values.yaml`) avec le bon certificat :
+
----
wget https://raw.githubusercontent.com/StackVista/http-header-injector/main/scripts/generate_ca_cert.sh
chmod +x generate_ca_cert.sh
./generate_ca_cert.sh <helm-agent-release-name> <helm-agent-namespace>
----
+
Assurez-vous d'utiliser le nom de release qui sera utilisé dans la commande helm et l'espace de noms, sinon le certificat sera invalide.

. Installez l'agent en ajoutant la configuration supplémentaire avec `--set httpHeaderInjectorWebhook.enabled=true -f tls_values.yaml` dans la commande helm.

== Générez un certificat en utilisant le cert-manager

Si votre cluster a le https://cert-manager.io/[cert-manager] installé, et un `ClusterIssuer` configuré, il est possible d'utiliser le certificat émis par le `ClusterIssuer` dans l'agent pour l'injecteur de sidecar. Pour ce faire, ajoutez les arguments de ligne de commande suivants pour installer l'agent : `--set httpHeaderInjectorWebhook.enabled=true --set-string httpHeaderInjectorWebhook.webhook.tls.mode="cert-manager" --set-string httpHeaderInjectorWebhook.webhook.tls.certManager.issuer="<my-cluster-issuer>"`. Assurez-vous de remplacer my-cluster-issuer par le nom de l'émetteur dans votre cluster.
