= API Keys
:revdate: 2025-07-22
:page-revdate: {revdate}
:description: SUSE Observability

API keys are used for sending telemetry data to SUSE Observability. There are three types of API keys:

* **Service Token** - With this key you can scope the data to be ingested.  It also offers expiration dates.  See xref:/use/security/k8s-service-tokens.adoc#_authenticate_using_service_tokens_for_data_ingestion[Service Tokens].
* **Receiver API Key** - This key is typically generated during the initial installation of your SUSE Observability instance, and it never expires.
* **Ingestion API Key** (Deprecated) - You can create Ingestion API Keys using the SUSE Observability CLI (STS). These keys offer expiration dates, requiring periodic rotation for continued functionality.

The receiver API key can be found in your `values.yaml` as the `receiverApiKey`, but you can also find it in the installation instructions of the stackpacks. For example if you installed the Kubernetes stackpack:

. Open SUSE Observability
. Navigate to StackPacks and select the Kubernetes StackPack
. Open one of the installed instances
. Scroll down to the first set of installation instructions. It shows the API key as `STACKSTATE_RECEIVER_API_KEY` in text and as `'stackstate.apiKey'` in the command.

== Ingestion API Keys (`Deprecated`)

Ingestion API Keys were used by external tools to ingest data (such as metrics, events and traces) to the SUSE Observability cluster.
These tools include the STS Agent or/and OTel Collector. The recommended authentication mechanism is through xref:/use/security/k8s-service-tokens.adoc#_authenticate_using_service_tokens_for_data_ingestion[Service Tokens].

== More info

* xref:/use/security/k8s-service-tokens.adoc[Service tokens]
