= API Keys
:revdate: 2025-07-22
:page-revdate: {revdate}
:description: SUSE Observability

Using an API key is the main method of authenticating against SUSE Observability for sending telemetry data to SUSE Observability. In a helm agent install this is done by setting the `stackstate.apiKey` helm variable.

An API Key can be obtained in various ways from the platform. The typical way is through the xref:/k8s-suse-rancher-prime.adoc#_installing_the_suse_observability_agent[StackPack install flow], which uses a Service Token from the platform. The following other ways for getting an API Key exist:

* **Service Token** - With this key you can scope the data to be ingested. A service token is required when installing with xref:/setup/security/rbac/rbac_rancher.adoc[Rancher RBAC support]. It also offers expiration dates. See xref:/use/security/k8s-service-tokens.adoc#_authenticate_using_service_tokens_for_data_ingestion[Service Tokens].
* **Bootstrap Service Token** - This can be used to setup a service token for data ingestion and RBAC, to be used as API key. This is the preferred method to create a key before installation. See xref:/setup/security/authentication/service_tokens.adoc#_set_up_a_bootstrap_service_token[Bootstrap Service Tokens].
* **Receiver API Key** - This key is typically generated during the initial installation of your SUSE Observability instance, and it never expires. It is not scoped, so can be used for all agent. However, RBAC data cannot be ingested with the receiver API Key. For this reason this method will be replaced in the long run.
* **Ingestion API Key** (Deprecated) - You can create Ingestion API Keys using the SUSE Observability CLI (STS). These keys offer expiration dates, requiring periodic rotation for continued functionality.

== Ingestion API Keys (`Deprecated`)

Ingestion API Keys were used by external tools to ingest data (such as metrics, events and traces) to the SUSE Observability cluster.
These tools include the STS Agent or/and OTel Collector. The recommended authentication mechanism is through xref:/use/security/k8s-service-tokens.adoc#_authenticate_using_service_tokens_for_data_ingestion[Service Tokens].

== More info

* xref:/use/security/k8s-service-tokens.adoc[Service tokens]
