= Remplacer la configuration par défaut
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: {stackstate-product-name} Auto-hébergé

Un certain nombre de valeurs peuvent être définies dans le https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} Helm chart]. Par exemple, il est possible de personnaliser le `tolerations` et le `nodeSelectors` pour chacun des composants. Vous pouvez également ajouter une configuration personnalisée et inclure des variables d'environnement

== Configuration personnalisée pour {stackstate-product-name} `api`

Pour le service {stackstate-product-name} `api`, la configuration personnalisée peut être directement intégrée dans le Helm chart. C'est la méthode conseillée pour remplacer la configuration par défaut fournie par {stackstate-product-name} et elle est particulièrement pratique pour personnaliser l'authentification. La configuration définie de cette manière sera disponible dans le fichier de configuration {stackstate-product-name} au format https://github.com/lightbend/config/blob/master/HOCON.md[HOCON].

Par exemple, vous pouvez définir un "lien de mot de passe oublié" personnalisé pour la page de connexion {stackstate-product-name} :

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      config: |
        stackstate.api.authentication.forgotPasswordLink =
        "https://www.stackstate.com/forgotPassword.html"
----

--
====

[NOTE]
====
Notez que la configuration personnalisée définie ici sera remplacée par xref:/setup/install-stackstate/kubernetes_openshift/customize_config.adoc#_environment_variables[les variables d'environnement].
====


== Variables d'environnement

La configuration de tous les services {stackstate-product-name} (`receiver`, `k2es-*`, `correlation` et `api`) peut être personnalisée à l'aide de variables d'environnement. Les variables d'environnement sont spécifiées dans le fichier `values.yaml` et peuvent être soit `secret` (comme les mots de passe) soit `open` (pour les valeurs normales). Pour convertir un élément de configuration en nom de variable d'environnement, remplacez `.` par `_` et ajoutez le préfixe `CONFIG_FORCE_`.

[,text]
----
# configuration item
stackstate.api.authentication.forgotPasswordLink

# environment variable name
CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink
----

Par exemple, vous pouvez définir un "lien de mot de passe oublié" personnalisé pour la page de connexion {stackstate-product-name} :

[tabs]
====
values.yaml::
+
--

[,text]
----
stackstate:
  components:
    api:
      extraEnv:
        # The value for open env vars is defined on the deployment
        open:
          CONFIG_FORCE_stackstate_api_authentication_forgotPasswordLink: "https://www.stackstate.com/forgotPassword.html"
        # The value for secret env vars is defined in a secret and referenced from the deployment
        secret:
          CONFIG_FORCE_some_config_with_sensitive_data: "data-stored-in-secret"
----

--
====

[NOTE]
====
Pour le service {stackstate-product-name} `api`, les variables d'environnement remplaceront <<_custom_configuration_for_suse_observability_api,la configuration personnalisée définie à l'aide de `config`>>.
====


* Tous les détails sur la nomination de tous les différents services peuvent être trouvés dans le https://github.com/StackVista/helm-charts/tree/master/stable/suse-observability[{stackstate-product-name} Helm chart readme].
* Trouvez plus de détails sur xref:/setup/security/authentication/README.adoc[la personnalisation de l'authentification].
