ifdef::ss-ff-stackpacks2_enabled[]
= Presentation Projections
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-11
:page-revdate: {revdate}
:description: Component Presentation Schema

== Projections

Projections extract relevant information from a component and define how that should be presented to the user.  Generally a xref:/setup/custom-integrations/presentation/interpolation.adoc[CEL expression] is used for data extraction, or a PromQL query string is interpolated.

Not every projection can be used in every context; the available projections and where they can be used is:

[cols="1,^1,^1"]
|===
|Projection |Overview | Highlight

|TextProjection           | icon:check[role="green"] | icon:check[role="green"]
|HealthProjection         | icon:check[role="green"] | icon:check[role="green"]
|DurationProjection       | icon:check[role="green"] | icon:check[role="green"]
|RatioProjection          | icon:check[role="green"] | icon:check[role="green"]
|NumericProjection        | icon:check[role="green"] | icon:check[role="green"]
|MetricProjection         | icon:check[role="green"] | icon:check[role="green"]
|ComponentLinkProjection  | icon:check[role="green"] | icon:check[role="green"]
|ContainerImageProjection | icon:check[role="green"] | icon:check[role="green"]
|MapProjection            | icon:times[role="red"]   | icon:check[role="green"]
|===

=== PromQL interpolation

In a promql query, these variables can be used to create label selectors (e.g. `the_metric{namespace=${tags.namespace},ip=${properties.ip_address}}`)

[cols="1,1,3"]
|===
|Variable               | Type                | Description

|name                   | string              | The name of the component
|type                   | string              | The type of the component
|layer                  | string              | The layer of the component
|domain                 | string              | The domain of the component
|tags                   | map<string,string>  | Labels of the component, in key-value pairs
|properties             | map<string,dyn>     | Properties of the component
|===


[,yaml]
----
_type: 'TextProjection'
value: cel:string             # Cel string for the text to display
asTag: boolean                # Optional - should the text be rendered as a tag
----

[,yaml]
----
_type: 'HealthProjection'
value: cel:string             # Cel string that represents a valid HealthState
----

[,yaml]
----
_type: 'DurationProjection'
startTime: cel:string         # Cel string in ISO8601 format for start time
endTime: cel:string           # Optional - Cel string in ISO8601 format for end time
----

[,yaml]
----
_type: 'RatioProjection'
numerator: cel:number         # Cel number for the numerator
denominator: cel:number       # Cel number for the denominator
status: cel:string            # Optional - expression that evaluates to a valid HealthState
----

[,yaml]
----
_type: 'NumericProjection'
value: cel:number             # Cel number for the value
decimalPlaces: integer        # Optional - number of decimal places to display
unit: string                  # Optional - unit of the number
----

[,yaml]
----
_type: 'MetricProjection'
query: string                 # Parametrized PromQL query
showChart: boolean            # Optional - should a chart be shown on an overview
decimalPlaces: integer        # Optional - number of decimal places to display
unit: string                  # Optional - unit of the metric
----

[,yaml]
----
_type: 'ComponentLinkProjection'
name: cel:string              # Cel string for the name of the link
identifier: cel:string        # Cel string that creates a valid identifier xref:/configure/topology/identifiers.adoc[identifiers]
----

[,yaml]
----
_type: 'ContainerImageProjection'
imageId: cel:string           # Cel expression for the image
imageName: cel:string         # Cel expression for a name for the image
----

[,yaml]
----
_type: 'MapProjection'
value: cel:map<string,string> # Cel map<string,string> with key value pairs
asTags: boolean               # Optional (default: true): should the entries be rendered as tags
----

endif::ss-ff-stackpacks2_enabled[]
