= 关于 StackPacks。
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自托管 v5.1.x。

== 概述

StackPacks 扩展了 SUSE Observability 的功能，并提供与外部系统的自动集成。它们可以从 SUSE Observability 的 StackPacks 页面轻松安装和卸载。

StackPack 有两种类型 - 附加组件和集成。可用的 StackPack 附加组件和集成可以在 SUSE Observability UI 的 *StackPacks* 页面找到。

== 安装或卸载 StackPack。

StackPacks 可以从 SUSE Observability 的 *StackPacks* 页面安装和卸载。提供了安装和卸载 StackPack 的完整说明。

[NOTE]
====
*请注意以下几点：*

* StackPack 可能需要 *manual* 安装步骤或外部系统的配置。请仔细阅读提供的说明。
* 当 StackPack 或 StackPack 实例被卸载时，*通过 StackPack（实例）接收的所有数据将从 SUSE Observability 中删除。*
* 在外部系统中对 StackPack 组件的任何（手动）配置或安装可能需要单独卸载。

====


=== StackPack 实例。

某些 StackPacks 允许您连接到外部系统上的多个帐户。每个帐户在 StackPack 的单独实例中配置。

例如，AWS StackPack 可以连接到多个 AWS 帐户，并将所有帐户的信息合并到 SUSE Observability 中。对于每个帐户，配置一个单独的 SUSE Observability 实例，以接收来自该 AWS 帐户的数据所需的信息。

== 升级 StackPack。

[CAUTION]
====
当 StackPack 升级时，*对该 StackPack 的配置项所做的任何更改将被覆盖。*有关详细信息，请参见 xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项]。
====


如果有新的 StackPack 版本可用，SUSE Observability UI StackPack 页面将显示警报，您将有机会查看升级详细信息并阅读发布说明。如果新版本是当前安装版本的小型升级，您也可以从这里升级 StackPack。

=== 新的小型 StackPack 版本。

要升级到新的小型 StackPack 版本，请在 SUSE Observability UI 的 StackPack 页面上点击 *立即升级*。

请注意，升级时所有 StackPack 配置项将被覆盖。要继续使用对这些项所做的任何更改，请在升级 StackPack 时选择 *保留* 现有配置。有关详细信息，请参见 xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项]。

=== 新的大型 StackPack 版本

[CAUTION]
====
当 StackPack 升级时，*对该 StackPack 的配置项所做的任何更改将被覆盖*。有关详细信息，请参见 xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[锁定的配置项]。
====


要升级到新的大型 StackPack 版本，请 xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[卸载并重新安装] StackPack。

[TIP]
====

在升级后继续使用对自定义 StackPack 配置项所做的更改：

. 在升级之前，导出每个自定义项：
 ** 前往 SUSE Observability UI 的 *设置* 页面。
 ** 在每个自定义项的 *...* 菜单中点击 *导出*。
. 升级 StackPack（卸载并重新安装）。
. 更改每个导出项的 `name` 和 `identifier`：
 ** 在文本编辑器中打开导出文件。
 ** 编辑顶层 `name` 和 `identifier` 字段。
 ** 保存导出。
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[导入] 更新后的导出文件。
. 自定义配置项现在将在 SUSE Observability 中可用，并可以复制到新安装的 StackPack 配置项中。

====


== 锁定的配置项

StackPacks 包含安装 StackPack（实例）时安装的 SUSE Observability 的配置信息。其中可能包括组件模板、功能、组件操作和视图。当 StackPack 升级时，*之前版本 StackPack 安装的配置项将被新版本 StackPack 的配置项覆盖。*这意味着对这些配置项所做的任何手动更改将在 StackPack 升级时被覆盖。

为了防止用户对 StackPack 安装的配置项进行更改，这些配置项在升级时将被 *默认锁定*。这意味着它们受到保护，用户必须明确 *解锁* 后才能更改。

[TIP]
====

您可以 xref:/setup/data-management/backup_restore/configuration_backup.adoc[备份配置项]。请注意，配置项的锁定状态不会作为配置备份的一部分导出。
====

