= Getting Started with Open Telemetry
:description: SUSE Observability

image::otel/open-telemetry.svg[Open Telemetry collector and 2 instrumented applications sending metrics and traces to SUSE Observability]

SUSE Observability supports https://opentelemetry.io/docs/what-is-opentelemetry/[Open Telemetry]. Open Telemetry is a set of standardized protocols and an open-source framework to collect, transform and ship telemetry data such as traces, metrics and logs. Open telemetry supports a wide variety of programming languages and platforms.

SUSE Observability has support for both metrics and traces and adds the Open Telemetry metrics and traces to the (Kubernetes) topology data that is provided by the SUSE Observability agent. Therefore it is still needed to also install the SUSE Observability agent. Support for logs and using Open Telemetry without the SUSE Observability agent is coming soon.

Open Telemetry consists of several different components. For usage with SUSE Observability, the xref:./languages/README.adoc[SDKs] to instrument your application and the xref:./collector.adoc[Open Telemetry collector] are the most important parts. We'll show how to configure both for usage with SUSE Observability.

If your application is already instrumented with Open Telemetry or with any other library that is supported by Open Telemetry, like Jaeger or Zipkin, the collector can be used to ship that data to SUSE Observability and no additional instrumentation is needed.

SUSE Observability requires the collector to be configured with specific processors and authentication to make sure all data used by SUSE Observability is available.

== References

* https://opentelemetry.io/docs/collector/[Open Telemetry collector] on the Open Telemetry documentation
* https://opentelemetry.io/docs/languages/[SDKs to instrument your application] on the Open Telemetry documentation
