= StackPacksについて
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability 自己ホスト型 v5.1.x

== 概要

StackPacksはSUSE Observabilityの機能を拡張し、外部システムとの自動統合を提供します。StackPacksはSUSE ObservabilityのStackPacksページから簡単にインストールおよびアンインストールできます。

StackPackにはアドオンと統合の2種類があります。利用可能なStackPackのアドオンと統合は、SUSE Observabilityの*StackPacks*ページで確認できます。

== StackPackをインストールまたはアンインストールする

StackPacksはSUSE Observabilityの*StackPacks*ページからインストールおよびアンインストールできます。StackPackのインストールおよびアンインストールに関する完全な手順が提供されています。

[NOTE]
====
*次のことに注意してください。*

* StackPackには、*manual*インストール手順や外部システムの設定が必要な場合があります。提供された手順を注意深くお読みください。
* StackPackまたはStackPackインスタンスがアンインストールされると、*StackPack（インスタンス）を介して受信したすべてのデータがSUSE Observabilityから削除されます。*
* 外部システムにおけるStackPackコンポーネントの（手動）設定やインストールは、別途アンインストールする必要がある場合があります。

====


=== StackPackインスタンス

一部のStackPacksでは、外部システムの複数のアカウントに接続できます。各アカウントはStackPackの別々のインスタンスで設定されます。

例えば、AWS StackPackは複数のAWSアカウントに接続し、すべてのアカウントの情報をSUSE Observabilityに統合できます。各アカウントについて、データを受信するために必要な情報を持つ別々のSUSE Observabilityインスタンスが設定されます。

== StackPackをアップグレードする

[CAUTION]
====
StackPackがアップグレードされると、*そのStackPackの設定項目に対する変更は上書きされます*。詳細については、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目]を参照してください。
====


新しいStackPackのバージョンが利用可能な場合、SUSE Observability UIのStackPackページにアラートが表示され、アップグレードの詳細を表示し、リリースノートを読むオプションがあります。新しいリリースが現在インストールされているバージョンからのマイナーアップグレードである場合、ここからStackPackをアップグレードすることもできます。

=== 新しいマイナーStackPackバージョン

新しいマイナーバージョンのStackPackにアップグレードするには、SUSE Observability UIのStackPackページで*今すぐアップグレード*をクリックしてください。

アップグレード時にすべてのStackPack設定項目が上書きされることに注意してください。これらに加えた変更を引き続き使用するには、StackPackをアップグレードする際に既存の設定を*キープ*することを選択してください。詳細については、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目]を参照してください。

=== 新しいメジャーStackPackバージョン

[CAUTION]
====
StackPackがアップグレードされると、*そのStackPackの設定項目に対する変更は上書きされます*。詳細については、xref:/stackpacks/about-stackpacks.adoc#_locked_configuration_items[ロックされた設定項目]を参照してください。
====


新しいメジャーバージョンのStackPackにアップグレードするには、xref:/stackpacks/about-stackpacks.adoc#_install_or_uninstall_a_stackpack[アンインストールして再インストール]してください。

[TIP]
====

アップグレード後にカスタマイズされたStackPack設定項目に加えた変更を引き続き使用します：

. アップグレードする前に、各カスタマイズされたアイテムをエクスポートしてください：
 ** SUSE Observability UIの*設定*ページに移動します。
 ** 各カスタマイズされたアイテムの*...*メニューで*エクスポート*をクリックします。
. StackPackをアップグレードします（アンインストールして再インストール）。
. 各エクスポートされたアイテムの`name`と`identifier`を変更します：
 ** エクスポートファイルをテキストエディタで開きます。
 ** 最上位の`name`と`identifier`フィールドを編集します。
 ** エクスポートを保存します。
. xref:/setup/data-management/backup_restore/configuration_backup.adoc#_import_configuration[更新されたエクスポートファイルをインポート]します。
. カスタマイズされた設定項目は、SUSE Observabilityで利用可能になり、新しくインストールされたStackPack設定項目にコピーできます。

====


== ロックされた設定項目

StackPackには、StackPack（インスタンス）がインストールされるときにインストールされるSUSE Observabilityの設定情報が含まれています。その他のものの中には、コンポーネントテンプレート、関数、コンポーネントアクション、ビューが含まれる可能性があります。StackPackがアップグレードされると、*以前のバージョンのStackPackによってインストールされた設定項目は、新しいStackPackのものに上書きされます。*これは、これらの設定項目に対して行われた手動の変更が、StackPackがアップグレードされると上書きされることを意味します。

StackPackによってインストールされた設定項目がアップグレード時に上書きされるのを防ぐために、これらの設定項目はデフォルトで*ロックされています*。これは、ユーザーによって変更されることから保護されており、変更する前に明示的に*ロック解除する必要があります*。

[TIP]
====

xref:/setup/data-management/backup_restore/configuration_backup.adoc[設定項目のバックアップを作成することができます]。設定バックアップの一部として、設定項目のロック状態はエクスポートされないことに注意してください。
====

