= Externe Secrets
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability External Secrets

== Übersicht

SUSE Observability kann Geheimnisse wie Lizenzschlüssel, API-Schlüssel und Authentifizierungsschlüssel über die Helm-Installation aufnehmen, kann diese jedoch auch aus bereits bereitgestellten Geheimnissen beziehen.

Hier wird beschrieben, wie man dies konfiguriert.

== Lizenzschlüssel aus einem externen Geheimnis abrufen

Erstellen Sie ein Geheimnis im Namespace, in dem SUSE Observability installiert ist, in folgender Form und füllen Sie die Lücken aus:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  LICENSE_KEY: "<base64 of the license key>"
----

Fügen Sie Folgendes zu Ihrem Helm-Installationsbefehl hinzu, um das Geheimnis zu verwenden:

[,bash]
----
  --set 'stackstate.license.fromExternalSecret'='<custom-secret-name>'
----

== Benutzername und Passwort für E-Mail-Benachrichtigungen aus einem externen Geheimnis abrufen

Erstellen Sie ein Geheimnis im Namespace, in dem SUSE Observability installiert ist, in folgender Form und füllen Sie die Lücken aus:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  SMTP_USER_NAME: "<base64 of the smtp username>"
  SMTP_PASSWORD: "<base64 of the smtp password>"
----

Fügen Sie Folgendes zu Ihrem Helm-Installationsbefehl hinzu, um das Geheimnis zu verwenden:

[,bash]
----
  --set 'stackstate.email.server.auth.fromExternalSecret'='<custom-secret-name>'
----

== API-Schlüssel aus einem externen Geheimnis abrufen

Erstellen Sie ein Geheimnis im Namespace, in dem SUSE Observability installiert ist, in folgender Form und füllen Sie die Lücken aus:

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
  API_KEY: "<base64 of the API key>"
----

Fügen Sie Folgendes zu Ihrem Helm-Installationsbefehl hinzu, um das Geheimnis zu verwenden:

[,bash]
----
  --set 'stackstate.apiKey.fromExternalSecret'='<custom-secret-name>'
----

== Authentifizierungsdaten aus einem externen Geheimnis abrufen

Erstellen Sie ein Geheimnis im Namespace, in dem SUSE Observability installiert ist, in folgender Form.

[,yaml]
----
kind: Secret
metadata:
   name: "<custom-secret-name>"
type: Opaque
data:
   default_password: <base64 of bcrypted password>
----

Je nach gewählter Authentifizierungsmethode wird das `default_password` Feld durch unterschiedliche Daten ersetzt. Siehe die xref:/setup/security/authentication/authentication_options.adoc[Authentifizierungsoptionen] für weitere Informationen. In diesem Beispiel wird das xref:/setup/security/authentication/single_password.adoc[Einzelpasswort] setup verwendet.

Fügen Sie Folgendes zu Ihrem Helm-Installationsbefehl hinzu, um das Geheimnis zu verwenden:

[,bash]
----
  --set 'stackstate.authentication.fromExternalSecret'='<custom-secret-name>'
----
