= Install SUSE Observability
:revdate: 2025-07-14
:page-revdate: {revdate}
:description: SUSE Observability Self-hosted

== Before you start

[NOTE]
====
Extra notes for installing on:

* *Kubernetes clusters with limited permissions*: Read the xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc[required permissions].
* *Alibaba Cloud Container Service for Kubernetes (ACK)*: Read the xref:/setup/install-stackstate/kubernetes_openshift/ack.adoc[ACK installation notes].
* *OpenShift*: Refer to the xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift installation instructions].
====


Before you start the installation of SUSE Observability:

* Check the xref:/setup/install-stackstate/requirements.adoc[requirements] to make sure that your Kubernetes environment fits the setup that you will use (recommended, minimal or non- high availability).
* Check that you have the xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc[required permissions].
* Add the SUSE Observability helm repository to the local helm client:

[,text]
----
helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
helm repo update
----

== Install SUSE Observability

[NOTE]
====
For environments without internet access, also known as air-gapped environments, first follow xref:/k8s-suse-rancher-prime-air-gapped.adoc[these extra instructions].

Also, make sure to follow the air-gapped installation instructions whenever those are present for a step.
====


. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where SUSE Observability will be installed]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#create-values-yaml[Create `values.yaml` configuration file]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_configure_storage_class_optional[Configure storage class (Optional)]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Deploy SUSE Observability with Helm]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Access the SUSE Observability UI]


=== Create namespace

Start by creating the namespace where you want to install SUSE Observability and deploy the secret in that namespace. In our walkthrough we will use the namespace `suse-observability`:

[,text]
----
kubectl create namespace suse-observability
----

[#create-values-yaml]
=== Create `values.yaml` configuration file

The `values.yaml` file contains all configuration required to deploy {stackstate-product-name} including your license key, base URL, admin password, and sizing profile.

[NOTE]
====
*Before you continue:* Make sure you have the latest version of the Helm charts with `helm repo update`.
====

[tabs]
====
Recommended method::
+
--
[NOTE]
=====
The `global.suseObservability` configuration method is available starting from version `2.8.0`. For earlier versions, use the legacy method.
=====

Create a `values.yaml` file with the `global.suseObservability` configuration structure:

[source,yaml]
----
global:
  # Optional: Override image registry (defaults to registry.rancher.com)
  # Only needed for air-gapped environments or custom registries
  # imageRegistry: "your-private-registry.example.com"

  # Optional: Override storage class (uses cluster default if not set)
  # storageClass: "your-storage-class"

  suseObservability:
    # Required: Your SUSE Observability license key
    license: "YOUR-LICENSE-KEY"

    # Required: Base URL for SUSE Observability
    # Use http://localhost:8080 if ingress is not configured yet
    baseUrl: "https://observability.example.com"

    # Required: Sizing profile
    # Available: trial, 10-nonha, 20-nonha, 50-nonha, 100-nonha,
    #            150-ha, 250-ha, 500-ha, 4000-ha
    sizing:
      profile: "150-ha"

    # Required: Plain text admin password
    adminPassword: "your-password"
    # Instead of adminPassword you can provide a bcrypt hashed password with adminPasswordBcrypt
    # Generate with: htpasswd -bnBC 10 "" "your-password" | tr -d ':\n'
    # adminPasswordBcrypt: "$2a$10$..."

    # Optional: Receiver API key (auto-generated if not provided)
    # receiverApiKey: "your-receiver-api-key"

    # Optional: Pull secret for private registry
    # pullSecret:
    #   username: "registry-user"
    #   password: "registry-pass"
----

For more configuration options including affinity settings, see xref:/setup/install-stackstate/kubernetes_openshift/affinity.adoc[Configure Kubernetes Affinities].

--
Legacy method (Deprecated)::
+
--
[WARNING]
=====
This method is deprecated. For new installations, use the recommended method above. For existing installations using this method, see the xref:/setup/upgrade-stackstate/migrate-to-global-mode.adoc[migration guide] to transition to the new configuration format.
=====

You can generate the SUSE Observability configuration files by running a separate Helm Chart. This is the `suse-observability/suse-observability-values` chart:

[,text]
----
export VALUES_DIR=.
helm template \
  --set license='<your license>' \
  --set baseUrl='<suse-observability-base-url>' \
  --set sizing.profile='<sizing.profile>' \
  suse-observability-values \
  suse-observability/suse-observability-values --output-dir $VALUES_DIR
----

This command generates the files `$VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml`, `$VALUES_DIR/suse-observability-values/templates/sizing_values.yaml`, and `$VALUES_DIR/suse-observability-values/templates/affinity_values.yaml`.

[NOTE]
=====
The {stackstate-product-name} administrator passwords will be autogenerated by the above command and are output as comments in the generated `basicConfig.yaml` file. The actual values contain the `bcrypt` hashes of those passwords so that they're securely stored in the Helm release in the cluster.
=====

The values that can be passed to this chart are:

[cols="1,1,2"]
|===
| Configuration | Value | Description

| Basic Config generate
| `basicConfig.generate`
| Switch on or off the generation of the `basicConfig_values.yaml` file.

| Receiver API Key
| `receiverApiKey`
| The API key used by SUSE Observability to receive data from agents. This is a secret key that should be kept private. If you omit this, a random key will be generated for you.

| Base URL
| `baseUrl`
| The `<STACKSTATE_BASE_URL>`. The external URL for SUSE Observability that users and agents will use to connect. For example `+https://suse-observability.internal+`. If you haven't decided on an Ingress configuration yet, use `+http://localhost:8080+`. This can be updated later in the generated file.

| Username and password**
| `-u` `-p`
| The username and password used by SUSE Observability to pull images. For air-gapped environments these need to be the username and password for the local contaier registry.

| License key
| `license`
| The SUSE Observability license key.

| Default password
| `adminPassword`
| The password for the default user (`admin`) to access SUSE Observability's UI. Alternatively, you can provide a bcrypt hashed password using `adminPasswordBcrypt`. Only one of the two options can be used at the same time.

| Image Registry
| `imageRegistry`
| The registry where the SUSE Observability images are hosted. If not provided, the default value will be 'registry.rancher.com'. Only needed for air-gapped environments or custom registries.

| Pull Secret Username
| `pullSecret.username`
| The username used to pull images from the Docker registry where the SUSE Observability images are hosted. Only needed for custom registries.

| Pull Secret Password
| `pullSecret.password`
| The password used to pull images from the Docker registry where the SUSE Observability images are hosted. Only needed for custom registries.

| Sizing generate
| `sizing.generate`
| Switch on or off the generation of the `sizing_values.yaml` file.

| Sizing profile
| `sizing.profile`
| OneOf trial, 10-nonha, 20-nonha, 50-nonha, 100-nonha, 150-ha, 250-ha, 500-ha. Based on these profiles, you can generate the `sizing_values.yaml` file containing default sizes for the SUSE Observability resources and configuration to deploy in HA or Non-HA mode. For example, 10-nonha produces a `sizing_values.yaml` to deploy a NonHa SUSE Observability instance to observe a 10 node cluster in a Non High availability mode. Currently, moving from a Non-HA to an HA environment is not possible. If you expect that your environment will require observing around 150 nodes, then it's better to go with HA immediately.

| Pod AntiAffinity
| `affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution`
| Enforce that the replicas of the same data services are scheduled to different Kubernetes nodes. Only applicable for `HA` profiles. Either `true` or `false`. The default is `true` - scheduling to different nodes is enforced.
|===

[NOTE]
=====
Store the generated `basicConfig.yaml` and `sizing_values.yaml` files safely. You can reuse these files for upgrades, saving time and ensuring that {stackstate-product-name} continues to use the same API key. This is desirable as it means Agents and other data providers for {stackstate-product-name} won't need updating.
You can regenerate the files independently using the switches `basicConfig.generate=false` and `sizing.generate=false` to disable any of them while still keeping the previously generated version of the file in the `output-dir`.
=====

[NOTE]
=====
The {stackstate-product-name} Values chart generates affinity configurations that you can use with the main {stackstate-product-name} chart to control pod scheduling behavior. Refer to xref:/setup/install-stackstate/kubernetes_openshift/affinity.adoc[Configure Kubernetes Affinities] documentation for more information.
=====

--
====

=== Configure storage class (Optional)

{stackstate-product-name} uses the cluster's default storage class if not specified. You can optionally override this by setting `global.storageClass` in your `values.yaml` file.

[tabs]
====
Recommended method::
+
--
If you need to use a specific storage class, add it to your `values.yaml` file under `global.storageClass`:

[source,yaml]
----
global:
  storageClass: "your-storage-class"  # e.g., "local-path" for Rancher local-path provisioner
  suseObservability:
    # ... other configuration
----
--
Legacy method (Deprecated)::
+
--
Edit the file `$VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml` to add the "storageClass" configuration:

[,text]
----
# Source suse-observability-values/templates/baseConfig_values.yaml
global:
  storageClass: "your-storage-class" # Optional: override default storage class
----
--
====


=== Deploy {stackstate-product-name} with Helm

The recommended deployment of SUSE Observability is a production ready, high availability setup with many services running redundantly. If required, it's also possible to run SUSE Observability in a non-redundant setup, where each service has only a single replica. This setup is only recommended for a test environment.

For air-gapped environments follow the instructions for the air-gapped installations.

[tabs]
====
Recommended method::
+
--

To deploy {stackstate-product-name} on Kubernetes:

. Before you deploy:
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where {stackstate-product-name} will be installed]
 ** <<create-values-yaml,Create `values.yaml` configuration file>>
. Deploy the latest {stackstate-product-name} version to the `suse-observability` namespace with the following command:

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values values.yaml \
suse-observability \
suse-observability/suse-observability
----

Alternatively, deploy directly using `--set` flags without a values file:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --set global.suseObservability.license="YOUR-LICENSE-KEY" \
  --set global.suseObservability.baseUrl="https://observability.example.com" \
  --set global.suseObservability.sizing.profile="150-ha" \
  --set global.suseObservability.adminPassword='$2a$10$...' \
suse-observability \
suse-observability/suse-observability
----

--
Recommended method (Air-gapped)::
+
--

To deploy {stackstate-product-name} in an air-gapped setup on Kubernetes:

. Before you deploy:
 ** xref:/k8s-suse-rancher-prime-air-gapped.adoc[Follow these extra instructions for air-gapped installations].
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where {stackstate-product-name} will be installed]
 ** <<create-values-yaml,Create `values.yaml` configuration file>>
. Deploy the latest {stackstate-product-name} version to the `suse-observability` namespace with the following command:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values local-docker-registry.yaml \
  --values values.yaml \
suse-observability \
suse-observability/suse-observability
----

--
Legacy method (Deprecated)::
+
--

[WARNING]
=====
This method is deprecated. For new installations, use the recommended method above. For existing installations using this method, see the xref:/setup/upgrade-stackstate/migrate-to-global-mode.adoc[migration guide] to transition to the new configuration format.
=====

To deploy {stackstate-product-name} on Kubernetes:

. Before you deploy:
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where {stackstate-product-name} will be installed]
 ** <<create-values-yaml,Generate `baseConfig_values.yaml` and `sizing_values.yaml`>>
. Deploy the latest {stackstate-product-name} version to the `suse-observability` namespace with the following command:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability/suse-observability
----

--
Legacy method (Air-gapped)::
+
--

[WARNING]
=====
This method is deprecated. For new installations, use the recommended method above. For existing installations using this method, see the xref:/setup/upgrade-stackstate/migrate-to-global-mode.adoc[migration guide] to transition to the new configuration format.
=====

To deploy {stackstate-product-name} in an air-gapped setup on Kubernetes:

. Before you deploy:
 ** xref:/k8s-suse-rancher-prime-air-gapped.adoc[Follow these extra instructions for air-gapped installations].
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where {stackstate-product-name} will be installed]
 ** <<create-values-yaml,Generate `baseConfig_values.yaml` and `sizing_values.yaml`>>
. Deploy the latest {stackstate-product-name} version to the `suse-observability` namespace with the following command:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values local-docker-registry.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability-A.B.C.tgz
----

--
====

After the install, the SUSE Observability release should be listed in the SUSE Observability namespace and all pods should be running:

[,text]
----
# Check the release is listed
helm list --namespace suse-observability

# Check pods are running
# It may take some time for all pods to be installed or available
kubectl get pods --namespace suse-observability
----

=== Access the SUSE Observability UI

After SUSE Observability has been deployed you can check if all pods are up and running:

[,bash]
----
kubectl get pods --namespace suse-observability
----

When all pods are up, you can enable a port-forward:

[,bash]
----
kubectl port-forward service/<helm-release-name>-suse-observability-router 8080:8080 --namespace suse-observability
----

For the ingress configuration, create an `ingress_values.yaml` file and add the below code.

[NOTE]
====
Remember to set a secret for the TLS configuration. For details on how to do that, consult the kubectl documentation.
====

[,yaml]
----
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #if external dns (cloudflare and similars) configure:
    #external-dns.alpha.kubernetes.io/target: <INGRESS_FQDN>
    #external-dns.alpha.kubernetes.io/ttl: "60"
    #end if
  hosts:
  - host: <SUSE_OBSERVABILITY_HOST>
  tls:
  - hosts:
    - <SUSE_OBSERVABILITY_HOST>
    secretName: suse-private-ai-tls
  existingSecret: suse-private-ai-tls
  # Set up your secrets in whichever way feels fit. Check k8s docs for details: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/
----

Proceed to run an upgrade to apply ingress configuration:

[tabs]
====
Upgrade::
+
--

[,bash]
----
helm upgrade --namespace suse-observability --reuse-values --values ingress_values.yaml suse-observability suse-observability/suse-observability
----

--
Air-gapped upgrade::
+
--

[,bash]
----
helm upgrade --namespace suse-observability --reuse-values --values suse-observability-values/templates/ingress_values.yaml suse-observability suse-observability-A.B.C.tgz
----

--
====

[NOTE]
====
If you are not using an external DNS, add to your local machine /etc/hosts: <CLUSTER_IP> <SUSE_OBSERVABILITY_HOST>.
====

SUSE Observability will now be available in your browser at `+https://localhost:8080+`. Log in with the username `admin` and the default password provided in the `baseConfig_values.yaml` file.

Next steps are

* xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc[Expose SUSE Observability outside of the cluster]
* xref:/k8s-quick-start-guide.adoc[Start monitoring your Kubernetes clusters]
* Give your xref:/setup/security/authentication/README.adoc[co-workers access].
