= Install SUSE Observability
:description: SUSE Observability Self-hosted

== Before you start

[NOTE]
====
Extra notes for installing on:

* *Kubernetes clusters with limited permissions*: Read the xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc[required permissions].
* *Alibaba Cloud Container Service for Kubernetes (ACK)*: Read the xref:/setup/install-stackstate/kubernetes_openshift/ack.adoc[ACK installation notes].
* *OpenShift*: Refer to the xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[OpenShift installation instructions].
====


Before you start the installation of SUSE Observability:

* Check the xref:/setup/install-stackstate/requirements.adoc[requirements] to make sure that your Kubernetes environment fits the setup that you will use (recommended, minimal or non- high availability).
* Check that you have the xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc[required permissions].
* Add the SUSE Observability helm repository to the local helm client:

[,text]
----
helm repo add suse-observability https://charts.rancher.com/server-charts/prime/suse-observability
helm repo update
----

== Install SUSE Observability

[NOTE]
====
For environments without internet access, also known as air-gapped environments, first follow xref:/k8s-suse-rancher-prime-air-gapped.adoc[these extra instructions].

Also, make sure to follow the air-gapped installation instructions whenever those are present for a step.
====


. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where SUSE Observability will be installed]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_generate_baseconfig_values_yaml_and_sizing_values_yaml[Generate `baseConfig_values.yaml` and `sizing_values.yaml`]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_set_up_a_storage_class[Set up a storage class]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_deploy_suse_observability_with_helm[Deploy SUSE Observability with Helm]
. xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_access_the_suse_observability_ui[Access the SUSE Observability UI]


=== Create namespace

Start by creating the namespace where you want to install SUSE Observability and deploy the secret in that namespace. In our walkthrough we will use the namespace `suse-observability`:

[,text]
----
kubectl create namespace suse-observability
----

=== Generate `baseConfig_values.yaml` and `sizing_values.yaml`

The `baseConfig_values.yaml` file is required to deploy StackState with Helm. It contains your StackState license key, StackState Receiver API key and other important information.
The `sizing_values.yaml` file is recommended to deploy StackState with Helm as it contains information about the resources that StackState will be provisioned with according to the size on the landscape you want to observe.
The `affinity_values.yaml` file contains Kubernetes affinities to deploy SUSE Observability with different scheduling options.

[NOTE]
====
*Before you continue:* Make sure you have the latest version of the Helm charts with `helm repo update`.
====


You can generate the SUSE Observability `baseConfig_values.yaml`, `sizing_values.yaml`, and `affinity_values.yaml` files by running a separate Helm Chart. This is the `suse-observability/suse-observability-values` chart. A sample command line is:

[,text]
----
export VALUES_DIR=.
helm template \
  --set license='<your license>' \
  --set baseUrl='<suse-observability-base-url>' \
  --set sizing.profile='<sizing.profile>' \
  suse-observability-values \
  suse-observability/suse-observability-values --output-dir $VALUES_DIR
----

This command generates the files `$VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml`, `$VALUES_DIR/suse-observability-values/templates/sizing_values.yaml`, and `$VALUES_DIR/suse-observability-values/templates/affinity_values.yaml`. These contain the necessary configuration for installing the SUSE Observability Helm Chart.

[NOTE]
====
The SUSE Observability administrator passwords will be autogenerated by the above command and are output as comments in the generated `basicConfig.yaml` file. The actual values contain the `bcrypt` hashes of those passwords so that they're securely stored in the Helm release in the cluster.
====


The values that can be passed to this chart are:

|===
| Configuration | Value | Description

| Basic Config generate
| `basicConfig.generate`
| Switch on or off the generation of the `basicConfig_values.yaml` file.

| Receiver API Key
| `receiverApiKey`
| The API key used by SUSE Observability to receive data from agents. This is a secret key that should be kept private. If you omit this, a random key will be generated for you.

| Base URL
| `baseUrl`
| The `<STACKSTATE_BASE_URL>`. The external URL for SUSE Observability that users and agents will use to connect. For example `+https://suse-observability.internal+`. If you haven't decided on an Ingress configuration yet, use `+http://localhost:8080+`. This can be updated later in the generated file.

| Username and password**
| `-u` `-p`
| The username and password used by SUSE Observability to pull images. For air-gapped environments these need to be the username and password for the local contaier registry.

| License key
| `license`
| The SUSE Observability license key.

| Default password
| `adminPassword`
| The password for the default user (`admin`) to access SUSE Observability's UI. If you omit this, a random password will be generated for you. If you do pass this value and it's not bcrypt hashed, the chart will hash it for you.

| Image Registry
| `imageRegistry`
| The registry where the SUSE Observability images are hosted. If not provided, the default value will be 'quay.io'

| Pull Secret Username
| `pullSecret.username`
| The username used to pull images from the Docker registry where the SUSE Observability images are hosted. Only needed for custom registries.

| Pull Secret Password
| `pullSecret.password`
| The password used to pull images from the Docker registry where the SUSE Observability images are hosted. Only needed for custom registries.

| Sizing generate
| `sizing.generate`
| Switch on or off the generation of the `sizing_values.yaml` file.

| Sizing profile
| `sizing.profile`
| OneOf trial, 10-nonha, 20-nonha, 50-nonha, 100-nonha, 150-ha, 250-ha, 500-ha. Based on these profiles, you can generate the `sizing_values.yaml` file containing default sizes for the SUSE Observability resources and configuration to deploy in HA or Non-HA mode. For example, 10-nonha produces a `sizing_values.yaml` to deploy a NonHa SUSE Observability instance to observe a 10 node cluster in a Non High availability mode. Currently, moving from a Non-HA to an HA environment is not possible. If you expect that your environment will require observing around 150 nodes, then it's better to go with HA immediately.

| Pod AntiAffinity
| `affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution`
| Enforce that the replicas of the same data services are scheduled to different Kubernetes nodes. Only applicable for `HA` profiles. Either `true` or `false`. The default is `true` - scheduling to different nodes is enforced.
|===

[NOTE]
====
Store the generated `basicConfig.yaml` and `sizing_values.yaml` files safely. You can reuse these files for upgrades, saving time and ensuring that SUSE Observability continues to use the same API key. This is desirable as it means Agents and other data providers for SUSE Observability won't need updating.
You can regenerate the files independently using the switches `basicConfig.generate=false` and `sizing.generate=false` to disable any of them while still keeping the previously generated version of the file in the `output-dir`.
====

[NOTE]
====
The SUSE Observability Values chart generates affinity configurations that you can use with the main SUSE Observability chart to control pod scheduling behavior. Refer to xref:/setup/install-stackstate/kubernetes_openshift/affinity.adoc[Configure Kubernetes Affinities] documentation for more information.
====

=== Set up a storage class

You need to set up a storage class. Rancher's `local-path` is recommended if available, but SUSE Storage is also supported. Edit the file `$VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml` to add the "storageClass" configuration:

[,text]
----
# Source suse-observability-values/templates/baseConfig_values.yaml
global:
  imageRegistry: "registry.rancher.com"
  storageClass: "local-path" # New configuration line, the rest remains the same
----


=== Deploy SUSE Observability with Helm

The recommended deployment of SUSE Observability is a production ready, high availability setup with many services running redundantly. If required, it's also possible to run SUSE Observability in a non-redundant setup, where each service has only a single replica. This setup is only recommended for a test environment.

For air-gapped environments follow the instructions for the air-gapped installations.

[tabs]
====
Setup::
+
--

To deploy SUSE Observability on Kubernetes:

. Before you deploy:
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where SUSE Observability will be installed]
 ** <<_generate_baseconfig_values_yaml_and_sizing_values_yaml,Generate `baseConfig_values.yaml` and `sizing_values.yaml`>>
. Deploy the latest SUSE Observability version to the `suse-observability` namespace with the following command:

[,text]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability/suse-observability
----

--
Air-gapped setup::
+
--

To deploy SUSE Observability in an air-gapped setup on Kubernetes:

. Before you deploy:
 ** xref:/k8s-suse-rancher-prime-air-gapped.adoc[Follow these extra instructions for air-gapped installations].
 ** xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc#_create_namespace[Create the namespace where SUSE Observability will be installed]
 ** <<_generate_baseconfig_values_yaml_and_sizing_values_yaml,Generate `baseConfig_values.yaml` and `sizing_values.yaml`>>
. Deploy the latest SUSE Observability version to the `suse-observability` namespace with the following command:

[,bash]
----
helm upgrade \
  --install \
  --namespace suse-observability \
  --values local-docker-registry.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/baseConfig_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/sizing_values.yaml \
  --values $VALUES_DIR/suse-observability-values/templates/affinity_values.yaml \
suse-observability \
suse-observability/suse-observability
----

--
====

After the install, the SUSE Observability release should be listed in the SUSE Observability namespace and all pods should be running:

[,text]
----
# Check the release is listed
helm list --namespace suse-observability

# Check pods are running
# It may take some time for all pods to be installed or available
kubectl get pods --namespace suse-observability
----

=== Access the SUSE Observability UI

After SUSE Observability has been deployed you can check if all pods are up and running:

[,text]
----
kubectl get pods --namespace suse-observability
----

When all pods are up, you can enable a port-forward:

[,text]
----
kubectl port-forward service/<helm-release-name>-suse-observability-router 8080:8080 --namespace suse-observability
----

For the ingress configuration, generate the file `$VALUES_DIR/suse-observability-values/templates/ingress_values.yaml` and add the below code. 

[NOTE]
====
Remember to set a secret for the TLS configuration. For details on how to do that, consult the kubectl documentation.
====

[,text]
----
ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #if external dns (cloudflare and similars) configure:
    #external-dns.alpha.kubernetes.io/target: <INGRESS_FQDN>
    #external-dns.alpha.kubernetes.io/ttl: "60"
    #end if
  host:  <SUSE_OBSERVABILITY_HOST>
  tls:
  - hosts:
    - <SUSE_OBSERVABILITY_HOST>
    secretName: suse-private-ai-tls
  existingSecret: suse-private-ai-tls
  # Set up your secrets in whichever way feels fit. Check k8s docs for details: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_secret_tls/
----

Proceed to run an upgrade to apply ingress configuration:

[,text]
----
helm upgrade --namespace suse-observability --reuse-values --values suse-observability-values/templates/ingress_values.yaml suse-observability suse-observability/suse-observability
----

[NOTE]
====
If you are not using an external DNS, add to your local machine /etc/hosts: <CLUSTER_IP> <SUSE_OBSERVABILITY_HOST>.
====

SUSE Observability will now be available in your browser at `+https://localhost:8080+`. Log in with the username `admin` and the default password provided in the `values.yaml` file.

Next steps are

* xref:/setup/install-stackstate/kubernetes_openshift/ingress.adoc[Expose SUSE Observability outside of the cluster]
* xref:/k8s-quick-start-guide.adoc[Start monitoring your Kubernetes clusters]
* Give your xref:/setup/security/authentication/README.adoc[co-workers access].
