= Dashboards
:revdate: 2025-11-24
:page-revdate: {revdate}
:description: Create and manage dashboards to visualize data from your resources.

A dashboard visualizes data from your resources and can be created and customized to suit your needs. A dashboard can include resources from distinct parts of your IT environment.

== Create a new dashboard

To create a new dashboard:

. In the main menu, click **Dashboards**.
. Click the **Add new dashboard** button in the top right.
. Fill in the **Name** and **Description**.
. (Optional) Select **Public** to make the dashboard visible to all users.
. (Optional) Select **Starred** to add the dashboard to the main menu for quick access.
. Click **Create dashboard**.

You will be navigated to the new empty dashboard.

// TODO STAC-22767 Add screenshots of the process?

== Dashboard properties

Once on a dashboard, you can edit the properties of a dashboard by using the dropdown menu next to the *Save...* button in the top navigation bar and selecting **Edit dashboard properties**. From here, you can update the name and description, and whether the dashboard is public or starred.

=== Public dashboards
By default, only you can see your dashboards. Making a dashboard public makes it visible to all users. Public dashbords are viewable but not editable by others.

=== Starred dashboards
Starring a dashboard makes it appear mroe prominently in the main menu, and when adding widgets from other pages. Star a dashboard when you want quick access to it.

Starred dashboards are scoped to your user. Other users have their own starred dashboards.

You can also star or unstar a dashboard wherever you see the star icon next to a dashboard's name.

== Dashboard settings

Dashboard settings give you control over whether the time range, data refresh interval and variables are saved in the dashboard or customizable by viewers. Click the cog icon in the top right of a dashboard to open the dashboard settings.

When you enable one of the checkboxes under the "Saving..." heading, for example the time range, the dashboard will be fixed to the chosen time range once it has been saved. When it is disabled, the time range can be chosen by the viewer of the dashboard; the change is reflected in the URL, so the link can be shared with other people, who can then view the dashboard with the same time range.
