= Dashboard widgets
:revdate: 2025-11-24
:page-revdate: {revdate}
:description: Visualize data from your resources with various widgets.

Widgets are the building blocks of your dashboard. They visualize data, usually from one or many Kubernetes resources. Widgets can also show static text information to viewers of the dashboard.

== Adding a new widget

You can add a new widget in either of the two ways:

* Click the *Add Widget* button in the top right of a dashboard.

* On an empty dashboard, click the *Add Widget* section in the middle of the screen. A drawer opens where you can configure the new widget.



// TODO STAC=-22767 Add a screenshot

== Adding an existing widget

When viewing an individual component in {stackstate-product-name}, you can add charts directly to a dashboard by using the "more actions" menu and selecting "Add to dashboard".

// TODO STAC-22767 Add a screenshot

This is also available for any pinned items.

// TODO STAC-22767 Add a screenshot showing add all items to dashboard from pinned items drawer.

The resulting widget in the dashboard has a link to the resource it was added from.

== Configuring a widget

Each widget has a number of configuration options. Some are common to all widgets, others are based on the widget type.

=== Common widget fields

|===
| Field name | Description

| Name
| A short, descriptive name shown in the header of the widget.

| Description
| Additional details shown in the header of the widget behind a tooltip.

| Type
| The <<types,type of visualization>>.
|===

In addition to these fields, there are some common tabs to all widgets: 

|===
| Tab name | Description

| Links
| Related resource links, shown underneath the name of the widget. The first link is always displayed. Other links are available in a dropdown menu.

| YAML
| The raw YAML configuration for the widget, which can be viewed and edited.
|===


=== Queries tab

Widget types intended to show data from resources will have a *Queries* tab. You can add one or more PromQL queries to retrieve the data for the widget.


=== Types [[types]]

==== TimeSeriesChart

The `TimeSeriesChart` visualizes time series data in a line chart. Each query in the widget configuration produces a line on the chart.

// TODO STAC-22767 Add a screenshot

You can configure the following settings:

* *Legend* - The position and mode of the legend.
* **Visual** - Connect null values to create a continuous line.
* **Y Axis** - The unit, label and min/max values for the Y-axis.
* **Thresholds** - Add horizontal lines to the chart to mark important value thresholds.

==== BarChart

The `BarChart` visualizes time series data in a bar chart. It has the same settings for legend, Y-axis and thresholds as the `TimeSeriesChart`.

// TODO STAC-22767 Add a screenshot

==== StatChart

The `StatChart` shows a sparkline chart and a single value that is easy to read at a glance. Thresholds can be configured to change the color of the text based on the value.

// TODO STAC-22767 Add a screenshot

You can configure the following settings:

* **Sparkline** - Show or hide the sparkline chart.
* **Unit** - The unit of the value.
* **Decimals** - The number of decimals to show.
* **Calculation** - The method used to calculate the value from the time series data.

==== GaugeChart

The `GaugeChart` displays a gauge with a value in the middle. The color of the gauge and the text change when the value crosses a threshold.

// TODO STAC-22767 Add a screenshot

You can configure the following settings:

* **Unit** - The unit of the value.
* **Decimals** - The number of decimals to show.
* **Max** - The maximum value of the gauge.
* **Calculation** - The method used to calculate the value from the time series data.

==== Markdown

The `Markdown` widget displays markdown text. This can be used to add explanations or other information to your dashboard.