= Dashboard variables
:revdate: 2025-11-24
:page-revdate: {revdate}
:description: Use variables to create dynamic dashboards.

By configuring variables for a dashboard, you can create dashboards with dynamic widgets. Variables enable the reuse of a single dashboard definition for different use-cases. 

== Viewing dashboard variables
In the top navigation bar, use the dropdown menu next to the "Save..." button, and click "Edit dashboard variables".

// TODO STAC-22767 Add a screenshot

=== Built-in variables
There are variables that are built-in to {stackstate-product-name}. The names of these variables are reserved, and you cannot give your own variables the same names.

To view all built-in variables, click the accordion titled "SUSE Observability PromQL variables".

== Adding a new variable

. Open the "Edit dashboard variables" drawer. 
. Click the "Add variable" button to open a second drawer where you can configure the new variable.

// TODO STAC-22767 Add a screenshot

The configuration fields for a variable are as follows:

|===
| Field name | Description

| Name
| The name identifier of the variable. This is the name that you can <<using-variables, use in compatible fields>>.

| Display label
| A friendly name for the variable that is shown on the dashboard when <<selecting-variables, selecting the variable>>. This helps you identify the variable.

| Description
| A description to understand the purpose for the variable. This description is shown in the "Edit dashboard variables" drawer.

| Type
| The type of the variable.
|===

== Variable types
=== Text variable

A text variable contains simple text. You can set an initial value and make the variable read-only.

=== List variable

A list variable has possible values which are defined by the "Source" field. Each source type provides additional fields which allow you to narrow down the possible values for the variable.

|===
| Source type | Source fields

| Metric label names
| Enter zero or more series selectors to refine which metric label names are present.

| Metric label values
| Enter a metric label name, and zero or more series selectors to refine which metric label values are present.

| Metric PromQL
| Enter a custom PromQL query, and a label name. The resulting possible values are the values for the given label name.

| Static list
| Enter one or more label and value pairs to construct a static list of possible values.
|===

As you change the source type and their related fields, the preview on the right-hand-side of the drawer will update with the new possible values.


==== Common list variable settings

All list variable sources also have the following common settings:

|===
| Field name | Description

| Sort
| Sort the values in the list. For example, alphabetically or numerically.

| Allow multiple values
| Allow users to select more than one value at a time.

| Enable "Include Everything" option
| Adds an option to the list to select all values. You can specify a custom value for this option, or let it be automatically generated.
|===


== Using variables [[using-variables]]
Once a variable is defined, it can be used to populate various fields in the dashboard:

* Other variables
* Widget queries, links
* TODO STAC-22767 - list other places?

To use a variable in a compatible field, use the variable name preceded by a `$` (for example, `$my_variable`). The value of the variable is interpolated.

== Selecting variables [[selecting-variables]]
Variables are listed towards the top of the dashboard, next to the time range selector. Only the first few variables are shown. To see the rest of the variables, use the "More" dropdown.

Click a variable to open its selector, and select the values you wish to show on the dashboard.

As you select different values, the widgets using the variable will react to the changes.