= Dashboard variables
:revdate: 2025-11-24
:page-revdate: {revdate}
:description: Use variables to create dynamic dashboards.

By configuring variables in a dashboard, you can create dashboards that are more dynamic and that react to changes in the variables. This makes it a powerful way to reuse a single dashboard definition that can be customized for different clusters or applications.

== Add a new variable

To add a new variable:

. In the top navigation bar, use the dropdown menu next to the *Save...* button.
. Click **Edit dashboard variables**.
. In the variables drawer, click **Add variable**.
. A second drawer will open where you can configure the new variable.

The configuration fields for a variable are:

* **Name** - The name of the variable.
* **Display label** - A friendly name for the variable that will be shown on the dashboard.
* **Description** - The description of the variable.
* **Type** - `Text variable` or `List variable`.

A preview on the right hand side of the drawer shows the options that will be available for the variable.

== Text variable

A text variable contains simple text. You can set an initial value and make the variable read-only.

== List variable

A list variable has a list of possible values. The values can be retrieved from a number of sources.

=== List variable source

The source of a list variable determines where the list of values comes from.

==== Metric label names

[NOTE]
====
TODO STAC-22767
====

==== Metric label values

[NOTE]
====
TODO STAC-22767
====

==== Metric PromQL

[NOTE]
====
TODO STAC-22767
====

==== Static list

[NOTE]
====
TODO STAC-22767
====

=== Common list variable settings

All list variable sources have the following common settings:

* **Sort** - Sort the values in the list. For example, alphabetically or numerically.
* **Allow multiple values** - Allow users to select more than one value.
* **Enable "Include Everything" option** - This adds an option to the list to select all values. You can specify a custom value for this option, or let it be automatically generated.

== Using a variable
Once a variable is defined, it can be used in to populate various fields in the dashboard:

* Other variables
* Widget queries, links
* TODO STAC-22767 - list other places?

To use a variable in a comaptible field, use the variable name preceeded by a `$` (e.g. `$my_variable`). The value of the variable will be interpolated.

== Selecting a variable
Variables are listed towards the top of the dashboard, next to the time range selector. Only the first few variables are shown. To see the rest of the variables, use the "More" dropdown.

Click on a variable to open its selector, and select the values you wish to show on the dashboard.

As you select different values, the widgets using the variable will react to the changes.