= Troubleshooting monitors
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Overview

* <<the-result-of-the-monitor-isnt-showing-on-a-component,The result of the monitor is not showing on a component>>
* <<the-monitor-is-showing-an-error-in-the-monitor-status-overview],The monitor is showing an error in the monitor status overview>>

[#the-result-of-the-monitor-isnt-showing-on-a-component]
=== The result of the monitor is not showing on a component

First check if the monitor is <<verify-the-execution-of-the-monitor,producing results>>. If this is the case but the monitor results do not show up on the components, there might be a problem with the binding. First use the following command to verify:

[,bash]
----
sts monitor status --id <id>
----

If the output has `+Monitor health states with identifier which has no matching topology element (<nr>): ....+`, this shows that the `urnTemplate` may not generate an identifier matching the topology. To remedy this xref:setup/custom-integrations/monitors/schemas-ref.adoc#bind-monitor-results-to-components[revisit your urnTemplate].

[#the-monitor-is-showing-an-error-in-the-monitor-status-overview]
=== The monitor is showing an error in the monitor status overview

Get the status of the monitor through the CLI

[,bash]
----
sts monitor status --id <id>
----

The section `Monitor Stream errors:` will show the errors happening on the monitor and offer further help.

[#verifying-the-results-of-a-monitor]
== Verifying the results of a monitor

It is good practice to, after a monitor is made, validate whether it produces the expected result. The following steps can be taken:

[#verify-the-execution-of-the-monitor]
=== Verify the execution of the monitor

Go to the monitor overview page (http://your-SUSE Observability-instance/#/monitors) and find your monitor.

. Verify the `Status` column is in `Enabled` state. If the monitor is in `Disabled` state, <<enable-or-disable-the-monitor,enable it>>. If the status is in `Error` state, follow the steps below <<the-monitor-is-showing-an-error-in-the-monitor-status-overview,to debug>>.
. Verify you see the expected amount of states in the `Clear`/`Deviating`/`Critical` column. If the number of states is lower or higher than the amount of components you meant to monitor, the PromQL query might be giving too many results.

=== Verify the binding of the monitor

Observe whether the monitor is producing a result on one of the components that it is meant to monitor for. If the monitor does not show up, follow <<the-result-of-the-monitor-isnt-showing-on-a-component,these steps>> to remedy.

