= Troubleshooting monitors
:revdate: 2026-01-14
:page-revdate: {revdate}
:description: SUSE Observability

== Overview

* <<_the_result_of_the_monitor_isnt_showing_on_a_component,The result of the monitor isn't showing on a component>>
* <<_the_monitor_is_showing_an_error_in_the_monitor_status_overview,The monitor is showing an error in the monitor status overview>>

=== The result of the monitor isn't showing on a component

First check if the monitor is actually xref:/setup/custom-integrations/monitors/index.adoc#_verify_the_execution_of_the_monitor[producing results]. If this is the case but the monitor results do not show up on the components, there might be a problem with the binding. First use the following command to verify:

[,bash]
----
sts monitor status --id <id>
----

If the output has `+Monitor health states with identifier which has no matching topology element (<nr>): ....+`, this shows that the `urnTemplate` may not generate an identifier matching the topology. To remedy this xref:/setup/custom-integrations/monitors/index.adoc#_bind_the_results_of_the_monitor_to_the_correct_components[revisit your urnTemplate].

=== The monitor is showing an error in the monitor status overview

Get the status of the monitor through the CLI

[,bash]
----
sts monitor status --id <id>
----

The section `Monitor Stream errors:` will show the errors happening on the monitor and offer further help.

